In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [18]:
df = pd.read_csv('data/card_data.csv', index_col=0)
df.head()

,카드명,카드사,카드타입,출시일,연회비,전월실적,카테고리,주요혜택,발급가능여부
카드번호,,,,,,,,,
1,신한카드 Hi-Point,신한카드,CRD,NaN,8000,0,"쇼핑, 모든가맹점, 주유, 금융, 통신, 적립","전국가맹점 0.2~2.0% 적립, 특정가맹점 1~5% 적립, 에이치디현대오일뱅크 6...",X
2,신한카드 Love,신한카드,CRD,NaN,8000,200000,"백화점, 패밀리레스토랑, 주유소, 영화, 적립, 테마파크, 경기관람","백화점/할인점 5% 할인, 스타벅스 20% 할인, GS칼텍스 60원/L 할인",X
3,신한카드 Lady,신한카드,CRD,NaN,5000,300000,"쇼핑, 푸드, 영화, 주유소, 교육/육아, 테마파크, 통신, 경기관람","3대백화점 5% 할인, 패밀리레스토랑 20% 할인, 놀이공원 30~50% 할인",X
4,SK에너지 신한카드The you,신한카드,CRD,NaN,7000,300000,"주유소, 대중교통, 무이자할부, 테마파크, 영화, 헤어, 경기관람, 여행사","SK주유소 100원/L 할인, 지하철,버스,택시 3~7% 할인, 놀이공원 30~50...",X
8,신한카드 The CLASSIC-Y,신한카드,CRD,NaN,100000,0,"선택형, 모든가맹점, 주유소, 생활, 면세점, 진에어, 공연/전시, 프리미엄","Gift Option 매년1회 선택이용, 마이신한포인트 0.7~5% 적립, GS칼텍...",O

In [20]:
df.shape

(2502, 9)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2502 entries, 1 to 2985
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   카드명     2502 non-null   object
 1   카드사     2502 non-null   object
 2   카드타입    2502 non-null   object
 3   출시일     300 non-null    object
 4   연회비     2502 non-null   int64
 5   전월실적    2502 non-null   int64
 6   카테고리    2477 non-null   object
 7   주요혜택    2498 non-null   object
 8   발급가능여부  2502 non-null   object
dtypes: int64(2), object(7)
memory usage: 195.5+ KB

In [22]:
df.isnull().sum()

카드명          0
카드사          0
카드타입         0
출시일       2202
연회비          0
전월실적         0
카테고리        25
주요혜택         4
발급가능여부       0
dtype: int64

카테고리 전처리 어떡하지 결측치 제외해야되나 근데 주요혜택은 들어있는데

#### 일단 국민카드만 볼까?

In [39]:
kb_df = df.loc[df.loc[:, '카드사'] == 'KB국민카드']
kb_df.head()

,카드명,카드사,카드타입,출시일,연회비,전월실적,카테고리,주요혜택,발급가능여부
카드번호,,,,,,,,,
105,이마트 KB국민카드,KB국민카드,CRD,NaN,5000,300000,"대형마트, 학원, 카페, 영화, 패밀리레스토랑","이마트 5~10% 청구할인, 학원 2~5% 청구할인, VIPS 15% 현장할인",X
106,굿데이카드,KB국민카드,CRD,NaN,5000,300000,"주유, 통신, 교통, 생활, 학원","주유 60원/L 할인, 통신요금 10% 할인, 커피 10% 할인",O
107,SK LPG SAVE KB국민카드,KB국민카드,CRD,NaN,3000,300000,"충전소, 정비, 패밀리레스토랑, 무이자할부","SK에너지(LPG) 충전시 1,500원 정액할인, 엔진오일 연 1회 무료교환, 패밀...",O
108,와이즈카드,KB국민카드,CRD,NaN,5000,0,"생활, 모든가맹점, 적립","특별포인트리 0.5~4.5% 적립, 기본포인트리 0.5% 적립, 학원/병원/백화점 ...",O
109,SK에너지 러브유 KB국민카드,KB국민카드,CRD,NaN,7000,300000,"주유소, 정비, 대중교통","SK에너지 충전시 100원/L 청구할인, 엔진오일 연 1회 무료교환, 버스,지하철 ...",O

In [42]:
kb_df.loc[:, '카테고리']

카드번호
105     대형마트, 학원, 카페, 영화, 패밀리레스토랑
106            주유, 통신, 교통, 생활, 학원
107       충전소, 정비, 패밀리레스토랑, 무이자할부
108                 생활, 모든가맹점, 적립
109                 주유소, 정비, 대중교통
                  ...
2931                       학원, 생활
2956                     경기관람, 할인
2964       간편결제, 온라인쇼핑, 디지털구독, 해외
2970     간편결제, 할인, 통신, 디지털구독, 선택형
2981                    해외, 국내가맹점
Name: 카테고리, Length: 286, dtype: object

In [43]:
kb_df['카테고리'].str.split(', ')

카드번호
105     [대형마트, 학원, 카페, 영화, 패밀리레스토랑]
106            [주유, 통신, 교통, 생활, 학원]
107       [충전소, 정비, 패밀리레스토랑, 무이자할부]
108                 [생활, 모든가맹점, 적립]
109                 [주유소, 정비, 대중교통]
                   ...
2931                       [학원, 생활]
2956                     [경기관람, 할인]
2964       [간편결제, 온라인쇼핑, 디지털구독, 해외]
2970     [간편결제, 할인, 통신, 디지털구독, 선택형]
2981                    [해외, 국내가맹점]
Name: 카테고리, Length: 286, dtype: object

In [44]:
category = kb_df['카테고리'].str.split(', ').explode()
category

카드번호
105        대형마트
105          학원
105          카페
105          영화
105     패밀리레스토랑
         ...
2970         통신
2970      디지털구독
2970        선택형
2981         해외
2981      국내가맹점
Name: 카테고리, Length: 1193, dtype: object

In [46]:
category.unique()

array(['대형마트', '학원', '카페', '영화', '패밀리레스토랑', '주유', '통신', '교통', '생활', '충전소',
       '정비', '무이자할부', '모든가맹점', '적립', '주유소', '대중교통', '공과금', '보험', '해피포인트',
       '테마파크', '여행/숙박', '자동차/하이패스', '멤버십포인트', '항공마일리지', '해외', '푸드', '선택형',
       '카페/디저트', '뷰티/피트니스', 'APP', 'OTT/영화/문화', '쇼핑', '캐시백', '간편결제',
       '레저/스포츠', '소셜커머스', '아이행복', '병원', '교육/육아', '약국', '아시아나항공', '해외이용',
       nan, '패스트푸드', '바우처', '프리미엄', '편의점', '택시', '온라인쇼핑', '배달앱', '대한항공',
       '애완동물', '할인', '인테리어', '공연/전시', '기차', '삼성페이', '카카오페이', '베이커리',
       '일반음식점', '금융', '도서', '병원/약국', '은행사', '드럭스토어', '백화점', '홈쇼핑', '화장품',
       '헤어', '항공권', '공과금/렌탈', '렌터카', '프리미엄 서비스', '피트니스', '렌탈 ', '디지털구독',
       '국민행복', '보험사', '자동차', '골프', '여행사', '호텔', '하이패스', '제휴/PLCC',
       'OK캐쉬백', '제주항공', 'KT', '비즈니스', 'LGU+', 'SKT', '학습지', '공항라운지',
       '마트/편의점', '면세점', '공항', 'SSM', '게임', '국내외가맹점', '아이스크림', '혜택 프로모션',
       '수수료우대', '고속버스', '전통시장', '경기관람', '국내가맹점'], dtype=object)

In [45]:
category.value_counts()

카테고리
통신        67
편의점       52
영화        47
카페        46
테마파크      44
          ..
렌터카        1
공과금/렌탈     1
홈쇼핑        1
삼성페이       1
국내가맹점      1
Name: count, Length: 104, dtype: int64

In [28]:
df.loc[df.loc[:, '발급가능여부'] == 'X']

,카드명,카드사,카드타입,출시일,연회비,전월실적,카테고리,주요혜택,발급가능여부
카드번호,,,,,,,,,
1,신한카드 Hi-Point,신한카드,CRD,NaN,8000,0,"쇼핑, 모든가맹점, 주유, 금융, 통신, 적립","전국가맹점 0.2~2.0% 적립, 특정가맹점 1~5% 적립, 에이치디현대오일뱅크 6...",X
2,신한카드 Love,신한카드,CRD,NaN,8000,200000,"백화점, 패밀리레스토랑, 주유소, 영화, 적립, 테마파크, 경기관람","백화점/할인점 5% 할인, 스타벅스 20% 할인, GS칼텍스 60원/L 할인",X
3,신한카드 Lady,신한카드,CRD,NaN,5000,300000,"쇼핑, 푸드, 영화, 주유소, 교육/육아, 테마파크, 통신, 경기관람","3대백화점 5% 할인, 패밀리레스토랑 20% 할인, 놀이공원 30~50% 할인",X
4,SK에너지 신한카드The you,신한카드,CRD,NaN,7000,300000,"주유소, 대중교통, 무이자할부, 테마파크, 영화, 헤어, 경기관람, 여행사","SK주유소 100원/L 할인, 지하철,버스,택시 3~7% 할인, 놀이공원 30~50...",X
11,신한카드 Simple+,신한카드,CRD,NaN,13000,0,"모든가맹점, 생활, 영화","전가맹점 0.7% 캐시백, 이동통신요금 0.7% 추가캐시백, 생활친화가맹점 월 10...",X
...,...,...,...,...,...,...,...,...,...
2762,THE iD. TITANIUM (아시아나),삼성카드,CRD,2024-08-26,700000,0,"바우처, 아시아나항공, 프리미엄 서비스","바우처 연 2가지 제공, 1,500원당 2 마일리지 기본 적립, 여행/골프/면세점 ...",X
2797,SKT T다운 하나카드,하나카드,CRD,NaN,25000,400000,SKT,SKT 라이트할부 청구할인,X
2798,LG전자 스페셜 롯데카드,롯데카드,CRD,NaN,12000,300000,"할인, 캐시백, 멤버십포인트","렌탈료 최대 23,000원 결제일 할인, 장기할부이용 최대 23,000원 캐시백",X
2802,LG U+ NU 우리카드 Ⅱ,우리카드,CRD,NaN,20000,0,LGU+,"LG U+ 통신요금 최대 20,000원 할인, LG U+ 단말기 장기할부 서비스",X
2891,신한카드 Hey Young 체크(잔망루피),신한카드,CHK,NaN,0,200000,"대중교통, 통신, 영화, 편의점, 카페, 패스트푸드, 배달앱, 생활, 디지털구독, ...","일상 서비스 최대 5천원 캐시백, 간편결제 서비스 최대 5천원 캐시백, 해외 이용서...",X

In [23]:
df.loc[df.loc[:, '카테고리'].isnull()].head()

,카드명,카드사,카드타입,출시일,연회비,전월실적,카테고리,주요혜택,발급가능여부
카드번호,,,,,,,,,
79,그랑블루Ⅱ카드,우리카드,CRD,NaN,100000,300000,NaN,"모아포인트 0.5~1.8% 적립, 기프트바우처 연 1회 제공, 공항라운지 무료 이용",X
83,ONLY 나만의카드,우리카드,CRD,NaN,13000,300000,NaN,"자동납부 10% 할인, 대형할인점 2,000원 할인, 스타벅스 10% 할인",X
90,카드의정석 위비온 플러스,우리카드,CRD,NaN,13000,300000,NaN,"국내가맹점 5% 할인, 해외가맹점 3% 할인, 워라밸업종 7% 할인",X
128,Liiv Mate카드,KB국민카드,CRD,NaN,12000,300000,NaN,"국내가맹점 0.7% 적립, 간편결제Pay 2% 적립, 해외가맹점 2% 할인캐시백",X
223,뉴 CJ헬로 롯데카드,롯데카드,CRD,NaN,10000,300000,NaN,"CJ헬로/헬로모바일 최대 2만원 할인, 미용실 최대 20% 할인, 놀이공원 50% 할인",X

In [ ]:
df.loc[df['카드타입']=='CHK']