In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import re
import time
import datetime
import requests
import tqdm

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By

### Selenium

In [66]:
# 크롬 드라이버 경로 설정
path = r"C:\Users\NT551_11TH\Downloads\chromedriver-win64\chromedriver.exe"

In [ ]:
# 카드 1개 상세 페이지
url = 'https://www.card-gorilla.com/card/detail/2885'

In [57]:
s = Service(path)
driver = webdriver.Chrome(service=s)
driver.get(url)

In [ ]:
# //*[@id="q-app"]/section/div[1]/section/div/article[2]/div[1]/dl[1]
# //*[@id="q-app"]/section/div[1]/section/div/article[2]/div[1]/dl[2]

In [68]:
benefit_list = []

In [73]:
# 할인 정보 데이터 개수 몇 개인지
benefit_path = '//*[@id="q-app"]/section/div[1]/section/div/article[2]/div[1]'
benefit_cnt = int(driver.find_element(By.XPATH, benefit_path).get_attribute('childElementCount'))

for cnt in range(1, benefit_cnt+1):
    benefit_btn = f'//*[@id="q-app"]/section/div[1]/section/div/article[2]/div[1]/dl[{cnt}]/dt'
    element = driver.find_element(By.XPATH, benefit_btn)
    # driver.find_element(By.XPATH, benefit_btn).click()
    driver.execute_script("arguments[0].click();", element)
    time.sleep(0.5)

    benefit_info_path = f'//*[@id="q-app"]/section/div[1]/section/div/article[2]/div[1]/dl[{cnt}]/dd'
    print(driver.find_element(By.XPATH, benefit_info_path).text)
    # benefit_list.append(driver.find_element(By.XPATH, benefit_info_path).text)

선택 옵션에 따른 할인 혜택 제공 (택 1)
- 국내 가맹점 0.7% 할인
- 아파트 관리비/통신 10% 할인
- 교육 10% 할인

  * 선택한 옵션에 대해서만 제공
  * 옵션은 모니모 앱, 삼성카드 홈페이지(PC, 모바일)/앱을 통해 매월 변경 가능하며, 변경 신청 다음 달 1일에 자동 반영
국내 가맹점 0.7% 할인
- 전월 이용금액에 관계없이, 할인한도 없이 국내 가맹점 0.7% 결제일할인
아파트 관리비/통신 10% 할인
- 아파트 관리비/통신요금 정기결제 시 10% 결제일할인
구분 할인 대상
아파트 관리비 아파트 관리비
이동통신 SKT/KT/LG U+/알뜰폰 (SK텔링크, KT스카이라이프, KT M 모바일, 헬로모바일, 미디어로그) 이동통신요금
인터넷, 유선통신 SK브로드밴드 /KT/KT스카이라이프/LG U+ 인터넷/유선통신요금

전월 이용금액대별 통합 월 할인한도
40만원 이상 80만원 이상 120만원 이상
7,000원 10,000원 15,000원
- 발급월 +1개월까지는 전월 이용금액 40만원 미만 시에도 40만원 이상 ~ 80만원 미만 실적구간 혜택 제공(전월 이용금액 80만원 이상 시에는 해당 실적구간 혜택 제공)
- 알뜰폰은 결합상품요금, 휴대폰 등 단말기 구매금액 및 대리점 카드 결제건 제외
- 인터넷, 유선통신은 사물인터넷(IoT)관련 요금, 휴대폰 등 단말기 구매금액 및 대리점 카드 결제건 제외
교육 10% 할인
- 교육 10% 결제일할인
구분 할인 대상
학원 입시/보습외국어/예체능계 학원
인터넷강의 이투스, 메가스터디교육(메가스터디, 엠베스트 엘리하이), 대성마이맥, 천재교과서(밀크T)
학습지 웅진씽크빅, 교원, 대교, 한솔교육

전월 이용금액대별 통합 월 할인한도
40만원 이상 80만원 이상 120만원 이상
7,000원 10,000원 15,000원
- 발급월 +1개월까지는 전월 이용금액 40만원 미만 시에도 40만원 이상 ~ 80만원 미만 실적구간 혜택 제공(전월 이용금액 80만원 이상 시에는 해당 실적구간 혜택 제공)
- 학원은 오프라인 결제건에 한함
- 인터넷 강의는 초/중/고 교육과정 관련 공식 홈페이지/앱을 통한 결제건에 한함
선택 옵션에 따른 할인 혜택 제공 (택 1)
- 온라인쇼핑몰/의료/배달앱 7% 할인
- 음식점/편의점/할인점/주유 7% 할인

  * 선택한 옵션에 대해서만 제공
  * 옵션은 모니모 앱, 삼성카드 홈페이지(PC, 모바일)/앱을 통해 매월 변경 가능하며, 변경 신청 다음 달 1일에 자동 반영
온라인쇼핑/의료/배달앱 7% 할인
- 온라인쇼핑/의료/배달앱 7% 결제일할인
구분 할인 대상
온라인쇼핑몰 쿠팡, 네이버플러스 스토어, SSG COM, G마켓, 옥션, 11번가, 컬리, 삼성카드 쇼핑
의료 병·의원, 약국, 동물병원
배달앱 배달의민족, 쿠팡이츠, 요기요

전월 이용금액대별 통합 월 할인한도
40만원 이상 80만원 이상 120만원 이상
7,000원 10,000원 15,000원
- 발급월 +1개월까지는 전월 이용금액 40만원 미만 시에도 40만원 이상 ~ 80만원 미만 실적구간 혜택 제공(전월 이용금액 80만원 이상 시에는 해당 실적구간 혜택 제공)
- 의료는 오프라인 결제건에 한하며, 요양병원, 보건소는 제외
- 배달앱은 공식 홈페이지/앱을 통한 결제건에 한하며, 가맹점 직접 결제건은 제외
음식점/편의점/할인점/주유 7% 할인
- 음식점/편의점/할인점/주유 7% 결제일할인
구분 할인 대상
음식점 한식, 양식, 일식, 중식, 뷔페, 패밀리레스토랑, 패스트푸드
편의점 CU, GS25, 세븐일레븐, 이마트24
할인점 이마트 트레이더스 홀세일 클럽, 롯데마트, 농협 하나로마트
주유 SK에너지, GS칼텍스, S-OIL, HD현대오일뱅크

전월 이용금액대별 통합 월 할인한도
40만원 이상 80만원 이상 120만원 이상
7,000원 10,000원 15,000원
- 발급월 +1개월까지는 전월 이용금액 40만원 미만 시에도 40만원 이상 ~ 80만원 미만 실적구간 혜택 제공(전월 이용금액 80만원 이상 시에는 해당 실적구간 혜택 제공)
- 음식점/편의점은 오프라인 결제건에 한하며, 백화점, 쇼핑몰 등의 임대매장은 제외
- 할인점은 오프라인 결제건에 한하며, 기업형 슈퍼마켓(이마트 에브리데이, 롯데슈퍼등), 쇼핑 외 결제건(상품권, 주차장 등), 임대매장은 제외
- 주유는 LPG충전소 제외
생활 편의 영역 5% 할인
- 생활잡화/공연/서점/보틀숍 5% 결제일할인
구분 할인 대상
생활잡화 다이소
공연 NOL 티켓
서점 알라딘
보틀숍 와인앤모어
- 통합 월 할인한도 : 5,000원
- 전월 이용금액 40만원 이상 시 제공
- 발급월 +1개월까지는 전월 이용금액 40만원 미만 시에도 제공
- 생활잡화는 오프라인 결제건에 한하며, 백화점, 할인점, 쇼핑몰 등의 임대매장은 제외
- 공연은 공식 홈페이지/앱을 통한 결제건에 한함
- 서점은 오프라인 및 공식 홈페이지 앱을 통한 결제건에 한하며, 캐시 충전건, 구글플레이, 앱스토어 등을 통한 결제건(인앱 결제) 제외
- 보틀숍은 와인앤모어 데일리 등 일부 임대매장 제외
디지털콘텐츠/멤버십 50% 할인
- 디지털콘텐츠/멤버십 정기결제 시 50% 결제일할인
구분 할인 대상
디지털콘텐츠 넷플릭스, 디즈니+, 유튜브, 티빙
멤버십 쿠팡 와우 멤버십, 네이버플러스 멤버십
- 통합 월 할인한도 : 5,000원
- 전월 이용금액 40만원 이상 시 제공
- 발급월 +1개월까지는 전월 이용금액 40만원 미만 시에도 제공
- 디지털콘텐츠의 유튜브는 유튜브 프리미엄 결제건에 한함
- 디지털콘텐츠는 구글플레이, 앱스토어 등을 통한 결제건(인앱 결제) 제외
해외 2% 할인
- 전월 이용금액에 관계없이, 할인한도 없이 해외 2% 결제일할인
구분 할인 대상
해외 해외 가맹점 및 해외 직접구매 이용건
- 해외겸용카드에 한해 제공
- 해외 이용 시 별도의 수수료 부과, 자세한 내용은 '유의사항'에서 확인
전월 이용금액 기준
- 매월 1일부터 말일까지 이용한 일시불 및 할부 이용금액(단기카드대출(현금서비스), 장기카드대출(카드론), 각종 수수료 및 이자(할부수수료, 카드대출 이자 등), 연체료, 연회비 납부건은 일시불 및 할부 이용금액에 해당되지 않음)

전월 이용금액 제외 대상
- 통신/교육 10% 할인, 음식점/편의점/할인점/주유/온라인쇼핑몰/의료/배달앱 7% 할인 혜택이 제공된 전체 이용금액
- 건강보험/국민연금/고용보험/산재보험 및 장애인 고용부담금, 국세/지방세/공과금 납부건
- 아파트 관리비, 부동산 임대료 납부건
- 유치원 납입금, 초/중/고등학교 학교납입금, 대학 등록금 납부건
- 기프트/선불카드(포인트, 사이버머니 등 전자지급수단 포함) 구매 및 충전, 상품권 구매건

할인 제외 대상
- 무이자할부 이용금액
- 삼성카드 할인이 적용된 일시불 및 할부 이용금액
- 건강보험/국민연금/고용보험/산재보험 및 장애인 고용부담금, 국세/지방세/공과금 납부건
- 부동산 임대료 납부건
- 유치원 납입금, 초/중/고등학교 학교납입금, 대학 등록금 납부건
- 대중교통(후불교통기능/모바일교통기능 결제건), 택시, 고속버스(차내 단말기 및 고속버스 앱 결제), 고속도로 통행요금 납부건
- 기프트/선불카드(포인트, 사이버머니 등 전자지급수단 포함) 구매 및 충전, 상품권 구매건
- 문자알림서비스, 스마트오토서비스 이용금액
- 삼성카드와 구매캐시백 포인트 제공 계약을 체결한 일부 가맹점 의 약품 유류 구매한도 대금결제건

기타
- 삼성카드의 다른 결제일할인 혜택과 중복 적용되지 않으며, 할인 혜택이 큰 금액만 적용
- 할인 혜택은 승인일 기준으로 적용
- 전월 이용금액 산정은 승인일 기준으로 적용. 다만, 해외 결제건 및 무승인 결제건(예 : 대중교통, 이동통신 등 정기결제건 등)은 매출전표 접수일 기준으로 적용
- 자체 가맹점번호로 승인 처리되는 일부 결제건(간편결제, 키오스크 등)은 할인 대상에서 제외

안내사항
- 삼성카드 가맹점 업종 분류 기준에 의한 등록 가맹점에 한함
- 삼성카드는 아래 항목을 공과금으로 분류함
  * 전기요금, 사회보험료(건강보험/국민연금/고용보험/산재보험), 우편요금 도시가스요금, 여권 발급비용, 상하수도요금, 과태료 범칙금, 벌금, 국가/공공기관/공공단체(지방자치단체, 공공조합 영조물, 공재단)에서 개설한 가맹점 이용금액
- 결제 취소금액은 매출취소전표가 삼성카드에 접수된 달의 이용금액에서 차감
  * 혜택이 적용된 결제건이 취소될 경우, 할인, 포인트 적립 등의 횟수 및 한도는 매출취소전표가 접수된 이후에 복원
  * 포인트가 적립된 결제건이 취소될 경우, 해당 포인트는 보유 포인트에서 자동 차감되며, 포인트 부족 시 카드 결제계좌에서 자동 출금

연회비

총 연회비 기본 연회비 제휴 연회비
해외겸용 (Mastercard) 2만원 7천원 1만 3천원
국내전용
  * 후불교통기능이 탑재되어 발급
  * 해외겸용카드는 컨택리스 결제 지원
- 연회비는 카드 발급일(발급 첫 해에는 카드 사용등록일)을 기준으로 매년 청구
 [예외 기준]
  * 카드 발급일(발급 첫 해에는 카드 사용등록일)에 연회비가 청구되지 않은 경우 최초 이용일자 기준으로 해당 결제일에 청구
  * 매년 카드 발급일을 기준으로 직전 1년 이내 실적이 없는 경우 연회비가 청구되지 않음
  * 재발급, 갱신 시에는 이전 카드의 카드 발급일을 기준으로 연회비 청구
- 연회비는 기본 연회비와 제휴 연회비로 구분
- 해당 카드 연회비(기본 연회비+제휴 연회비)는 카드별로 청구
- 카드 중도 해지 시, 연회비 반환 금액은 회원이 카드사와 계약을 해지한 날부터 일 단위로 나누어 계산(카드 이용이 가능하게 된 날을 기준으로 계산)하여 반환됨. 카드의 발행, 배송 등 카드 발급에 소요된 비용(신규 가입연도에 해당)은 반환 금액에서 제외되며, 제휴 연회비가 있는 경우에는 카드 이용 시 제공되는 추가적인 혜택 등 부가 서비스 제공에 소요된 비용이 추가적으로 반환 금액에서 제외됨
- 연회비 반환 금액은 계약을 해지한 날로부터 10영업일 이내에 반환됨. 부가 서비스 제공 내역 확인에 시간이 소요되는 등 불가피한 사유가 있을 때에는 계약을 해지한 날로부터 3개월 이내에 반환됨

유의사항
- 결제계좌 개설 기관의 영업 마감시간(평일 16:00) 이후 결제대금 입금 시, 해당 기관의 사정에 따라 입금 당일에 출금되지 않으면 연체료가 발생할 수 있습니다.
- 즉시결제, 가상계좌, 무통장입금을 이용하시면 위의 영업 마감시간 이후에도 당일 입출금이 가능합니다.
  * 이용방법
  ① 홈페이지(PC) → 전체메뉴 → 마이 → 카드대금 결제 → 즉시결제 또는 가상계좌
  ② 앱 → 전체메뉴 → 대금결제 → 즉시결제 또는 가상계좌
- 카드를 이용하는 경우 제공되는 포인트 및 할인혜택 등의 부가서비스는 카드 신규 출시(2025년 7월 2일) 이후 다음 사유 중 어느 하나에 해당하는 경우 외에는 변경할 수 없습니다. (단, 회원의 권익을 증진하거나 부담을 완화하는 경우는 제외) 카드사가 부가서비스를 변경하는 경우에는 변경사유, 변경 내용 등을 다음에서 정하는 기간에 따라 서면교부, 우편 또는 전자우편, 전화 또는 팩스, 휴대폰 메시지 또는 이에 준하는 전자적 의사표시 중 서로 다른 2가지 이상의 방법으로 고지하여 드립니다.
  ① 카드사의 휴업·파산·경영상의 위기 등에 따른 불가피한 경우 : 사유발생 즉시
  ② 제휴업체의 휴업·파산·경영상의 위기로 인해 불가피하게 부가서비스를 축소·변경하는 경우로서 다른 제휴업체를 통해 동종의 유사한 부가서비스 제공이 불가한 경우 : 사유발생 즉시
  ③ 제휴업체가 카드사의 의사에 반하여 해당 부가서비스를 축소하거나 변경 시, 당초 부가서비스에 상응하는 다른 부가서비스를 제공하는 경우 : 사유발생 즉시
  ④ 부가서비스를 3년 이상 제공한 상태에서 해당 부가서비스로 인해 상품의 수익성이 현저히 낮아진 경우 : 부가서비스 변경일 6개월 전부터 매월
- 해외에서 카드 결제 시, 현지 통화가 아닌 원화로 결제하는 경우 해외원화결제 서비스(DCC) 수수료가 추가로 발생할 수 있으므로 유의하시기 바랍니다.
  * 해외원화결제서비스(DCC) 차단방법 : 홈페이지(PC) 또는 앱 → 전체메뉴 → 고객센터 → 해외 이용 → 해외 이용 잠금 서비스
- 해외 이용 시(해외 사이트 거래 포함) 미화(USD) 기준 거래미화금액에 접수일의 우리은행 최초 고시 전신환매도율을 적용한 후, 국제브랜드사가 부과하는 브랜드사수수료(Mastercard 1%)와 삼성카드가 부과하는 해외이용수수료 (0.2%)를 합산하여 원화로 청구됩니다.
- 해외 이용 시 청구금액 산출방법은 아래와 같습니다.
  * 해외 이용 시 청구금액 = (거래미화금액 × 전신환매도율①) + 브랜드사수수료② + 해외이용수수료③
  ① 전신환매도율 : 접수일의 우리은행 최초 고시 전신환매도율
  ② 브랜드사수수료 = (거래미화금액 × 국제브랜드 이용 수수료율 1%) × 전신환매도율
  ③ 해외이용수수료 = (거래미화금액 × 해외서비스 수수료율 0.2%) × 전신환매도율

In [ ]:
# 테스트용
btn = '//*[@id="q-app"]/section/div[1]/section/div/article[2]/div[1]/dl[1]/dt'
driver.find_element( By.XPATH, btn).click()

test = '//*[@id="q-app"]/section/div[1]/section/div/article[2]/div[1]/dl[1]/dd'
driver.find_element(By.XPATH, test).text
# driver.find_element(By.XPATH, test).text.split('\n')

'선택 옵션에 따른 할인 혜택 제공 (택 1)\n- 국내 가맹점 0.7% 할인\n- 아파트 관리비/통신 10% 할인\n- 교육 10% 할인\n\n  * 선택한 옵션에 대해서만 제공\n  * 옵션은 모니모 앱, 삼성카드 홈페이지(PC, 모바일)/앱을 통해 매월 변경 가능하며, 변경 신청 다음 달 1일에 자동 반영'

In [ ]:
# //*[@id="q-app"]/section/div[1]/section/div/article[2]/div[1]/dl[2]/dd

### API 호출

In [43]:
card_data_list = []

In [ ]:
# raw_data.get('corp')['name']

'신한카드'

In [ ]:
# url = f"https://api.card-gorilla.com:8080/v1/cards/{1}"
# headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36'}
    
# response = requests.get(url, headers=headers)
# # response

# raw_data = response.json()
# raw_data
# # card_info = {
# #     '카드번호': card_id,
# #     '카드명': raw_data.get('name', '이름없음'),       # name 키가 없으면 '이름없음' 반환
# #     '카드사': raw_data.get('corp_name', '알수없음'), # 예: 신한카드
# #     '카드타입': raw_data.get('type', '알수없음')     # 예: 신용/체크
# # }
            
# # card_data_list.append(card_info)

{'idx': 1,
 'cid': '001',
 'cate': 'CRD',
 'corp': {'idx': 2,
  'name': '신한카드',
  'name_eng': 'shinhan',
  'color': '#2252FF',
  'logo_img': {'name': 'logo_sh.png',
   'url': 'https://d1c5n4ri2guedi.cloudfront.net/corp/2/logo_img/33324/logo_sh.png'},
  'pr_container': None,
  'pr_detail_img': [],
  'pr_detail': '<!-- 소스코드 시작 --><div class="modal-promo"><div class="btn-close"><br></div></div><!-- 소스코드 끝 -->',
  'pr_container_chk': None,
  'pr_detail_img_chk': [],
  'pr_detail_chk': None,
  'tips': [{'title': '고릴라 TIP', 'contents': ''}],
  'is_event': True,
  'is_visible': True},
 'name': '신한카드 Hi-Point',
 'brand': [{'idx': 1,
   'name': 'VISA',
   'code': 'VISA',
   'logo_img': {'name': 'brand_visa.png',
    'url': 'https://d1c5n4ri2guedi.cloudfront.net/brand/1/logo_img/44542/brand_visa.png'},
   'is_visible': True},
  {'idx': 4,
   'name': 'Mastercard',
   'code': 'Mastercard',
   'logo_img': {'name': 'brand_mc.png',
    'url': 'https://d1c5n4ri2guedi.cloudfront.net/brand/4/logo_img/44573/brand_mc.png'},
   'is_visible': True},
  {'idx': 7,
   'name': 'JCB',
   'code': 'JCB',
   'logo_img': {'name': 'brand_jcb.png',
    'url': 'https://d1c5n4ri2guedi.cloudfront.net/brand/7/logo_img/44548/brand_jcb.png'},
   'is_visible': True}],
 'pre_month_money': 0,
 'only_online': False,
 'annual_fee_basic': '해외겸용 [8,000]원',
 'annual_fee_detail': 'URS 8,000원<br>해외겸용(VISA, mastercard, JCB) 10,000원<br>Platinum 15,000원<br><br>URS, UPI, S&amp; 브랜드는 로컬과 연회비가 동일하며,<br>해외 JCB(URS)/은련(UPI)/AMEX(S&amp;) 가맹점에서 사용가능합니다.<p data-f-id="pbf" style="text-align: center; font-size: 14px; margin-top: 30px; opacity: 0.65; font-family: sans-serif;">Powered by <a href="https://www.froala.com/wysiwyg-editor?pb=1" title="Froala Editor">Froala Editor</a></p>',
 'event': None,
 'pr_view_mode': '2',
 'pr_container': None,
 'pr_detail_img': [],
 'pr_detail': None,
 'is_request_name': False,
 'request_name': '카드사 바로가기',
 'request_pc': None,
 'request_m': None,
 'card_img': {'name': '1card.png',
  'url': 'https://d1c5n4ri2guedi.cloudfront.net/card/1/card_img/20083/1card.png'},
 'card_imgs': [],
 'top_benefit': [{'idx': 86,
   'tags': ['전국가맹점', '0.2~2.0%', '적립'],
   'title': '적립',
   'logo_img': {'name': 'ico_point.png',
    'url': 'https://d1c5n4ri2guedi.cloudfront.net/benefit/86/logo_img/950/ico_point.png'},
   'inputValue': ''},
  {'idx': 86,
   'tags': ['특정가맹점', '1~5%', '적립'],
   'title': '적립',
   'logo_img': {'name': 'ico_point.png',
    'url': 'https://d1c5n4ri2guedi.cloudfront.net/benefit/86/logo_img/950/ico_point.png'},
   'inputValue': ''},
  {'idx': 21,
   'tags': ['에이치디현대오일뱅크', '60원/L', '적립'],
   'title': '주유',
   'logo_img': {'name': 'ico_oil(주유).png',
    'url': 'https://d1c5n4ri2guedi.cloudfront.net/benefit/21/logo_img/859/ico_oil%28%EC%A3%BC%EC%9C%A0%29.png'},
   'inputValue': ''}],
 'c_type': 'P',
 'search_benefit': [{'title': '금융',
   'value': 6,
   'options': [{'label': '증권사', 'value': 57}]},
  {'title': '마트/편의점',
   'value': 9,
   'options': [{'label': '대형마트', 'value': 75}, {'label': '기타', 'value': 78}]},
  {'title': '모든가맹점',
   'value': 11,
   'options': [{'label': '국내외가맹점', 'value': 180}]},
  {'title': '무실적', 'value': 12, 'options': [{'label': '적립', 'value': 86}]},
  {'title': '쇼핑',
   'value': 16,
   'options': [{'label': '백화점', 'value': 97},
    {'label': '온라인쇼핑', 'value': 99},
    {'label': '홈쇼핑', 'value': 100}]},
  {'title': 'OTT/영화/문화',
   'value': 19,
   'options': [{'label': '영화', 'value': 115}]},
  {'title': '주유', 'value': 21, 'options': [{'label': '주유소', 'value': 122}]},
  {'title': '통신',
   'value': 23,
   'options': [{'label': 'KT', 'value': 129},
    {'label': 'LGU+', 'value': 130},
    {'label': 'SKT', 'value': 131}]},
  {'title': '푸드',
   'value': 24,
   'options': [{'label': '일반음식점', 'value': 133},
    {'label': '패밀리레스토랑', 'value': 135}]},
  {'title': '해외', 'value': 27, 'options': [{'label': '해외이용', 'value': 150}]}],
 'key_benefit': [{'cate': {'idx': 16,
    'idx_p': 0,
    'name': '쇼핑',
    'logo_img': {'name': 'ico_shopping(쇼핑).png',
     'url': 'https://d1c5n4ri2guedi.cloudfront.net/benefit/16/logo_img/854/ico_shopping%28%EC%87%BC%ED%95%91%29.png'},
    'sort': 2,
    'is_visible': True,
    'created_at': '2019-03-19 12:38:41',
    'updated_at': '2026-03-13 15:29:39',
    'media': [{'id': 854,
      'model_type': 'App\\CardBenefit',
      'model_id': 16,
      'collection_name': 'logo_img',
      'name': 'ico_shopping(쇼핑)',
      'file_name': 'ico_shopping(쇼핑).png',
      'mime_type': 'image/png',
      'disk': 'benefit',
      'size': 4156,
      'manipulations': [],
      'custom_properties': [],
      'responsive_images': [],
      'order_column': 843,
      'created_at': '2019-04-23 12:19:39',
      'updated_at': '2019-04-23 12:19:39'}]},
   'info': '<p><strong>롯데/ 현대백화점 마이신한포인트 1.0~5.0% 적립</strong></p><p>- 문화센타 등 비쇼핑 항목 및 온라인매장은 적립 제외</p><p>- 세일기간, 식품매장에서도 적립 서비스 제공</p><p><br></p><p><strong>롯데마트/이마트/홈플러스/토이저러스 1.0~5.0% 적립</strong></p><p>- 문화센타 등 비쇼핑 항목 및 온라인 매장은 적립 제외</p><p>- 롯데슈퍼/이마트에브리데이/이마트메트로/홈플러스익스프레스 등 할인점 계열, 슈퍼마켓(SSM)은 특별적립 대상 제외</p><p><br></p><p><strong>CJ오쇼핑/CJmall 마이신한포인트 1.0~5.0% 적립</strong></p><p>- 상품권 구매건 제외(0.2~2.0% 적립률 적용)</p>',
   'title': '쇼핑',
   'comment': '백화점/할인점/홈쇼핑·온라인몰 1.0~5.0% 적립',
   'cate_idx': 16},
  {'cate': {'idx': 11,
    'idx_p': 0,
    'name': '모든가맹점',
    'logo_img': {'name': 'ico_allStore.png',
     'url': 'https://d1c5n4ri2guedi.cloudfront.net/benefit/11/logo_img/916/ico_allStore.png'},
    'sort': 19,
    'is_visible': True,
    'created_at': '2019-03-19 12:38:41',
    'updated_at': '2026-03-13 15:29:39',
    'media': [{'id': 916,
      'model_type': 'App\\CardBenefit',
      'model_id': 11,
      'collection_name': 'logo_img',
      'name': 'ico_allStore',
      'file_name': 'ico_allStore.png',
      'mime_type': 'image/png',
      'disk': 'benefit',
      'size': 4540,
      'manipulations': [],
      'custom_properties': [],
      'responsive_images': [],
      'order_column': 893,
      'created_at': '2019-05-07 17:12:16',
      'updated_at': '2019-05-07 17:12:16'}]},
   'info': '<p><strong>전국 가맹점 0.2~2.0% 적립</strong></p><p>- 국내 어디서나 이용한 일시불/할부 금액의 0.2~2.0% 마이신한포인트 적립</p><p>&nbsp; * 1.0~5.0% 적립처, 60원/ℓ 적립처를 제외한 전국 모든 가맹점을 대상으로 함.</p><p>&nbsp; * 지방세 및 선불충전형카드(기프트카드 등), 수도요금 적립제외</p><p><br></p><p><strong>해외 가맹점 1.0~5.0% 마이신한포인트 적립</strong></p><p>- 해외가맹점 일시불/할부 이용금액에 대하여 1.0~5.0% 마이신한포인트 적립</p>',
   'title': '모든가맹점',
   'comment': '전국 가맹점 0.2~2.0% 적립\n해외 가맹점 1~5% 적립',
   'cate_idx': 11},
  {'cate': {'idx': 21,
    'idx_p': 0,
    'name': '주유',
    'logo_img': {'name': 'ico_oil(주유).png',
     'url': 'https://d1c5n4ri2guedi.cloudfront.net/benefit/21/logo_img/859/ico_oil%28%EC%A3%BC%EC%9C%A0%29.png'},
    'sort': 9,
    'is_visible': True,
    'created_at': '2019-03-19 12:38:41',
    'updated_at': '2026-03-13 15:29:39',
    'media': [{'id': 859,
      'model_type': 'App\\CardBenefit',
      'model_id': 21,
      'collection_name': 'logo_img',
      'name': 'ico_oil(주유)',
      'file_name': 'ico_oil(주유).png',
      'mime_type': 'image/png',
      'disk': 'benefit',
      'size': 3610,
      'manipulations': [],
      'custom_properties': [],
      'responsive_images': [],
      'order_column': 848,
      'created_at': '2019-04-23 12:20:45',
      'updated_at': '2019-04-23 12:20:45'}]},
   'info': '<p><strong>S-OIL / 에이치디현대오일뱅크 주유 시 리터 당 60원 마이신한포인트 적립</strong></p><p>- S-OIL/에이치디현대오일뱅크 리터 당 60원 적립</p><p>- 적립포인트 산정방법 = 주유이용금액 &times; 리터당 적립금액(60원) / 기준유가</p><p>&nbsp; * 기준유가 : S-OIL/에이치디현대오일뱅크가 통보한 휘발유가입니다.</p><p>- S-OIL/에이치디현대오일뱅크 정유사별 월 2회, 주유금액 20만원까지 적립</p><p>- 주유금액 20만원 월한도 초과시 다음 결제건부터 0.2~2.0% 적립처와 동일한 포인트 적립</p><p>- 정유사가 통보한 휘발유 표준 고시유가 기준</p><p>&nbsp; * LPG 충전소 제외, 경유&middot;등유는 휘발유가로 계산되어 적립됩니다.</p>',
   'title': '주유',
   'comment': 'S-OIL, 에이치디현대오일뱅크 주유 시 리터 당 60원 적립',
   'cate_idx': 21},
  {'cate': {'idx': 6,
    'idx_p': 0,
    'name': '금융',
    'logo_img': {'name': 'ico_finance.png',
     'url': 'https://d1c5n4ri2guedi.cloudfront.net/benefit/6/logo_img/911/ico_finance.png'},
    'sort': 23,
    'is_visible': True,
    'created_at': '2019-03-19 12:38:41',
    'updated_at': '2026-03-13 15:29:39',
    'media': [{'id': 911,
      'model_type': 'App\\CardBenefit',
      'model_id': 6,
      'collection_name': 'logo_img',
      'name': 'ico_finance',
      'file_name': 'ico_finance.png',
      'mime_type': 'image/png',
      'disk': 'benefit',
      'size': 8475,
      'manipulations': [],
      'custom_properties': [],
      'responsive_images': [],
      'order_column': 888,
      'created_at': '2019-05-07 17:11:21',
      'updated_at': '2019-05-07 17:11:21'}]},
   'info': '<p><strong>신한투자증권 CMA 결제계좌 지정 시 신판이용 금액의 0.2% 마이신한포인트 추가 적립</strong></p><p>- 결제일 기준 적용</p><p>&nbsp; ex) 3월 21일 결제일인 경우, 3월 18일 결제계좌로 지정되더라도 이전 승인 건에 대하여 적립 적용</p><p>* 금융투자의 경우, 결제계좌 변경 시 실반영까지 3~4영업일의 시일이 소요될 수 있으므로 이를 고려하여 변경 바랍니다.</p><p>* 무이자할부는 적립 제외/월한도 적용 없음</p><p>* 0.2% 추가적립 서비스도 &lsquo;포인트 상세기준&rsquo; (8~9페이지)의 모든 적립 기준이 동일하게 적용됩니다.</p><p><br></p><p><strong>마이신한포인트 가맹점</strong></p><p>- 마이신한포인트 가맹점에서 제공하는 포인트 추가 적립</p><p>- 신한카드 홈페이지(www.shinhancard.com)내, 마이신한포인트 페이지에서 적립가맹점 확인</p>',
   'title': '금융',
   'comment': '신한투자증권 CMA 결제계좌 0.2% 추가 적립\n마이신한포인트 가맹점 추가 적립',
   'cate_idx': 6},
  {'cate': {'idx': 23,
    'idx_p': 0,
    'name': '통신',
    'logo_img': {'name': 'ico_mobile(통신).png',
     'url': 'https://d1c5n4ri2guedi.cloudfront.net/benefit/23/logo_img/861/ico_mobile%28%ED%86%B5%EC%8B%A0%29.png'},
    'sort': 7,
    'is_visible': True,
    'created_at': '2019-03-19 12:38:41',
    'updated_at': '2026-03-13 15:29:39',
    'media': [{'id': 861,
      'model_type': 'App\\CardBenefit',
      'model_id': 23,
      'collection_name': 'logo_img',
      'name': 'ico_mobile(통신)',
      'file_name': 'ico_mobile(통신).png',
      'mime_type': 'image/png',
      'disk': 'benefit',
      'size': 2621,
      'manipulations': [],
      'custom_properties': [],
      'responsive_images': [],
      'order_column': 850,
      'created_at': '2019-04-23 12:21:57',
      'updated_at': '2019-04-23 12:21:57'}]},
   'info': '<p><strong>SK텔레콤/KT/LG U+ 이동통신요금 1.0~5.0% 적립</strong></p><p>- SK텔레콤/KT/LG U+ 이동통신요금 자동이체 결제금액(KT 통신요금 결합상품 통합 과금 포함)</p><p>- 자동이체 건수에 관계없이 포인트 적립(가족도 가능)</p><p>&nbsp; * 순수 결제금액 자동이체외 요금은 적립불가(약정금액 대납, 지점을 통한 월납 제외)</p><p>- 결제금액 기준 월 10만원 한도(10만원 초과 결제건 이후의 추가 결제건에 대해서는 0.2~2.0% 적립률 적용)</p><p>&nbsp; 예) 13만원 결제 시, 10만원에 대해 특별 적립률(1.0~5.0%)이 적용되며 나머지 3만원에 대해서는 서비스 적용되지 않음. 이후 결제 건부터 일반적립률(0.2~2.0%) 적용됨.</p>',
   'title': '통신',
   'comment': 'SK텔레콤/KT/LG U+ 이동통신요금 1.0~5.0% 적립',
   'cate_idx': 23},
  {'cate': {'idx': 7,
    'idx_p': 0,
    'name': '기타',
    'logo_img': {'name': 'ico_etc.png',
     'url': 'https://d1c5n4ri2guedi.cloudfront.net/benefit/7/logo_img/912/ico_etc.png'},
    'sort': 27,
    'is_visible': True,
    'created_at': '2019-03-19 12:38:41',
    'updated_at': '2026-03-13 15:29:39',
    'media': [{'id': 912,
      'model_type': 'App\\CardBenefit',
      'model_id': 7,
      'collection_name': 'logo_img',
      'name': 'ico_etc',
      'file_name': 'ico_etc.png',
      'mime_type': 'image/png',
      'disk': 'benefit',
      'size': 5482,
      'manipulations': [],
      'custom_properties': [],
      'responsive_images': [],
      'order_column': 889,
      'created_at': '2019-05-07 17:11:34',
      'updated_at': '2019-05-07 17:11:34'}]},
   'info': '<p><strong>4대 백화점, 3대 할인점 무이자 할부 서비스</strong></p><p>- 백화점 : 롯데백화점, 현대백화점, 신세계백화점, 갤러리아백화점</p><p>- 할인점 : 롯데마트, 이마트, 홈플러스(구 홈에버 포함) 2~3개월 무이자 할부 제공</p><p>&nbsp; * 문화센터 등 비쇼핑 항목 및 온라인 매장은 제외</p><p>&nbsp; * 롯데슈퍼/이마트 에브리데이/홈플러스 익스프레스 등 슈퍼슈퍼마켓(SSM)은 제외</p><p>&nbsp; * 무이자할부 이용시 포인트 적립은 제외됩니다.</p><p><br></p><p><strong>온라인 영화 할인</strong></p><p>- CGV, 메가박스에서 영화 에매 시 최대 3,000원 결제일 할인</p><p>- 9천원 이상일 경우 1,500원 할인, 18천원 이상일 경우 3,000원 할인</p><p>- 제공 기준 : 통합 1일 2회, 월 6회, 연 15회에 한함 (年 기준: 1월~12월)</p><p>* 온라인 영화 할인 서비스의 경우 공식 홈페이지 및 APP을 통해 예매 시 제공됩니다.</p><p><br></p><p><strong>에버랜드, 롯데월드, 서울랜드 50% 할인 서비스</strong></p><p>- 1일 1회, 연 3회 할인 가능 / 본인 자유이용권에 한함</p><p><strong>캐리비안베이 입장권 30% 할인 서비스</strong></p><p>- 1일 1회, 연 3회 할인 가능 / 본인입장권에 한해 할인</p><p><br></p><p>*상기 테마/워터파크 및 영화 할인 서비스는 &nbsp;이용 직전월 Hi-Point &nbsp;일시불,할부 이용액이 30만원 이상일 경우 할인 가능합니다.(교통카드 이용금액은 전월기준 합산)</p><p>*신규발급 회원에 대해서는 카드 사용 등록월 포함 2개월은 실적 제한없이 서비스가 제공됩니다.</p><p>*신한카드 Hi-Point 계열 간 직전월 실적 합산, 이용횟수 동시 차감됩니다.</p><p>*본인/가족카드 복수 소지 시, 제공실적 및 횟수는 본인/가족 별도 운영됩니다.</p>',
   'title': '기타',
   'comment': '무이자/영화/테마파크',
   'cate_idx': 7},
  {'cate': {'idx': 86,
    'idx_p': 12,
    'name': '적립',
    'logo_img': {'name': 'ico_point.png',
     'url': 'https://d1c5n4ri2guedi.cloudfront.net/benefit/86/logo_img/950/ico_point.png'},
    'sort': 0,
    'is_visible': True,
    'created_at': '2019-03-19 12:38:41',
    'updated_at': '2019-05-07 17:24:30',
    'media': [{'id': 950,
      'model_type': 'App\\CardBenefit',
      'model_id': 86,
      'collection_name': 'logo_img',
      'name': 'ico_point',
      'file_name': 'ico_point.png',
      'mime_type': 'image/png',
      'disk': 'benefit',
      'size': 6619,
      'manipulations': [],
      'custom_properties': [],
      'responsive_images': [],
      'order_column': 927,
      'created_at': '2019-05-07 17:24:30',
      'updated_at': '2019-05-07 17:24:30'}]},
   'info': '<p><strong>포인트 적립율 산정</strong></p><p>- 직전월 일시불/할부 이용실적을 기준으로 당월의 매 승인 건에 대한 적립율이 결정됩니다.</p><p>&nbsp; * 당월 결제일에 청구되는 금액에 대한 적립률이 아닙니다</p><table border="0" cellpadding="0" cellspacing="0" class="b-table" width="100%"><tbody><tr class="b-table-top"><td class="b-table-top">전월 신판 이용금액</td><td class="b-table-top">50만원 미만</td><td class="b-table-top">50만원 이상~100만원 미만</td><td class="b-table-top">100만원 이상~150만원 미만</td><td class="b-table-top">150만원 이상</td></tr><tr><td>1~5% 적립처</td><td>1.0%</td><td>2.0%</td><td>3.5%</td><td>5.0%</td></tr><tr><td>0.2~2% 적립처</td><td>0.2%</td><td>0.8%</td><td>1.5%</td><td>2.0%</td></tr></tbody></table><p>- 신한카드 Hi-Point 이용금액만 반영됩니다.</p><p>- 전월 이용금액은 전월 1일부터 말일까지의 거래시점 이용금액으로 반영됩니다.</p><p>&nbsp; * 교통카드 이용금액은 전전월 이용금액이 반영됩니다.</p><p>&nbsp; * 해외이용금액은 매입일자 기준으로 반영됩니다.(해외이용금액은 승인일자와 매입일자의 차이가 큰 관계로 매입 후, 매입일자 기준으로 실적 반영됩니다)</p><p>- 신규 회원의 경우 카드사용 등록월의 익월말(등록월+1개월)까지 &lsquo;50~100만원 미만&rsquo; 이용금액 구간의 적립율을 제공합니다.</p><p>&nbsp;</p><p><strong>포인트 적립 안내</strong></p><p>- 신한카드 하이포인트로 마이신한포인트는 월 최대 5만원까지 적립됩니다. (해당월 총 청구금액 기준/가족카드 및 복수카드 통합한도임)&nbsp;</p><p>&nbsp; * 결제월에 청구되는 총금액 기준입니다.&nbsp;</p><p>&nbsp; * 가족카드 및 복수카드에 통합 적용됩니다.</p><p>&nbsp; * +&alpha;서비스(CMA+0.2%, 마이신한포인트 가맹점)를 통한 포인트 적립 금액은 월 한도 적용을 받지 않습니다.</p><p>&nbsp; * 가맹점 전표매입이 지연되는 승인건의 경우 익월 청구될 수 있으며 이 경우 해당 청구월의 5만원 한도를 적용 받게 됩니다.&nbsp;</p><p><br></p><p><strong>포인트 적립 시점</strong></p><p>- 매월 결제일에 적립됩니다.&nbsp;</p><p>- 일부결제금액이월약정(리볼빙) 매출건의 경우 입금 비율과 관계없이 첫 결제일에 전액 적립됩니다.&nbsp;</p><p>- 할부이용금액은 매월 청구되는 분할금액 기준으로 적립됩니다.</p><p>- 중도 상환/선입금 시 상환/입금 당일에 적립 되나, 상환/입금일 당일 매입 처리된 거래에 대해서는 원결제일에 적립이 되오니 유의하시기 바랍니다.</p><p>- 중도 상환/선입금에 의한 포인트 적립의 경우, 포인트가 적립되는 월 기준이 아닌, 중도 상환/선입금한 해당 거래건의 결제월 기준으로 월한도를 적용 받게 됩니다.&nbsp;</p><p>&nbsp; [예] 결제일이 25일인 회원의 경우,&nbsp;</p><p>&nbsp; - 6월 15일 거래건을 6월 24일 중도상환 시 포인트는 6월 24일에 적립&nbsp;</p><p>&nbsp; - 월포인트 적립한도(5만 포인트)는 6월 15일 거래의 결제일인 7월 25일에 해당하는 신용제공기간 內 거래건의 적립 포인트와 합산되어 적용</p><p><br></p><p><strong>포인트 적립 제외 대상</strong></p><p>- 무이자할부/슬림할부</p><p>- 단기카드대출(현금서비스)/장기카드대출(카드론)/연회비/각종 수수료/이자 /포인트사용건/기프트카드 등 당사 선불카드 (Pre ⓘ, Maxx등) 충전실적 /당사 모든 할인 서비스 이용 금액&nbsp;</p><p>* 해외에서 일시불 이용 후, 국내에서 할부로 전환하시는 경우, &lsquo;0.2~2.0% 적립처&rsquo;로 적립률이 재산정됩니다.</p><p>* 포인트 소멸 등 기본 정책은 마이신한포인트 기본 정책을 따릅니다.</p><p>* 신한카드 Hi-Point, Nano, Nano F 동시소지 고객은 카드별 이용금액이 개별 산정되며 월 한도 역시 개별 적용됩니다.(단, Hi-Save 약정 시에는 통합 적용됨)</p><p><br></p><p><strong>포인트 사용 방법</strong></p><p><strong>[상품권]</strong></p><p>&nbsp;- 롯데백화점/신세계백화점/현대백화점/갤러리아/백화점세이/이마트/홈플러스/롯데마트/메가마트</p><p>&nbsp; * 백화점/마트 상품권 데스크에서 상품권으로 교환</p><p>&nbsp; * 상품권 교환 시 부분 신판결제(일시불+할부) 불가(포인트로 전액 사용)</p><p>&nbsp; * 5천원권 이상부터 교환가능 (현대백화점은 1만원권 이상부터 교환가능)</p><p>- 컬쳐랜드</p><p>&nbsp; * 컬쳐랜드(www.cultureland.co.kr)에서 포인트로 상품권 교환</p><p>&nbsp; * 5천원(온라인상품권)/5만원(실물상품권) 이상부터 사용 가능</p><p>&nbsp; * 온라인상품권은 e-mail 배송/실물상품권은 등기우편 배송</p><p><strong>[주유소]</strong></p><p>- S-OIL, 에이치디현대오일뱅크 주유 시 포인트 전액 결제</p><p>- 주유소 직원에게 포인트 사용 요청 후 주유(주유소 직원이 잘 모르는 경우, &ldquo;60할부 결제해 주세요&rdquo;라고 요청)</p><p>- 포인트 부족시 일시불/할부 이용금액으로 결제</p><p>- S-OIL은 LPG충전소 포인트 사용 불가(에이치디현대오일뱅크는 가능)</p><p><strong>[마일리지전환]</strong></p><p>- 아시아나항공 마일리지 전환(20포인트-&gt;1마일, 50마일 단위신청)</p><p>&nbsp; * 일 1회, 연간(1~12월 누적) 10만 마일리지까지 전환 가능</p><p>&nbsp; * 가족카드로 신청 가능(단, 본인회원의 아시아나 마일리지로 적립됨)</p><p>&nbsp;- 대한항공 마일리지 전환(25포인트-&gt;1마일, 50마일 단위신청)</p><p>&nbsp; * 일 1회, 연간(1~12월 누적) 3만 마일리지까지 전환 가능</p><p>&nbsp; * 가족카드로 신청 가능(단, 본인회원의 아시아나 마일리지로 적립됨)</p><p><strong>[테마파크]</strong></p><p>- 롯데월드 자유이용권 본인 50% + 동반자 40% 할인</p><p>&nbsp; * 동반자 40% 할인 = 20% 포인트 차감결제 + 20% 보너스 할인</p><p>&nbsp; * 인원수 제한없음 / 차감결제에 해당하는 포인트 보유회원에 한함</p><p>&nbsp; * 본인 50% 할인은 직전월 카드사용액 30만원 이상 시 제공</p><p><strong>[쇼핑/온라인몰]</strong></p><p>- 전액결제가능: 벅스, 롯데월드 아쿠아리움, 키자니아, CU&nbsp;</p><p>- 30% 포인트 차감 결제 가능: CJ오쇼핑/CJmall</p><p>- 10% 포인트 차감 결제 가능: 반디앤루니스 결제금액&nbsp;</p><p>* 결제 시 매장직원에게 포인트 사용 요청</p><p>* 포인트 부족 시 일시불/할부로 잔여 금액 결제 가능(CU 제외)</p><p>* 반디앤루니스 온라인 매장 사용 가능(단, 백화점 입점 매장은 제외)</p><p><strong>[요식]</strong></p><p>- 전액결제가능: 아웃백스테이크하우스/온더보더/TGI.Friday</p><p>- 30% 포인트 차감 결제 가능: 불고기브라더스, 도미노피자</p><p>- 20% 포인트 차감 결제 가능: 빕스</p><p>- 15% 포인트 차감 결제 가능: 뚜레쥬르</p><p>- 10% 포인트 차감 결제 가능: 닥터로빈</p><p>* 결제 시 매장직원에게 포인트 사용 요청</p><p>* 잔여포인트 부족 시 잔여포인트만큼 사용 가능(단, 도미노피자는 제외)</p><p>* 닥터로빈 서울지역 매장에 한함</p><p>* 백화점/ 쇼핑몰 등 입점 매장은 제외</p><p><strong>[펀드불입]</strong></p><p>- 신한투자증권 사이트에서 포인트로 펀드불입</p><p>- 펀드매수 화면에서 포인트 사용하기 체크한 후 사용</p>',
   'title': '적립',
   'editor': False,
   'comment': '포인트 적립상세 및 포인트 사용 안내',
   'cate_idx': 86},
  {'cate': {'idx': 28,
    'idx_p': 0,
    'name': '유의사항',
    'logo_img': {'name': 'ico_note(유의사항).png',
     'url': 'https://d1c5n4ri2guedi.cloudfront.net/benefit/28/logo_img/866/ico_note%28%EC%9C%A0%EC%9D%98%EC%82%AC%ED%95%AD%29.png'},
    'sort': 30,
    'is_visible': True,
    'created_at': '2019-03-19 12:38:41',
    'updated_at': '2026-03-13 15:29:39',
    'media': [{'id': 866,
      'model_type': 'App\\CardBenefit',
      'model_id': 28,
      'collection_name': 'logo_img',
      'name': 'ico_note(유의사항)',
      'file_name': 'ico_note(유의사항).png',
      'mime_type': 'image/png',
      'disk': 'benefit',
      'size': 4513,
      'manipulations': [],
      'custom_properties': [],
      'responsive_images': [],
      'order_column': 855,
      'created_at': '2019-04-23 12:22:46',
      'updated_at': '2019-04-23 12:22:46'}]},
   'info': '<p>- 계약 체결 전 상품에 관한 사항은 상품설명서 및 약관을 읽어보시기 바랍니다.</p><p>※ 카드이용시 제공되는 포인트 및 할인혜택 등의 부가서비스는 카드 신규출시(2018.03.12) 이후 3년 이상 축소, 폐지 없이 유지됩니다.</p><p>※ 상기에도 불구하고, 다음과 같은 사유가 발생한 경우 카드사는 부가서비스를 변경할 수 있습니다.</p><p>&nbsp; &nbsp; &nbsp;① 카드사의 휴업&middot;파산&middot;경영상의 위기 등에 따른 불가피한 경우</p><p>&nbsp; &nbsp; &nbsp;② 제휴업체의 휴업&bull;파산&bull;경영상의 위기로 인해 불가피하게 부가서비스를 축소&bull;변경하는 경우로서 다른 제휴업체를 통해 동종의 유사한 부가서비스 제공이 불가한 경우</p><p>&nbsp; &nbsp; &nbsp;③ 제휴업체가 카드사의 의사에 반하여 해당 부가서비스를 축소하거나 변경 시, 당초 부가서비스에 상응하는 다른 부가서비스를 제공하는 경우</p><p>&nbsp; &nbsp; &nbsp;④ 부가서비스를 3년 이상 제공한 상태에서 해당 부가서비스로 인해 카드의 수익성이 현저히 낮아진 경우</p><p>※ 카드사가 부가서비스를 변경하는 경우에는 부가서비스 변경 사유, 변경 내용 등을 사유발생 즉시 아래 고지방법 중 2가지 이상의 방법으로 고지해 드립니다. 특히 부가서비스를 3년 이상 제공한 상태에서 해당 부가서비스로 인해 카드의 수익성이 현저히 낮아져 부가서비스를 변경하는 경우에는 6개월 전부터 아래 고지방법 중2가지 이상의 방법으로 매월 고지해 드립니다.</p><p>- 고지 방법 : 서면 교부, 우편 또는 전자우편, 전화 또는 팩스, 휴대폰 메시지 또는 이에 준하는 전자적 의사표시</p>',
   'title': '유의사항',
   'editor': False,
   'comment': '꼭 확인하세요!',
   'cate_idx': 28}],

In [44]:
for card_id in tqdm.tqdm(range(1, 3000)):
    url = f"https://api.card-gorilla.com:8080/v1/cards/{card_id}"
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36'}
    
    try:
        response = requests.get(url, headers=headers)
        if response.status_code == 200:
            raw_data = response.json()

            card_info = {
                '카드번호': card_id,
                '카드명': raw_data.get('name', '이름없음'),       # name 키가 없으면 '이름없음' 반환
                '카드사': raw_data.get('corp').get('name', '알수없음'),  # 예: 신한카드
                '카드타입': raw_data.get('cate', '알수없음')     # 예: 신용/체크
                }
            
            card_data_list.append(card_info)
            print(f"[성공] {card_id}번 카드 ({card_info['카드명']}) 수집 완료")

        elif response.status_code == 404:
            print(f"[Skip] {card_id}번 카드 정보가 존재하지 않습니다.")
        else:
            print(f"[Error] {card_id}번 카드 정보 요청 실패 (상태 코드: {response.status_code})")
    
    except Exception as e:
        print(f"[오류] {card_id}번 카드 정보 요청 중 예외 발생: {e}")

    time.sleep(1)

  0%|          | 0/2999 [00:00<?, ?it/s]

[성공] 1번 카드 (신한카드 Hi-Point) 수집 완료

  0%|          | 1/2999 [00:01<57:31,  1.15s/it]

[성공] 2번 카드 (신한카드 Love) 수집 완료

  0%|          | 2/2999 [00:02<56:43,  1.14s/it]

[성공] 3번 카드 (신한카드 Lady) 수집 완료

  0%|          | 3/2999 [00:03<56:02,  1.12s/it]

[성공] 4번 카드 (SK에너지 신한카드The you) 수집 완료

  0%|          | 4/2999 [00:04<55:38,  1.11s/it]

[Skip] 5번 카드 정보가 존재하지 않습니다.

  0%|          | 5/2999 [00:05<55:55,  1.12s/it]

[Skip] 6번 카드 정보가 존재하지 않습니다.

  0%|          | 6/2999 [00:06<54:49,  1.10s/it]

[Skip] 7번 카드 정보가 존재하지 않습니다.

  0%|          | 7/2999 [00:07<54:09,  1.09s/it]

[성공] 8번 카드 (신한카드 The CLASSIC-Y) 수집 완료

  0%|          | 8/2999 [00:08<54:43,  1.10s/it]

[Skip] 9번 카드 정보가 존재하지 않습니다.

  0%|          | 9/2999 [00:09<54:03,  1.08s/it]

[성공] 10번 카드 (신한카드 B.Big(삑)) 수집 완료

  0%|          | 10/2999 [00:11<58:19,  1.17s/it]

[성공] 11번 카드 (신한카드 Simple+) 수집 완료

  0%|          | 11/2999 [00:12<57:43,  1.16s/it]

[성공] 12번 카드 (신한카드 Air Platinum#) 수집 완료

  0%|          | 12/2999 [00:13<57:19,  1.15s/it]

[성공] 13번 카드 (신한카드 Mr.Life) 수집 완료

  0%|          | 13/2999 [00:14<57:22,  1.15s/it]

[성공] 14번 카드 (신한카드 YOLO ⓘ) 수집 완료

  0%|          | 14/2999 [00:15<56:38,  1.14s/it]

[성공] 15번 카드 (신한카드 The CLASSIC+) 수집 완료

  1%|          | 15/2999 [00:16<56:37,  1.14s/it]

[성공] 16번 카드 (신한카드 RPM+ Platinum#) 수집 완료

  1%|          | 16/2999 [00:18<1:00:44,  1.22s/it]

[Skip] 17번 카드 정보가 존재하지 않습니다.

  1%|          | 17/2999 [00:19<58:12,  1.17s/it]

[성공] 18번 카드 (신한카드 Shopping) 수집 완료

  1%|          | 18/2999 [00:20<1:02:10,  1.25s/it]

[Skip] 19번 카드 정보가 존재하지 않습니다.

  1%|          | 19/2999 [00:21<1:00:39,  1.22s/it]

[Skip] 20번 카드 정보가 존재하지 않습니다.

  1%|          | 20/2999 [00:23<59:16,  1.19s/it]

[성공] 21번 카드 (신한카드 Simple Platinum#) 수집 완료

  1%|          | 21/2999 [00:24<59:53,  1.21s/it]

[Skip] 22번 카드 정보가 존재하지 않습니다.

  1%|          | 22/2999 [00:25<58:09,  1.17s/it]

[Skip] 23번 카드 정보가 존재하지 않습니다.

  1%|          | 23/2999 [00:26<56:41,  1.14s/it]

[Skip] 24번 카드 정보가 존재하지 않습니다.

  1%|          | 24/2999 [00:27<55:22,  1.12s/it]

[Skip] 25번 카드 정보가 존재하지 않습니다.

  1%|          | 25/2999 [00:28<54:24,  1.10s/it]

[성공] 26번 카드 (신한카드 Edu) 수집 완료

  1%|          | 26/2999 [00:29<55:34,  1.12s/it]

[Skip] 27번 카드 정보가 존재하지 않습니다.

  1%|          | 27/2999 [00:30<54:42,  1.10s/it]

[성공] 28번 카드 (신세계 신한카드) 수집 완료

  1%|          | 28/2999 [00:31<54:45,  1.11s/it]

[Skip] 29번 카드 정보가 존재하지 않습니다.

  1%|          | 29/2999 [00:33<53:57,  1.09s/it]

[Skip] 30번 카드 정보가 존재하지 않습니다.

  1%|          | 30/2999 [00:34<53:34,  1.08s/it]

[Skip] 31번 카드 정보가 존재하지 않습니다.

  1%|          | 31/2999 [00:35<53:10,  1.08s/it]

[Skip] 32번 카드 정보가 존재하지 않습니다.

  1%|          | 32/2999 [00:36<52:53,  1.07s/it]

[Skip] 33번 카드 정보가 존재하지 않습니다.

  1%|          | 33/2999 [00:37<52:36,  1.06s/it]

[Skip] 34번 카드 정보가 존재하지 않습니다.

  1%|          | 34/2999 [00:38<52:31,  1.06s/it]

[성공] 35번 카드 (GS칼텍스 신한카드 Shine) 수집 완료

  1%|          | 35/2999 [00:39<53:36,  1.09s/it]

[성공] 36번 카드 (신한카드 Cube Platinum#) 수집 완료

  1%|          | 36/2999 [00:40<54:19,  1.10s/it]

[성공] 37번 카드 (신한카드 The BEST-F) 수집 완료

  1%|          | 37/2999 [00:41<55:10,  1.12s/it]

[성공] 38번 카드 (신한카드 Lesson Platinum#) 수집 완료

  1%|▏         | 38/2999 [00:42<55:23,  1.12s/it]

[성공] 39번 카드 (신한카드 Deep Oil) 수집 완료

  1%|▏         | 39/2999 [00:44<56:15,  1.14s/it]

[Skip] 40번 카드 정보가 존재하지 않습니다.

  1%|▏         | 40/2999 [00:45<55:00,  1.12s/it]

[성공] 41번 카드 (신한카드 Deep On Platinum+) 수집 완료

  1%|▏         | 41/2999 [00:46<55:15,  1.12s/it]

[성공] 42번 카드 (SOCAR 제휴 SOCAR 신한카드) 수집 완료

  1%|▏         | 42/2999 [00:47<55:10,  1.12s/it]

[성공] 43번 카드 (신한카드 Deep Store) 수집 완료

  1%|▏         | 43/2999 [00:48<55:00,  1.12s/it]

[Skip] 44번 카드 정보가 존재하지 않습니다.

  1%|▏         | 44/2999 [00:49<54:07,  1.10s/it]

[성공] 45번 카드 (American Express Blue) 수집 완료

  2%|▏         | 45/2999 [00:50<55:17,  1.12s/it]

[성공] 46번 카드 (삼성카앤모아카드) 수집 완료

  2%|▏         | 46/2999 [00:51<57:08,  1.16s/it]

[성공] 47번 카드 (삼성카드4) 수집 완료

  2%|▏         | 47/2999 [00:53<58:26,  1.19s/it]

[성공] 48번 카드 (국민행복 삼성카드) 수집 완료

  2%|▏         | 48/2999 [00:54<57:17,  1.16s/it]

[성공] 49번 카드 (삼성카드 & MILEAGE PLATINUM (스카이패스)) 수집 완료

  2%|▏         | 49/2999 [00:55<57:08,  1.16s/it]

[성공] 50번 카드 (아시아나 삼성지엔미플래티늄카드) 수집 완료

  2%|▏         | 50/2999 [00:56<56:10,  1.14s/it]

[성공] 51번 카드 (삼성카드 taptap O) 수집 완료

  2%|▏         | 51/2999 [00:57<56:30,  1.15s/it]

[성공] 52번 카드 (삼성카드 taptap S) 수집 완료

  2%|▏         | 52/2999 [00:59<58:15,  1.19s/it]

[성공] 53번 카드 (아시아나 삼성애니패스플래티늄카드) 수집 완료

  2%|▏         | 53/2999 [01:00<57:06,  1.16s/it]

[성공] 54번 카드 (삼성카드 스페셜마일리지(스카이패스)) 수집 완료

  2%|▏         | 54/2999 [01:01<56:45,  1.16s/it]

[성공] 55번 카드 (CU·배달의민족 삼성카드 taptap) 수집 완료

  2%|▏         | 55/2999 [01:02<56:37,  1.15s/it]

[성공] 56번 카드 (삼성카드 지엔미+) 수집 완료

  2%|▏         | 56/2999 [01:03<56:17,  1.15s/it]

[성공] 57번 카드 (삼성카드 애니패스+) 수집 완료

  2%|▏         | 57/2999 [01:04<56:29,  1.15s/it]

[성공] 58번 카드 (카라이프 삼성카드 DISCOUNT+) 수집 완료

  2%|▏         | 58/2999 [01:06<1:02:30,  1.28s/it]

[성공] 59번 카드 (삼성카드 taptap I) 수집 완료

  2%|▏         | 59/2999 [01:07<1:00:33,  1.24s/it]

[성공] 60번 카드 (American Express Green) 수집 완료

  2%|▏         | 60/2999 [01:08<58:44,  1.20s/it]

[성공] 61번 카드 (스카이패스 삼성아멕스카드) 수집 완료

  2%|▏         | 61/2999 [01:09<57:11,  1.17s/it]

[성공] 62번 카드 (글로벌쇼핑 삼성카드 5 V2) 수집 완료

  2%|▏         | 62/2999 [01:10<56:36,  1.16s/it]

[성공] 63번 카드 (삼성페이 삼성카드 taptap) 수집 완료

  2%|▏         | 63/2999 [01:11<55:39,  1.14s/it]

[성공] 64번 카드 (신세계이마트 삼성카드7) 수집 완료

  2%|▏         | 64/2999 [01:12<55:07,  1.13s/it]

[성공] 65번 카드 (삼성카드 2V3(아지냥이 Edition)) 수집 완료

  2%|▏         | 65/2999 [01:14<54:50,  1.12s/it]

[성공] 66번 카드 (삼성카드 6V3) 수집 완료

  2%|▏         | 66/2999 [01:15<54:27,  1.11s/it]

[성공] 67번 카드 (삼성카드 3V3(GS칼텍스)) 수집 완료

  2%|▏         | 67/2999 [01:16<56:11,  1.15s/it]

[성공] 68번 카드 (삼성카드 3V3(SK에너지)) 수집 완료

  2%|▏         | 68/2999 [01:17<56:05,  1.15s/it]

[성공] 69번 카드 (삼성카드 4V3(포인트)) 수집 완료

  2%|▏         | 69/2999 [01:18<57:00,  1.17s/it]

[성공] 70번 카드 (삼성카드 5V3) 수집 완료

  2%|▏         | 70/2999 [01:19<56:06,  1.15s/it]

[성공] 71번 카드 (삼성카드 4V3) 수집 완료

  2%|▏         | 71/2999 [01:20<55:41,  1.14s/it]

[성공] 72번 카드 (트레이더스신세계 삼성카드) 수집 완료

  2%|▏         | 72/2999 [01:22<55:31,  1.14s/it]

[성공] 73번 카드 (카드의정석 NEW우리V카드) 수집 완료

  2%|▏         | 73/2999 [01:23<55:09,  1.13s/it]

[성공] 74번 카드 (All For Me카드) 수집 완료

  2%|▏         | 74/2999 [01:24<54:54,  1.13s/it]

[성공] 75번 카드 (KT 카드의정석 Super DC) 수집 완료

  3%|▎         | 75/2999 [01:25<54:13,  1.11s/it]

[성공] 76번 카드 (LGU+ 카드의정석 장기할부) 수집 완료

  3%|▎         | 76/2999 [01:26<56:09,  1.15s/it]

[성공] 77번 카드 (위비멤버스카드) 수집 완료

  3%|▎         | 77/2999 [01:27<57:46,  1.19s/it]

[성공] 78번 카드 (블루다이아몬드Ⅱ 카드) 수집 완료

  3%|▎         | 78/2999 [01:29<58:04,  1.19s/it]

[성공] 79번 카드 (그랑블루Ⅱ카드) 수집 완료

  3%|▎         | 79/2999 [01:30<57:11,  1.18s/it]

[성공] 80번 카드 (썸(SUM) 페이 카드) 수집 완료

  3%|▎         | 80/2999 [01:31<56:09,  1.15s/it]

[성공] 81번 카드 (위메프 우리카드) 수집 완료

  3%|▎         | 81/2999 [01:32<55:08,  1.13s/it]

[성공] 82번 카드 (우리 XGOLF 카드) 수집 완료

  3%|▎         | 82/2999 [01:33<55:07,  1.13s/it]

[성공] 83번 카드 (ONLY 나만의카드) 수집 완료

  3%|▎         | 83/2999 [01:34<55:22,  1.14s/it]

[성공] 84번 카드 (카드의정석 POINT) 수집 완료

  3%|▎         | 84/2999 [01:35<55:11,  1.14s/it]

[성공] 85번 카드 (카드의정석 SHOPPING) 수집 완료

  3%|▎         | 85/2999 [01:37<58:23,  1.20s/it]

[성공] 86번 카드 (카드의정석 DISCOUNT) 수집 완료

  3%|▎         | 86/2999 [01:38<57:00,  1.17s/it]

[성공] 87번 카드 (DA@카드의정석) 수집 완료

  3%|▎         | 87/2999 [01:39<58:25,  1.20s/it]

[성공] 88번 카드 (D4@카드의정석) 수집 완료

  3%|▎         | 88/2999 [01:40<57:06,  1.18s/it]

[성공] 89번 카드 (우리Most카드) 수집 완료

  3%|▎         | 89/2999 [01:41<56:18,  1.16s/it]

[성공] 90번 카드 (카드의정석 위비온 플러스) 수집 완료

  3%|▎         | 90/2999 [01:43<56:07,  1.16s/it]

[성공] 91번 카드 (카드의정석 PREMIUM POINT) 수집 완료

  3%|▎         | 91/2999 [01:44<58:47,  1.21s/it]

[성공] 92번 카드 (카드의정석 PREMIUM MILEAGE(SKYPASS)) 수집 완료

  3%|▎         | 92/2999 [01:45<57:37,  1.19s/it]

[성공] 93번 카드 (카드의정석 PREMIUM MILEAGE(AsianaClub)) 수집 완료

  3%|▎         | 93/2999 [01:46<56:35,  1.17s/it]

[성공] 94번 카드 (LoL CHAMPIONS KOREA 우리카드) 수집 완료

  3%|▎         | 94/2999 [01:47<55:20,  1.14s/it]

[성공] 95번 카드 (갤러리아 씨티카드 프레스티지) 수집 완료

  3%|▎         | 95/2999 [01:48<54:34,  1.13s/it]

[성공] 96번 카드 (씨티 리워드) 수집 완료

  3%|▎         | 96/2999 [01:49<55:25,  1.15s/it]

[성공] 97번 카드 (신세계 씨티 리워드) 수집 완료

  3%|▎         | 97/2999 [01:51<54:55,  1.14s/it]

[성공] 98번 카드 (신세계 씨티카드 콰트로) 수집 완료

  3%|▎         | 98/2999 [01:52<56:19,  1.16s/it]

[성공] 99번 카드 (신세계 씨티 플래티늄 아시아나) 수집 완료

  3%|▎         | 99/2999 [01:53<57:21,  1.19s/it]

[성공] 100번 카드 (씨티 NEW 캐시백) 수집 완료

  3%|▎         | 100/2999 [01:54<56:02,  1.16s/it]

[성공] 101번 카드 (NEW 씨티 클리어) 수집 완료

  3%|▎         | 101/2999 [01:55<56:02,  1.16s/it]

[성공] 102번 카드 (씨티 NEW 프리미어마일 대한항공) 수집 완료

  3%|▎         | 102/2999 [01:56<55:34,  1.15s/it]

[성공] 103번 카드 (씨티 NEW 프리미어마일 아시아나) 수집 완료

  3%|▎         | 103/2999 [01:58<54:59,  1.14s/it]

[성공] 104번 카드 (대백 씨티카드 아인스) 수집 완료

  3%|▎         | 104/2999 [01:59<54:35,  1.13s/it]

[성공] 105번 카드 (이마트 KB국민카드) 수집 완료

  4%|▎         | 105/2999 [02:00<54:30,  1.13s/it]

[성공] 106번 카드 (굿데이카드) 수집 완료

  4%|▎         | 106/2999 [02:01<54:46,  1.14s/it]

[성공] 107번 카드 (SK LPG SAVE KB국민카드) 수집 완료

  4%|▎         | 107/2999 [02:02<54:00,  1.12s/it]

[성공] 108번 카드 (와이즈카드) 수집 완료

  4%|▎         | 108/2999 [02:03<53:43,  1.12s/it]

[성공] 109번 카드 (SK에너지 러브유 KB국민카드) 수집 완료

  4%|▎         | 109/2999 [02:04<53:24,  1.11s/it]

[성공] 110번 카드 (서울도시가스 KB국민카드) 수집 완료

  4%|▎         | 110/2999 [02:05<53:07,  1.10s/it]

[성공] 111번 카드 (혜담Ⅱ카드) 수집 완료

  4%|▎         | 111/2999 [02:06<52:58,  1.10s/it]

[성공] 112번 카드 (GS행복가득카드) 수집 완료

  4%|▎         | 112/2999 [02:08<52:52,  1.10s/it]

[성공] 113번 카드 (마일리지 가온카드(대한항공)) 수집 완료

  4%|▍         | 113/2999 [02:09<52:52,  1.10s/it]

[성공] 114번 카드 (마일리지 가온카드(아시아나)) 수집 완료

  4%|▍         | 114/2999 [02:10<52:42,  1.10s/it]

[성공] 115번 카드 (굿데이올림카드) 수집 완료

  4%|▍         | 115/2999 [02:11<53:31,  1.11s/it]

[성공] 116번 카드 (청춘대로카드) 수집 완료

  4%|▍         | 116/2999 [02:12<53:25,  1.11s/it]

[성공] 117번 카드 (청춘대로 티타늄 카드) 수집 완료

  4%|▍         | 117/2999 [02:13<54:05,  1.13s/it]

[성공] 118번 카드 (FINETECH카드(아시아나)) 수집 완료

  4%|▍         | 118/2999 [02:14<53:37,  1.12s/it]

[성공] 119번 카드 (FINETECH카드(대한항공)) 수집 완료

  4%|▍         | 119/2999 [02:15<53:25,  1.11s/it]

[성공] 120번 카드 (ONE카드) 수집 완료

  4%|▍         | 120/2999 [02:16<53:10,  1.11s/it]

[성공] 121번 카드 (다담카드) 수집 완료

  4%|▍         | 121/2999 [02:18<55:41,  1.16s/it]

[성공] 122번 카드 (모바일101카드) 수집 완료

  4%|▍         | 122/2999 [02:19<55:17,  1.15s/it]

[성공] 123번 카드 (아이행복카드(S-type)) 수집 완료

  4%|▍         | 123/2999 [02:20<56:36,  1.18s/it]

[성공] 124번 카드 (아이행복카드(T-type)) 수집 완료

  4%|▍         | 124/2999 [02:21<55:29,  1.16s/it]

[성공] 125번 카드 (E1 LPG KB국민카드) 수집 완료

  4%|▍         | 125/2999 [02:22<54:40,  1.14s/it]

[성공] 126번 카드 (아시아나 올림카드) 수집 완료

  4%|▍         | 126/2999 [02:23<53:48,  1.12s/it]

[성공] 127번 카드 (청춘대로 매니아i카드) 수집 완료

  4%|▍         | 127/2999 [02:25<53:46,  1.12s/it]

[성공] 128번 카드 (Liiv Mate카드) 수집 완료

  4%|▍         | 128/2999 [02:26<53:36,  1.12s/it]

[성공] 129번 카드 (청춘대로 톡톡카드) 수집 완료

  4%|▍         | 129/2999 [02:27<56:38,  1.18s/it]

[성공] 130번 카드 (BeV V카드(포인트형)) 수집 완료

  4%|▍         | 130/2999 [02:28<56:08,  1.17s/it]

[성공] 131번 카드 (BeV V카드(스카이패스형)) 수집 완료

  4%|▍         | 131/2999 [02:29<55:17,  1.16s/it]

[성공] 132번 카드 (청춘대로 1코노미 카드) 수집 완료

  4%|▍         | 132/2999 [02:30<54:47,  1.15s/it]

[성공] 133번 카드 (BeV Ⅲ 카드) 수집 완료

  4%|▍         | 133/2999 [02:32<58:17,  1.22s/it]

[성공] 134번 카드 (탄탄대로 온리유카드) 수집 완료

  4%|▍         | 134/2999 [02:33<56:57,  1.19s/it]

[성공] 135번 카드 (탄탄대로 이지홈카드) 수집 완료

  5%|▍         | 135/2999 [02:34<56:09,  1.18s/it]

[성공] 136번 카드 (가온 워킹업카드) 수집 완료

  5%|▍         | 136/2999 [02:35<54:59,  1.15s/it]

[성공] 137번 카드 (탄탄대로 Miz&Mr카드) 수집 완료

  5%|▍         | 137/2999 [02:36<54:31,  1.14s/it]

[성공] 138번 카드 (스카이패스 KB국민카드) 수집 완료

  5%|▍         | 138/2999 [02:37<53:58,  1.13s/it]

[성공] 139번 카드 (아시아나항공 KB국민카드) 수집 완료

  5%|▍         | 139/2999 [02:38<53:29,  1.12s/it]

[성공] 140번 카드 (S-OIL LPG KB국민카드) 수집 완료

  5%|▍         | 140/2999 [02:40<54:06,  1.14s/it]

[성공] 141번 카드 (KB국민 펫코노미 카드) 수집 완료

  5%|▍         | 141/2999 [02:41<53:39,  1.13s/it]

[성공] 142번 카드 (톡톡 Pay카드) 수집 완료

  5%|▍         | 142/2999 [02:42<54:36,  1.15s/it]

[성공] 143번 카드 (청춘대로 꿀맛α카드) 수집 완료

  5%|▍         | 143/2999 [02:43<53:56,  1.13s/it]

[성공] 144번 카드 (청춘대로 꿀잠α카드) 수집 완료

  5%|▍         | 144/2999 [02:44<53:22,  1.12s/it]

[성공] 145번 카드 (청춘대로 꿀잼α카드) 수집 완료

  5%|▍         | 145/2999 [02:45<54:57,  1.16s/it]

[성공] 146번 카드 (The Easy카드) 수집 완료

  5%|▍         | 146/2999 [02:46<54:18,  1.14s/it]

[성공] 147번 카드 (레일포인트 KB국민카드) 수집 완료

  5%|▍         | 147/2999 [02:48<53:34,  1.13s/it]

[성공] 148번 카드 (삼성페이 KB국민카드) 수집 완료

  5%|▍         | 148/2999 [02:49<53:11,  1.12s/it]

[성공] 149번 카드 (탄탄대로 올쇼핑카드) 수집 완료

  5%|▍         | 149/2999 [02:50<53:07,  1.12s/it]

[성공] 150번 카드 (탄탄대로 Miz&Mr 티타늄카드) 수집 완료

  5%|▌         | 150/2999 [02:51<53:15,  1.12s/it]

[성공] 151번 카드 (탄탄대로 오토카드) 수집 완료

  5%|▌         | 151/2999 [02:52<53:07,  1.12s/it]

[성공] 152번 카드 (에듀카드) 수집 완료

  5%|▌         | 152/2999 [02:53<53:15,  1.12s/it]

[Skip] 153번 카드 정보가 존재하지 않습니다.

  5%|▌         | 153/2999 [02:54<52:35,  1.11s/it]

[Skip] 154번 카드 정보가 존재하지 않습니다.

  5%|▌         | 154/2999 [02:55<51:56,  1.10s/it]

[성공] 155번 카드 (Lady다솜카드) 수집 완료

  5%|▌         | 155/2999 [02:56<51:54,  1.10s/it]

[성공] 156번 카드 (Shopping Save카드) 수집 완료

  5%|▌         | 156/2999 [02:57<51:54,  1.10s/it]

[성공] 157번 카드 (아시아나클럽카드) 수집 완료

  5%|▌         | 157/2999 [02:59<55:39,  1.18s/it]

[성공] 158번 카드 (스카이패스카드) 수집 완료

  5%|▌         | 158/2999 [03:00<54:50,  1.16s/it]

[성공] 159번 카드 (TAKE(테이크)5카드) 수집 완료

  5%|▌         | 159/2999 [03:01<58:04,  1.23s/it]

[성공] 160번 카드 (알뜰주유카드(할인형)) 수집 완료

  5%|▌         | 160/2999 [03:02<56:16,  1.19s/it]

[성공] 161번 카드 (NC다이노스카드) 수집 완료

  5%|▌         | 161/2999 [03:04<54:54,  1.16s/it]

[성공] 162번 카드 (#ing(샵핑)카드) 수집 완료

  5%|▌         | 162/2999 [03:05<53:47,  1.14s/it]

[성공] 163번 카드 (#ing+(샵핑플러스)카드) 수집 완료

  5%|▌         | 163/2999 [03:06<52:58,  1.12s/it]

[성공] 164번 카드 (ME+(미플러스)카드) 수집 완료

  5%|▌         | 164/2999 [03:07<52:28,  1.11s/it]

[성공] 165번 카드 (ME(미)카드) 수집 완료

  6%|▌         | 165/2999 [03:08<52:21,  1.11s/it]

[성공] 166번 카드 (BAZIC(베이직)카드) 수집 완료

  6%|▌         | 166/2999 [03:09<53:04,  1.12s/it]

[성공] 167번 카드 (BAZIC+(베이직플러스)카드) 수집 완료

  6%|▌         | 167/2999 [03:10<52:43,  1.12s/it]

[성공] 168번 카드 (아이행복카드(교육)(비씨)) 수집 완료

  6%|▌         | 168/2999 [03:11<52:18,  1.11s/it]

[성공] 169번 카드 (아이행복카드(쇼핑)(비씨)) 수집 완료

  6%|▌         | 169/2999 [03:12<51:50,  1.10s/it]

[성공] 170번 카드 (jumjum(점점)카드(할인)(비씨)) 수집 완료

  6%|▌         | 170/2999 [03:13<51:37,  1.09s/it]

[성공] 171번 카드 (jumjum(점점)카드(적립)(비씨)) 수집 완료

  6%|▌         | 171/2999 [03:14<51:23,  1.09s/it]

[성공] 172번 카드 (NH올원카드) 수집 완료

  6%|▌         | 172/2999 [03:16<51:11,  1.09s/it]

[성공] 173번 카드 (NH올원+(플러스)카드) 수집 완료

  6%|▌         | 173/2999 [03:17<54:26,  1.16s/it]

[성공] 174번 카드 (국민행복카드(신용)) 수집 완료

  6%|▌         | 174/2999 [03:18<53:42,  1.14s/it]

[성공] 175번 카드 (NH올원 하나로카드) 수집 완료

  6%|▌         | 175/2999 [03:19<53:01,  1.13s/it]

[성공] 176번 카드 (부자되세요 HomeShopping카드(비씨)) 수집 완료

  6%|▌         | 176/2999 [03:20<52:17,  1.11s/it]

[성공] 177번 카드 (NH올원 All100(올백)카드) 수집 완료

  6%|▌         | 177/2999 [03:21<51:58,  1.10s/it]

[성공] 178번 카드 (NH올원 Shopping&11번가카드(R1타입)) 수집 완료

  6%|▌         | 178/2999 [03:22<52:12,  1.11s/it]

[성공] 179번 카드 (NH올원 Shopping&11번가카드(R2타입)) 수집 완료

  6%|▌         | 179/2999 [03:24<52:58,  1.13s/it]

[성공] 180번 카드 (위카드) 수집 완료

  6%|▌         | 180/2999 [03:25<58:00,  1.23s/it]

[성공] 181번 카드 (NH올원 파이카드) 수집 완료

  6%|▌         | 181/2999 [03:26<57:02,  1.21s/it]

[성공] 182번 카드 (SolSol++(쏠쏠투플러스)카드) 수집 완료

  6%|▌         | 182/2999 [03:27<56:37,  1.21s/it]

[성공] 183번 카드 (SolSol(쏠쏠)카드) 수집 완료

  6%|▌         | 183/2999 [03:28<55:14,  1.18s/it]

[성공] 184번 카드 (NH20해봄카드) 수집 완료

  6%|▌         | 184/2999 [03:30<54:41,  1.17s/it]

[성공] 185번 카드 (NH농협 부자되세요 아파트카드(비씨)) 수집 완료

  6%|▌         | 185/2999 [03:31<53:48,  1.15s/it]

[성공] 186번 카드 (NH농협 콕카드) 수집 완료

  6%|▌         | 186/2999 [03:32<52:49,  1.13s/it]

[성공] 187번 카드 (올바른POINT카드) 수집 완료

  6%|▌         | 187/2999 [03:33<53:21,  1.14s/it]

[성공] 188번 카드 (올바른OIL카드) 수집 완료

  6%|▋         | 188/2999 [03:34<54:38,  1.17s/it]

[성공] 189번 카드 (올바른TRAVEL카드(일본특화)) 수집 완료

  6%|▋         | 189/2999 [03:35<53:36,  1.14s/it]

[성공] 190번 카드 (올바른TRAVEL카드(중국특화)) 수집 완료

  6%|▋         | 190/2999 [03:36<52:46,  1.13s/it]

[성공] 191번 카드 (T라이트카드) 수집 완료

  6%|▋         | 191/2999 [03:37<52:09,  1.11s/it]

[성공] 192번 카드 (KT수퍼할부카드(비씨)) 수집 완료

  6%|▋         | 192/2999 [03:39<51:43,  1.11s/it]

[성공] 193번 카드 (NH올원 LGU+카드) 수집 완료

  6%|▋         | 193/2999 [03:40<51:46,  1.11s/it]

[성공] 194번 카드 (롯데포인트 플러스 카드) 수집 완료

  6%|▋         | 194/2999 [03:41<51:38,  1.10s/it]

[성공] 195번 카드 (VEEX 플래티넘 카드) 수집 완료

  7%|▋         | 195/2999 [03:42<52:03,  1.11s/it]

[성공] 196번 카드 (뉴 에듀드림롯데카드) 수집 완료

  7%|▋         | 196/2999 [03:43<51:31,  1.10s/it]

[성공] 197번 카드 (올마이쇼핑 카드 (교통)) 수집 완료

  7%|▋         | 197/2999 [03:44<51:25,  1.10s/it]

[성공] 198번 카드 (올마이쇼핑 카드 (통신)) 수집 완료

  7%|▋         | 198/2999 [03:45<51:22,  1.10s/it]

[성공] 199번 카드 (올마이쇼핑 카드 (점심)) 수집 완료

  7%|▋         | 199/2999 [03:46<51:08,  1.10s/it]

[성공] 200번 카드 (올마이쇼핑 카드 (해외)) 수집 완료

  7%|▋         | 200/2999 [03:47<52:20,  1.12s/it]

[성공] 201번 카드 (롯데백화점 롯데카드) 수집 완료

  7%|▋         | 201/2999 [03:49<51:58,  1.11s/it]

[성공] 202번 카드 (SKYPASS THE DREAM 롯데카드) 수집 완료

  7%|▋         | 202/2999 [03:50<51:42,  1.11s/it]

[성공] 203번 카드 (ALL MY DC) 수집 완료

  7%|▋         | 203/2999 [03:51<51:28,  1.10s/it]

[성공] 204번 카드 (ALL MY POINT) 수집 완료

  7%|▋         | 204/2999 [03:52<51:16,  1.10s/it]

[성공] 205번 카드 (ALL MY LIVING) 수집 완료

  7%|▋         | 205/2999 [03:53<52:58,  1.14s/it]

[성공] 206번 카드 (ALL MY DRIVING) 수집 완료

  7%|▋         | 206/2999 [03:54<52:22,  1.13s/it]

[성공] 207번 카드 (경차 smart 롯데카드) 수집 완료

  7%|▋         | 207/2999 [03:55<52:14,  1.12s/it]

[성공] 208번 카드 (LIKIT FUN 카드) 수집 완료

  7%|▋         | 208/2999 [03:56<52:07,  1.12s/it]

[성공] 209번 카드 (LIKIT ON 카드) 수집 완료

  7%|▋         | 209/2999 [03:57<52:29,  1.13s/it]

[성공] 210번 카드 (LIKIT ALL 카드) 수집 완료

  7%|▋         | 210/2999 [03:59<53:03,  1.14s/it]

[성공] 211번 카드 (트래블패스 시그니처카드) 수집 완료

  7%|▋         | 211/2999 [04:00<52:18,  1.13s/it]

[성공] 212번 카드 (포인트플러스 GRANDE카드) 수집 완료

  7%|▋         | 212/2999 [04:01<51:49,  1.12s/it]

[성공] 213번 카드 (I’m WONDERFUL) 수집 완료

  7%|▋         | 213/2999 [04:02<51:22,  1.11s/it]

[성공] 214번 카드 (I’m GREAT) 수집 완료

  7%|▋         | 214/2999 [04:03<55:51,  1.20s/it]

[성공] 215번 카드 (I’m CHEERFUL) 수집 완료

  7%|▋         | 215/2999 [04:04<54:29,  1.17s/it]

[성공] 216번 카드 (I’m HEARTFUL) 수집 완료

  7%|▋         | 216/2999 [04:06<53:30,  1.15s/it]

[성공] 217번 카드 (I’m JOYFUL) 수집 완료

  7%|▋         | 217/2999 [04:07<53:31,  1.15s/it]

[성공] 218번 카드 (L.pay 롯데카드) 수집 완료

  7%|▋         | 218/2999 [04:08<52:33,  1.13s/it]

[성공] 219번 카드 (I’m YOLO) 수집 완료

  7%|▋         | 219/2999 [04:09<55:44,  1.20s/it]

[성공] 220번 카드 (L.CLASS L20 (스카이패스형)) 수집 완료

  7%|▋         | 220/2999 [04:10<54:07,  1.17s/it]

[성공] 221번 카드 (L.CLASS L20 (아시아나클럽형)) 수집 완료

  7%|▋         | 221/2999 [04:11<54:16,  1.17s/it]

[성공] 222번 카드 (L.CLASS L20 (L.POINT형)) 수집 완료

  7%|▋         | 222/2999 [04:13<54:44,  1.18s/it]

[성공] 223번 카드 (뉴 CJ헬로 롯데카드) 수집 완료

  7%|▋         | 223/2999 [04:14<54:08,  1.17s/it]

[성공] 224번 카드 (카카오페이 롯데카드) 수집 완료

  7%|▋         | 224/2999 [04:15<52:51,  1.14s/it]

[성공] 225번 카드 (PAYCO 플래티넘 롯데카드) 수집 완료

  8%|▊         | 225/2999 [04:16<52:28,  1.13s/it]

[성공] 226번 카드 (터치원카드(Touch1)) 수집 완료

  8%|▊         | 226/2999 [04:17<51:53,  1.12s/it]

[성공] 227번 카드 (CLUB SK 카드) 수집 완료

  8%|▊         | 227/2999 [04:18<53:06,  1.15s/it]

[성공] 228번 카드 (Smart Any 카드(스마트애니)) 수집 완료

  8%|▊         | 228/2999 [04:20<56:02,  1.21s/it]

[성공] 229번 카드 (미생카드) 수집 완료

  8%|▊         | 229/2999 [04:21<54:15,  1.18s/it]

[성공] 230번 카드 (아이행복카드) 수집 완료

  8%|▊         | 230/2999 [04:22<52:58,  1.15s/it]

[성공] 231번 카드 (하나멤버스 1Q(원큐) 카드 Living) 수집 완료

  8%|▊         | 231/2999 [04:23<52:19,  1.13s/it]

[성공] 232번 카드 (하나멤버스 1Q(원큐) 카드 Shopping) 수집 완료

  8%|▊         | 232/2999 [04:24<51:43,  1.12s/it]

[성공] 233번 카드 (카카오페이 신용카드) 수집 완료

  8%|▊         | 233/2999 [04:25<55:39,  1.21s/it]

[성공] 234번 카드 (하나멤버스 1Q(원큐) 카드 Daily) 수집 완료

  8%|▊         | 234/2999 [04:27<1:02:23,  1.35s/it]

[성공] 235번 카드 (Ohmyzip(오마이집) 카드) 수집 완료

  8%|▊         | 235/2999 [04:28<59:10,  1.28s/it]

[성공] 236번 카드 (Simple Life) 수집 완료

  8%|▊         | 236/2999 [04:29<56:57,  1.24s/it]

[성공] 237번 카드 (하나멤버스 1Q카드 내맘대로) 수집 완료

  8%|▊         | 237/2999 [04:31<55:45,  1.21s/it]

[성공] 238번 카드 (1Q Daily+) 수집 완료

  8%|▊         | 238/2999 [04:32<1:00:38,  1.32s/it]

[Error] 239번 카드 정보 요청 실패 (상태 코드: 502)

  8%|▊         | 239/2999 [04:33<56:54,  1.24s/it]

[성공] 240번 카드 (1Q Living+) 수집 완료

  8%|▊         | 240/2999 [04:34<58:19,  1.27s/it]

[성공] 241번 카드 (1Q Special+) 수집 완료

  8%|▊         | 241/2999 [04:36<55:47,  1.21s/it]

[성공] 242번 카드 (Mile 1.6 대한항공) 수집 완료

  8%|▊         | 242/2999 [04:37<56:12,  1.22s/it]

[성공] 243번 카드 (Mile 1.6 아시아나) 수집 완료

  8%|▊         | 243/2999 [04:38<54:46,  1.19s/it]

[성공] 244번 카드 (Mile 1.8 대한항공) 수집 완료

  8%|▊         | 244/2999 [04:39<54:13,  1.18s/it]

[성공] 245번 카드 (Mile 1.8 아시아나) 수집 완료

  8%|▊         | 245/2999 [04:40<52:50,  1.15s/it]

[성공] 246번 카드 (통커 카드) 수집 완료

  8%|▊         | 246/2999 [04:41<52:10,  1.14s/it]

[성공] 247번 카드 (#tag1카드 Orange) 수집 완료

  8%|▊         | 247/2999 [04:42<51:41,  1.13s/it]

[성공] 248번 카드 (#tag1카드 Navy) 수집 완료

  8%|▊         | 248/2999 [04:44<51:48,  1.13s/it]

[성공] 249번 카드 (1Q Coupon 카드) 수집 완료

  8%|▊         | 249/2999 [04:45<51:11,  1.12s/it]

[성공] 250번 카드 (my pass 마패 카드) 수집 완료

  8%|▊         | 250/2999 [04:46<50:47,  1.11s/it]

[성공] 251번 카드 (1Q Global VIVA) 수집 완료

  8%|▊         | 251/2999 [04:47<50:49,  1.11s/it]

[성공] 252번 카드 (Any PLUS 카드) 수집 완료

  8%|▊         | 252/2999 [04:48<50:37,  1.11s/it]

[성공] 253번 카드 (1Q My Café) 수집 완료

  8%|▊         | 253/2999 [04:49<50:44,  1.11s/it]

[성공] 254번 카드 (1Q My Lunch) 수집 완료

  8%|▊         | 254/2999 [04:50<53:45,  1.18s/it]

[성공] 255번 카드 (1Q My Edu) 수집 완료

  9%|▊         | 255/2999 [04:51<53:02,  1.16s/it]

[Skip] 256번 카드 정보가 존재하지 않습니다.

  9%|▊         | 256/2999 [04:53<53:12,  1.16s/it]

[Skip] 257번 카드 정보가 존재하지 않습니다.

  9%|▊         | 257/2999 [04:54<51:40,  1.13s/it]

[성공] 258번 카드 (Oil & Life카드(Oil카드)) 수집 완료

  9%|▊         | 258/2999 [04:55<51:22,  1.12s/it]

[성공] 259번 카드 (Oil & Life카드(Life카드)) 수집 완료

  9%|▊         | 259/2999 [04:56<51:14,  1.12s/it]

[성공] 260번 카드 (국민행복카드(신용)) 수집 완료

  9%|▊         | 260/2999 [04:57<50:53,  1.11s/it]

[Skip] 261번 카드 정보가 존재하지 않습니다.

  9%|▊         | 261/2999 [04:58<50:09,  1.10s/it]

[Skip] 262번 카드 정보가 존재하지 않습니다.

  9%|▊         | 262/2999 [04:59<49:46,  1.09s/it]

[성공] 263번 카드 (참! 좋은 kt wiz 카드(신용)) 수집 완료

  9%|▉         | 263/2999 [05:00<49:58,  1.10s/it]

[성공] 264번 카드 (olleh Super DC IBK카드) 수집 완료

  9%|▉         | 264/2999 [05:01<51:12,  1.12s/it]

[Skip] 265번 카드 정보가 존재하지 않습니다.

  9%|▉         | 265/2999 [05:03<50:15,  1.10s/it]

[성공] 266번 카드 (일상의 기쁨카드(신용)) 수집 완료

  9%|▉         | 266/2999 [05:04<50:53,  1.12s/it]

[성공] 267번 카드 (마일앤조이카드(대한항공)) 수집 완료

  9%|▉         | 267/2999 [05:05<51:04,  1.12s/it]

[성공] 268번 카드 (마일앤조이카드(아시아나)) 수집 완료

  9%|▉         | 268/2999 [05:06<50:47,  1.12s/it]

[성공] 269번 카드 (IBK-Hybrid(하이브리드)카드) 수집 완료

  9%|▉         | 269/2999 [05:07<50:34,  1.11s/it]

[성공] 270번 카드 (아모레퍼시픽 IBK카드) 수집 완료

  9%|▉         | 270/2999 [05:08<50:55,  1.12s/it]

[성공] 271번 카드 (일년의 설렘카드) 수집 완료

  9%|▉         | 271/2999 [05:09<50:35,  1.11s/it]

[Skip] 272번 카드 정보가 존재하지 않습니다.

  9%|▉         | 272/2999 [05:10<49:39,  1.09s/it]

[성공] 273번 카드 (참! 좋은 다이소카드(신용)) 수집 완료

  9%|▉         | 273/2999 [05:11<49:55,  1.10s/it]

[성공] 274번 카드 (쇼핑앤조이 카드) 수집 완료

  9%|▉         | 274/2999 [05:12<49:49,  1.10s/it]

[성공] 275번 카드 (제주항공 Refresh Point 카드) 수집 완료

  9%|▉         | 275/2999 [05:14<52:43,  1.16s/it]

[성공] 276번 카드 (플러스마일카드) 수집 완료

  9%|▉         | 276/2999 [05:15<51:43,  1.14s/it]

[성공] 277번 카드 (시그마카드) 수집 완료

  9%|▉         | 277/2999 [05:16<51:00,  1.12s/it]

[Skip] 278번 카드 정보가 존재하지 않습니다.

  9%|▉         | 278/2999 [05:17<50:09,  1.11s/it]

[성공] 279번 카드 (CJ ONE 신한카드 체크) 수집 완료

  9%|▉         | 279/2999 [05:18<50:06,  1.11s/it]

[Skip] 280번 카드 정보가 존재하지 않습니다.

  9%|▉         | 280/2999 [05:19<49:19,  1.09s/it]

[성공] 281번 카드 (신한카드 Deep Dream 체크) 수집 완료

  9%|▉         | 281/2999 [05:20<49:50,  1.10s/it]

[성공] 282번 카드 (신세계 신한카드 체크) 수집 완료

  9%|▉         | 282/2999 [05:21<49:49,  1.10s/it]

[Skip] 283번 카드 정보가 존재하지 않습니다.

  9%|▉         | 283/2999 [05:22<49:06,  1.08s/it]

[성공] 284번 카드 (신한카드 주거래 체크) 수집 완료

  9%|▉         | 284/2999 [05:24<49:17,  1.09s/it]

[Skip] 285번 카드 정보가 존재하지 않습니다.

 10%|▉         | 285/2999 [05:25<48:40,  1.08s/it]

[성공] 286번 카드 (카카오페이 신한 체크카드) 수집 완료

 10%|▉         | 286/2999 [05:26<49:45,  1.10s/it]

[성공] 287번 카드 (NCSOFT 신한카드 체크) 수집 완료

 10%|▉         | 287/2999 [05:27<49:42,  1.10s/it]

[Skip] 288번 카드 정보가 존재하지 않습니다.

 10%|▉         | 288/2999 [05:28<49:01,  1.09s/it]

[Skip] 289번 카드 정보가 존재하지 않습니다.

 10%|▉         | 289/2999 [05:29<49:16,  1.09s/it]

[Skip] 290번 카드 정보가 존재하지 않습니다.

 10%|▉         | 290/2999 [05:30<48:43,  1.08s/it]

[Skip] 291번 카드 정보가 존재하지 않습니다.

 10%|▉         | 291/2999 [05:31<48:28,  1.07s/it]

[Skip] 292번 카드 정보가 존재하지 않습니다.

 10%|▉         | 292/2999 [05:32<48:20,  1.07s/it]

[Skip] 293번 카드 정보가 존재하지 않습니다.

 10%|▉         | 293/2999 [05:33<48:49,  1.08s/it]

[성공] 294번 카드 (신한카드 S-Line 체크) 수집 완료

 10%|▉         | 294/2999 [05:34<49:12,  1.09s/it]

[Skip] 295번 카드 정보가 존재하지 않습니다.

 10%|▉         | 295/2999 [05:35<48:46,  1.08s/it]

[성공] 296번 카드 (신한 S-Choice체크카드) 수집 완료

 10%|▉         | 296/2999 [05:37<49:04,  1.09s/it]

[Skip] 297번 카드 정보가 존재하지 않습니다.

 10%|▉         | 297/2999 [05:38<48:45,  1.08s/it]

[Skip] 298번 카드 정보가 존재하지 않습니다.

 10%|▉         | 298/2999 [05:39<48:30,  1.08s/it]

[Skip] 299번 카드 정보가 존재하지 않습니다.

 10%|▉         | 299/2999 [05:40<48:09,  1.07s/it]

[성공] 300번 카드 (SOCAR 제휴 SOCAR 신한카드 체크) 수집 완료

 10%|█         | 300/2999 [05:41<48:34,  1.08s/it]

[성공] 301번 카드 (KT 신한카드 체크) 수집 완료

 10%|█         | 301/2999 [05:42<49:33,  1.10s/it]

[성공] 302번 카드 (LG U+ 신한카드 Smart 체크) 수집 완료

 10%|█         | 302/2999 [05:43<49:36,  1.10s/it]

[성공] 303번 카드 (GS칼텍스 신한카드 경차사랑 체크) 수집 완료

 10%|█         | 303/2999 [05:44<49:39,  1.11s/it]

[Skip] 304번 카드 정보가 존재하지 않습니다.

 10%|█         | 304/2999 [05:45<48:58,  1.09s/it]

[성공] 305번 카드 (KBO 제휴 신한카드 MY KBO 체크) 수집 완료

 10%|█         | 305/2999 [05:46<49:03,  1.09s/it]

[성공] 306번 카드 (리디 신한카드 체크) 수집 완료

 10%|█         | 306/2999 [05:48<49:28,  1.10s/it]

[성공] 307번 카드 (더본 신한카드 체크) 수집 완료

 10%|█         | 307/2999 [05:49<49:18,  1.10s/it]

[Skip] 308번 카드 정보가 존재하지 않습니다.

 10%|█         | 308/2999 [05:50<48:48,  1.09s/it]

[성공] 309번 카드 (EDIYA 신한카드 체크) 수집 완료

 10%|█         | 309/2999 [05:51<48:50,  1.09s/it]

[성공] 310번 카드 (마이 홈플러스 신한카드 체크) 수집 완료

 10%|█         | 310/2999 [05:52<48:58,  1.09s/it]

[성공] 311번 카드 (몰테일 신한카드 체크) 수집 완료

 10%|█         | 311/2999 [05:53<49:31,  1.11s/it]

[성공] 312번 카드 (카드의정석 COOKIE CHECK) 수집 완료

 10%|█         | 312/2999 [05:54<50:25,  1.13s/it]

[성공] 313번 카드 (LoL CHAMPIONS KOREA 우리체크카드) 수집 완료

 10%|█         | 313/2999 [05:55<50:14,  1.12s/it]

[성공] 314번 카드 (카드의정석 SSO3 CHECK) 수집 완료

 10%|█         | 314/2999 [05:57<54:55,  1.23s/it]

[성공] 315번 카드 (카카오페이 체크카드) 수집 완료

 11%|█         | 315/2999 [05:58<53:21,  1.19s/it]

[성공] 316번 카드 (카드의정석 L.POINT CHECK) 수집 완료

 11%|█         | 316/2999 [05:59<53:14,  1.19s/it]

[성공] 317번 카드 (카드의정석 POINT CHECK) 수집 완료

 11%|█         | 317/2999 [06:00<52:16,  1.17s/it]

[성공] 318번 카드 (위메프 우리체크) 수집 완료

 11%|█         | 318/2999 [06:01<53:55,  1.21s/it]

[성공] 319번 카드 (배달의민족 우리체크) 수집 완료

 11%|█         | 319/2999 [06:03<53:02,  1.19s/it]

[성공] 320번 카드 (롯데마트 라서 즐거운 체크카드) 수집 완료

 11%|█         | 320/2999 [06:04<51:53,  1.16s/it]

[Skip] 321번 카드 정보가 존재하지 않습니다.

 11%|█         | 321/2999 [06:05<52:25,  1.17s/it]

[성공] 322번 카드 (우리 아이행복체크카드) 수집 완료

 11%|█         | 322/2999 [06:06<52:02,  1.17s/it]

[성공] 323번 카드 (우리국민행복체크카드) 수집 완료

 11%|█         | 323/2999 [06:07<53:53,  1.21s/it]

[성공] 324번 카드 (우리 YG 체크카드) 수집 완료

 11%|█         | 324/2999 [06:09<53:01,  1.19s/it]

[성공] 325번 카드 (그랑블루 체크카드) 수집 완료

 11%|█         | 325/2999 [06:10<52:41,  1.18s/it]

[성공] 326번 카드 (해피포인트 우리체크카드) 수집 완료

 11%|█         | 326/2999 [06:11<53:01,  1.19s/it]

[Skip] 327번 카드 정보가 존재하지 않습니다.

 11%|█         | 327/2999 [06:12<52:09,  1.17s/it]

[성공] 328번 카드 (라떼 우리체크카드) 수집 완료

 11%|█         | 328/2999 [06:13<51:40,  1.16s/it]

[성공] 329번 카드 (갤러리아 체크카드) 수집 완료

 11%|█         | 329/2999 [06:14<51:16,  1.15s/it]

[성공] 330번 카드 (카드의정석 CREAM TEENS CHECK) 수집 완료

 11%|█         | 330/2999 [06:16<52:45,  1.19s/it]

[성공] 331번 카드 (New 현대백화점 체크카드) 수집 완료

 11%|█         | 331/2999 [06:17<52:09,  1.17s/it]

[성공] 332번 카드 (카카오페이 KB국민 체크카드) 수집 완료

 11%|█         | 332/2999 [06:18<51:34,  1.16s/it]

[성공] 333번 카드 (Liiv Mate 체크카드) 수집 완료

 11%|█         | 333/2999 [06:19<52:19,  1.18s/it]

[성공] 334번 카드 (아시아나 체크카드) 수집 완료

 11%|█         | 334/2999 [06:20<51:28,  1.16s/it]

[성공] 335번 카드 (청춘대로 싱글 체크카드) 수집 완료

 11%|█         | 335/2999 [06:21<51:15,  1.15s/it]

[성공] 336번 카드 (가온체크카드) 수집 완료

 11%|█         | 336/2999 [06:22<50:37,  1.14s/it]

[성공] 337번 카드 (ONE 체크카드) 수집 완료

 11%|█         | 337/2999 [06:24<50:27,  1.14s/it]

[성공] 338번 카드 (누리체크카드) 수집 완료

 11%|█▏        | 338/2999 [06:25<50:00,  1.13s/it]

[성공] 339번 카드 (음 체크카드) 수집 완료

 11%|█▏        | 339/2999 [06:26<49:40,  1.12s/it]

[성공] 340번 카드 (락스타 체크카드) 수집 완료

 11%|█▏        | 340/2999 [06:27<50:41,  1.14s/it]

[성공] 341번 카드 (훈 체크카드) 수집 완료

 11%|█▏        | 341/2999 [06:28<51:50,  1.17s/it]

[성공] 342번 카드 (해피노리체크카드) 수집 완료

 11%|█▏        | 342/2999 [06:29<52:08,  1.18s/it]

[성공] 343번 카드 (포인트리체크카드) 수집 완료

 11%|█▏        | 343/2999 [06:30<51:05,  1.15s/it]

[성공] 344번 카드 (아이행복 체크카드) 수집 완료

 11%|█▏        | 344/2999 [06:32<50:47,  1.15s/it]

[성공] 345번 카드 (정 체크카드) 수집 완료

 12%|█▏        | 345/2999 [06:33<50:32,  1.14s/it]

[성공] 346번 카드 (민 체크카드) 수집 완료

 12%|█▏        | 346/2999 [06:34<50:04,  1.13s/it]

[성공] 347번 카드 (비트윈체크카드) 수집 완료

 12%|█▏        | 347/2999 [06:35<49:57,  1.13s/it]

[성공] 348번 카드 (노리체크카드) 수집 완료

 12%|█▏        | 348/2999 [06:37<55:47,  1.26s/it]

[성공] 349번 카드 (해피락스타 체크카드) 수집 완료

 12%|█▏        | 349/2999 [06:38<54:26,  1.23s/it]

[성공] 350번 카드 (직장인보너스체크카드) 수집 완료

 12%|█▏        | 350/2999 [06:39<55:48,  1.26s/it]

[성공] 351번 카드 (스타체크카드) 수집 완료

 12%|█▏        | 351/2999 [06:41<1:00:27,  1.37s/it]

[Skip] 352번 카드 정보가 존재하지 않습니다.

 12%|█▏        | 352/2999 [06:42<56:36,  1.28s/it]

[성공] 353번 카드 (해피CU포인트 체크카드) 수집 완료

 12%|█▏        | 353/2999 [06:43<54:18,  1.23s/it]

[성공] 354번 카드 (LG U+ 체크카드) 수집 완료

 12%|█▏        | 354/2999 [06:44<52:29,  1.19s/it]

[성공] 355번 카드 (H.Point 체크카드) 수집 완료

 12%|█▏        | 355/2999 [06:45<51:12,  1.16s/it]

[Skip] 356번 카드 정보가 존재하지 않습니다.

 12%|█▏        | 356/2999 [06:46<49:47,  1.13s/it]

[성공] 357번 카드 (AK KB국민 체크카드) 수집 완료

 12%|█▏        | 357/2999 [06:47<49:39,  1.13s/it]

[Skip] 358번 카드 정보가 존재하지 않습니다.

 12%|█▏        | 358/2999 [06:48<48:54,  1.11s/it]

[성공] 359번 카드 (아모레퍼시픽 체크카드) 수집 완료

 12%|█▏        | 359/2999 [06:49<48:55,  1.11s/it]

[성공] 360번 카드 (올바른POINT체크카드) 수집 완료

 12%|█▏        | 360/2999 [06:51<48:58,  1.11s/it]

[성공] 361번 카드 (콕체크카드) 수집 완료

 12%|█▏        | 361/2999 [06:52<49:28,  1.13s/it]

[성공] 362번 카드 (NH20해봄체크카드) 수집 완료

 12%|█▏        | 362/2999 [06:53<50:49,  1.16s/it]

[성공] 363번 카드 (Global Unlimited(글로벌 언리미티드)체크카드) 수집 완료

 12%|█▏        | 363/2999 [06:54<50:07,  1.14s/it]

[성공] 364번 카드 (국민행복체크카드(비씨)) 수집 완료

 12%|█▏        | 364/2999 [06:55<51:34,  1.17s/it]

[성공] 365번 카드 (DC줌체크카드(비씨)) 수집 완료

 12%|█▏        | 365/2999 [06:57<54:13,  1.24s/it]

[성공] 366번 카드 (jumjum(점점) 체크카드(비씨)) 수집 완료

 12%|█▏        | 366/2999 [06:58<59:53,  1.36s/it]

[성공] 367번 카드 (내일배움체크카드) 수집 완료

 12%|█▏        | 367/2999 [07:00<59:52,  1.36s/it]

[성공] 368번 카드 (NH올원체크카드) 수집 완료

 12%|█▏        | 368/2999 [07:01<1:02:42,  1.43s/it]

[성공] 369번 카드 (아이행복체크카드(비씨)) 수집 완료

 12%|█▏        | 369/2999 [07:03<1:01:09,  1.40s/it]

[성공] 370번 카드 (BAZIC(베이직)체크카드) 수집 완료

 12%|█▏        | 370/2999 [07:04<56:55,  1.30s/it]

[성공] 371번 카드 (#ing(샵핑) 체크카드) 수집 완료

 12%|█▏        | 371/2999 [07:05<54:08,  1.24s/it]

[성공] 372번 카드 (NC다이노스체크카드) 수집 완료

 12%|█▏        | 372/2999 [07:06<52:01,  1.19s/it]

[성공] 373번 카드 (Global체크카드) 수집 완료

 12%|█▏        | 373/2999 [07:07<50:56,  1.16s/it]

[성공] 374번 카드 (청년동행체크카드(비씨)) 수집 완료

 12%|█▏        | 374/2999 [07:08<49:37,  1.13s/it]

[성공] 375번 카드 (올바른GLOBAL체크카드) 수집 완료

 13%|█▎        | 375/2999 [07:09<49:04,  1.12s/it]

[성공] 376번 카드 (문화융성체크카드) 수집 완료

 13%|█▎        | 376/2999 [07:10<48:39,  1.11s/it]

[성공] 377번 카드 (행복건강체크카드) 수집 완료

 13%|█▎        | 377/2999 [07:11<48:17,  1.11s/it]

[성공] 378번 카드 (VIVA+ 체크카드) 수집 완료

 13%|█▎        | 378/2999 [07:12<48:41,  1.11s/it]

[성공] 379번 카드 (VIVA e-Platinum 체크카드) 수집 완료

 13%|█▎        | 379/2999 [07:13<48:13,  1.10s/it]

[성공] 380번 카드 (하나멤버스 1Q 체크카드) 수집 완료

 13%|█▎        | 380/2999 [07:15<47:55,  1.10s/it]

[성공] 381번 카드 (뷰티풀해피 체크카드) 수집 완료

 13%|█▎        | 381/2999 [07:16<48:03,  1.10s/it]

[성공] 382번 카드 (카카오페이 체크카드) 수집 완료

 13%|█▎        | 382/2999 [07:17<47:52,  1.10s/it]

[성공] 383번 카드 (해피포인트 체크카드) 수집 완료

 13%|█▎        | 383/2999 [07:18<47:37,  1.09s/it]

[Skip] 384번 카드 정보가 존재하지 않습니다.

 13%|█▎        | 384/2999 [07:19<47:03,  1.08s/it]

[성공] 385번 카드 (VIVA G platinum 체크카드) 수집 완료

 13%|█▎        | 385/2999 [07:20<47:23,  1.09s/it]

[성공] 386번 카드 (CJ ONE 체크카드) 수집 완료

 13%|█▎        | 386/2999 [07:21<47:51,  1.10s/it]

[성공] 387번 카드 (비바2 플래티늄 체크카드) 수집 완료

 13%|█▎        | 387/2999 [07:22<47:52,  1.10s/it]

[성공] 388번 카드 (하나멤버스 Mega 체크카드) 수집 완료

 13%|█▎        | 388/2999 [07:23<47:50,  1.10s/it]

[성공] 389번 카드 (시코르 체크카드) 수집 완료

 13%|█▎        | 389/2999 [07:24<47:48,  1.10s/it]

[성공] 390번 카드 (신세계 하나 체크카드) 수집 완료

 13%|█▎        | 390/2999 [07:25<47:24,  1.09s/it]

[성공] 391번 카드 (신한카드 하이패스(전용) 체크) 수집 완료

 13%|█▎        | 391/2999 [07:27<49:08,  1.13s/it]

[성공] 392번 카드 (국민행복 삼성체크카드) 수집 완료

 13%|█▎        | 392/2999 [07:28<48:32,  1.12s/it]

[성공] 393번 카드 (삼성체크카드 & POINT) 수집 완료

 13%|█▎        | 393/2999 [07:29<49:35,  1.14s/it]

[성공] 394번 카드 (삼성체크카드 & CASHBACK) 수집 완료

 13%|█▎        | 394/2999 [07:30<48:43,  1.12s/it]

[성공] 395번 카드 (삼성체크카드 & YOUNG) 수집 완료

 13%|█▎        | 395/2999 [07:31<48:34,  1.12s/it]

[성공] 396번 카드 (씨티 캐시백 체크카드) 수집 완료

 13%|█▎        | 396/2999 [07:32<50:23,  1.16s/it]

[성공] 397번 카드 (신세계 씨티 플러스 체크카드) 수집 완료

 13%|█▎        | 397/2999 [07:34<50:52,  1.17s/it]

[성공] 398번 카드 (롯데 아이행복 체크카드) 수집 완료

 13%|█▎        | 398/2999 [07:35<49:37,  1.14s/it]

[성공] 399번 카드 (위클리 체크카드) 수집 완료

 13%|█▎        | 399/2999 [07:36<48:41,  1.12s/it]

[성공] 400번 카드 (롯데포인트플러스 체크카드) 수집 완료

 13%|█▎        | 400/2999 [07:37<48:00,  1.11s/it]

[Skip] 401번 카드 정보가 존재하지 않습니다.

 13%|█▎        | 401/2999 [07:38<47:11,  1.09s/it]

[성공] 402번 카드 (롯데 플래티넘 체크카드) 수집 완료

 13%|█▎        | 402/2999 [07:39<47:25,  1.10s/it]

[성공] 403번 카드 (롯데체크카드) 수집 완료

 13%|█▎        | 403/2999 [07:40<49:27,  1.14s/it]

[성공] 404번 카드 (롯데 국민행복 체크카드) 수집 완료

 13%|█▎        | 404/2999 [07:42<50:58,  1.18s/it]

[성공] 405번 카드 (에이스플러스체크카드(미키90주년)) 수집 완료

 14%|█▎        | 405/2999 [07:43<55:03,  1.27s/it]

[성공] 406번 카드 (부자되세요 더 마일리지 체크카드) 수집 완료

 14%|█▎        | 406/2999 [07:44<55:18,  1.28s/it]

[성공] 407번 카드 (현대카드M CHECK) 수집 완료

 14%|█▎        | 407/2999 [07:46<55:30,  1.28s/it]

[성공] 408번 카드 (현대카드X CHECK) 수집 완료

 14%|█▎        | 408/2999 [07:47<55:06,  1.28s/it]

[성공] 409번 카드 (부자되세요 더 마일리지 카드(체크)) 수집 완료

 14%|█▎        | 409/2999 [07:48<55:55,  1.30s/it]

[성공] 410번 카드 (현대카드ZERO(할인형)) 수집 완료

 14%|█▎        | 410/2999 [07:50<1:05:33,  1.52s/it]

[성공] 411번 카드 (현대카드X Edition2) 수집 완료

 14%|█▎        | 411/2999 [07:51<1:00:17,  1.40s/it]

[성공] 412번 카드 (현대카드X2 Edition2) 수집 완료

 14%|█▎        | 412/2999 [07:52<56:17,  1.31s/it]

[성공] 413번 카드 (현대카드M2 Edition2) 수집 완료

 14%|█▍        | 413/2999 [07:54<53:48,  1.25s/it]

[성공] 414번 카드 (현대카드M HYBRID) 수집 완료

 14%|█▍        | 414/2999 [07:55<52:16,  1.21s/it]

[성공] 415번 카드 (현대카드X HYBRID) 수집 완료

 14%|█▍        | 415/2999 [07:56<50:37,  1.18s/it]

[성공] 416번 카드 (현대카드X3 Edition2) 수집 완료

 14%|█▍        | 416/2999 [07:57<49:30,  1.15s/it]

[성공] 417번 카드 (현대카드T3 Edition2) 수집 완료

 14%|█▍        | 417/2999 [07:58<48:41,  1.13s/it]

[성공] 418번 카드 (현대카드ZERO MOBILE(포인트형)) 수집 완료

 14%|█▍        | 418/2999 [07:59<48:18,  1.12s/it]

[성공] 419번 카드 (현대카드ZERO MOBILE(할인형)) 수집 완료

 14%|█▍        | 419/2999 [08:00<48:18,  1.12s/it]

[성공] 420번 카드 (현대카드ZERO(포인트형)) 수집 완료

 14%|█▍        | 420/2999 [08:01<47:55,  1.11s/it]

[성공] 421번 카드 (현대카드M-경차전용카드(유류세 환급)) 수집 완료

 14%|█▍        | 421/2999 [08:02<48:04,  1.12s/it]

[성공] 422번 카드 (the Green) 수집 완료

 14%|█▍        | 422/2999 [08:04<48:03,  1.12s/it]

[성공] 423번 카드 (the Red Edition3) 수집 완료

 14%|█▍        | 423/2999 [08:05<48:06,  1.12s/it]

[성공] 424번 카드 (the Purple Edition2) 수집 완료

 14%|█▍        | 424/2999 [08:06<48:11,  1.12s/it]

[성공] 425번 카드 (코스트코 리워드 현대카드) 수집 완료

 14%|█▍        | 425/2999 [08:07<47:59,  1.12s/it]

[성공] 426번 카드 (알파원카드) 수집 완료

 14%|█▍        | 426/2999 [08:08<48:46,  1.14s/it]

[성공] 427번 카드 (내일배움카드) 수집 완료

 14%|█▍        | 427/2999 [08:09<48:15,  1.13s/it]

[Skip] 428번 카드 정보가 존재하지 않습니다.

 14%|█▍        | 428/2999 [08:10<47:23,  1.11s/it]

[Skip] 429번 카드 정보가 존재하지 않습니다.

 14%|█▍        | 429/2999 [08:11<46:54,  1.10s/it]

[성공] 430번 카드 (아시아나클럽 롯데 플래티넘 카드) 수집 완료

 14%|█▍        | 430/2999 [08:12<47:05,  1.10s/it]

[성공] 431번 카드 (아시아나클럽 롯데 골드 아멕스카드) 수집 완료

 14%|█▍        | 431/2999 [08:14<46:48,  1.09s/it]

[성공] 432번 카드 (SKYPASS 롯데 아멕스카드) 수집 완료

 14%|█▍        | 432/2999 [08:15<46:45,  1.09s/it]

[성공] 433번 카드 (롯데카드 텔로 SKT) 수집 완료

 14%|█▍        | 433/2999 [08:16<46:49,  1.10s/it]

[성공] 434번 카드 (SSG카드) 수집 완료

 14%|█▍        | 434/2999 [08:17<46:49,  1.10s/it]

[성공] 435번 카드 (카카오뱅크 프렌즈 체크카드) 수집 완료

 15%|█▍        | 435/2999 [08:18<47:15,  1.11s/it]

[성공] 436번 카드 (케이뱅크 X KT멤버십더블혜택 체크카드) 수집 완료

 15%|█▍        | 436/2999 [08:19<48:50,  1.14s/it]

[성공] 437번 카드 (케이뱅크X네이버페이 체크카드2) 수집 완료

 15%|█▍        | 437/2999 [08:20<50:44,  1.19s/it]

[성공] 438번 카드 (케이뱅크 체크카드 포인트적립형) 수집 완료

 15%|█▍        | 438/2999 [08:22<49:46,  1.17s/it]

[성공] 439번 카드 (케이뱅크X해피포인트 체크카드) 수집 완료

 15%|█▍        | 439/2999 [08:23<48:39,  1.14s/it]

[성공] 440번 카드 (GD카드(체크)) 수집 완료

 15%|█▍        | 440/2999 [08:24<48:04,  1.13s/it]

[성공] 441번 카드 (일상의 기쁨카드(체크)) 수집 완료

 15%|█▍        | 441/2999 [08:25<47:44,  1.12s/it]

[성공] 442번 카드 (IBK 국민행복 체크카드) 수집 완료

 15%|█▍        | 442/2999 [08:26<50:58,  1.20s/it]

[성공] 443번 카드 (아이행복카드(체크)) 수집 완료

 15%|█▍        | 443/2999 [08:27<49:43,  1.17s/it]

[성공] 444번 카드 (참! 좋은 글로벌 체크카드) 수집 완료

 15%|█▍        | 444/2999 [08:28<48:43,  1.14s/it]

[성공] 445번 카드 (문화융성카드(체크)) 수집 완료

 15%|█▍        | 445/2999 [08:29<47:57,  1.13s/it]

[성공] 446번 카드 (IBK 나라사랑카드) 수집 완료

 15%|█▍        | 446/2999 [08:31<50:31,  1.19s/it]

[성공] 447번 카드 (CLUB Premier (Travel 형)) 수집 완료

 15%|█▍        | 447/2999 [08:32<49:23,  1.16s/it]

[성공] 448번 카드 (CLUB Premier (Hotel형)) 수집 완료

 15%|█▍        | 448/2999 [08:33<49:23,  1.16s/it]

[성공] 449번 카드 (CLUB Signature SKYPASS 카드) 수집 완료

 15%|█▍        | 449/2999 [08:34<48:33,  1.14s/it]

[성공] 450번 카드 (CLUB Signature Asiana Club 카드) 수집 완료

 15%|█▌        | 450/2999 [08:35<49:57,  1.18s/it]

[성공] 451번 카드 (CLUB Primus Point 카드) 수집 완료

 15%|█▌        | 451/2999 [08:37<48:52,  1.15s/it]

[성공] 452번 카드 (CLUB Primus Skypass 카드) 수집 완료

 15%|█▌        | 452/2999 [08:38<48:14,  1.14s/it]

[성공] 453번 카드 (CLUB Primus Asiana Club 카드) 수집 완료

 15%|█▌        | 453/2999 [08:39<48:28,  1.14s/it]

[성공] 454번 카드 (가온 올포인트 체크카드) 수집 완료

 15%|█▌        | 454/2999 [08:40<47:52,  1.13s/it]

[성공] 455번 카드 (롯데 국민행복카드) 수집 완료

 15%|█▌        | 455/2999 [08:41<49:06,  1.16s/it]

[성공] 456번 카드 (롯데 아이행복 카드) 수집 완료

 15%|█▌        | 456/2999 [08:42<48:13,  1.14s/it]

[성공] 457번 카드 (썸타는 우리 체크) 수집 완료

 15%|█▌        | 457/2999 [08:43<47:58,  1.13s/it]

[성공] 458번 카드 (네이버페이 taptap) 수집 완료

 15%|█▌        | 458/2999 [08:44<47:41,  1.13s/it]

[성공] 459번 카드 (카드의정석 WOWRI) 수집 완료

 15%|█▌        | 459/2999 [08:46<48:07,  1.14s/it]

[Skip] 460번 카드 정보가 존재하지 않습니다.

 15%|█▌        | 460/2999 [08:47<47:17,  1.12s/it]

[성공] 461번 카드 (현대카드M Edition2) 수집 완료

 15%|█▌        | 461/2999 [08:48<48:56,  1.16s/it]

[성공] 462번 카드 (현대카드M3 Edition2) 수집 완료

 15%|█▌        | 462/2999 [08:49<48:27,  1.15s/it]

[성공] 463번 카드 (신세계 씨티 클리어 카드) 수집 완료

 15%|█▌        | 463/2999 [08:50<48:19,  1.14s/it]

[Skip] 464번 카드 정보가 존재하지 않습니다.

 15%|█▌        | 464/2999 [08:51<47:33,  1.13s/it]

[성공] 465번 카드 (K리그 축덕 하나멤버스 1Q Play1 카드) 수집 완료

 16%|█▌        | 465/2999 [08:52<47:41,  1.13s/it]

[성공] 466번 카드 (신한카드 Air One) 수집 완료

 16%|█▌        | 466/2999 [08:54<47:37,  1.13s/it]

[Skip] 467번 카드 정보가 존재하지 않습니다.

 16%|█▌        | 467/2999 [08:55<47:31,  1.13s/it]

[Skip] 468번 카드 정보가 존재하지 않습니다.

 16%|█▌        | 468/2999 [08:56<47:08,  1.12s/it]

[성공] 469번 카드 (Easy pick카드) 수집 완료

 16%|█▌        | 469/2999 [08:57<46:56,  1.11s/it]

[성공] 470번 카드 (Easy on카드) 수집 완료

 16%|█▌        | 470/2999 [08:58<47:57,  1.14s/it]

[성공] 471번 카드 (LOTTE ONers 롯데카드) 수집 완료

 16%|█▌        | 471/2999 [08:59<47:23,  1.12s/it]

[성공] 472번 카드 (카드의정석 일본여행) 수집 완료

 16%|█▌        | 472/2999 [09:00<49:59,  1.19s/it]

[성공] 473번 카드 (카드의정석 UniMile) 수집 완료

 16%|█▌        | 473/2999 [09:02<50:06,  1.19s/it]

[성공] 474번 카드 (카카오페이 신한 체크카드(무지)) 수집 완료

 16%|█▌        | 474/2999 [09:03<49:34,  1.18s/it]

[성공] 475번 카드 (ONE AIR(UniMile)) 수집 완료

 16%|█▌        | 475/2999 [09:04<48:41,  1.16s/it]

[성공] 476번 카드 (신한카드 Deep Making) 수집 완료

 16%|█▌        | 476/2999 [09:05<51:21,  1.22s/it]

[성공] 477번 카드 (신한카드 Deep Taking) 수집 완료

 16%|█▌        | 477/2999 [09:06<50:36,  1.20s/it]

[성공] 478번 카드 (마이 홈플러스 신한카드) 수집 완료

 16%|█▌        | 478/2999 [09:08<49:35,  1.18s/it]

[성공] 479번 카드 (마이 홈플러스 체크카드) 수집 완료

 16%|█▌        | 479/2999 [09:09<50:01,  1.19s/it]

[성공] 480번 카드 (카카오 T 하나카드) 수집 완료

 16%|█▌        | 480/2999 [09:10<48:51,  1.16s/it]

[성공] 481번 카드 (카드의정석 댕댕냥이(강아지)) 수집 완료

 16%|█▌        | 481/2999 [09:11<48:22,  1.15s/it]

[성공] 482번 카드 (카드의정석 댕댕냥이(고양이)) 수집 완료

 16%|█▌        | 482/2999 [09:12<47:56,  1.14s/it]

[성공] 483번 카드 (뉴타임카드) 수집 완료

 16%|█▌        | 483/2999 [09:13<49:03,  1.17s/it]

[성공] 484번 카드 (탄탄대로 Biz 티타늄카드) 수집 완료

 16%|█▌        | 484/2999 [09:15<48:35,  1.16s/it]

[성공] 485번 카드 (탄탄대로 올쇼핑 티타늄카드) 수집 완료

 16%|█▌        | 485/2999 [09:16<48:59,  1.17s/it]

[성공] 486번 카드 (CJ ONE 우리카드 체크) 수집 완료

 16%|█▌        | 486/2999 [09:17<48:20,  1.15s/it]

[성공] 487번 카드 (신한카드 B.Big(마이펫 스노우볼 삑)) 수집 완료

 16%|█▌        | 487/2999 [09:18<47:59,  1.15s/it]

[성공] 488번 카드 (Easy auto 티타늄카드) 수집 완료

 16%|█▋        | 488/2999 [09:19<47:28,  1.13s/it]

[성공] 489번 카드 (Easy fly 티타늄카드) 수집 완료

 16%|█▋        | 489/2999 [09:20<47:01,  1.12s/it]

[성공] 490번 카드 (11번가 신한카드) 수집 완료

 16%|█▋        | 490/2999 [09:21<46:48,  1.12s/it]

[성공] 491번 카드 (11번가 신한카드 체크) 수집 완료

 16%|█▋        | 491/2999 [09:23<48:58,  1.17s/it]

[성공] 492번 카드 (현대카드M Edition3) 수집 완료

 16%|█▋        | 492/2999 [09:24<49:16,  1.18s/it]

[성공] 493번 카드 (현대카드M2 Edition3) 수집 완료

 16%|█▋        | 493/2999 [09:25<48:17,  1.16s/it]

[성공] 494번 카드 (현대카드M3 Edition3) 수집 완료

 16%|█▋        | 494/2999 [09:26<47:35,  1.14s/it]

[Skip] 495번 카드 정보가 존재하지 않습니다.

 17%|█▋        | 495/2999 [09:27<46:54,  1.12s/it]

[성공] 496번 카드 (씨티 글로벌 월렛 체크카드) 수집 완료

 17%|█▋        | 496/2999 [09:28<46:42,  1.12s/it]

[성공] 497번 카드 (NEW농촌사랑체크카드) 수집 완료

 17%|█▋        | 497/2999 [09:29<46:22,  1.11s/it]

[성공] 498번 카드 (농부의마음 Farmers Heart 체크카드) 수집 완료

 17%|█▋        | 498/2999 [09:30<46:15,  1.11s/it]

[성공] 499번 카드 (체크카드) 수집 완료

 17%|█▋        | 499/2999 [09:31<45:54,  1.10s/it]

[성공] 500번 카드 (신세계면세점 SSG카드) 수집 완료

 17%|█▋        | 500/2999 [09:33<46:12,  1.11s/it]

[성공] 501번 카드 (이마트에브리데이 SSG카드) 수집 완료

 17%|█▋        | 501/2999 [09:34<45:52,  1.10s/it]

[성공] 502번 카드 (네이버페이 플래티넘 롯데카드) 수집 완료

 17%|█▋        | 502/2999 [09:35<46:05,  1.11s/it]

[성공] 503번 카드 (씨티 메가마일 스카이패스) 수집 완료

 17%|█▋        | 503/2999 [09:36<47:44,  1.15s/it]

[성공] 504번 카드 (씨티 메가마일 아시아나) 수집 완료

 17%|█▋        | 504/2999 [09:37<47:41,  1.15s/it]

[성공] 505번 카드 (적립조아카드) 수집 완료

 17%|█▋        | 505/2999 [09:38<47:17,  1.14s/it]

[성공] 506번 카드 (할인조아카드) 수집 완료

 17%|█▋        | 506/2999 [09:39<46:36,  1.12s/it]

[성공] 507번 카드 (쇼핑조아카드) 수집 완료

 17%|█▋        | 507/2999 [09:41<47:20,  1.14s/it]

[성공] 508번 카드 (올바른 Edu 카드) 수집 완료

 17%|█▋        | 508/2999 [09:42<46:47,  1.13s/it]

[Skip] 509번 카드 정보가 존재하지 않습니다.

 17%|█▋        | 509/2999 [09:43<46:01,  1.11s/it]

[Skip] 510번 카드 정보가 존재하지 않습니다.

 17%|█▋        | 510/2999 [09:44<45:21,  1.09s/it]

[Skip] 511번 카드 정보가 존재하지 않습니다.

 17%|█▋        | 511/2999 [09:45<44:46,  1.08s/it]

[성공] 512번 카드 (올바른 POINT UP 카드) 수집 완료

 17%|█▋        | 512/2999 [09:46<45:07,  1.09s/it]

[성공] 513번 카드 (올바른 POINT UP+ 카드) 수집 완료

 17%|█▋        | 513/2999 [09:47<46:32,  1.12s/it]

[성공] 514번 카드 (올바른 BAZIC 카드) 수집 완료

 17%|█▋        | 514/2999 [09:48<48:37,  1.17s/it]

[Skip] 515번 카드 정보가 존재하지 않습니다.

 17%|█▋        | 515/2999 [09:50<48:42,  1.18s/it]

[성공] 516번 카드 (올바른 BAZIC+ 카드) 수집 완료

 17%|█▋        | 516/2999 [09:51<48:55,  1.18s/it]

[성공] 517번 카드 (NH1934 체크카드) 수집 완료

 17%|█▋        | 517/2999 [09:52<47:33,  1.15s/it]

[Skip] 518번 카드 정보가 존재하지 않습니다.

 17%|█▋        | 518/2999 [09:53<46:39,  1.13s/it]

[Skip] 519번 카드 정보가 존재하지 않습니다.

 17%|█▋        | 519/2999 [09:54<46:31,  1.13s/it]

[성공] 520번 카드 (스마일 신용카드) 수집 완료

 17%|█▋        | 520/2999 [09:55<46:43,  1.13s/it]

[성공] 521번 카드 (카드의정석 베트남여행) 수집 완료

 17%|█▋        | 521/2999 [09:56<46:20,  1.12s/it]

[성공] 522번 카드 (Liiv M 카드) 수집 완료

 17%|█▋        | 522/2999 [09:58<49:44,  1.20s/it]

[성공] 523번 카드 (Liiv M 체크카드) 수집 완료

 17%|█▋        | 523/2999 [09:59<48:37,  1.18s/it]

[Skip] 524번 카드 정보가 존재하지 않습니다.

 17%|█▋        | 524/2999 [10:00<47:30,  1.15s/it]

[성공] 525번 카드 (에너지플러스카드) 수집 완료

 18%|█▊        | 525/2999 [10:01<46:43,  1.13s/it]

[성공] 526번 카드 (NH농협 올바른LIFE카드(할인형)) 수집 완료

 18%|█▊        | 526/2999 [10:02<46:37,  1.13s/it]

[성공] 527번 카드 (NH농협 올바른LIFE카드(적립형)) 수집 완료

 18%|█▊        | 527/2999 [10:03<45:59,  1.12s/it]

[성공] 528번 카드 (라이언 치즈 체크카드) 수집 완료

 18%|█▊        | 528/2999 [10:05<48:11,  1.17s/it]

[성공] 529번 카드 (the Red Edition4) 수집 완료

 18%|█▊        | 529/2999 [10:06<47:31,  1.15s/it]

[성공] 530번 카드 (LCC UniMile카드) 수집 완료

 18%|█▊        | 530/2999 [10:07<47:04,  1.14s/it]

[성공] 531번 카드 (NH농협 올바른 하나로(Hanaro) 카드) 수집 완료

 18%|█▊        | 531/2999 [10:08<47:32,  1.16s/it]

[성공] 532번 카드 (NH농협 올바른 하나로(Hanaro) 체크카드) 수집 완료

 18%|█▊        | 532/2999 [10:09<46:49,  1.14s/it]

[성공] 533번 카드 (I’m DRIVING) 수집 완료

 18%|█▊        | 533/2999 [10:10<46:15,  1.13s/it]

[성공] 534번 카드 (인터파크 롯데카드) 수집 완료

 18%|█▊        | 534/2999 [10:11<47:45,  1.16s/it]

[성공] 535번 카드 (샤롯데 플래티넘 스타 카드) 수집 완료

 18%|█▊        | 535/2999 [10:13<47:24,  1.15s/it]

[성공] 536번 카드 (신한카드 Deep Once) 수집 완료

 18%|█▊        | 536/2999 [10:14<47:14,  1.15s/it]

[성공] 537번 카드 (신한카드 Deep Once Plus) 수집 완료

 18%|█▊        | 537/2999 [10:15<47:37,  1.16s/it]

[성공] 538번 카드 (Easy study 티타늄카드) 수집 완료

 18%|█▊        | 538/2999 [10:16<47:11,  1.15s/it]

[성공] 539번 카드 (샤롯데 비앤 롯데카드) 수집 완료

 18%|█▊        | 539/2999 [10:17<46:30,  1.13s/it]

[성공] 540번 카드 (I’m ACTIVE) 수집 완료

 18%|█▊        | 540/2999 [10:18<46:51,  1.14s/it]

[성공] 541번 카드 (I’m Wonderful Plus) 수집 완료

 18%|█▊        | 541/2999 [10:19<46:24,  1.13s/it]

[성공] 542번 카드 (갤러리아 우리카드) 수집 완료

 18%|█▊        | 542/2999 [10:20<46:03,  1.12s/it]

[성공] 543번 카드 (카드의정석 APT) 수집 완료

 18%|█▊        | 543/2999 [10:22<46:08,  1.13s/it]

[성공] 544번 카드 (카드의정석 APT Platinum) 수집 완료

 18%|█▊        | 544/2999 [10:23<45:50,  1.12s/it]

[성공] 545번 카드 (카드의정석 APT CHECK) 수집 완료

 18%|█▊        | 545/2999 [10:24<45:40,  1.12s/it]

[성공] 546번 카드 (다둥이 행복카드) 수집 완료

 18%|█▊        | 546/2999 [10:25<45:25,  1.11s/it]

[Skip] 547번 카드 정보가 존재하지 않습니다.

 18%|█▊        | 547/2999 [10:26<44:47,  1.10s/it]

[성공] 548번 카드 (카드의정석 MILEAGE SKYPASS) 수집 완료

 18%|█▊        | 548/2999 [10:27<44:42,  1.09s/it]

[성공] 549번 카드 (아이행복카드) 수집 완료

 18%|█▊        | 549/2999 [10:28<45:49,  1.12s/it]

[성공] 550번 카드 (에이스플러스체크카드 (벨리미키)) 수집 완료

 18%|█▊        | 550/2999 [10:29<45:59,  1.13s/it]

[성공] 551번 카드 (Easy link 티타늄카드) 수집 완료

 18%|█▊        | 551/2999 [10:30<46:02,  1.13s/it]

[성공] 552번 카드 (삼성카드 2 V4) 수집 완료

 18%|█▊        | 552/2999 [10:32<47:09,  1.16s/it]

[성공] 553번 카드 (삼성카드 3 V4) 수집 완료

 18%|█▊        | 553/2999 [10:33<46:34,  1.14s/it]

[성공] 554번 카드 (삼성카드 6 V4) 수집 완료

 18%|█▊        | 554/2999 [10:34<46:27,  1.14s/it]

[성공] 555번 카드 (삼성카드 4 V4) 수집 완료

 19%|█▊        | 555/2999 [10:35<46:38,  1.15s/it]

[성공] 556번 카드 (삼성카드 4 V4 (포인트)) 수집 완료

 19%|█▊        | 556/2999 [10:36<47:26,  1.17s/it]

[성공] 557번 카드 (삼성카드 5 V4) 수집 완료

 19%|█▊        | 557/2999 [10:38<48:21,  1.19s/it]

[성공] 558번 카드 (카드의정석 MILEAGE Asiana Club) 수집 완료

 19%|█▊        | 558/2999 [10:39<47:57,  1.18s/it]

[성공] 559번 카드 (펭수 노리 체크카드(펭카)) 수집 완료

 19%|█▊        | 559/2999 [10:40<47:17,  1.16s/it]

[성공] 560번 카드 (위 레아카드(아시아나클럽)) 수집 완료

 19%|█▊        | 560/2999 [10:41<46:44,  1.15s/it]

[성공] 561번 카드 (펭수 노리 체크카드(펭모티콘)) 수집 완료

 19%|█▊        | 561/2999 [10:42<46:55,  1.15s/it]

[성공] 562번 카드 (올바른 GIVE 카드) 수집 완료

 19%|█▊        | 562/2999 [10:43<46:34,  1.15s/it]

[성공] 563번 카드 (위 레아카드(스카이패스)) 수집 완료

 19%|█▉        | 563/2999 [10:44<47:05,  1.16s/it]

[성공] 564번 카드 (위 레아카드(포인트)) 수집 완료

 19%|█▉        | 564/2999 [10:46<46:19,  1.14s/it]

[성공] 565번 카드 (위 테라카드(스카이패스)) 수집 완료

 19%|█▉        | 565/2999 [10:47<48:07,  1.19s/it]

[성공] 566번 카드 (위 테라카드(아시아나클럽)) 수집 완료

 19%|█▉        | 566/2999 [10:48<47:15,  1.17s/it]

[성공] 567번 카드 (위 테라카드(포인트)) 수집 완료

 19%|█▉        | 567/2999 [10:49<46:22,  1.14s/it]

[성공] 568번 카드 (부릉 삼성카드 BIZ) 수집 완료

 19%|█▉        | 568/2999 [10:50<45:57,  1.13s/it]

[성공] 569번 카드 (현대카드 DIGITAL LOVER) 수집 완료

 19%|█▉        | 569/2999 [10:51<45:52,  1.13s/it]

[성공] 570번 카드 (이로운카드) 수집 완료

 19%|█▉        | 570/2999 [10:52<45:23,  1.12s/it]

[성공] 571번 카드 (어디서나 체크카드) 수집 완료

 19%|█▉        | 571/2999 [10:54<47:46,  1.18s/it]

[성공] 572번 카드 (포미 하이브리드 체크카드) 수집 완료

 19%|█▉        | 572/2999 [10:55<48:42,  1.20s/it]

[성공] 573번 카드 (다드림 체크카드) 수집 완료

 19%|█▉        | 573/2999 [10:56<47:33,  1.18s/it]

[성공] 574번 카드 (드림플러스 아시아나 체크카드) 수집 완료

 19%|█▉        | 574/2999 [10:57<46:42,  1.16s/it]

[성공] 575번 카드 (라이프+플러스 체크카드) 수집 완료

 19%|█▉        | 575/2999 [10:59<51:08,  1.27s/it]

[성공] 576번 카드 (young利한(영리한) 체크카드) 수집 완료

 19%|█▉        | 576/2999 [11:00<49:32,  1.23s/it]

[Skip] 577번 카드 정보가 존재하지 않습니다.

 19%|█▉        | 577/2999 [11:01<47:51,  1.19s/it]

[성공] 578번 카드 (금융포인트리카드) 수집 완료

 19%|█▉        | 578/2999 [11:02<47:38,  1.18s/it]

[성공] 579번 카드 (I’m YOLO 플래티넘) 수집 완료

 19%|█▉        | 579/2999 [11:03<46:44,  1.16s/it]

[성공] 580번 카드 (Easy pick 티타늄 카드) 수집 완료

 19%|█▉        | 580/2999 [11:04<46:49,  1.16s/it]

[성공] 581번 카드 (I’m Powerful) 수집 완료

 19%|█▉        | 581/2999 [11:05<46:06,  1.14s/it]

[성공] 582번 카드 (I’m WONDERFUL platinum) 수집 완료

 19%|█▉        | 582/2999 [11:07<45:37,  1.13s/it]

[성공] 583번 카드 (우리 K-패스(신용)) 수집 완료

 19%|█▉        | 583/2999 [11:08<45:32,  1.13s/it]

[성공] 584번 카드 (우리 K-패스 (COOKIE CHECK)) 수집 완료

 19%|█▉        | 584/2999 [11:09<45:52,  1.14s/it]

[성공] 585번 카드 (행복한 체크카드) 수집 완료

 20%|█▉        | 585/2999 [11:10<46:09,  1.15s/it]

[성공] 586번 카드 (어피치 스윗 체크카드) 수집 완료

 20%|█▉        | 586/2999 [11:11<48:23,  1.20s/it]

[성공] 587번 카드 (모두의 쇼핑) 수집 완료

 20%|█▉        | 587/2999 [11:13<47:46,  1.19s/it]

[성공] 588번 카드 (네이버페이 우리카드 체크) 수집 완료

 20%|█▉        | 588/2999 [11:14<46:52,  1.17s/it]

[성공] 589번 카드 (토스 신용카드) 수집 완료

 20%|█▉        | 589/2999 [11:15<46:49,  1.17s/it]

[Skip] 590번 카드 정보가 존재하지 않습니다.

 20%|█▉        | 590/2999 [11:16<45:46,  1.14s/it]

[성공] 591번 카드 (카카오뱅크 KB국민카드) 수집 완료

 20%|█▉        | 591/2999 [11:17<45:27,  1.13s/it]

[성공] 592번 카드 (카카오뱅크 삼성카드) 수집 완료

 20%|█▉        | 592/2999 [11:18<45:17,  1.13s/it]

[성공] 593번 카드 (카카오뱅크 씨티카드) 수집 완료

 20%|█▉        | 593/2999 [11:19<45:36,  1.14s/it]

[성공] 594번 카드 (카드의정석 삼성디지털프라자) 수집 완료

 20%|█▉        | 594/2999 [11:20<46:03,  1.15s/it]

[성공] 595번 카드 (아이파킹 크레딧 카) 수집 완료

 20%|█▉        | 595/2999 [11:22<46:02,  1.15s/it]

[성공] 596번 카드 (셀리턴 우리카드) 수집 완료

 20%|█▉        | 596/2999 [11:23<46:04,  1.15s/it]

[성공] 597번 카드 (AK우리카드) 수집 완료

 20%|█▉        | 597/2999 [11:24<45:28,  1.14s/it]

[성공] 598번 카드 (AK우리카드 VIP) 수집 완료

 20%|█▉        | 598/2999 [11:25<45:22,  1.13s/it]

[성공] 599번 카드 (AK우리카드 체크) 수집 완료

 20%|█▉        | 599/2999 [11:26<45:12,  1.13s/it]

[성공] 600번 카드 (대한항공카드 030) 수집 완료

 20%|██        | 600/2999 [11:28<49:04,  1.23s/it]

[성공] 601번 카드 (대한항공카드 070) 수집 완료

 20%|██        | 601/2999 [11:29<48:55,  1.22s/it]

[성공] 602번 카드 (대한항공카드 150) 수집 완료

 20%|██        | 602/2999 [11:30<48:37,  1.22s/it]

[성공] 603번 카드 (대한항공카드 the First) 수집 완료

 20%|██        | 603/2999 [11:31<47:49,  1.20s/it]

[성공] 604번 카드 (씨티 프리미어마일 대한항공) 수집 완료

 20%|██        | 604/2999 [11:32<47:48,  1.20s/it]

[성공] 605번 카드 (씨티 프리미어마일 아시아나) 수집 완료

 20%|██        | 605/2999 [11:33<46:51,  1.17s/it]

[성공] 606번 카드 (카드의정석 UNTACT) 수집 완료

 20%|██        | 606/2999 [11:35<46:21,  1.16s/it]

[성공] 607번 카드 (카드의정석 UNTACT PLATINUM) 수집 완료

 20%|██        | 607/2999 [11:36<47:35,  1.19s/it]

[성공] 608번 카드 (현대카드ZERO Edition2(할인형)) 수집 완료

 20%|██        | 608/2999 [11:37<46:55,  1.18s/it]

[성공] 609번 카드 (현대카드ZERO MOBILE Edition2(할인형)) 수집 완료

 20%|██        | 609/2999 [11:38<46:04,  1.16s/it]

[성공] 610번 카드 (현대카드ZERO Edition2(포인트형)) 수집 완료

 20%|██        | 610/2999 [11:39<45:59,  1.16s/it]

[성공] 611번 카드 (현대카드ZERO MOBILE Edition2(포인트형)) 수집 완료

 20%|██        | 611/2999 [11:40<45:48,  1.15s/it]

[성공] 612번 카드 (펫블리(PETvely) 카드) 수집 완료

 20%|██        | 612/2999 [11:41<45:10,  1.14s/it]

[성공] 613번 카드 (신한카드 YaY) 수집 완료

 20%|██        | 613/2999 [11:43<45:08,  1.14s/it]

[성공] 614번 카드 (위글위글 첵첵 체크카드) 수집 완료

 20%|██        | 614/2999 [11:44<44:43,  1.12s/it]

[성공] 615번 카드 (Easy ring 티타늄카드) 수집 완료

 21%|██        | 615/2999 [11:45<44:32,  1.12s/it]

[성공] 616번 카드 (다이소 삼성카드) 수집 완료

 21%|██        | 616/2999 [11:46<46:41,  1.18s/it]

[성공] 617번 카드 (카드의정석 UniMile in JEJU) 수집 완료

 21%|██        | 617/2999 [11:47<45:35,  1.15s/it]

[성공] 618번 카드 (신한카드 Hey Young 체크) 수집 완료

 21%|██        | 618/2999 [11:48<45:41,  1.15s/it]

[Skip] 619번 카드 정보가 존재하지 않습니다.

 21%|██        | 619/2999 [11:49<44:37,  1.13s/it]

[성공] 620번 카드 (LOCA CLASSIC) 수집 완료

 21%|██        | 620/2999 [11:51<44:17,  1.12s/it]

[성공] 621번 카드 (LOCA for Auto) 수집 완료

 21%|██        | 621/2999 [11:52<44:29,  1.12s/it]

[성공] 622번 카드 (LOCA for Coffee) 수집 완료

 21%|██        | 622/2999 [11:53<44:20,  1.12s/it]

[성공] 623번 카드 (LOCA for Edu) 수집 완료

 21%|██        | 623/2999 [11:54<44:26,  1.12s/it]

[성공] 624번 카드 (LOCA for Health) 수집 완료

 21%|██        | 624/2999 [11:55<45:22,  1.15s/it]

[성공] 625번 카드 (LOCA for Shopping) 수집 완료

 21%|██        | 625/2999 [11:56<44:40,  1.13s/it]

[성공] 626번 카드 (LOCA PLATINUM 할인형) 수집 완료

 21%|██        | 626/2999 [11:57<44:13,  1.12s/it]

[성공] 627번 카드 (LOCA PLATINUM 마일리지형) 수집 완료

 21%|██        | 627/2999 [11:58<43:47,  1.11s/it]

[성공] 628번 카드 (카드의정석 POINT CHECK x 아기상어) 수집 완료

 21%|██        | 628/2999 [11:59<43:32,  1.10s/it]

[성공] 629번 카드 ([IBK] 그린카드v2) 수집 완료

 21%|██        | 629/2999 [12:01<43:43,  1.11s/it]

[성공] 630번 카드 (Easy all 카드) 수집 완료

 21%|██        | 630/2999 [12:02<44:33,  1.13s/it]

[성공] 631번 카드 ([NH농협] 그린카드v2) 수집 완료

 21%|██        | 631/2999 [12:03<44:12,  1.12s/it]

[성공] 632번 카드 ([DGB대구] 그린카드v2) 수집 완료

 21%|██        | 632/2999 [12:04<45:23,  1.15s/it]

[성공] 633번 카드 ([BNK부산] 그린카드v2) 수집 완료

 21%|██        | 633/2999 [12:05<45:05,  1.14s/it]

[성공] 634번 카드 (Easy all 티타늄카드) 수집 완료

 21%|██        | 634/2999 [12:06<45:09,  1.15s/it]

[성공] 635번 카드 (올바른 NEW HAVE카드) 수집 완료

 21%|██        | 635/2999 [12:08<44:54,  1.14s/it]

[성공] 636번 카드 (올바른 NEW HAVE+카드) 수집 완료

 21%|██        | 636/2999 [12:09<44:23,  1.13s/it]

[Skip] 637번 카드 정보가 존재하지 않습니다.

 21%|██        | 637/2999 [12:10<43:49,  1.11s/it]

[성공] 638번 카드 (신한 슈퍼SOL 체크) 수집 완료

 21%|██▏       | 638/2999 [12:11<43:47,  1.11s/it]

[Skip] 639번 카드 정보가 존재하지 않습니다.

 21%|██▏       | 639/2999 [12:12<43:10,  1.10s/it]

[Skip] 640번 카드 정보가 존재하지 않습니다.

 21%|██▏       | 640/2999 [12:13<42:43,  1.09s/it]

[Skip] 641번 카드 정보가 존재하지 않습니다.

 21%|██▏       | 641/2999 [12:14<42:28,  1.08s/it]

[Skip] 642번 카드 정보가 존재하지 않습니다.

 21%|██▏       | 642/2999 [12:15<42:14,  1.08s/it]

[Skip] 643번 카드 정보가 존재하지 않습니다.

 21%|██▏       | 643/2999 [12:16<42:02,  1.07s/it]

[성공] 644번 카드 (JYP Fan’s EDM 체크) 수집 완료

 21%|██▏       | 644/2999 [12:17<42:35,  1.09s/it]

[성공] 645번 카드 (L.pay 신한카드 체크) 수집 완료

 22%|██▏       | 645/2999 [12:18<42:58,  1.10s/it]

[성공] 646번 카드 (신한카드 Deep Dream 체크(미니언즈)) 수집 완료

 22%|██▏       | 646/2999 [12:20<44:30,  1.13s/it]

[성공] 647번 카드 (신한카드 S-Line 체크(마이펫)) 수집 완료

 22%|██▏       | 647/2999 [12:21<44:11,  1.13s/it]

[Skip] 648번 카드 정보가 존재하지 않습니다.

 22%|██▏       | 648/2999 [12:22<43:21,  1.11s/it]

[성공] 649번 카드 (마이핏카드(적립형)) 수집 완료

 22%|██▏       | 649/2999 [12:23<43:13,  1.10s/it]

[성공] 650번 카드 (마이핏카드(할인형)) 수집 완료

 22%|██▏       | 650/2999 [12:24<44:22,  1.13s/it]

[성공] 651번 카드 (네이버페이 라인프렌즈 신한카드) 수집 완료

 22%|██▏       | 651/2999 [12:25<45:44,  1.17s/it]

[성공] 652번 카드 (올바른 OIL&PASS) 수집 완료

 22%|██▏       | 652/2999 [12:26<45:08,  1.15s/it]

[성공] 653번 카드 (Air Money(에어머니)카드) 수집 완료

 22%|██▏       | 653/2999 [12:28<44:39,  1.14s/it]

[성공] 654번 카드 (올바른 MYPICK 카드) 수집 완료

 22%|██▏       | 654/2999 [12:29<45:38,  1.17s/it]

[성공] 655번 카드 (Daily With(데일리위드)카드) 수집 완료

 22%|██▏       | 655/2999 [12:30<45:53,  1.17s/it]

[성공] 656번 카드 (카드의 정석 SSO3 NEW-TRO CHECK) 수집 완료

 22%|██▏       | 656/2999 [12:31<44:53,  1.15s/it]

[성공] 657번 카드 (taptap DIGITAL) 수집 완료

 22%|██▏       | 657/2999 [12:32<44:35,  1.14s/it]

[성공] 658번 카드 (taptap DRIVE) 수집 완료

 22%|██▏       | 658/2999 [12:33<44:41,  1.15s/it]

[성공] 659번 카드 (taptap SHOPPING) 수집 완료

 22%|██▏       | 659/2999 [12:35<46:27,  1.19s/it]

[성공] 660번 카드 (LIKIT FUN+ 카드) 수집 완료

 22%|██▏       | 660/2999 [12:36<45:23,  1.16s/it]

[성공] 661번 카드 (카드의정석 UNTACT AIR) 수집 완료

 22%|██▏       | 661/2999 [12:37<44:38,  1.15s/it]

[성공] 662번 카드 (삼성페이카드) 수집 완료

 22%|██▏       | 662/2999 [12:38<44:16,  1.14s/it]

[성공] 663번 카드 (롤라카드) 수집 완료

 22%|██▏       | 663/2999 [12:39<44:12,  1.14s/it]

[성공] 664번 카드 (New PAYCO 롯데카드) 수집 완료

 22%|██▏       | 664/2999 [12:40<43:45,  1.12s/it]

[성공] 665번 카드 (위메프페이 롯데카드) 수집 완료

 22%|██▏       | 665/2999 [12:41<43:20,  1.11s/it]

[성공] 666번 카드 (올바른 FLEX 카드) 수집 완료

 22%|██▏       | 666/2999 [12:43<46:33,  1.20s/it]

[성공] 667번 카드 (모두의 건강) 수집 완료

 22%|██▏       | 667/2999 [12:44<45:22,  1.17s/it]

[성공] 668번 카드 (go 캐시백 글로벌 체크카드) 수집 완료

 22%|██▏       | 668/2999 [12:45<44:57,  1.16s/it]

[성공] 669번 카드 (케이뱅크 플러스 체크카드) 수집 완료

 22%|██▏       | 669/2999 [12:46<44:17,  1.14s/it]

[Skip] 670번 카드 정보가 존재하지 않습니다.

 22%|██▏       | 670/2999 [12:47<43:20,  1.12s/it]

[성공] 671번 카드 (BLISS.7 카드(마일리지)) 수집 완료

 22%|██▏       | 671/2999 [12:48<43:07,  1.11s/it]

[성공] 672번 카드 (BLISS.7 카드(포인트)) 수집 완료

 22%|██▏       | 672/2999 [12:49<43:15,  1.12s/it]

[성공] 673번 카드 (스타벅스 현대카드) 수집 완료

 22%|██▏       | 673/2999 [12:50<44:22,  1.14s/it]

[성공] 674번 카드 (IBK무민카드(체크)) 수집 완료

 22%|██▏       | 674/2999 [12:52<45:24,  1.17s/it]

[성공] 675번 카드 (Air Money(에어머니)체크) 수집 완료

 23%|██▎       | 675/2999 [12:53<44:46,  1.16s/it]

[성공] 676번 카드 (올리 POINT 체크) 수집 완료

 23%|██▎       | 676/2999 [12:54<45:23,  1.17s/it]

[성공] 677번 카드 (배달의민족 비장의카드 V.2) 수집 완료

 23%|██▎       | 677/2999 [12:55<45:51,  1.19s/it]

[Skip] 678번 카드 정보가 존재하지 않습니다.

 23%|██▎       | 678/2999 [12:56<44:28,  1.15s/it]

[성공] 679번 카드 (샘 쏘영 체크카드) 수집 완료

 23%|██▎       | 679/2999 [12:57<44:10,  1.14s/it]

[성공] 680번 카드 (쏘영 체크카드) 수집 완료

 23%|██▎       | 680/2999 [12:59<43:51,  1.13s/it]

[성공] 681번 카드 (SSG.COM 삼성카드) 수집 완료

 23%|██▎       | 681/2999 [13:00<43:34,  1.13s/it]

[Skip] 682번 카드 정보가 존재하지 않습니다.

 23%|██▎       | 682/2999 [13:01<42:50,  1.11s/it]

[Skip] 683번 카드 정보가 존재하지 않습니다.

 23%|██▎       | 683/2999 [13:02<42:14,  1.09s/it]

[성공] 684번 카드 (리틀프렌즈 체크카드) 수집 완료

 23%|██▎       | 684/2999 [13:03<42:25,  1.10s/it]

[성공] 685번 카드 (하이틴즈 체크카드) 수집 완료

 23%|██▎       | 685/2999 [13:04<43:58,  1.14s/it]

[성공] 686번 카드 (카카오뱅크 mini카드) 수집 완료

 23%|██▎       | 686/2999 [13:05<43:42,  1.13s/it]

[성공] 687번 카드 (신한카드 Unboxing) 수집 완료

 23%|██▎       | 687/2999 [13:06<43:36,  1.13s/it]

[성공] 688번 카드 (카드의정석 POINT CHECK x 핑크퐁) 수집 완료

 23%|██▎       | 688/2999 [13:08<43:54,  1.14s/it]

[성공] 689번 카드 (해외에선 체크카드) 수집 완료

 23%|██▎       | 689/2999 [13:09<43:20,  1.13s/it]

[성공] 690번 카드 (모두의 일상 체크카드) 수집 완료

 23%|██▎       | 690/2999 [13:10<42:51,  1.11s/it]

[성공] 691번 카드 (요기요 삼성카드) 수집 완료

 23%|██▎       | 691/2999 [13:11<43:03,  1.12s/it]

[성공] 692번 카드 (요기요 신한카드) 수집 완료

 23%|██▎       | 692/2999 [13:12<42:48,  1.11s/it]

[성공] 693번 카드 (신한카드 MY CAR) 수집 완료

 23%|██▎       | 693/2999 [13:13<42:48,  1.11s/it]

[성공] 694번 카드 (배민현대카드) 수집 완료

 23%|██▎       | 694/2999 [13:14<43:04,  1.12s/it]

[성공] 695번 카드 (롯데백화점 FLEX카드) 수집 완료

 23%|██▎       | 695/2999 [13:15<42:59,  1.12s/it]

[성공] 696번 카드 (카드의정석 US) 수집 완료

 23%|██▎       | 696/2999 [13:17<44:15,  1.15s/it]

[성공] 697번 카드 (탄탄대로 Biz 카드) 수집 완료

 23%|██▎       | 697/2999 [13:18<44:30,  1.16s/it]

[Skip] 698번 카드 정보가 존재하지 않습니다.

 23%|██▎       | 698/2999 [13:19<43:16,  1.13s/it]

[성공] 699번 카드 (톡톡 with카드) 수집 완료

 23%|██▎       | 699/2999 [13:20<43:36,  1.14s/it]

[성공] 700번 카드 (현대카드 M BOOST) 수집 완료

 23%|██▎       | 700/2999 [13:21<43:21,  1.13s/it]

[성공] 701번 카드 (현대카드 X BOOST) 수집 완료

 23%|██▎       | 701/2999 [13:22<43:14,  1.13s/it]

[성공] 702번 카드 (현대카드 M2 BOOST) 수집 완료

 23%|██▎       | 702/2999 [13:24<46:32,  1.22s/it]

[성공] 703번 카드 (현대카드 M3 BOOST) 수집 완료

 23%|██▎       | 703/2999 [13:25<46:20,  1.21s/it]

[성공] 704번 카드 (현대카드 X2 BOOST) 수집 완료

 23%|██▎       | 704/2999 [13:26<45:00,  1.18s/it]

[성공] 705번 카드 (현대카드 X3 BOOST) 수집 완료

 24%|██▎       | 705/2999 [13:27<44:50,  1.17s/it]

[성공] 706번 카드 (LOCA MONEY) 수집 완료

 24%|██▎       | 706/2999 [13:28<43:57,  1.15s/it]

[성공] 707번 카드 (LOCA 100) 수집 완료

 24%|██▎       | 707/2999 [13:30<47:23,  1.24s/it]

[성공] 708번 카드 (쏘카카드) 수집 완료

 24%|██▎       | 708/2999 [13:31<45:56,  1.20s/it]

[성공] 709번 카드 (MULTI Any(멀티 애니) 카드) 수집 완료

 24%|██▎       | 709/2999 [13:32<45:22,  1.19s/it]

[성공] 710번 카드 (MULTI On(멀티 온) 카드) 수집 완료

 24%|██▎       | 710/2999 [13:33<45:33,  1.19s/it]

[성공] 711번 카드 (MULTI Living(멀티 리빙) 카드) 수집 완료

 24%|██▎       | 711/2999 [13:34<45:02,  1.18s/it]

[성공] 712번 카드 (신한카드 국민행복) 수집 완료

 24%|██▎       | 712/2999 [13:35<44:07,  1.16s/it]

[성공] 713번 카드 (신한카드 국민행복 체크) 수집 완료

 24%|██▍       | 713/2999 [13:36<43:29,  1.14s/it]

[성공] 714번 카드 (MULTI Oil(멀티 오일) 카드) 수집 완료

 24%|██▍       | 714/2999 [13:38<42:59,  1.13s/it]

[성공] 715번 카드 (MULTI Young(멀티 영) 카드) 수집 완료

 24%|██▍       | 715/2999 [13:39<43:08,  1.13s/it]

[성공] 716번 카드 (메리어트 본보이™ 더 베스트 신한카드) 수집 완료

 24%|██▍       | 716/2999 [13:40<43:49,  1.15s/it]

[성공] 717번 카드 (그랑블루 1st) 수집 완료

 24%|██▍       | 717/2999 [13:41<43:15,  1.14s/it]

[성공] 718번 카드 (국민행복 삼성카드 V2) 수집 완료

 24%|██▍       | 718/2999 [13:42<43:18,  1.14s/it]

[성공] 719번 카드 (WON DISCOUNT(원 디스카운트) AIR) 수집 완료

 24%|██▍       | 719/2999 [13:43<42:44,  1.12s/it]

[성공] 720번 카드 (WON POINT(원 포인트) AIR) 수집 완료

 24%|██▍       | 720/2999 [13:44<42:25,  1.12s/it]

[성공] 721번 카드 (국민행복카드 S2) 수집 완료

 24%|██▍       | 721/2999 [13:45<42:21,  1.12s/it]

[성공] 722번 카드 (국민행복 체크카드 S2) 수집 완료

 24%|██▍       | 722/2999 [13:47<42:18,  1.11s/it]

[성공] 723번 카드 (IBK무민카드(신용)) 수집 완료

 24%|██▍       | 723/2999 [13:48<42:49,  1.13s/it]

[성공] 724번 카드 (the Purple osée) 수집 완료

 24%|██▍       | 724/2999 [13:49<42:59,  1.13s/it]

[성공] 725번 카드 (새로이 체크카드) 수집 완료

 24%|██▍       | 725/2999 [13:50<43:18,  1.14s/it]

[성공] 726번 카드 (알뜰폰 Hub 카드) 수집 완료

 24%|██▍       | 726/2999 [13:51<42:44,  1.13s/it]

[성공] 727번 카드 (알뜰폰 Hub Ⅱ 카드) 수집 완료

 24%|██▍       | 727/2999 [13:52<42:20,  1.12s/it]

[성공] 728번 카드 (언택트 L 하나카드) 수집 완료

 24%|██▍       | 728/2999 [13:53<41:57,  1.11s/it]

[성공] 729번 카드 (삼성스토어 BENEFIT 삼성카드) 수집 완료

 24%|██▍       | 729/2999 [13:54<41:46,  1.10s/it]

[성공] 730번 카드 (현대카드Z family) 수집 완료

 24%|██▍       | 730/2999 [13:56<41:51,  1.11s/it]

[성공] 731번 카드 (현대카드Z work) 수집 완료

 24%|██▍       | 731/2999 [13:57<42:18,  1.12s/it]

[성공] 732번 카드 (현대카드Z ontact) 수집 완료

 24%|██▍       | 732/2999 [13:58<42:49,  1.13s/it]

[성공] 733번 카드 (무신사 현대카드) 수집 완료

 24%|██▍       | 733/2999 [13:59<42:19,  1.12s/it]

[성공] 734번 카드 (MULTI Global(멀티 글로벌) 카드) 수집 완료

 24%|██▍       | 734/2999 [14:00<43:40,  1.16s/it]

[성공] 735번 카드 (커피빈 신용카드) 수집 완료

 25%|██▍       | 735/2999 [14:01<42:57,  1.14s/it]

[성공] 736번 카드 (American Express® Reserve) 수집 완료

 25%|██▍       | 736/2999 [14:02<42:17,  1.12s/it]

[성공] 737번 카드 (American Express® Gold) 수집 완료

 25%|██▍       | 737/2999 [14:03<42:03,  1.12s/it]

[성공] 738번 카드 (신한카드 혼디모앙) 수집 완료

 25%|██▍       | 738/2999 [14:05<42:21,  1.12s/it]

[성공] 739번 카드 (나라사랑체크카드) 수집 완료

 25%|██▍       | 739/2999 [14:06<42:03,  1.12s/it]

[성공] 740번 카드 (Hyundai Mobility(모빌리티) 카드) 수집 완료

 25%|██▍       | 740/2999 [14:07<41:50,  1.11s/it]

[성공] 741번 카드 (Hyundai Mobility(모빌리티) Platinum) 수집 완료

 25%|██▍       | 741/2999 [14:08<41:45,  1.11s/it]

[Skip] 742번 카드 정보가 존재하지 않습니다.

 25%|██▍       | 742/2999 [14:09<41:21,  1.10s/it]

[Skip] 743번 카드 정보가 존재하지 않습니다.

 25%|██▍       | 743/2999 [14:10<40:54,  1.09s/it]

[성공] 744번 카드 (IKEA(이케아) Family with 신한카드) 수집 완료

 25%|██▍       | 744/2999 [14:11<41:43,  1.11s/it]

[성공] 745번 카드 (알뜰교통 my pass 마패 신용카드(Hana-BC)) 수집 완료

 25%|██▍       | 745/2999 [14:12<41:45,  1.11s/it]

[성공] 746번 카드 (알뜰교통 비바 e 플래티늄 체크카드) 수집 완료

 25%|██▍       | 746/2999 [14:13<41:49,  1.11s/it]

[성공] 747번 카드 (Liiv M Ⅱ 카드) 수집 완료

 25%|██▍       | 747/2999 [14:14<41:20,  1.10s/it]

[성공] 748번 카드 (이지캐시백) 수집 완료

 25%|██▍       | 748/2999 [14:16<41:31,  1.11s/it]

[성공] 749번 카드 (VIVA X 체크카드) 수집 완료

 25%|██▍       | 749/2999 [14:17<41:21,  1.10s/it]

[성공] 750번 카드 (하나 국민행복 체크카드) 수집 완료

 25%|██▌       | 750/2999 [14:18<41:49,  1.12s/it]

[성공] 751번 카드 (KB국민 국민행복카드) 수집 완료

 25%|██▌       | 751/2999 [14:19<41:27,  1.11s/it]

[성공] 752번 카드 (KB국민 국민행복체크) 수집 완료

 25%|██▌       | 752/2999 [14:20<43:41,  1.17s/it]

[성공] 753번 카드 (아모레퍼시픽 신한카드) 수집 완료

 25%|██▌       | 753/2999 [14:21<43:15,  1.16s/it]

[성공] 754번 카드 (국민행복 삼성체크카드 V2) 수집 완료

 25%|██▌       | 754/2999 [14:22<42:34,  1.14s/it]

[성공] 755번 카드 (LIKIT fun 체크카드) 수집 완료

 25%|██▌       | 755/2999 [14:24<42:04,  1.12s/it]

[성공] 756번 카드 (LIKIT all 체크카드) 수집 완료

 25%|██▌       | 756/2999 [14:25<41:36,  1.11s/it]

[성공] 757번 카드 (LIKIT on 체크카드) 수집 완료

 25%|██▌       | 757/2999 [14:26<41:12,  1.10s/it]

[성공] 758번 카드 (다이소 신한카드) 수집 완료

 25%|██▌       | 758/2999 [14:27<41:19,  1.11s/it]

[Skip] 759번 카드 정보가 존재하지 않습니다.

 25%|██▌       | 759/2999 [14:28<40:51,  1.09s/it]

[성공] 760번 카드 (Young Youth 체크카드) 수집 완료

 25%|██▌       | 760/2999 [14:29<40:55,  1.10s/it]

[성공] 761번 카드 (Hole In:WON(홀인원) 카드) 수집 완료

 25%|██▌       | 761/2999 [14:30<40:58,  1.10s/it]

[성공] 762번 카드 (NU 오하쳌(오늘하루체크)) 수집 완료

 25%|██▌       | 762/2999 [14:32<44:43,  1.20s/it]

[성공] 763번 카드 (the Pink) 수집 완료

 25%|██▌       | 763/2999 [14:33<44:16,  1.19s/it]

[성공] 764번 카드 (카카오페이 신용카드) 수집 완료

 25%|██▌       | 764/2999 [14:34<43:54,  1.18s/it]

[성공] 765번 카드 (010PAY 체크카드) 수집 완료

 26%|██▌       | 765/2999 [14:35<43:05,  1.16s/it]

[성공] 766번 카드 (몰테일 플러스 하나카드) 수집 완료

 26%|██▌       | 766/2999 [14:36<42:53,  1.15s/it]

[성공] 767번 카드 (go 캐시백 글로벌 하이브리드) 수집 완료

 26%|██▌       | 767/2999 [14:37<42:48,  1.15s/it]

[성공] 768번 카드 (Green Wave 1.5℃카드) 수집 완료

 26%|██▌       | 768/2999 [14:39<43:48,  1.18s/it]

[성공] 769번 카드 (가온올림카드(실속형)) 수집 완료

 26%|██▌       | 769/2999 [14:40<43:42,  1.18s/it]

[성공] 770번 카드 (그린재킷 체크카드) 수집 완료

 26%|██▌       | 770/2999 [14:41<43:25,  1.17s/it]

[성공] 771번 카드 (L.pay 롯데카드 Ⅱ) 수집 완료

 26%|██▌       | 771/2999 [14:42<42:40,  1.15s/it]

[성공] 772번 카드 (BLISS.5 카드(마일리지)) 수집 완료

 26%|██▌       | 772/2999 [14:43<42:22,  1.14s/it]

[성공] 773번 카드 (BLISS.5 카드(포인트)) 수집 완료

 26%|██▌       | 773/2999 [14:44<42:05,  1.13s/it]

[성공] 774번 카드 (쿠팡 롯데카드) 수집 완료

 26%|██▌       | 774/2999 [14:45<41:39,  1.12s/it]

[성공] 775번 카드 (해피포인트 우리체크 V.2) 수집 완료

 26%|██▌       | 775/2999 [14:46<41:15,  1.11s/it]

[성공] 776번 카드 (홈플러스 삼성카드) 수집 완료

 26%|██▌       | 776/2999 [14:47<40:57,  1.11s/it]

[성공] 777번 카드 (카드의정석 L.POINT) 수집 완료

 26%|██▌       | 777/2999 [14:49<40:57,  1.11s/it]

[성공] 778번 카드 (GS SHOP KB국민카드) 수집 완료

 26%|██▌       | 778/2999 [14:50<40:57,  1.11s/it]

[성공] 779번 카드 (위메프페이 신용카드) 수집 완료

 26%|██▌       | 779/2999 [14:51<41:00,  1.11s/it]

[성공] 780번 카드 (삼성카드 BIZ LEADERS) 수집 완료

 26%|██▌       | 780/2999 [14:52<41:16,  1.12s/it]

[성공] 781번 카드 (IBK hi 카드) 수집 완료

 26%|██▌       | 781/2999 [14:53<43:05,  1.17s/it]

[성공] 782번 카드 (SC제일은행 글로벌 삼성체크카드) 수집 완료

 26%|██▌       | 782/2999 [14:54<42:28,  1.15s/it]

[성공] 783번 카드 (SSG.COM카드) 수집 완료

 26%|██▌       | 783/2999 [14:55<41:49,  1.13s/it]

[성공] 784번 카드 (LG U+ 삼성카드) 수집 완료

 26%|██▌       | 784/2999 [14:56<41:14,  1.12s/it]

[성공] 785번 카드 (KT 삼성카드) 수집 완료

 26%|██▌       | 785/2999 [14:58<40:58,  1.11s/it]

[성공] 786번 카드 (T멤버십 더블 롯데체크카드) 수집 완료

 26%|██▌       | 786/2999 [14:59<40:37,  1.10s/it]

[성공] 787번 카드 (T멤버십 더블 롯데카드) 수집 완료

 26%|██▌       | 787/2999 [15:00<40:41,  1.10s/it]

[성공] 788번 카드 (CJ ONE 삼성카드) 수집 완료

 26%|██▋       | 788/2999 [15:01<43:21,  1.18s/it]

[성공] 789번 카드 (이마트 e카드 Edition2) 수집 완료

 26%|██▋       | 789/2999 [15:02<42:28,  1.15s/it]

[성공] 790번 카드 (V Street 카드) 수집 완료

 26%|██▋       | 790/2999 [15:03<42:04,  1.14s/it]

[성공] 791번 카드 (코스트코 리워드 비즈니스 현대카드) 수집 완료

 26%|██▋       | 791/2999 [15:04<41:41,  1.13s/it]

[성공] 792번 카드 (그린기업체크카드) 수집 완료

 26%|██▋       | 792/2999 [15:06<41:21,  1.12s/it]

[성공] 793번 카드 (DGB biz POINT 체크카드) 수집 완료

 26%|██▋       | 793/2999 [15:07<40:55,  1.11s/it]

[성공] 794번 카드 (참! 좋은 kt wiz 카드[체크]) 수집 완료

 26%|██▋       | 794/2999 [15:08<40:53,  1.11s/it]

[성공] 795번 카드 (세이브존 IBK 체크카드) 수집 완료

 27%|██▋       | 795/2999 [15:09<43:14,  1.18s/it]

[성공] 796번 카드 (참! 좋은친구 청년동행카드(체크)) 수집 완료

 27%|██▋       | 796/2999 [15:10<42:22,  1.15s/it]

[성공] 797번 카드 (동반성공카드(체크)) 수집 완료

 27%|██▋       | 797/2999 [15:11<42:20,  1.15s/it]

[성공] 798번 카드 (인피니트카드(INFINITE CARD)) 수집 완료

 27%|██▋       | 798/2999 [15:13<44:18,  1.21s/it]

[성공] 799번 카드 (IBK 각자내기카드) 수집 완료

 27%|██▋       | 799/2999 [15:14<43:10,  1.18s/it]

[성공] 800번 카드 (Kt텔레캅 안심 Plus 카드) 수집 완료

 27%|██▋       | 800/2999 [15:15<42:13,  1.15s/it]

[Skip] 801번 카드 정보가 존재하지 않습니다.

 27%|██▋       | 801/2999 [15:16<41:39,  1.14s/it]

[성공] 802번 카드 (동반성장카드) 수집 완료

 27%|██▋       | 802/2999 [15:17<41:32,  1.13s/it]

[성공] 803번 카드 (동반성공카드) 수집 완료

 27%|██▋       | 803/2999 [15:18<41:34,  1.14s/it]

[성공] 804번 카드 (코웨이 IBK 카드) 수집 완료

 27%|██▋       | 804/2999 [15:19<42:24,  1.16s/it]

[성공] 805번 카드 (파이팅코리아카드) 수집 완료

 27%|██▋       | 805/2999 [15:21<41:34,  1.14s/it]

[성공] 806번 카드 (파이팅코리아플러스카드) 수집 완료

 27%|██▋       | 806/2999 [15:22<41:14,  1.13s/it]

[성공] 807번 카드 (일상의 기쁨 Dream 체크카드) 수집 완료

 27%|██▋       | 807/2999 [15:23<40:53,  1.12s/it]

[성공] 808번 카드 (V-BIG멤버스 롯데체크카드(성인여성용)) 수집 완료

 27%|██▋       | 808/2999 [15:24<40:32,  1.11s/it]

[성공] 809번 카드 (American Express Platinum) 수집 완료

 27%|██▋       | 809/2999 [15:25<43:14,  1.18s/it]

[성공] 810번 카드 (현대백화점 체크카드) 수집 완료

 27%|██▋       | 810/2999 [15:26<42:29,  1.16s/it]

[성공] 811번 카드 (Y+(영플러스)체크카드) 수집 완료

 27%|██▋       | 811/2999 [15:27<41:53,  1.15s/it]

[성공] 812번 카드 (국민행복카드 체크카드) 수집 완료

 27%|██▋       | 812/2999 [15:29<42:32,  1.17s/it]

[성공] 813번 카드 (V-BIG멤버스 롯데체크카드(성인남성용)) 수집 완료

 27%|██▋       | 813/2999 [15:30<45:47,  1.26s/it]

[성공] 814번 카드 (해피포인트 DGB체크카드) 수집 완료

 27%|██▋       | 814/2999 [15:31<45:07,  1.24s/it]

[성공] 815번 카드 (대백 플러스 체크카드) 수집 완료

 27%|██▋       | 815/2999 [15:32<43:39,  1.20s/it]

[성공] 816번 카드 (단디체크카드) 수집 완료

 27%|██▋       | 816/2999 [15:34<42:47,  1.18s/it]

[성공] 817번 카드 (해피포인트DGB체크카드(대경교통)) 수집 완료

 27%|██▋       | 817/2999 [15:35<41:56,  1.15s/it]

[성공] 818번 카드 (Master Y+(영플러스)체크카드(대경교통)) 수집 완료

 27%|██▋       | 818/2999 [15:36<41:27,  1.14s/it]

[성공] 819번 카드 (카카오페이 체크카드) 수집 완료

 27%|██▋       | 819/2999 [15:37<42:15,  1.16s/it]

[성공] 820번 카드 (대백 플러스 체크카드(대경교통)) 수집 완료

 27%|██▋       | 820/2999 [15:38<41:38,  1.15s/it]

[성공] 821번 카드 (똑디체크카드(비교통)) 수집 완료

 27%|██▋       | 821/2999 [15:39<41:10,  1.13s/it]

[성공] 822번 카드 (Master Y+(영플러스)체크카드) 수집 완료

 27%|██▋       | 822/2999 [15:40<40:49,  1.13s/it]

[성공] 823번 카드 (NEW현대백화점체크카드) 수집 완료

 27%|██▋       | 823/2999 [15:41<40:35,  1.12s/it]

[성공] 824번 카드 (DGB SOHO 기업카드) 수집 완료

 27%|██▋       | 824/2999 [15:42<40:40,  1.12s/it]

[성공] 825번 카드 (단디비지니스카드) 수집 완료

 28%|██▊       | 825/2999 [15:44<40:33,  1.12s/it]

[성공] 826번 카드 (DGB氣UP!카드) 수집 완료

 28%|██▊       | 826/2999 [15:45<40:26,  1.12s/it]

[성공] 827번 카드 (DGB biz DC카드) 수집 완료

 28%|██▊       | 827/2999 [15:46<40:14,  1.11s/it]

[성공] 828번 카드 (DGB BIZ+카드) 수집 완료

 28%|██▊       | 828/2999 [15:47<40:09,  1.11s/it]

[성공] 829번 카드 (DGB biz 소호(SOHO)카드) 수집 완료

 28%|██▊       | 829/2999 [15:48<39:53,  1.10s/it]

[성공] 830번 카드 (후불 하이패스카드) 수집 완료

 28%|██▊       | 830/2999 [15:49<39:42,  1.10s/it]

[성공] 831번 카드 (대백-대구은행카드(퍼플)) 수집 완료

 28%|██▊       | 831/2999 [15:50<42:14,  1.17s/it]

[성공] 832번 카드 (단디[DANDI]카드) 수집 완료

 28%|██▊       | 832/2999 [15:52<41:26,  1.15s/it]

[성공] 833번 카드 (부자되세요 아파트카드) 수집 완료

 28%|██▊       | 833/2999 [15:53<40:50,  1.13s/it]

[성공] 834번 카드 (국민행복카드 신용카드) 수집 완료

 28%|██▊       | 834/2999 [15:54<41:45,  1.16s/it]

[성공] 835번 카드 (대백-대구은행카드(블랙)) 수집 완료

 28%|██▊       | 835/2999 [15:55<42:52,  1.19s/it]

[성공] 836번 카드 (DGB 레일플러스포인트카드) 수집 완료

 28%|██▊       | 836/2999 [15:56<41:46,  1.16s/it]

[성공] 837번 카드 (DGB Pet Love 카드) 수집 완료

 28%|██▊       | 837/2999 [15:57<41:00,  1.14s/it]

[성공] 838번 카드 (올레 Super DC 대구은행카드) 수집 완료

 28%|██▊       | 838/2999 [15:58<40:56,  1.14s/it]

[성공] 839번 카드 (부자되세요 홈쇼핑카드) 수집 완료

 28%|██▊       | 839/2999 [15:59<40:22,  1.12s/it]

[성공] 840번 카드 (DGB 쇼핑카드) 수집 완료

 28%|██▊       | 840/2999 [16:01<40:01,  1.11s/it]

[성공] 841번 카드 (GREit(그래잇)카드) 수집 완료

 28%|██▊       | 841/2999 [16:02<39:42,  1.10s/it]

[성공] 842번 카드 (OIL&LPG카드) 수집 완료

 28%|██▊       | 842/2999 [16:03<39:39,  1.10s/it]

[성공] 843번 카드 (DGB ONE 카드) 수집 완료

 28%|██▊       | 843/2999 [16:04<40:04,  1.12s/it]

[성공] 844번 카드 (DGB 세븐캐쉬백카드) 수집 완료

 28%|██▊       | 844/2999 [16:05<39:53,  1.11s/it]

[성공] 845번 카드 (V-BIG멤버스 롯데체크카드(청소년용)) 수집 완료

 28%|██▊       | 845/2999 [16:06<40:39,  1.13s/it]

[성공] 846번 카드 (XPEED 롯데카드) 수집 완료

 28%|██▊       | 846/2999 [16:07<40:11,  1.12s/it]

[성공] 847번 카드 (가연 롯데카드) 수집 완료

 28%|██▊       | 847/2999 [16:08<39:50,  1.11s/it]

[성공] 848번 카드 (강원방송 롯데카드) 수집 완료

 28%|██▊       | 848/2999 [16:10<41:10,  1.15s/it]

[성공] 849번 카드 (골든웨이브 카드) 수집 완료

 28%|██▊       | 849/2999 [16:11<40:31,  1.13s/it]

[성공] 850번 카드 (Hyundai EV카드) 수집 완료

 28%|██▊       | 850/2999 [16:12<40:11,  1.12s/it]

[성공] 851번 카드 (화물운전자복지 신한카드 체크) 수집 완료

 28%|██▊       | 851/2999 [16:13<40:27,  1.13s/it]

[성공] 852번 카드 (SmileCard Edition2) 수집 완료

 28%|██▊       | 852/2999 [16:14<40:08,  1.12s/it]

[성공] 853번 카드 (SmileCard the Club) 수집 완료

 28%|██▊       | 853/2999 [16:15<39:49,  1.11s/it]

[성공] 854번 카드 (Kia Members 경차전용카드) 수집 완료

 28%|██▊       | 854/2999 [16:17<42:28,  1.19s/it]

[성공] 855번 카드 (알뜰주유소 화물운전자복지 신한카드 체크) 수집 완료

 29%|██▊       | 855/2999 [16:18<41:44,  1.17s/it]

[성공] 856번 카드 (화물운전자복지 신한카드) 수집 완료

 29%|██▊       | 856/2999 [16:19<41:13,  1.15s/it]

[성공] 857번 카드 (현대오일뱅크 2UP 화물운전자복지 신한카드) 수집 완료

 29%|██▊       | 857/2999 [16:20<40:39,  1.14s/it]

[성공] 858번 카드 (그루폰 롯데카드) 수집 완료

 29%|██▊       | 858/2999 [16:21<40:10,  1.13s/it]

[성공] 859번 카드 (Kia Members 경차전용카드(유류세 환급)) 수집 완료

 29%|██▊       | 859/2999 [16:22<39:47,  1.12s/it]

[성공] 860번 카드 (S-OIL 2UP 화물운전자복지 신한카드) 수집 완료

 29%|██▊       | 860/2999 [16:23<40:16,  1.13s/it]

[성공] 861번 카드 (SK에너지 2MORE 화물복지 신한카드) 수집 완료

 29%|██▊       | 861/2999 [16:24<39:58,  1.12s/it]

[성공] 862번 카드 (LG U+ 현대카드M Edition3 (라이트할부형)) 수집 완료

 29%|██▊       | 862/2999 [16:25<39:48,  1.12s/it]

[성공] 863번 카드 (남선교회전국연합회 롯데포인트 플러스 카드) 수집 완료

 29%|██▉       | 863/2999 [16:27<42:39,  1.20s/it]

[성공] 864번 카드 (일년의 설렘카드(모바일전용)) 수집 완료

 29%|██▉       | 864/2999 [16:28<41:37,  1.17s/it]

[성공] 865번 카드 (홈플러스 스페셜 신한카드) 수집 완료

 29%|██▉       | 865/2999 [16:29<40:52,  1.15s/it]

[성공] 866번 카드 (큰수레 비즈니스 신한카드 Simple+) 수집 완료

 29%|██▉       | 866/2999 [16:30<40:44,  1.15s/it]

[Skip] 867번 카드 정보가 존재하지 않습니다.

 29%|██▉       | 867/2999 [16:31<39:54,  1.12s/it]

[Skip] 868번 카드 정보가 존재하지 않습니다.

 29%|██▉       | 868/2999 [16:32<39:24,  1.11s/it]

[성공] 869번 카드 (교보문고 롯데카드) 수집 완료

 29%|██▉       | 869/2999 [16:33<39:11,  1.10s/it]

[성공] 870번 카드 (교보증권PLUS αCMA 롯데체크카드) 수집 완료

 29%|██▉       | 870/2999 [16:34<39:09,  1.10s/it]

[성공] 871번 카드 (교육지대 롯데포인트플러스카드) 수집 완료

 29%|██▉       | 871/2999 [16:36<38:56,  1.10s/it]

[성공] 872번 카드 (SKT-현대카드M Edition3 (라이트할부형)) 수집 완료

 29%|██▉       | 872/2999 [16:37<40:06,  1.13s/it]

[성공] 873번 카드 (ROVL 시그니쳐(토탈마일)기업카드) 수집 완료

 29%|██▉       | 873/2999 [16:38<39:44,  1.12s/it]

[성공] 874번 카드 (참! 좋은친구 청년동행카드(신용)) 수집 완료

 29%|██▉       | 874/2999 [16:39<39:50,  1.12s/it]

[성공] 875번 카드 (에스원 안심 신한카드) 수집 완료

 29%|██▉       | 875/2999 [16:40<39:30,  1.12s/it]

[성공] 876번 카드 (알뜰주유소 화물운전자복지 신한카드) 수집 완료

 29%|██▉       | 876/2999 [16:41<41:12,  1.16s/it]

[성공] 877번 카드 (kt-현대카드M Edition3 (통신할인형)) 수집 완료

 29%|██▉       | 877/2999 [16:43<40:37,  1.15s/it]

[성공] 878번 카드 (SK One+ 화물복지 신한카드) 수집 완료

 29%|██▉       | 878/2999 [16:44<40:33,  1.15s/it]

[성공] 879번 카드 (자연드림 IBK카드) 수집 완료

 29%|██▉       | 879/2999 [16:45<40:05,  1.13s/it]

[성공] 880번 카드 (S.Sing 씽화물복지 신한카드 체크) 수집 완료

 29%|██▉       | 880/2999 [16:46<39:43,  1.12s/it]

[성공] 881번 카드 (IBK-Syrup카드[신용]) 수집 완료

 29%|██▉       | 881/2999 [16:47<39:15,  1.11s/it]

[성공] 882번 카드 (S.Sing 씽화물복지 신한카드) 수집 완료

 29%|██▉       | 882/2999 [16:48<39:07,  1.11s/it]

[성공] 883번 카드 (SME기업카드) 수집 완료

 29%|██▉       | 883/2999 [16:49<39:13,  1.11s/it]

[성공] 884번 카드 (신한카드 후불하이패스+ (하이패스 전용)) 수집 완료

 29%|██▉       | 884/2999 [16:50<39:04,  1.11s/it]

[성공] 885번 카드 (SME기업카드 (아시아나)) 수집 완료

 30%|██▉       | 885/2999 [16:51<39:05,  1.11s/it]

[성공] 886번 카드 (LG U+-현대카드M Edition3(통신할인형)) 수집 완료

 30%|██▉       | 886/2999 [16:53<40:23,  1.15s/it]

[성공] 887번 카드 (E1 & 아이파크 백화점 카드) 수집 완료

 30%|██▉       | 887/2999 [16:54<39:46,  1.13s/it]

[성공] 888번 카드 (SME기업카드 (대한항공)) 수집 완료

 30%|██▉       | 888/2999 [16:55<39:21,  1.12s/it]

[성공] 889번 카드 (신한카드 집) 수집 완료

 30%|██▉       | 889/2999 [16:56<39:25,  1.12s/it]

[성공] 890번 카드 (e플래티넘 롯데카드) 수집 완료

 30%|██▉       | 890/2999 [16:57<39:07,  1.11s/it]

[성공] 891번 카드 (StarBiz 고유기업카드) 수집 완료

 30%|██▉       | 891/2999 [16:58<38:45,  1.10s/it]

[성공] 892번 카드 (하이패스 기업카드) 수집 완료

 30%|██▉       | 892/2999 [16:59<39:06,  1.11s/it]

[성공] 893번 카드 (B tv KB국민카드) 수집 완료

 30%|██▉       | 893/2999 [17:00<39:09,  1.12s/it]

[Skip] 894번 카드 정보가 존재하지 않습니다.

 30%|██▉       | 894/2999 [17:01<38:36,  1.10s/it]

[성공] 895번 카드 (신한카드 주거래 신용) 수집 완료

 30%|██▉       | 895/2999 [17:03<38:48,  1.11s/it]

[Skip] 896번 카드 정보가 존재하지 않습니다.

 30%|██▉       | 896/2999 [17:04<38:28,  1.10s/it]

[성공] 897번 카드 (신한카드 아름다운) 수집 완료

 30%|██▉       | 897/2999 [17:05<38:37,  1.10s/it]

[Skip] 898번 카드 정보가 존재하지 않습니다.

 30%|██▉       | 898/2999 [17:06<38:21,  1.10s/it]

[성공] 899번 카드 (LG헬로비전-현대카드M Edition2(청구할인형)) 수집 완료

 30%|██▉       | 899/2999 [17:07<38:20,  1.10s/it]

[성공] 900번 카드 (신한금융투자 CMA R+ 신한카드 Love 체크) 수집 완료

 30%|███       | 900/2999 [17:08<38:48,  1.11s/it]

[성공] 901번 카드 (SK브로드밴드-현대카드M Edition2(청구할인형)) 수집 완료

 30%|███       | 901/2999 [17:09<41:23,  1.18s/it]

[성공] 902번 카드 (E1-현대카드M) 수집 완료

 30%|███       | 902/2999 [17:10<40:23,  1.16s/it]

[성공] 903번 카드 (신한금융투자 CMA R+ GS칼텍스 신한카드 Shine) 수집 완료

 30%|███       | 903/2999 [17:12<41:33,  1.19s/it]

[성공] 904번 카드 (현대카드M-경차전용카드) 수집 완료

 30%|███       | 904/2999 [17:13<40:33,  1.16s/it]

[성공] 905번 카드 (메가쇼핑 신한카드) 수집 완료

 30%|███       | 905/2999 [17:14<39:55,  1.14s/it]

[성공] 906번 카드 (메가쇼핑 신한카드 체크) 수집 완료

 30%|███       | 906/2999 [17:15<39:21,  1.13s/it]

[성공] 907번 카드 (SK 화물복지 50) 수집 완료

 30%|███       | 907/2999 [17:16<39:11,  1.12s/it]

[성공] 908번 카드 (에쓰-오일 400 우리카드) 수집 완료

 30%|███       | 908/2999 [17:17<39:05,  1.12s/it]

[성공] 909번 카드 (LPG 화물복지카드 E1) 수집 완료

 30%|███       | 909/2999 [17:18<38:45,  1.11s/it]

[성공] 910번 카드 (남양 i 프리미엄 롯데카드) 수집 완료

 30%|███       | 910/2999 [17:19<38:37,  1.11s/it]

[성공] 911번 카드 (네이버 체크아웃 DC20 롯데카드) 수집 완료

 30%|███       | 911/2999 [17:21<38:30,  1.11s/it]

[성공] 912번 카드 (Easy shopping 티타늄카드) 수집 완료

 30%|███       | 912/2999 [17:22<39:08,  1.13s/it]

[성공] 913번 카드 (현대카드M3 BLUEmembers Edition2) 수집 완료

 30%|███       | 913/2999 [17:23<38:51,  1.12s/it]

[성공] 914번 카드 (노랑풍선 롯데카드) 수집 완료

 30%|███       | 914/2999 [17:24<38:52,  1.12s/it]

[성공] 915번 카드 (뉴 롯데손해보험 롯데카드) 수집 완료

 31%|███       | 915/2999 [17:25<38:34,  1.11s/it]

[성공] 916번 카드 (위비 알뜰주유소 할인카드) 수집 완료

 31%|███       | 916/2999 [17:26<38:48,  1.12s/it]

[성공] 917번 카드 (썸(SUM)화물복지카드(개인신용)) 수집 완료

 31%|███       | 917/2999 [17:27<38:30,  1.11s/it]

[성공] 918번 카드 (현대카드M-화물차유가보조금카드) 수집 완료

 31%|███       | 918/2999 [17:28<38:26,  1.11s/it]

[성공] 919번 카드 (현대카드X-화물차유가보조금카드(S-OIL)) 수집 완료

 31%|███       | 919/2999 [17:29<38:17,  1.10s/it]

[성공] 920번 카드 (skylife Ultra IBK카드) 수집 완료

 31%|███       | 920/2999 [17:31<38:36,  1.11s/it]

[성공] 921번 카드 (현대카드X-화물차유가보조금카드(SK에너지)) 수집 완료

 31%|███       | 921/2999 [17:32<38:33,  1.11s/it]

[Skip] 922번 카드 정보가 존재하지 않습니다.

 31%|███       | 922/2999 [17:33<38:09,  1.10s/it]

[성공] 923번 카드 (LG전자-현대카드M Edition3) 수집 완료

 31%|███       | 923/2999 [17:34<40:31,  1.17s/it]

[성공] 924번 카드 (coway-현대카드M Edition3) 수집 완료

 31%|███       | 924/2999 [17:35<39:43,  1.15s/it]

[성공] 925번 카드 (뉴 인터파크 롯데카드) 수집 완료

 31%|███       | 925/2999 [17:36<39:15,  1.14s/it]

[성공] 926번 카드 (SK매직-현대카드M Edition3) 수집 완료

 31%|███       | 926/2999 [17:37<38:49,  1.12s/it]

[성공] 927번 카드 (CUCKOO-현대카드M Edition3) 수집 완료

 31%|███       | 927/2999 [17:39<39:58,  1.16s/it]

[성공] 928번 카드 (뉴S-OIL보너스 롯데카드) 수집 완료

 31%|███       | 928/2999 [17:40<39:32,  1.15s/it]

[성공] 929번 카드 (청호나이스-현대카드M Edition3) 수집 완료

 31%|███       | 929/2999 [17:41<39:09,  1.14s/it]

[성공] 930번 카드 (현대큐밍-현대카드M Edition3) 수집 완료

 31%|███       | 930/2999 [17:42<39:07,  1.13s/it]

[성공] 931번 카드 (용인시민카드(신용)) 수집 완료

 31%|███       | 931/2999 [17:43<38:48,  1.13s/it]

[성공] 932번 카드 (뉴하우머치 인슈포인트카드) 수집 완료

 31%|███       | 932/2999 [17:44<38:52,  1.13s/it]

[성공] 933번 카드 (현대홈쇼핑-현대카드M Edition3(청구할인형)) 수집 완료

 31%|███       | 933/2999 [17:45<38:44,  1.13s/it]

[성공] 934번 카드 (IBK TMON 카드) 수집 완료

 31%|███       | 934/2999 [17:47<41:59,  1.22s/it]

[성공] 935번 카드 (1st플래티늄 플러스카드 (포인트적립형)) 수집 완료

 31%|███       | 935/2999 [17:48<40:41,  1.18s/it]

[성공] 936번 카드 (신한카드 미래설계) 수집 완료

 31%|███       | 936/2999 [17:49<41:11,  1.20s/it]

[성공] 937번 카드 (1st플래티늄 플러스카드 (아시아나형)) 수집 완료

 31%|███       | 937/2999 [17:50<40:00,  1.16s/it]

[성공] 938번 카드 (신한카드 경차사랑 Life) 수집 완료

 31%|███▏      | 938/2999 [17:51<39:27,  1.15s/it]

[성공] 939번 카드 (1st플래티늄 플러스카드 (캐시백형)) 수집 완료

 31%|███▏      | 939/2999 [17:52<38:51,  1.13s/it]

[성공] 940번 카드 (CHALLENGE BAG KB국민카드) 수집 완료

 31%|███▏      | 940/2999 [17:54<38:26,  1.12s/it]

[성공] 941번 카드 (The CJ-현대카드M Edition2) 수집 완료

 31%|███▏      | 941/2999 [17:55<38:17,  1.12s/it]

[성공] 942번 카드 (AK KB국민카드) 수집 완료

 31%|███▏      | 942/2999 [17:56<38:37,  1.13s/it]

[Skip] 943번 카드 정보가 존재하지 않습니다.

 31%|███▏      | 943/2999 [17:57<37:53,  1.11s/it]

[성공] 944번 카드 (불타는청춘 베테랑 신용카드) 수집 완료

 31%|███▏      | 944/2999 [17:58<38:16,  1.12s/it]

[성공] 945번 카드 (신한카드 The CLASSIC-S) 수집 완료

 32%|███▏      | 945/2999 [17:59<38:19,  1.12s/it]

[Skip] 946번 카드 정보가 존재하지 않습니다.

 32%|███▏      | 946/2999 [18:00<37:49,  1.11s/it]

[성공] 947번 카드 (멍이냥이카드) 수집 완료

 32%|███▏      | 947/2999 [18:01<37:58,  1.11s/it]

[성공] 948번 카드 (여행스케치 아시아나클럽 플래티늄카드) 수집 완료

 32%|███▏      | 948/2999 [18:02<37:54,  1.11s/it]

[성공] 949번 카드 (1st카드 (캐시백형)) 수집 완료

 32%|███▏      | 949/2999 [18:04<37:53,  1.11s/it]

[성공] 950번 카드 (1st카드 (포인트 적립형)) 수집 완료

 32%|███▏      | 950/2999 [18:05<37:47,  1.11s/it]

[성공] 951번 카드 (넥센타이어 우리카드) 수집 완료

 32%|███▏      | 951/2999 [18:06<37:47,  1.11s/it]

[성공] 952번 카드 (SK Oil 400 우리카드) 수집 완료

 32%|███▏      | 952/2999 [18:07<38:17,  1.12s/it]

[성공] 953번 카드 (마이카 우리카드) 수집 완료

 32%|███▏      | 953/2999 [18:08<38:08,  1.12s/it]

[성공] 954번 카드 (대전광역시 승용차요일제카드) 수집 완료

 32%|███▏      | 954/2999 [18:09<38:16,  1.12s/it]

[성공] 955번 카드 (에코마일리지 New우리V카드) 수집 완료

 32%|███▏      | 955/2999 [18:10<38:01,  1.12s/it]

[Skip] 956번 카드 정보가 존재하지 않습니다.

 32%|███▏      | 956/2999 [18:11<37:36,  1.10s/it]

[성공] 957번 카드 (부산광역시 승용차요일제카드) 수집 완료

 32%|███▏      | 957/2999 [18:12<37:54,  1.11s/it]

[성공] 958번 카드 (초록마을 롯데카드) 수집 완료

 32%|███▏      | 958/2999 [18:14<39:46,  1.17s/it]

[성공] 959번 카드 (현대카드M2 BLUEmembers Edition2) 수집 완료

 32%|███▏      | 959/2999 [18:15<39:13,  1.15s/it]

[성공] 960번 카드 (큰수레비지니스내트럭건설기계카드) 수집 완료

 32%|███▏      | 960/2999 [18:16<40:05,  1.18s/it]

[성공] 961번 카드 (현대카드M2 RED members Edition2(구 Qmembers)) 수집 완료

 32%|███▏      | 961/2999 [18:17<39:37,  1.17s/it]

[성공] 962번 카드 (현대카드M BLUEmembers Edition2) 수집 완료

 32%|███▏      | 962/2999 [18:18<39:10,  1.15s/it]

[성공] 963번 카드 (우체국 스마트카드) 수집 완료

 32%|███▏      | 963/2999 [18:20<39:00,  1.15s/it]

[성공] 964번 카드 (현대카드M RED MEMBERS Edition2(구 Qmembers)) 수집 완료

 32%|███▏      | 964/2999 [18:21<38:46,  1.14s/it]

[성공] 965번 카드 (NEW화물차유류구매카드(개인신용)) 수집 완료

 32%|███▏      | 965/2999 [18:22<40:59,  1.21s/it]

[성공] 966번 카드 (우체국 Biz플러스 카드) 수집 완료

 32%|███▏      | 966/2999 [18:23<39:51,  1.18s/it]

[성공] 967번 카드 (현대카드M3 BLUEmembers Platinum) 수집 완료

 32%|███▏      | 967/2999 [18:24<39:10,  1.16s/it]

[성공] 968번 카드 (현대카드M2 BLUEmembers Platinum (5만원)) 수집 완료

 32%|███▏      | 968/2999 [18:25<38:41,  1.14s/it]

[성공] 969번 카드 (현대카드M2 BLUEmembers Platinum (3만원)) 수집 완료

 32%|███▏      | 969/2999 [18:26<38:30,  1.14s/it]

[성공] 970번 카드 (현대카드M2 RED MEMBERS Platinum (5만원)(구 Qmembers)) 수집 완료

 32%|███▏      | 970/2999 [18:28<38:09,  1.13s/it]

[성공] 971번 카드 (현대카드M2 RED MEMBERS Platinum (3만원)(구 Qmembers)) 수집 완료

 32%|███▏      | 971/2999 [18:29<37:58,  1.12s/it]

[성공] 972번 카드 (캐시백 플러스 카드(온라인+해외)) 수집 완료

 32%|███▏      | 972/2999 [18:30<37:30,  1.11s/it]

[성공] 973번 카드 (우체국 카드의정석 POINT) 수집 완료

 32%|███▏      | 973/2999 [18:31<37:19,  1.11s/it]

[성공] 974번 카드 (우체국 카드의정석 SHOPPING) 수집 완료

 32%|███▏      | 974/2999 [18:32<38:30,  1.14s/it]

[성공] 975번 카드 (우체국 하나로 전자카드) 수집 완료

 33%|███▎      | 975/2999 [18:33<38:00,  1.13s/it]

[성공] 976번 카드 (우체국 드림플러스 아시아나 하이브리드카드) 수집 완료

 33%|███▎      | 976/2999 [18:34<37:48,  1.12s/it]

[성공] 977번 카드 (우체국 어디서나 하이브리드 체크카드) 수집 완료

 33%|███▎      | 977/2999 [18:35<37:27,  1.11s/it]

[성공] 978번 카드 (행복한 하이브리드 체크카드) 수집 완료

 33%|███▎      | 978/2999 [18:36<37:23,  1.11s/it]

[성공] 979번 카드 (다드림 하이브리드 체크카드) 수집 완료

 33%|███▎      | 979/2999 [18:38<37:26,  1.11s/it]

[성공] 980번 카드 (우체국 나눔 체크카드) 수집 완료

 33%|███▎      | 980/2999 [18:39<37:15,  1.11s/it]

[성공] 981번 카드 (우체국 국민행복 체크카드) 수집 완료

 33%|███▎      | 981/2999 [18:40<38:11,  1.14s/it]

[성공] 982번 카드 (1st플래티늄카드 (포인트적립형)) 수집 완료

 33%|███▎      | 982/2999 [18:41<38:05,  1.13s/it]

[성공] 983번 카드 (1st플래티늄카드 (캐시백형)) 수집 완료

 33%|███▎      | 983/2999 [18:42<37:36,  1.12s/it]

[성공] 984번 카드 (부자되세요 The Oil카드) 수집 완료

 33%|███▎      | 984/2999 [18:43<37:18,  1.11s/it]

[성공] 985번 카드 (광주·전남愛사랑카드) 수집 완료

 33%|███▎      | 985/2999 [18:45<42:42,  1.27s/it]

[성공] 986번 카드 (광주·전남愛사랑플래티늄카드) 수집 완료

 33%|███▎      | 986/2999 [18:46<40:52,  1.22s/it]

[성공] 987번 카드 (신협-현대카드M Edition2) 수집 완료

 33%|███▎      | 987/2999 [18:47<39:27,  1.18s/it]

[성공] 988번 카드 (신협-현대카드M2 Edition2) 수집 완료

 33%|███▎      | 988/2999 [18:48<38:29,  1.15s/it]

[성공] 989번 카드 (신협-현대카드 ZERO) 수집 완료

 33%|███▎      | 989/2999 [18:49<38:09,  1.14s/it]

[성공] 990번 카드 (신협-현대카드 MY BUSINESS M Edition2) 수집 완료

 33%|███▎      | 990/2999 [18:50<38:04,  1.14s/it]

[Skip] 991번 카드 정보가 존재하지 않습니다.

 33%|███▎      | 991/2999 [18:51<37:12,  1.11s/it]

[성공] 992번 카드 (산림조합-현대카드M Edition2) 수집 완료

 33%|███▎      | 992/2999 [18:53<38:39,  1.16s/it]

[성공] 993번 카드 (신한카드 The BEST+) 수집 완료

 33%|███▎      | 993/2999 [18:54<38:15,  1.14s/it]

[성공] 994번 카드 (신한카드 The ACE BLUE LABEL) 수집 완료

 33%|███▎      | 994/2999 [18:55<38:19,  1.15s/it]

[성공] 995번 카드 (나주사랑 신한카드 S-Choice(선택형) 체크) 수집 완료

 33%|███▎      | 995/2999 [18:56<37:46,  1.13s/it]

[Skip] 996번 카드 정보가 존재하지 않습니다.

 33%|███▎      | 996/2999 [18:57<37:39,  1.13s/it]

[성공] 997번 카드 (산림조합-현대카드M2 Edition2) 수집 완료

 33%|███▎      | 997/2999 [18:58<37:25,  1.12s/it]

[성공] 998번 카드 (산림조합-현대카드ZERO) 수집 완료

 33%|███▎      | 998/2999 [18:59<37:13,  1.12s/it]

[성공] 999번 카드 (현대카드 MY BUSINESS ZERO MOBILE(포인트형)) 수집 완료

 33%|███▎      | 999/2999 [19:00<37:08,  1.11s/it]

[성공] 1000번 카드 (현대카드 MY BUSINESS ZERO(포인트형)) 수집 완료

 33%|███▎      | 1000/2999 [19:02<36:53,  1.11s/it]

[성공] 1001번 카드 (현대카드 MY BUSINESS M3 Edition2) 수집 완료

 33%|███▎      | 1001/2999 [19:03<36:48,  1.11s/it]

[성공] 1002번 카드 (Mobile x LOCA 롯데카드) 수집 완료

 33%|███▎      | 1002/2999 [19:04<36:31,  1.10s/it]

[성공] 1003번 카드 (신한카드 Love Platinum#) 수집 완료

 33%|███▎      | 1003/2999 [19:05<36:33,  1.10s/it]

[성공] 1004번 카드 (다이아몬드 (Diamond) 카드) 수집 완료

 33%|███▎      | 1004/2999 [19:06<36:29,  1.10s/it]

[성공] 1005번 카드 (대교리브로 롯데카드) 수집 완료

 34%|███▎      | 1005/2999 [19:07<37:26,  1.13s/it]

[성공] 1006번 카드 (신한카드 LABE) 수집 완료

 34%|███▎      | 1006/2999 [19:08<37:21,  1.12s/it]

[성공] 1007번 카드 (Clip카드) 수집 완료

 34%|███▎      | 1007/2999 [19:09<36:49,  1.11s/it]

[성공] 1008번 카드 (대신 CMA 롯데DC플러스 카드) 수집 완료

 34%|███▎      | 1008/2999 [19:10<36:41,  1.11s/it]

[성공] 1009번 카드 (MY RENTAL 롯데카드) 수집 완료

 34%|███▎      | 1009/2999 [19:12<36:34,  1.10s/it]

[성공] 1010번 카드 (EVO 티타늄카드) 수집 완료

 34%|███▎      | 1010/2999 [19:13<36:27,  1.10s/it]

[성공] 1011번 카드 (OIL KING SK 롯데카드) 수집 완료

 34%|███▎      | 1011/2999 [19:14<36:20,  1.10s/it]

[성공] 1012번 카드 (신한카드 Hi-Point MyShop PLATINUM#) 수집 완료

 34%|███▎      | 1012/2999 [19:15<36:29,  1.10s/it]

[성공] 1013번 카드 (신한카드 Hi-Point MyShop) 수집 완료

 34%|███▍      | 1013/2999 [19:16<36:47,  1.11s/it]

[성공] 1014번 카드 (olleh 롯데 삼삼한 체크카드) 수집 완료

 34%|███▍      | 1014/2999 [19:17<36:33,  1.11s/it]

[성공] 1015번 카드 (신한카드 EV) 수집 완료

 34%|███▍      | 1015/2999 [19:18<38:17,  1.16s/it]

[성공] 1016번 카드 (OPTIN 플래티넘 카드) 수집 완료

 34%|███▍      | 1016/2999 [19:19<38:06,  1.15s/it]

[성공] 1017번 카드 (신세계 신한카드 SKYPASS / Asiana Club) 수집 완료

 34%|███▍      | 1017/2999 [19:21<37:36,  1.14s/it]

[성공] 1018번 카드 (리디 신한카드) 수집 완료

 34%|███▍      | 1018/2999 [19:22<37:50,  1.15s/it]

[성공] 1019번 카드 (더본 신한카드) 수집 완료

 34%|███▍      | 1019/2999 [19:23<37:39,  1.14s/it]

[성공] 1020번 카드 (노란우산 신한카드) 수집 완료

 34%|███▍      | 1020/2999 [19:24<38:33,  1.17s/it]

[성공] 1021번 카드 (롯데면세점 롯데 아멕스카드) 수집 완료

 34%|███▍      | 1021/2999 [19:26<42:11,  1.28s/it]

[성공] 1022번 카드 (현대카드 MY BUSINESS M2 Edition2) 수집 완료

 34%|███▍      | 1022/2999 [19:27<40:50,  1.24s/it]

[성공] 1023번 카드 (대신 CMA 롯데체크카드) 수집 완료

 34%|███▍      | 1023/2999 [19:28<39:44,  1.21s/it]

[성공] 1024번 카드 (대신 CMA 롯데포인트플러스 카드) 수집 완료

 34%|███▍      | 1024/2999 [19:29<38:43,  1.18s/it]

[성공] 1025번 카드 (현대카드 MY BUSINESS M Edition2) 수집 완료

 34%|███▍      | 1025/2999 [19:30<37:53,  1.15s/it]

[성공] 1026번 카드 (현대카드 MY BUSINESS ZERO MOBILE(할인형)) 수집 완료

 34%|███▍      | 1026/2999 [19:31<37:56,  1.15s/it]

[성공] 1027번 카드 (대신증권 꼬박꼬박 롯데카드) 수집 완료

 34%|███▍      | 1027/2999 [19:32<37:59,  1.16s/it]

[성공] 1028번 카드 (현대카드 MY BUSINESS ZERO(할인형)) 수집 완료

 34%|███▍      | 1028/2999 [19:34<37:18,  1.14s/it]

[성공] 1029번 카드 (현대카드 MY BUSINESS X3 Edition2) 수집 완료

 34%|███▍      | 1029/2999 [19:35<37:02,  1.13s/it]

[성공] 1030번 카드 (현대카드 MY BUSINESS X2 Edition2) 수집 완료

 34%|███▍      | 1030/2999 [19:36<36:45,  1.12s/it]

[성공] 1031번 카드 (현대카드 MY BUSINESS X Edition2) 수집 완료

 34%|███▍      | 1031/2999 [19:37<36:25,  1.11s/it]

[성공] 1032번 카드 (후불하이패스 카드) 수집 완료

 34%|███▍      | 1032/2999 [19:38<36:01,  1.10s/it]

[성공] 1033번 카드 (현대렌탈서비스 하나카드) 수집 완료

 34%|███▍      | 1033/2999 [19:39<37:31,  1.15s/it]

[성공] 1034번 카드 (SB롯데카드) 수집 완료

 34%|███▍      | 1034/2999 [19:40<37:55,  1.16s/it]

[성공] 1035번 카드 (한화손해보험 카드) 수집 완료

 35%|███▍      | 1035/2999 [19:42<40:03,  1.22s/it]

[성공] 1036번 카드 (캐시비 롯데카드) 수집 완료

 35%|███▍      | 1036/2999 [19:43<39:49,  1.22s/it]

[성공] 1037번 카드 (하나멤버스 1Q Hit1 카드) 수집 완료

 35%|███▍      | 1037/2999 [19:44<38:43,  1.18s/it]

[성공] 1038번 카드 (SK 드라이빙패스 롯데카드) 수집 완료

 35%|███▍      | 1038/2999 [19:45<37:54,  1.16s/it]

[성공] 1039번 카드 (카카오페이 체크카드) 수집 완료

 35%|███▍      | 1039/2999 [19:46<38:15,  1.17s/it]

[성공] 1040번 카드 (컬쳐랜드 롯데카드) 수집 완료

 35%|███▍      | 1040/2999 [19:48<41:51,  1.28s/it]

[성공] 1041번 카드 (하나멤버스 1Q(원큐) 카드 Special) 수집 완료

 35%|███▍      | 1041/2999 [19:49<40:04,  1.23s/it]

[성공] 1042번 카드 (SK롯데 체크카드) 수집 완료

 35%|███▍      | 1042/2999 [19:50<38:59,  1.20s/it]

[성공] 1043번 카드 (불타는청춘 베테랑 체크카드) 수집 완료

 35%|███▍      | 1043/2999 [19:51<38:13,  1.17s/it]

[성공] 1044번 카드 (코리아패스 체크카드) 수집 완료

 35%|███▍      | 1044/2999 [19:52<37:35,  1.15s/it]

[성공] 1045번 카드 (멍이냥이 체크카드) 수집 완료

 35%|███▍      | 1045/2999 [19:54<38:40,  1.19s/it]

[성공] 1046번 카드 (여행스케치 아시아나클럽 체크카드) 수집 완료

 35%|███▍      | 1046/2999 [19:55<37:53,  1.16s/it]

[성공] 1047번 카드 (SUPER PLUS 체크카드) 수집 완료

 35%|███▍      | 1047/2999 [19:56<37:01,  1.14s/it]

[성공] 1048번 카드 (코리아패스 카드) 수집 완료

 35%|███▍      | 1048/2999 [19:57<36:45,  1.13s/it]

[성공] 1049번 카드 (모두투어 투어마일리지 롯데카드) 수집 완료

 35%|███▍      | 1049/2999 [19:58<37:09,  1.14s/it]

[성공] 1050번 카드 (K-CHECK 카드) 수집 완료

 35%|███▌      | 1050/2999 [19:59<37:00,  1.14s/it]

[성공] 1051번 카드 (롯데손해보험 롯데카드) 수집 완료

 35%|███▌      | 1051/2999 [20:00<36:48,  1.13s/it]

[성공] 1052번 카드 (코코몽 롯데카드) 수집 완료

 35%|███▌      | 1052/2999 [20:01<36:23,  1.12s/it]

[성공] 1053번 카드 (The CJ 롯데카드) 수집 완료

 35%|███▌      | 1053/2999 [20:03<36:23,  1.12s/it]

[성공] 1054번 카드 (대한적십자사 Give1004 롯데카드) 수집 완료

 35%|███▌      | 1054/2999 [20:04<36:43,  1.13s/it]

[성공] 1055번 카드 (우체국 하이브리드 여행 체크카드) 수집 완료

 35%|███▌      | 1055/2999 [20:05<36:17,  1.12s/it]

[성공] 1056번 카드 (쿠첸 프리미엄 롯데카드) 수집 완료

 35%|███▌      | 1056/2999 [20:06<36:19,  1.12s/it]

[성공] 1057번 카드 (쿠쿠전자 렌탈 Free 롯데카드) 수집 완료

 35%|███▌      | 1057/2999 [20:07<38:46,  1.20s/it]

[성공] 1058번 카드 (롯데영플 체크카드) 수집 완료

 35%|███▌      | 1058/2999 [20:08<39:02,  1.21s/it]

[성공] 1059번 카드 (에듀카 롯데카드) 수집 완료

 35%|███▌      | 1059/2999 [20:10<37:58,  1.17s/it]

[성공] 1060번 카드 (큐니걸스 롯데포인트플러스 카드) 수집 완료

 35%|███▌      | 1060/2999 [20:11<37:38,  1.16s/it]

[성공] 1061번 카드 (Real? Real! 2 카드) 수집 완료

 35%|███▌      | 1061/2999 [20:12<37:12,  1.15s/it]

[성공] 1062번 카드 (롯데월드 롯데카드) 수집 완료

 35%|███▌      | 1062/2999 [20:13<36:49,  1.14s/it]

[성공] 1063번 카드 (VIC마켓 롯데카드) 수집 완료

 35%|███▌      | 1063/2999 [20:14<36:22,  1.13s/it]

[Skip] 1064번 카드 정보가 존재하지 않습니다.

 35%|███▌      | 1064/2999 [20:15<36:07,  1.12s/it]

[성공] 1065번 카드 (미니골드 롯데카드) 수집 완료

 36%|███▌      | 1065/2999 [20:16<35:44,  1.11s/it]

[성공] 1066번 카드 (키자니아 롯데카드) 수집 완료

 36%|███▌      | 1066/2999 [20:17<35:38,  1.11s/it]

[성공] 1067번 카드 (태평백화점 롯데카드) 수집 완료

 36%|███▌      | 1067/2999 [20:18<35:45,  1.11s/it]

[성공] 1068번 카드 (트래블패스 비즈니스 카드) 수집 완료

 36%|███▌      | 1068/2999 [20:20<35:31,  1.10s/it]

[Skip] 1069번 카드 정보가 존재하지 않습니다.

 36%|███▌      | 1069/2999 [20:21<35:05,  1.09s/it]

[성공] 1070번 카드 (위비마일(SKYPASS)) 수집 완료

 36%|███▌      | 1070/2999 [20:22<35:46,  1.11s/it]

[성공] 1071번 카드 (휘닉스 우리V카드) 수집 완료

 36%|███▌      | 1071/2999 [20:23<35:37,  1.11s/it]

[성공] 1072번 카드 (하나멤버스 1Q(원큐) 카드 Pay) 수집 완료

 36%|███▌      | 1072/2999 [20:24<36:42,  1.14s/it]

[성공] 1073번 카드 (KT 카드의정석 SUPER DC Ⅱ) 수집 완료

 36%|███▌      | 1073/2999 [20:25<36:47,  1.15s/it]

[성공] 1074번 카드 (하나멤버스 1Q(원큐) 카드 Business) 수집 완료

 36%|███▌      | 1074/2999 [20:26<36:11,  1.13s/it]

[성공] 1075번 카드 (KB국민 MyBiz 기업체크카드) 수집 완료

 36%|███▌      | 1075/2999 [20:28<36:58,  1.15s/it]

[성공] 1076번 카드 (iMBC 롯데카드) 수집 완료

 36%|███▌      | 1076/2999 [20:29<36:32,  1.14s/it]

[성공] 1077번 카드 (KB국민 그린기업카드) 수집 완료

 36%|███▌      | 1077/2999 [20:30<36:02,  1.12s/it]

[성공] 1078번 카드 (IMI 롯데카드) 수집 완료

 36%|███▌      | 1078/2999 [20:31<38:43,  1.21s/it]

[성공] 1079번 카드 (JTBC Golf 롯데카드) 수집 완료

 36%|███▌      | 1079/2999 [20:32<37:34,  1.17s/it]

[성공] 1080번 카드 (JTN 롯데카드) 수집 완료

 36%|███▌      | 1080/2999 [20:33<36:56,  1.15s/it]

[성공] 1081번 카드 (KB캐피탈 롯데포인트플러스 카드) 수집 완료

 36%|███▌      | 1081/2999 [20:34<36:29,  1.14s/it]

[성공] 1082번 카드 (하나멤버스 1Q(원큐) 카드 ALL in) 수집 완료

 36%|███▌      | 1082/2999 [20:36<36:22,  1.14s/it]

[성공] 1083번 카드 (하나멤버스 1Q(원큐) Play1 (플레이원) 카드) 수집 완료

 36%|███▌      | 1083/2999 [20:37<36:10,  1.13s/it]

[성공] 1084번 카드 (KDB다이렉트보험 P+410 롯데카드) 수집 완료

 36%|███▌      | 1084/2999 [20:38<36:04,  1.13s/it]

[성공] 1085번 카드 (우체국 후불 하이패스 카드) 수집 완료

 36%|███▌      | 1085/2999 [20:39<36:40,  1.15s/it]

[성공] 1086번 카드 (KDB롯데체크카드) 수집 완료

 36%|███▌      | 1086/2999 [20:40<36:17,  1.14s/it]

[성공] 1087번 카드 (KT 클립 Super 스마트 롯데카드) 수집 완료

 36%|███▌      | 1087/2999 [20:41<36:31,  1.15s/it]

[성공] 1088번 카드 (KTF 멤버스 롯데카드) 수집 완료

 36%|███▋      | 1088/2999 [20:42<35:57,  1.13s/it]

[성공] 1089번 카드 (LG전자 베스트샵 롯데카드) 수집 완료

 36%|███▋      | 1089/2999 [20:43<35:37,  1.12s/it]

[성공] 1090번 카드 (LG전자 베스트샵 멤버십 롯데카드) 수집 완료

 36%|███▋      | 1090/2999 [20:45<35:26,  1.11s/it]

[성공] 1091번 카드 (LG패션 롯데카드) 수집 완료

 36%|███▋      | 1091/2999 [20:46<35:20,  1.11s/it]

[성공] 1092번 카드 (MG손해보험 롯데카드) 수집 완료

 36%|███▋      | 1092/2999 [20:47<35:49,  1.13s/it]

[성공] 1093번 카드 (New 위메프 롯데카드) 수집 완료

 36%|███▋      | 1093/2999 [20:48<37:14,  1.17s/it]

[성공] 1094번 카드 (NRC롯데카드) 수집 완료

 36%|███▋      | 1094/2999 [20:50<41:02,  1.29s/it]

[성공] 1095번 카드 (NRC프리미엄롯데카드) 수집 완료

 37%|███▋      | 1095/2999 [20:51<40:12,  1.27s/it]

[성공] 1096번 카드 (OK Cashbag 롯데카드) 수집 완료

 37%|███▋      | 1096/2999 [20:52<38:40,  1.22s/it]

[성공] 1097번 카드 (SBS골프 롯데카드) 수집 완료

 37%|███▋      | 1097/2999 [20:53<38:06,  1.20s/it]

[성공] 1098번 카드 (NH농협증권 롯데체크카드) 수집 완료

 37%|███▋      | 1098/2999 [20:54<37:24,  1.18s/it]

[성공] 1099번 카드 (Oh! point 롯데 포인트플러스 체크카드) 수집 완료

 37%|███▋      | 1099/2999 [20:55<36:55,  1.17s/it]

[성공] 1100번 카드 (Olleh Super DC 롯데카드) 수집 완료

 37%|███▋      | 1100/2999 [20:57<36:53,  1.17s/it]

[성공] 1101번 카드 (Olleh Super Save 롯데카드) 수집 완료

 37%|███▋      | 1101/2999 [20:58<36:39,  1.16s/it]

[성공] 1102번 카드 (Olleh 스마트세이브 롯데카드) 수집 완료

 37%|███▋      | 1102/2999 [20:59<36:40,  1.16s/it]

[성공] 1103번 카드 (olleh-롯데카드) 수집 완료

 37%|███▋      | 1103/2999 [21:00<36:21,  1.15s/it]

[성공] 1104번 카드 (PAT/NEPA/ELLE GOLF 롯데카드) 수집 완료

 37%|███▋      | 1104/2999 [21:01<35:53,  1.14s/it]

[성공] 1105번 카드 (ROTC중앙회 롯데체크카드) 수집 완료

 37%|███▋      | 1105/2999 [21:02<35:42,  1.13s/it]

[성공] 1106번 카드 (ROTC중앙회 멤버십 롯데VEEX 카드) 수집 완료

 37%|███▋      | 1106/2999 [21:03<35:39,  1.13s/it]

[성공] 1107번 카드 (SK스마트 롯데카드) 수집 완료

 37%|███▋      | 1107/2999 [21:05<35:29,  1.13s/it]

[성공] 1108번 카드 (SUPER PLUS 카드) 수집 완료

 37%|███▋      | 1108/2999 [21:06<35:22,  1.12s/it]

[성공] 1109번 카드 (S-OIL보너스 롯데카드) 수집 완료

 37%|███▋      | 1109/2999 [21:07<35:36,  1.13s/it]

[성공] 1110번 카드 (TGIF 롯데카드) 수집 완료

 37%|███▋      | 1110/2999 [21:08<35:29,  1.13s/it]

[성공] 1111번 카드 (SKYPASS 롯데카드) 수집 완료

 37%|███▋      | 1111/2999 [21:09<35:43,  1.14s/it]

[성공] 1112번 카드 ((사)한국청소년진흥협회 롯데카드 아임조이풀) 수집 완료

 37%|███▋      | 1112/2999 [21:10<35:32,  1.13s/it]

[성공] 1113번 카드 (11번가 ShoppingMaster 롯데카드) 수집 완료

 37%|███▋      | 1113/2999 [21:11<35:21,  1.13s/it]

[성공] 1114번 카드 (11번가 쇼핑마스터 롯데체크카드) 수집 완료

 37%|███▋      | 1114/2999 [21:12<35:56,  1.14s/it]

[성공] 1115번 카드 (Smart 렌탈 대림케어 롯데카드) 수집 완료

 37%|███▋      | 1115/2999 [21:14<35:40,  1.14s/it]

[성공] 1116번 카드 (ABC마트 롯데카드) 수집 완료

 37%|███▋      | 1116/2999 [21:15<35:25,  1.13s/it]

[성공] 1117번 카드 (ABN아름방송 롯데카드) 수집 완료

 37%|███▋      | 1117/2999 [21:16<36:47,  1.17s/it]

[성공] 1118번 카드 (AJ렌터카 드라이빙 패스 롯데카드) 수집 완료

 37%|███▋      | 1118/2999 [21:17<36:18,  1.16s/it]

[성공] 1119번 카드 (7 Unit 카드) 수집 완료

 37%|███▋      | 1119/2999 [21:18<35:50,  1.14s/it]

[성공] 1120번 카드 (AXA 롯데카드) 수집 완료

 37%|███▋      | 1120/2999 [21:19<35:42,  1.14s/it]

[성공] 1121번 카드 (BNK AUTO 롯데카드) 수집 완료

 37%|███▋      | 1121/2999 [21:20<35:24,  1.13s/it]

[성공] 1122번 카드 (CGV 롯데포인트플러스 카드) 수집 완료

 37%|███▋      | 1122/2999 [21:22<35:03,  1.12s/it]

[성공] 1123번 카드 (CJ헬로비전 롯데카드) 수집 완료

 37%|███▋      | 1123/2999 [21:23<34:55,  1.12s/it]

[성공] 1124번 카드 (CMB 롯데카드) 수집 완료

 37%|███▋      | 1124/2999 [21:24<40:16,  1.29s/it]

[성공] 1125번 카드 (coway PayFree 롯데카드) 수집 완료

 38%|███▊      | 1125/2999 [21:26<41:09,  1.32s/it]

[성공] 1126번 카드 (DC PASS 롯데카드) 수집 완료

 38%|███▊      | 1126/2999 [21:28<46:29,  1.49s/it]

[성공] 1127번 카드 (DC Supreme 카드) 수집 완료

 38%|███▊      | 1127/2999 [21:29<43:34,  1.40s/it]

[성공] 1128번 카드 (DC Sweet 롯데카드) 수집 완료

 38%|███▊      | 1128/2999 [21:30<41:19,  1.33s/it]

[성공] 1129번 카드 (DC 클릭카드) 수집 완료

 38%|███▊      | 1129/2999 [21:31<41:01,  1.32s/it]

[성공] 1130번 카드 (DC 클릭카드 삼성페이) 수집 완료

 38%|███▊      | 1130/2999 [21:33<45:28,  1.46s/it]

[성공] 1131번 카드 (DC스마트 카드) 수집 완료

 38%|███▊      | 1131/2999 [21:35<54:05,  1.74s/it]

[성공] 1132번 카드 (DC카드) 수집 완료

 38%|███▊      | 1132/2999 [21:37<52:30,  1.69s/it]

[성공] 1133번 카드 (DC플러스 PiTaPa 카드) 수집 완료

 38%|███▊      | 1133/2999 [21:39<54:29,  1.75s/it]

[성공] 1134번 카드 (Diver’s 플래티넘 카드-다이버 상해보험 전용) 수집 완료

 38%|███▊      | 1134/2999 [21:41<53:05,  1.71s/it]

[성공] 1135번 카드 (Diver’s 플래티넘 카드-보너스플라이어마일 적립전용) 수집 완료

 38%|███▊      | 1135/2999 [21:42<52:37,  1.69s/it]

[성공] 1136번 카드 (Driving Pass 카드) 수집 완료

 38%|███▊      | 1136/2999 [21:44<56:37,  1.82s/it]

[성공] 1137번 카드 (EBS교육방송 롯데카드) 수집 완료

 38%|███▊      | 1137/2999 [21:46<58:50,  1.90s/it]

[성공] 1138번 카드 (파스퇴르 아이 롯데카드) 수집 완료

 38%|███▊      | 1138/2999 [21:48<55:16,  1.78s/it]

[성공] 1139번 카드 (elLOTTE 카드) 수집 완료

 38%|███▊      | 1139/2999 [21:49<52:35,  1.70s/it]

[성공] 1140번 카드 (E-PASS 롯데카드) 수집 완료

 38%|███▊      | 1140/2999 [21:51<51:23,  1.66s/it]

[성공] 1141번 카드 (EXR 롯데포인트플러스 카드) 수집 완료

 38%|███▊      | 1141/2999 [21:53<51:45,  1.67s/it]

[성공] 1142번 카드 (패션플러스 롯데포인트플러스카드) 수집 완료

 38%|███▊      | 1142/2999 [21:55<53:22,  1.72s/it]

[성공] 1143번 카드 (GS25 롯데카드) 수집 완료

 38%|███▊      | 1143/2999 [21:56<52:12,  1.69s/it]

[성공] 1144번 카드 (GS칼텍스 롯데카드) 수집 완료

 38%|███▊      | 1144/2999 [21:57<49:13,  1.59s/it]

[성공] 1145번 카드 (G마켓 롯데카드) 수집 완료

 38%|███▊      | 1145/2999 [21:59<44:38,  1.44s/it]

[성공] 1146번 카드 (Hi-pass 행복 롯데카드) 수집 완료

 38%|███▊      | 1146/2999 [22:00<41:30,  1.34s/it]

[성공] 1147번 카드 (I♥HoNam DC플러스카드) 수집 완료

 38%|███▊      | 1147/2999 [22:01<40:06,  1.30s/it]

[성공] 1148번 카드 (I♥공주 드라이빙 패스 롯데카드) 수집 완료

 38%|███▊      | 1148/2999 [22:02<38:20,  1.24s/it]

[성공] 1149번 카드 (삼성 iD 달달할인) 수집 완료

 38%|███▊      | 1149/2999 [22:03<37:38,  1.22s/it]

[성공] 1150번 카드 (에르고다음 롯데포인트플러스 카드) 수집 완료

 38%|███▊      | 1150/2999 [22:04<36:46,  1.19s/it]

[성공] 1151번 카드 (엔조이뉴욕 롯데카드) 수집 완료

 38%|███▊      | 1151/2999 [22:05<36:09,  1.17s/it]

[성공] 1152번 카드 (KB국민 주유전용기업카드) 수집 완료

 38%|███▊      | 1152/2999 [22:07<35:14,  1.14s/it]

[성공] 1153번 카드 (KB국민 하이패스 주유 기업카드) 수집 완료

 38%|███▊      | 1153/2999 [22:08<34:53,  1.13s/it]

[성공] 1154번 카드 (MyBiz Up 기업카드) 수집 완료

 38%|███▊      | 1154/2999 [22:09<34:32,  1.12s/it]

[성공] 1155번 카드 (Easy shopping 카드) 수집 완료

 39%|███▊      | 1155/2999 [22:10<34:19,  1.12s/it]

[성공] 1156번 카드 (YES24 Mania롯데카드) 수집 완료

 39%|███▊      | 1156/2999 [22:11<33:54,  1.10s/it]

[성공] 1157번 카드 (하나멤버스 1Q 카드 Special Auto) 수집 완료

 39%|███▊      | 1157/2999 [22:12<33:49,  1.10s/it]

[성공] 1158번 카드 (엘지생활건강 롯데포인트플러스카드) 수집 완료

 39%|███▊      | 1158/2999 [22:13<35:11,  1.15s/it]

[성공] 1159번 카드 (개인택시 운송사업자 롯데카드) 수집 완료

 39%|███▊      | 1159/2999 [22:14<35:23,  1.15s/it]

[성공] 1160번 카드 (하나멤버스 1Q(원큐) Tour1 카드) 수집 완료

 39%|███▊      | 1160/2999 [22:16<35:13,  1.15s/it]

[성공] 1161번 카드 (Get100카드) 수집 완료

 39%|███▊      | 1161/2999 [22:17<35:16,  1.15s/it]

[성공] 1162번 카드 (Get100 체크카드) 수집 완료

 39%|███▊      | 1162/2999 [22:18<34:30,  1.13s/it]

[성공] 1163번 카드 (경차 smart 롯데체크카드) 수집 완료

 39%|███▉      | 1163/2999 [22:19<34:03,  1.11s/it]

[성공] 1164번 카드 (ONE KB국민 기업카드) 수집 완료

 39%|███▉      | 1164/2999 [22:20<33:56,  1.11s/it]

[성공] 1165번 카드 (골프존 롯데카드) 수집 완료

 39%|███▉      | 1165/2999 [22:21<33:58,  1.11s/it]

[Skip] 1166번 카드 정보가 존재하지 않습니다.

 39%|███▉      | 1166/2999 [22:22<33:28,  1.10s/it]

[성공] 1167번 카드 (엠비에이(MBA) 카드) 수집 완료

 39%|███▉      | 1167/2999 [22:23<33:38,  1.10s/it]

[성공] 1168번 카드 (IBK 웰릭스 카드) 수집 완료

 39%|███▉      | 1168/2999 [22:24<33:22,  1.09s/it]

[성공] 1169번 카드 (교보문고 롯데체크카드) 수집 완료

 39%|███▉      | 1169/2999 [22:25<33:34,  1.10s/it]

[성공] 1170번 카드 (이사배 카드) 수집 완료

 39%|███▉      | 1170/2999 [22:27<34:46,  1.14s/it]

[성공] 1171번 카드 (H.Point KB국민카드) 수집 완료

 39%|███▉      | 1171/2999 [22:28<34:22,  1.13s/it]

[성공] 1172번 카드 (하나로마트 하나카드) 수집 완료

 39%|███▉      | 1172/2999 [22:29<33:56,  1.11s/it]

[성공] 1173번 카드 (교보문고 핫트랙스 롯데카드) 수집 완료

 39%|███▉      | 1173/2999 [22:30<34:22,  1.13s/it]

[성공] 1174번 카드 (하나 원큐 카드) 수집 완료

 39%|███▉      | 1174/2999 [22:31<33:52,  1.11s/it]

[성공] 1175번 카드 (딩딩 신용카드) 수집 완료

 39%|███▉      | 1175/2999 [22:33<37:14,  1.23s/it]

[성공] 1176번 카드 (프리미엄 GS POP 하나카드) 수집 완료

 39%|███▉      | 1176/2999 [22:34<36:08,  1.19s/it]

[성공] 1177번 카드 (BNK 부자되세요 홈쇼핑카드) 수집 완료

 39%|███▉      | 1177/2999 [22:35<36:10,  1.19s/it]

[성공] 1178번 카드 (BNK 청춘불패 369(Oh!point)체크카드) 수집 완료

 39%|███▉      | 1178/2999 [22:36<35:40,  1.18s/it]

[성공] 1179번 카드 (교원 베이비 롯데카드) 수집 완료

 39%|███▉      | 1179/2999 [22:37<34:47,  1.15s/it]

[성공] 1180번 카드 (풀무원 하나카드) 수집 완료

 39%|███▉      | 1180/2999 [22:38<34:06,  1.13s/it]

[성공] 1181번 카드 (여인닷컴 롯데DC플러스카드) 수집 완료

 39%|███▉      | 1181/2999 [22:39<33:49,  1.12s/it]

[성공] 1182번 카드 (옥토 CMA 샤롯데카드) 수집 완료

 39%|███▉      | 1182/2999 [22:40<34:34,  1.14s/it]

[성공] 1183번 카드 (교원DC 롯데카드) 수집 완료

 39%|███▉      | 1183/2999 [22:42<37:00,  1.22s/it]

[성공] 1184번 카드 (Z:IN 인테리어 신한카드) 수집 완료

 39%|███▉      | 1184/2999 [22:43<35:48,  1.18s/it]

[성공] 1185번 카드 (골든라이프 티타늄카드) 수집 완료

 40%|███▉      | 1185/2999 [22:44<34:59,  1.16s/it]

[성공] 1186번 카드 (포켓몬을 사랑하는 고객용 하나멤버스 1Q 체크카드) 수집 완료

 40%|███▉      | 1186/2999 [22:45<34:13,  1.13s/it]

[성공] 1187번 카드 (THE BOON SVIP 신한카드) 수집 완료

 40%|███▉      | 1187/2999 [22:46<34:42,  1.15s/it]

[성공] 1188번 카드 (펫 사랑 카드) 수집 완료

 40%|███▉      | 1188/2999 [22:47<34:41,  1.15s/it]

[성공] 1189번 카드 (SK렌터카 신한카드 MY CAR) 수집 완료

 40%|███▉      | 1189/2999 [22:49<34:28,  1.14s/it]

[성공] 1190번 카드 (SKT T라이트 신한카드) 수집 완료

 40%|███▉      | 1190/2999 [22:50<34:07,  1.13s/it]

[성공] 1191번 카드 (olleh 슈퍼 DC(Super DC) 신한카드 빅플러스) 수집 완료

 40%|███▉      | 1191/2999 [22:51<35:44,  1.19s/it]

[성공] 1192번 카드 (LG U+ 스마트플랜 Plus 신한카드) 수집 완료

 40%|███▉      | 1192/2999 [22:52<34:57,  1.16s/it]

[성공] 1193번 카드 (LG U+ 사장님 통할인 신한카드) 수집 완료

 40%|███▉      | 1193/2999 [22:53<34:20,  1.14s/it]

[성공] 1194번 카드 (LG U+ Smart 10 신한카드 Big Plus) 수집 완료

 40%|███▉      | 1194/2999 [22:54<34:20,  1.14s/it]

[성공] 1195번 카드 (LG BEST 모바일 Gold 신한카드) 수집 완료

 40%|███▉      | 1195/2999 [22:55<33:54,  1.13s/it]

[성공] 1196번 카드 (KT Super할부 Plus 신한카드) 수집 완료

 40%|███▉      | 1196/2999 [22:57<35:47,  1.19s/it]

[성공] 1197번 카드 (KBO제휴 신한카드 MY KBO) 수집 완료

 40%|███▉      | 1197/2999 [22:58<35:01,  1.17s/it]

[성공] 1198번 카드 (IKEA for Business with 신한카드) 수집 완료

 40%|███▉      | 1198/2999 [22:59<35:30,  1.18s/it]

[성공] 1199번 카드 (GS칼텍스 신한카드 BigPlus) 수집 완료

 40%|███▉      | 1199/2999 [23:00<35:11,  1.17s/it]

[Skip] 1200번 카드 정보가 존재하지 않습니다.

 40%|████      | 1200/2999 [23:01<34:10,  1.14s/it]

[성공] 1201번 카드 (BC 부자되세요 홈쇼핑 신한카드) 수집 완료

 40%|████      | 1201/2999 [23:02<33:50,  1.13s/it]

[성공] 1202번 카드 (부산 동백전 체크카드) 수집 완료

 40%|████      | 1202/2999 [23:04<33:23,  1.12s/it]

[성공] 1203번 카드 (콘텐츠박스 1Q(원큐) 카드 Daily) 수집 완료

 40%|████      | 1203/2999 [23:05<33:03,  1.10s/it]

[성공] 1204번 카드 (코웨이 하나카드) 수집 완료

 40%|████      | 1204/2999 [23:06<32:50,  1.10s/it]

[성공] 1205번 카드 (청호나이스 플러스 하나카드) 수집 완료

 40%|████      | 1205/2999 [23:07<32:40,  1.09s/it]

[성공] 1206번 카드 (청년취업카드 하나멤버스 Mega BC 체크카드) 수집 완료

 40%|████      | 1206/2999 [23:08<32:34,  1.09s/it]

[성공] 1207번 카드 (이랜드 클럽 신용카드) 수집 완료

 40%|████      | 1207/2999 [23:09<33:09,  1.11s/it]

[성공] 1208번 카드 (캐쉬백카드) 수집 완료

 40%|████      | 1208/2999 [23:10<32:58,  1.10s/it]

[성공] 1209번 카드 (BNK 프렌즈 신용카드) 수집 완료

 40%|████      | 1209/2999 [23:11<32:49,  1.10s/it]

[성공] 1210번 카드 (이랜드 클럽 체크카드) 수집 완료

 40%|████      | 1210/2999 [23:12<32:59,  1.11s/it]

[성공] 1211번 카드 (윙고 장학재단 체크카드) 수집 완료

 40%|████      | 1211/2999 [23:13<32:48,  1.10s/it]

[성공] 1212번 카드 (현대홈쇼핑 삼성지엔미포인트카드) 수집 완료

 40%|████      | 1212/2999 [23:15<33:28,  1.12s/it]

[성공] 1213번 카드 (펫(PET)카드) 수집 완료

 40%|████      | 1213/2999 [23:16<33:16,  1.12s/it]

[성공] 1214번 카드 (웰릭스렌탈 하나카드) 수집 완료

 40%|████      | 1214/2999 [23:17<33:04,  1.11s/it]

[성공] 1215번 카드 (아모레퍼시픽 카드) 수집 완료

 41%|████      | 1215/2999 [23:18<32:48,  1.10s/it]

[성공] 1216번 카드 (썸뱅크 체크카드) 수집 완료

 41%|████      | 1216/2999 [23:19<32:37,  1.10s/it]

[성공] 1217번 카드 (현대홈쇼핑 삼성애니패스포인트카드) 수집 완료

 41%|████      | 1217/2999 [23:20<32:47,  1.10s/it]

[성공] 1218번 카드 (현대하이카다이렉트 삼성카드 7) 수집 완료

 41%|████      | 1218/2999 [23:21<32:58,  1.11s/it]

[성공] 1219번 카드 (헬로모바일 삼성카드 2) 수집 완료

 41%|████      | 1219/2999 [23:22<32:54,  1.11s/it]

[성공] 1220번 카드 (BNK 부자되세요 아파트카드) 수집 완료

 41%|████      | 1220/2999 [23:23<33:04,  1.12s/it]

[성공] 1221번 카드 (한화이글스 삼성카앤모아카드) 수집 완료

 41%|████      | 1221/2999 [23:25<33:43,  1.14s/it]

[성공] 1222번 카드 (BNK 2030 플래티늄카드(실버)) 수집 완료

 41%|████      | 1222/2999 [23:26<33:19,  1.13s/it]

[성공] 1223번 카드 (한화손해보험카젠 삼성애니패스포인트카드) 수집 완료

 41%|████      | 1223/2999 [23:27<36:01,  1.22s/it]

[성공] 1224번 카드 (한마음 패밀리 삼성티클래스카드) 수집 완료

 41%|████      | 1224/2999 [23:28<35:08,  1.19s/it]

[성공] 1225번 카드 (KB국민 윙크카드) 수집 완료

 41%|████      | 1225/2999 [23:29<34:29,  1.17s/it]

[성공] 1226번 카드 (롯데청주영플 체크카드) 수집 완료

 41%|████      | 1226/2999 [23:30<33:56,  1.15s/it]

[성공] 1227번 카드 (한국투자증권CMA 삼성체크카드) 수집 완료

 41%|████      | 1227/2999 [23:32<33:23,  1.13s/it]

[성공] 1228번 카드 (하이증권CMA 삼성체크카드) 수집 완료

 41%|████      | 1228/2999 [23:33<34:29,  1.17s/it]

[성공] 1229번 카드 (kt M mobile카드) 수집 완료

 41%|████      | 1229/2999 [23:34<33:42,  1.14s/it]

[성공] 1230번 카드 (LGU＋ 심플라이트카드) 수집 완료

 41%|████      | 1230/2999 [23:35<33:08,  1.12s/it]

[성공] 1231번 카드 (BNK 2030 플래티늄카드(골드)) 수집 완료

 41%|████      | 1231/2999 [23:36<35:07,  1.19s/it]

[성공] 1232번 카드 (플러스모바일 삼성카드 2) 수집 완료

 41%|████      | 1232/2999 [23:37<34:26,  1.17s/it]

[성공] 1233번 카드 (LG전자 KB국민카드) 수집 완료

 41%|████      | 1233/2999 [23:39<33:45,  1.15s/it]

[성공] 1234번 카드 (롯데카드 웨어러블(기본)) 수집 완료

 41%|████      | 1234/2999 [23:40<33:10,  1.13s/it]

[성공] 1235번 카드 (테크노마트 삼성빅앤빅카드) 수집 완료

 41%|████      | 1235/2999 [23:41<33:46,  1.15s/it]

[성공] 1236번 카드 (BNK카드) 수집 완료

 41%|████      | 1236/2999 [23:42<33:06,  1.13s/it]

[성공] 1237번 카드 (롯데카드 웨어러블(디씨레빗)) 수집 완료

 41%|████      | 1237/2999 [23:43<32:38,  1.11s/it]

[성공] 1238번 카드 (동부화재 롯데카드) 수집 완료

 41%|████▏     | 1238/2999 [23:44<34:34,  1.18s/it]

[성공] 1239번 카드 (롯데카드 웨어러블(로카&로카박스/피겨)) 수집 완료

 41%|████▏     | 1239/2999 [23:45<34:01,  1.16s/it]

[성공] 1240번 카드 (STARTLUCK 카드) 수집 완료

 41%|████▏     | 1240/2999 [23:47<35:34,  1.21s/it]

[성공] 1241번 카드 (롯데카드 웨어러블(솜솜이)) 수집 완료

 41%|████▏     | 1241/2999 [23:48<35:01,  1.20s/it]

[성공] 1242번 카드 (스피킹맥스 하나카드) 수집 완료

 41%|████▏     | 1242/2999 [23:49<34:12,  1.17s/it]

[성공] 1243번 카드 (U＋ 알뜰모바일카드) 수집 완료

 41%|████▏     | 1243/2999 [23:50<33:28,  1.14s/it]

[성공] 1244번 카드 (롯데카드 웨어러블(포인트 먹보)) 수집 완료

 41%|████▏     | 1244/2999 [23:51<33:05,  1.13s/it]

[성공] 1245번 카드 (동원몰포인트플러스 롯데카드) 수집 완료

 42%|████▏     | 1245/2999 [23:52<32:39,  1.12s/it]

[성공] 1246번 카드 (소노시즌 하나카드) 수집 완료

 42%|████▏     | 1246/2999 [23:53<32:25,  1.11s/it]

[성공] 1247번 카드 (kt family 카드) 수집 완료

 42%|████▏     | 1247/2999 [23:55<32:30,  1.11s/it]

[성공] 1248번 카드 (바디프랜드 하나카드) 수집 완료

 42%|████▏     | 1248/2999 [23:56<32:19,  1.11s/it]

[성공] 1249번 카드 (SDU-V Family 카드) 수집 완료

 42%|████▏     | 1249/2999 [23:57<32:16,  1.11s/it]

[성공] 1250번 카드 (롯데캐슬라이프 카드) 수집 완료

 42%|████▏     | 1250/2999 [23:58<32:30,  1.12s/it]

[성공] 1251번 카드 (연세동문V카드(LIFE CARE)) 수집 완료

 42%|████▏     | 1251/2999 [23:59<32:44,  1.12s/it]

[성공] 1252번 카드 (연세동문V카드(ASIANA)) 수집 완료

 42%|████▏     | 1252/2999 [24:00<32:27,  1.11s/it]

[성공] 1253번 카드 (랭킹닭컴 하나카드) 수집 완료

 42%|████▏     | 1253/2999 [24:01<32:48,  1.13s/it]

[성공] 1254번 카드 (에코마일리지 우리체크카드) 수집 완료

 42%|████▏     | 1254/2999 [24:02<32:28,  1.12s/it]

[성공] 1255번 카드 (우리 한국장학재단(KOSAF) 체크카드) 수집 완료

 42%|████▏     | 1255/2999 [24:03<32:18,  1.11s/it]

[성공] 1256번 카드 (카드의정석 U+알뜰모바일 CHECK) 수집 완료

 42%|████▏     | 1256/2999 [24:05<31:56,  1.10s/it]

[성공] 1257번 카드 (화물차유류구매카드(개인체크)) 수집 완료

 42%|████▏     | 1257/2999 [24:06<32:09,  1.11s/it]

[성공] 1258번 카드 (OK캐쉬백 썸(SUM)타는 우리체크카드) 수집 완료

 42%|████▏     | 1258/2999 [24:07<32:03,  1.10s/it]

[성공] 1259번 카드 (LGU+ 라서즐거운 체크카드) 수집 완료

 42%|████▏     | 1259/2999 [24:08<31:55,  1.10s/it]

[성공] 1260번 카드 (우리성당 체크카드) 수집 완료

 42%|████▏     | 1260/2999 [24:09<32:24,  1.12s/it]

[성공] 1261번 카드 (우리 국민연금증체크카드) 수집 완료

 42%|████▏     | 1261/2999 [24:10<32:10,  1.11s/it]

[성공] 1262번 카드 (POP 우리V체크카드) 수집 완료

 42%|████▏     | 1262/2999 [24:11<32:00,  1.11s/it]

[성공] 1263번 카드 (태평백화점 삼성티클래스카드) 수집 완료

 42%|████▏     | 1263/2999 [24:12<32:12,  1.11s/it]

[성공] 1264번 카드 (태평백화점 삼성애니패스포인트카드) 수집 완료

 42%|████▏     | 1264/2999 [24:13<32:13,  1.11s/it]

[성공] 1265번 카드 (코레일멤버십이마트 삼성티클래스카드) 수집 완료

 42%|████▏     | 1265/2999 [24:15<32:36,  1.13s/it]

[성공] 1266번 카드 (코레일멤버십 삼성티클래스카드) 수집 완료

 42%|████▏     | 1266/2999 [24:16<33:22,  1.16s/it]

[성공] 1267번 카드 (크리스찬 삼성애니패스카드) 수집 완료

 42%|████▏     | 1267/2999 [24:17<33:37,  1.17s/it]

[성공] 1268번 카드 (코레일멤버십이마트 삼성지엔미포인트카드) 수집 완료

 42%|████▏     | 1268/2999 [24:18<33:13,  1.15s/it]

[성공] 1269번 카드 (패밀리클럽 플래티넘 위버스카이 카드) 수집 완료

 42%|████▏     | 1269/2999 [24:19<33:04,  1.15s/it]

[성공] 1270번 카드 (프리미엄 렌탈DC 쿠쿠FreeMembership롯데카드) 수집 완료

 42%|████▏     | 1270/2999 [24:20<32:25,  1.13s/it]

[성공] 1271번 카드 (코레일멤버십 삼성지엔미포인트카드) 수집 완료

 42%|████▏     | 1271/2999 [24:22<33:48,  1.17s/it]

[성공] 1272번 카드 (프리미엄 렌탈DC 청호나이스 롯데카드) 수집 완료

 42%|████▏     | 1272/2999 [24:23<32:58,  1.15s/it]

[성공] 1273번 카드 (프리미엄 렌탈DC 바디프랜드 롯데카드) 수집 완료

 42%|████▏     | 1273/2999 [24:24<33:28,  1.16s/it]

[성공] 1274번 카드 (프리미엄 렌탈DC 모두렌탈 롯데카드) 수집 완료

 42%|████▏     | 1274/2999 [24:25<32:48,  1.14s/it]

[성공] 1275번 카드 (프리미엄 렌탈DC SK매직 롯데카드) 수집 완료

 43%|████▎     | 1275/2999 [24:26<33:03,  1.15s/it]

[성공] 1276번 카드 (프리미엄 렌탈DC CJ온스타일 롯데카드) 수집 완료

 43%|████▎     | 1276/2999 [24:27<32:52,  1.14s/it]

[성공] 1277번 카드 (드림미즈 롯데포인트플러스 카드) 수집 완료

 43%|████▎     | 1277/2999 [24:28<33:07,  1.15s/it]

[성공] 1278번 카드 (국민행복카드) 수집 완료

 43%|████▎     | 1278/2999 [24:30<34:23,  1.20s/it]

[성공] 1279번 카드 (딩딩 체크카드) 수집 완료

 43%|████▎     | 1279/2999 [24:31<33:42,  1.18s/it]

[성공] 1280번 카드 (국기원 단증 체크카드) 수집 완료

 43%|████▎     | 1280/2999 [24:32<33:02,  1.15s/it]

[성공] 1281번 카드 (코레일멤버십 삼성애니패스포인트카드) 수집 완료

 43%|████▎     | 1281/2999 [24:33<33:43,  1.18s/it]

[성공] 1282번 카드 (코레일멤버십 삼성애니패스카드) 수집 완료

 43%|████▎     | 1282/2999 [24:34<34:23,  1.20s/it]

[성공] 1283번 카드 (코레일멤버십 삼성플래티늄카드) 수집 완료

 43%|████▎     | 1283/2999 [24:36<35:00,  1.22s/it]

[성공] 1284번 카드 (뇌새김 하나카드) 수집 완료

 43%|████▎     | 1284/2999 [24:37<33:56,  1.19s/it]

[성공] 1285번 카드 (넥슨 메이플스토리 하나BC 체크카드) 수집 완료

 43%|████▎     | 1285/2999 [24:38<33:15,  1.16s/it]

[성공] 1286번 카드 (The CJ KB국민카드) 수집 완료

 43%|████▎     | 1286/2999 [24:39<32:51,  1.15s/it]

[성공] 1287번 카드 (마이존 체크카드) 수집 완료

 43%|████▎     | 1287/2999 [24:40<32:22,  1.13s/it]

[성공] 1288번 카드 (toss KB국민카드) 수집 완료

 43%|████▎     | 1288/2999 [24:41<31:56,  1.12s/it]

[성공] 1289번 카드 (T-Premium KB국민카드) 수집 완료

 43%|████▎     | 1289/2999 [24:42<31:52,  1.12s/it]

[성공] 1290번 카드 (넥슨 던전앤파이터 체크카드) 수집 완료

 43%|████▎     | 1290/2999 [24:44<31:45,  1.12s/it]

[성공] 1291번 카드 (코레일멤버십 삼성체크카드) 수집 완료

 43%|████▎     | 1291/2999 [24:45<31:35,  1.11s/it]

[성공] 1292번 카드 (내맘대로 T Plus 카드) 수집 완료

 43%|████▎     | 1292/2999 [24:46<32:07,  1.13s/it]

[성공] 1293번 카드 (코레일멤버십 삼성에스마일카드) 수집 완료

 43%|████▎     | 1293/2999 [24:47<32:04,  1.13s/it]

[성공] 1294번 카드 (가온 Biz카드) 수집 완료

 43%|████▎     | 1294/2999 [24:48<31:45,  1.12s/it]

[성공] 1295번 카드 (코레일멤버십 삼성에스마일플래티늄카드) 수집 완료

 43%|████▎     | 1295/2999 [24:49<33:05,  1.17s/it]

[성공] 1296번 카드 (인터파크G마켓 삼성지엔미포인트카드) 수집 완료

 43%|████▎     | 1296/2999 [24:51<34:54,  1.23s/it]

[성공] 1297번 카드 (부빅스(BUVIX)카드) 수집 완료

 43%|████▎     | 1297/2999 [24:52<33:45,  1.19s/it]

[성공] 1298번 카드 (청소년 후불교통 체크카드) 수집 완료

 43%|████▎     | 1298/2999 [24:53<32:57,  1.16s/it]

[성공] 1299번 카드 (가온 플래티늄바우처카드) 수집 완료

 43%|████▎     | 1299/2999 [24:54<32:57,  1.16s/it]

[성공] 1300번 카드 (인터파크G마켓 삼성애니패스포인트카드) 수집 완료

 43%|████▎     | 1300/2999 [24:55<32:37,  1.15s/it]

[성공] 1301번 카드 (미래에셋 자산관리 CMA 롯데DC플러스 카드) 수집 완료

 43%|████▎     | 1301/2999 [24:56<32:27,  1.15s/it]

[성공] 1302번 카드 (제주도 삼성체크카드) 수집 완료

 43%|████▎     | 1302/2999 [24:57<31:55,  1.13s/it]

[성공] 1303번 카드 (캐디카드) 수집 완료

 43%|████▎     | 1303/2999 [24:59<32:13,  1.14s/it]

[성공] 1304번 카드 (제주항공 삼성카드) 수집 완료

 43%|████▎     | 1304/2999 [25:00<31:55,  1.13s/it]

[성공] 1305번 카드 (길한통 체크카드) 수집 완료

 44%|████▎     | 1305/2999 [25:01<31:58,  1.13s/it]

[성공] 1306번 카드 (전주코아백화점 삼성카드) 수집 완료

 44%|████▎     | 1306/2999 [25:02<31:45,  1.13s/it]

[성공] 1307번 카드 (가온 플래티늄카드) 수집 완료

 44%|████▎     | 1307/2999 [25:03<31:37,  1.12s/it]

[성공] 1308번 카드 (인디안NII 삼성애니패스카드) 수집 완료

 44%|████▎     | 1308/2999 [25:04<31:38,  1.12s/it]

[성공] 1309번 카드 (가온글로벌카드) 수집 완료

 44%|████▎     | 1309/2999 [25:05<31:35,  1.12s/it]

[성공] 1310번 카드 (인디안NII 삼성지엔미카드) 수집 완료

 44%|████▎     | 1310/2999 [25:06<31:30,  1.12s/it]

[성공] 1311번 카드 (BNK 프렌즈 체크카드) 수집 완료

 44%|████▎     | 1311/2999 [25:07<31:11,  1.11s/it]

[성공] 1312번 카드 (골든대로 체크카드) 수집 완료

 44%|████▎     | 1312/2999 [25:09<31:22,  1.12s/it]

[성공] 1313번 카드 (롯데포인트 플러스 PiTaPa 카드) 수집 완료

 44%|████▍     | 1313/2999 [25:10<31:12,  1.11s/it]

[성공] 1314번 카드 (BNK 부자되세요 더 마일리지 체크카드) 수집 완료

 44%|████▍     | 1314/2999 [25:11<31:07,  1.11s/it]

[성공] 1315번 카드 (골든라이프올림카드) 수집 완료

 44%|████▍     | 1315/2999 [25:12<31:18,  1.12s/it]

[성공] 1316번 카드 (유안타WCMA 신세계삼성지엔미P 체크카드) 수집 완료

 44%|████▍     | 1316/2999 [25:13<33:14,  1.18s/it]

[성공] 1317번 카드 (유안타WCMA 신세계삼성애니패스P 체크카드) 수집 완료

 44%|████▍     | 1317/2999 [25:14<32:32,  1.16s/it]

[성공] 1318번 카드 (우리은행 삼성애니패스포인트 체크카드) 수집 완료

 44%|████▍     | 1318/2999 [25:15<32:00,  1.14s/it]

[성공] 1319번 카드 (유안타WCMA 삼성플래티늄체크카드) 수집 완료

 44%|████▍     | 1319/2999 [25:17<31:29,  1.12s/it]

[성공] 1320번 카드 (오라클 삼성티클래스카드) 수집 완료

 44%|████▍     | 1320/2999 [25:18<31:50,  1.14s/it]

[성공] 1321번 카드 (REX카드(기업)) 수집 완료

 44%|████▍     | 1321/2999 [25:19<31:29,  1.13s/it]

[성공] 1322번 카드 (REX카드(개인)) 수집 완료

 44%|████▍     | 1322/2999 [25:20<31:12,  1.12s/it]

[성공] 1323번 카드 (카카오페이 체크카드) 수집 완료

 44%|████▍     | 1323/2999 [25:21<30:50,  1.10s/it]

[성공] 1324번 카드 (국민행복체크카드) 수집 완료

 44%|████▍     | 1324/2999 [25:22<30:38,  1.10s/it]

[성공] 1325번 카드 (Y카드(개인 체크)) 수집 완료

 44%|████▍     | 1325/2999 [25:23<31:48,  1.14s/it]

[성공] 1326번 카드 (그린 카드) 수집 완료

 44%|████▍     | 1326/2999 [25:24<31:34,  1.13s/it]

[성공] 1327번 카드 (한베가족 썸(SUM)타는 우리 체크카드) 수집 완료

 44%|████▍     | 1327/2999 [25:26<32:10,  1.15s/it]

[성공] 1328번 카드 (Young Hana 체크카드 with OKcashbag) 수집 완료

 44%|████▍     | 1328/2999 [25:27<32:40,  1.17s/it]

[성공] 1329번 카드 (우체국 Biz플러스 체크카드) 수집 완료

 44%|████▍     | 1329/2999 [25:28<33:36,  1.21s/it]

[성공] 1330번 카드 (오라클 삼성지엔미포인트카드) 수집 완료

 44%|████▍     | 1330/2999 [25:29<34:36,  1.24s/it]

[성공] 1331번 카드 (야우리백화점 삼성티클래스카드) 수집 완료

 44%|████▍     | 1331/2999 [25:31<33:21,  1.20s/it]

[성공] 1332번 카드 (야우리백화점 삼성애니패스카드) 수집 완료

 44%|████▍     | 1332/2999 [25:32<32:36,  1.17s/it]

[성공] 1333번 카드 (VIVA+ Allpoint 체크카드) 수집 완료

 44%|████▍     | 1333/2999 [25:33<31:47,  1.15s/it]

[성공] 1334번 카드 (우체국 성공partner 체크카드) 수집 완료

 44%|████▍     | 1334/2999 [25:34<31:54,  1.15s/it]

[성공] 1335번 카드 (The-K Auto 체크카드) 수집 완료

 45%|████▍     | 1335/2999 [25:35<31:32,  1.14s/it]

[성공] 1336번 카드 (T&R(티앤알) 하나카드) 수집 완료

 45%|████▍     | 1336/2999 [25:36<31:10,  1.13s/it]

[성공] 1337번 카드 (새마을금고 삼성카드) 수집 완료

 45%|████▍     | 1337/2999 [25:37<30:48,  1.11s/it]

[성공] 1338번 카드 (삼성티클래스카드) 수집 완료

 45%|████▍     | 1338/2999 [25:38<30:41,  1.11s/it]

[성공] 1339번 카드 (골프존 KB국민카드) 수집 완료

 45%|████▍     | 1339/2999 [25:39<30:29,  1.10s/it]

[성공] 1340번 카드 (New Happy 하나카드) 수집 완료

 45%|████▍     | 1340/2999 [25:40<30:33,  1.11s/it]

[성공] 1341번 카드 (삼성티클래스앤오일카드) 수집 완료

 45%|████▍     | 1341/2999 [25:42<31:00,  1.12s/it]

[성공] 1342번 카드 (새마을금고 삼성티클래스앤오일카드) 수집 완료

 45%|████▍     | 1342/2999 [25:43<30:50,  1.12s/it]

[성공] 1343번 카드 (북스리브로 우리카드) 수집 완료

 45%|████▍     | 1343/2999 [25:44<30:42,  1.11s/it]

[성공] 1344번 카드 (전자랜드 삼성티클래스앤오일카드) 수집 완료

 45%|████▍     | 1344/2999 [25:45<30:55,  1.12s/it]

[성공] 1345번 카드 (우리군인연금증카드) 수집 완료

 45%|████▍     | 1345/2999 [25:46<30:57,  1.12s/it]

[성공] 1346번 카드 (My Trip SKYPASS 카드 My flight) 수집 완료

 45%|████▍     | 1346/2999 [25:47<30:31,  1.11s/it]

[성공] 1347번 카드 (현대카드M2 Lady BLUEmembers Platinum) 수집 완료

 45%|████▍     | 1347/2999 [25:48<30:36,  1.11s/it]

[성공] 1348번 카드 (My Trip AsianaClub 카드 My flight) 수집 완료

 45%|████▍     | 1348/2999 [25:50<31:46,  1.15s/it]

[성공] 1349번 카드 (우리군인연금증체크카드) 수집 완료

 45%|████▍     | 1349/2999 [25:51<32:15,  1.17s/it]

[성공] 1350번 카드 (Y카드(개인 신용)) 수집 완료

 45%|████▌     | 1350/2999 [25:52<31:41,  1.15s/it]

[Skip] 1351번 카드 정보가 존재하지 않습니다.

 45%|████▌     | 1351/2999 [25:53<31:02,  1.13s/it]

[성공] 1352번 카드 (My Trip 1Q Global VIVA) 수집 완료

 45%|████▌     | 1352/2999 [25:54<30:55,  1.13s/it]

[성공] 1353번 카드 (신한금융투자 명품CMA 롯데체크카드) 수집 완료

 45%|████▌     | 1353/2999 [25:55<30:34,  1.11s/it]

[성공] 1354번 카드 (교원 웰스 KB국민카드) 수집 완료

 45%|████▌     | 1354/2999 [25:56<30:17,  1.10s/it]

[성공] 1355번 카드 (신한금융투자명품CMA 삼성체크카드) 수집 완료

 45%|████▌     | 1355/2999 [25:57<30:19,  1.11s/it]

[성공] 1356번 카드 (알라딘 삼성지엔미e포인트카드) 수집 완료

 45%|████▌     | 1356/2999 [25:59<31:23,  1.15s/it]

[성공] 1357번 카드 (알라딘 삼성애니패스e포인트카드) 수집 완료

 45%|████▌     | 1357/2999 [26:00<31:34,  1.15s/it]

[성공] 1358번 카드 (알라딘 삼성빅앤빅카드) 수집 완료

 45%|████▌     | 1358/2999 [26:01<31:24,  1.15s/it]

[성공] 1359번 카드 (삼성플래티늄체크카드) 수집 완료

 45%|████▌     | 1359/2999 [26:02<30:56,  1.13s/it]

[성공] 1360번 카드 (삼성포인트체크카드) 수집 완료

 45%|████▌     | 1360/2999 [26:03<30:53,  1.13s/it]

[성공] 1361번 카드 (새마을금고 삼성지엔미카드) 수집 완료

 45%|████▌     | 1361/2999 [26:04<30:38,  1.12s/it]

[성공] 1362번 카드 (새마을금고 삼성오일앤세이브플러스카드) 수집 완료

 45%|████▌     | 1362/2999 [26:05<30:57,  1.13s/it]

[성공] 1363번 카드 (유류환급에버리치 삼성티클래스앤오일 체크카드) 수집 완료

 45%|████▌     | 1363/2999 [26:07<31:06,  1.14s/it]

[성공] 1364번 카드 (새마을금고 IN 삼성카드) 수집 완료

 45%|████▌     | 1364/2999 [26:08<31:19,  1.15s/it]

[성공] 1365번 카드 (새마을금고 삼성애니패스포인트카드) 수집 완료

 46%|████▌     | 1365/2999 [26:09<30:50,  1.13s/it]

[성공] 1366번 카드 (은혜나눔 삼성오일앤세이브플러스카드) 수집 완료

 46%|████▌     | 1366/2999 [26:10<30:53,  1.13s/it]

[성공] 1367번 카드 (코레일멤버십 삼성빅보너스카드) 수집 완료

 46%|████▌     | 1367/2999 [26:11<30:50,  1.13s/it]

[성공] 1368번 카드 (코레일멤버십 삼성마이키즈카드) 수집 완료

 46%|████▌     | 1368/2999 [26:12<30:25,  1.12s/it]

[성공] 1369번 카드 (큰수레TAX 삼성플래티늄체크카드) 수집 완료

 46%|████▌     | 1369/2999 [26:13<30:11,  1.11s/it]

[성공] 1370번 카드 (포인트플러스 포텐 국내 체크카드) 수집 완료

 46%|████▌     | 1370/2999 [26:14<29:53,  1.10s/it]

[성공] 1371번 카드 (큰수레 삼성비즈니스플래티늄카드) 수집 완료

 46%|████▌     | 1371/2999 [26:15<30:03,  1.11s/it]

[성공] 1372번 카드 (포인트플러스 포텐 비자 체크카드) 수집 완료

 46%|████▌     | 1372/2999 [26:17<30:06,  1.11s/it]

[성공] 1373번 카드 (새마을금고 삼성마이키즈카드) 수집 완료

 46%|████▌     | 1373/2999 [26:18<30:12,  1.11s/it]

[성공] 1374번 카드 (삼성지엔미포인트카드) 수집 완료

 46%|████▌     | 1374/2999 [26:19<30:37,  1.13s/it]

[성공] 1375번 카드 (퍼스트클럽 삼성플래티늄카드) 수집 완료

 46%|████▌     | 1375/2999 [26:20<30:28,  1.13s/it]

[성공] 1376번 카드 (포인트플러스 포텐 카드) 수집 완료

 46%|████▌     | 1376/2999 [26:21<30:17,  1.12s/it]

[성공] 1377번 카드 (이마트모바일 삼성카드 2) 수집 완료

 46%|████▌     | 1377/2999 [26:22<30:23,  1.12s/it]

[성공] 1378번 카드 (에너지다이어트 삼성카드 & POINT) 수집 완료

 46%|████▌     | 1378/2999 [26:23<30:25,  1.13s/it]

[성공] 1379번 카드 (굿데이 플래티늄카드) 수집 완료

 46%|████▌     | 1379/2999 [26:24<30:10,  1.12s/it]

[성공] 1380번 카드 (넥센타이어 KB국민카드) 수집 완료

 46%|████▌     | 1380/2999 [26:26<31:28,  1.17s/it]

[성공] 1381번 카드 (모두투어 투어마일리지 KB국민카드) 수집 완료

 46%|████▌     | 1381/2999 [26:27<31:28,  1.17s/it]

[성공] 1382번 카드 (몰테일 KB국민카드) 수집 완료

 46%|████▌     | 1382/2999 [26:28<31:28,  1.17s/it]

[성공] 1383번 카드 (반려愛카드(강아지)) 수집 완료

 46%|████▌     | 1383/2999 [26:29<31:32,  1.17s/it]

[성공] 1384번 카드 (스마트렌탈카드) 수집 완료

 46%|████▌     | 1384/2999 [26:30<30:45,  1.14s/it]

[성공] 1385번 카드 (삼성지엔미카드) 수집 완료

 46%|████▌     | 1385/2999 [26:31<30:36,  1.14s/it]

[성공] 1386번 카드 (삼성지엔미e포인트카드) 수집 완료

 46%|████▌     | 1386/2999 [26:33<30:43,  1.14s/it]

[성공] 1387번 카드 (신라피트니스클럽 삼성플래티늄카드) 수집 완료

 46%|████▌     | 1387/2999 [26:34<30:33,  1.14s/it]

[성공] 1388번 카드 (신라피트니스클럽 멤버십 삼성플래티늄카드) 수집 완료

 46%|████▋     | 1388/2999 [26:35<32:37,  1.22s/it]

[성공] 1389번 카드 (신라피트니스클럽 스카이패스 삼성플래티늄카드) 수집 완료

 46%|████▋     | 1389/2999 [26:36<32:08,  1.20s/it]

[성공] 1390번 카드 (LG U+ Bora 신한카드 Big Plus) 수집 완료

 46%|████▋     | 1390/2999 [26:37<31:54,  1.19s/it]

[성공] 1391번 카드 (탑모아 체크카드) 수집 완료

 46%|████▋     | 1391/2999 [26:39<34:11,  1.28s/it]

[성공] 1392번 카드 (메가쇼핑체크카드) 수집 완료

 46%|████▋     | 1392/2999 [26:40<33:07,  1.24s/it]

[성공] 1393번 카드 (미래에셋 자산관리 CMA 롯데포인트플러스 카드) 수집 완료

 46%|████▋     | 1393/2999 [26:41<32:23,  1.21s/it]

[성공] 1394번 카드 (현대백화점 체크카드) 수집 완료

 46%|████▋     | 1394/2999 [26:42<31:49,  1.19s/it]

[성공] 1395번 카드 (DUAL PARTNERS 기업카드) 수집 완료

 47%|████▋     | 1395/2999 [26:43<30:56,  1.16s/it]

[성공] 1396번 카드 (신한생명 多달이 롯데카드) 수집 완료

 47%|████▋     | 1396/2999 [26:45<31:13,  1.17s/it]

[성공] 1397번 카드 (YO 체크카드) 수집 완료

 47%|████▋     | 1397/2999 [26:46<30:33,  1.14s/it]

[성공] 1398번 카드 (마이존 그린 체크카드) 수집 완료

 47%|████▋     | 1398/2999 [26:47<30:08,  1.13s/it]

[성공] 1399번 카드 (미래에셋아내펀드CMA 삼성체크카드) 수집 완료

 47%|████▋     | 1399/2999 [26:48<30:41,  1.15s/it]

[성공] 1400번 카드 (무비매니아 삼성지엔미포인트카드) 수집 완료

 47%|████▋     | 1400/2999 [26:49<31:00,  1.16s/it]

[성공] 1401번 카드 (무비매니아 삼성애니패스포인트카드) 수집 완료

 47%|████▋     | 1401/2999 [26:50<30:47,  1.16s/it]

[성공] 1402번 카드 (메가티즌 삼성애니패스포인트카드) 수집 완료

 47%|████▋     | 1402/2999 [26:51<30:33,  1.15s/it]

[성공] 1403번 카드 (DGB UntacT 카드) 수집 완료

 47%|████▋     | 1403/2999 [26:53<30:07,  1.13s/it]

[성공] 1404번 카드 (메가티즌 삼성지엔미포인트카드) 수집 완료

 47%|████▋     | 1404/2999 [26:54<30:01,  1.13s/it]

[성공] 1405번 카드 (우리 국민연금증카드) 수집 완료

 47%|████▋     | 1405/2999 [26:55<30:08,  1.13s/it]

[성공] 1406번 카드 (리브로 삼성지엔미포인트카드) 수집 완료

 47%|████▋     | 1406/2999 [26:56<29:58,  1.13s/it]

[성공] 1407번 카드 (리브로 삼성애니패스포인트카드) 수집 완료

 47%|████▋     | 1407/2999 [26:57<29:43,  1.12s/it]

[성공] 1408번 카드 (리브로 롯데카드) 수집 완료

 47%|████▋     | 1408/2999 [26:59<32:06,  1.21s/it]

[성공] 1409번 카드 (현대카드M2 Lady RED MEMBERS Platinum(구 Qmembers)) 수집 완료

 47%|████▋     | 1409/2999 [27:00<31:14,  1.18s/it]

[성공] 1410번 카드 (현대카드M BLUEmembers) 수집 완료

 47%|████▋     | 1410/2999 [27:01<31:19,  1.18s/it]

[성공] 1411번 카드 (마이비 선불교통 롯데체크카드) 수집 완료

 47%|████▋     | 1411/2999 [27:02<34:32,  1.31s/it]

[성공] 1412번 카드 (미래에셋 대우증권 CMA 롯데체크카드) 수집 완료

 47%|████▋     | 1412/2999 [27:03<32:47,  1.24s/it]

[성공] 1413번 카드 (다둥이행복체크카드) 수집 완료

 47%|████▋     | 1413/2999 [27:05<32:12,  1.22s/it]

[성공] 1414번 카드 (POP 우리V스쿨카드) 수집 완료

 47%|████▋     | 1414/2999 [27:06<31:13,  1.18s/it]

[성공] 1415번 카드 (우리 SCHOOL CHECK) 수집 완료

 47%|████▋     | 1415/2999 [27:07<31:19,  1.19s/it]

[성공] 1416번 카드 (서울대학교 CHECK) 수집 완료

 47%|████▋     | 1416/2999 [27:08<31:22,  1.19s/it]

[성공] 1417번 카드 (새마을금고 삼성럭투유카드) 수집 완료

 47%|████▋     | 1417/2999 [27:09<30:46,  1.17s/it]

[성공] 1418번 카드 (새마을금고 데일리 삼성카드) 수집 완료

 47%|████▋     | 1418/2999 [27:10<30:12,  1.15s/it]

[성공] 1419번 카드 (신세계이마트 삼성카드 7+) 수집 완료

 47%|████▋     | 1419/2999 [27:11<29:52,  1.13s/it]

[성공] 1420번 카드 (와이비엠시사닷컴 롯데카드) 수집 완료

 47%|████▋     | 1420/2999 [27:13<29:41,  1.13s/it]

[성공] 1421번 카드 (삼성플래티늄라이프카드) 수집 완료

 47%|████▋     | 1421/2999 [27:14<29:32,  1.12s/it]

[성공] 1422번 카드 (삼성카드 7) 수집 완료

 47%|████▋     | 1422/2999 [27:15<30:12,  1.15s/it]

[성공] 1423번 카드 (삼성카드 7+) 수집 완료

 47%|████▋     | 1423/2999 [27:16<29:51,  1.14s/it]

[성공] 1424번 카드 (스타트럭 플러스 현대오일뱅크카드) 수집 완료

 47%|████▋     | 1424/2999 [27:17<29:26,  1.12s/it]

[성공] 1425번 카드 (우리 OCTO CMA 롯데포인트플러스카드) 수집 완료

 48%|████▊     | 1425/2999 [27:18<29:09,  1.11s/it]

[성공] 1426번 카드 (삼성전자 삼성애니패스카드) 수집 완료

 48%|████▊     | 1426/2999 [27:19<29:08,  1.11s/it]

[성공] 1427번 카드 (삼성애니패스카드) 수집 완료

 48%|████▊     | 1427/2999 [27:21<29:57,  1.14s/it]

[성공] 1428번 카드 (삼성애니패스포인트카드) 수집 완료

 48%|████▊     | 1428/2999 [27:22<31:16,  1.19s/it]

[성공] 1429번 카드 (삼성애니패스e포인트카드) 수집 완료

 48%|████▊     | 1429/2999 [27:23<30:27,  1.16s/it]

[성공] 1430번 카드 (부빅스 부가세 환급카드) 수집 완료

 48%|████▊     | 1430/2999 [27:24<30:07,  1.15s/it]

[성공] 1431번 카드 (CJ 삼성애니패스카드) 수집 완료

 48%|████▊     | 1431/2999 [27:25<30:03,  1.15s/it]

[성공] 1432번 카드 (CJ 삼성지엔미카드) 수집 완료

 48%|████▊     | 1432/2999 [27:26<29:47,  1.14s/it]

[성공] 1433번 카드 (후불 하이패스카드) 수집 완료

 48%|████▊     | 1433/2999 [27:28<30:42,  1.18s/it]

[성공] 1434번 카드 (스타트럭Ⅱ GS칼텍스카드) 수집 완료

 48%|████▊     | 1434/2999 [27:29<29:59,  1.15s/it]

[성공] 1435번 카드 (현대카드M RED MEMBERS(구 Qmembers)) 수집 완료

 48%|████▊     | 1435/2999 [27:30<31:37,  1.21s/it]

[성공] 1436번 카드 (스타트럭플러스 S-OIL카드) 수집 완료

 48%|████▊     | 1436/2999 [27:31<30:41,  1.18s/it]

[성공] 1437번 카드 (현대카드M Lady BLUEmembers) 수집 완료

 48%|████▊     | 1437/2999 [27:32<30:13,  1.16s/it]

[성공] 1438번 카드 (해피포인트 체크카드) 수집 완료

 48%|████▊     | 1438/2999 [27:33<29:49,  1.15s/it]

[성공] 1439번 카드 (현대카드M Lady REDmembers(구 Qmembers)) 수집 완료

 48%|████▊     | 1439/2999 [27:34<29:51,  1.15s/it]

[성공] 1440번 카드 (하이 체크카드) 수집 완료

 48%|████▊     | 1440/2999 [27:36<29:21,  1.13s/it]

[성공] 1441번 카드 (맘 & 데디(Mom & Daddy) 카드) 수집 완료

 48%|████▊     | 1441/2999 [27:37<29:05,  1.12s/it]

[성공] 1442번 카드 (CJ 삼성애니스타일카드) 수집 완료

 48%|████▊     | 1442/2999 [27:38<29:03,  1.12s/it]

[성공] 1443번 카드 (에버랜드 판다카드) 수집 완료

 48%|████▊     | 1443/2999 [27:39<29:42,  1.15s/it]

[성공] 1444번 카드 (ROVL 다이아몬드(스카이패스)기업카드) 수집 완료

 48%|████▊     | 1444/2999 [27:40<29:24,  1.13s/it]

[성공] 1445번 카드 (예다함 카드) 수집 완료

 48%|████▊     | 1445/2999 [27:41<28:52,  1.11s/it]

[성공] 1446번 카드 (웅진씽크빅 카드) 수집 완료

 48%|████▊     | 1446/2999 [27:42<28:43,  1.11s/it]

[성공] 1447번 카드 (NEW_UNI체크) 수집 완료

 48%|████▊     | 1447/2999 [27:43<28:38,  1.11s/it]

[성공] 1448번 카드 (CJ 삼성애니스타일플래티늄카드) 수집 완료

 48%|████▊     | 1448/2999 [27:45<29:17,  1.13s/it]

[성공] 1449번 카드 (웰릭스렌탈 카드) 수집 완료

 48%|████▊     | 1449/2999 [27:46<29:11,  1.13s/it]

[성공] 1450번 카드 (맘스스토리 DC플러스카드) 수집 완료

 48%|████▊     | 1450/2999 [27:47<29:01,  1.12s/it]

[성공] 1451번 카드 (우리V외국인체크카드) 수집 완료

 48%|████▊     | 1451/2999 [27:48<28:50,  1.12s/it]

[성공] 1452번 카드 (삼성애니스타일카드) 수집 완료

 48%|████▊     | 1452/2999 [27:49<31:05,  1.21s/it]

[성공] 1453번 카드 (삼성애니스타일플래티늄카드) 수집 완료

 48%|████▊     | 1453/2999 [27:50<30:25,  1.18s/it]

[성공] 1454번 카드 (맘스클럽 롯데카드) 수집 완료

 48%|████▊     | 1454/2999 [27:52<30:46,  1.20s/it]

[성공] 1455번 카드 (KFC 삼성지엔미카드) 수집 완료

 49%|████▊     | 1455/2999 [27:53<30:00,  1.17s/it]

[성공] 1456번 카드 (GS홈쇼핑 삼성지엔미포인트카드) 수집 완료

 49%|████▊     | 1456/2999 [27:54<29:40,  1.15s/it]

[성공] 1457번 카드 (CU big SIMPLE(일반형)) 수집 완료

 49%|████▊     | 1457/2999 [27:55<29:03,  1.13s/it]

[성공] 1458번 카드 (the Black Edition2) 수집 완료

 49%|████▊     | 1458/2999 [27:56<28:50,  1.12s/it]

[성공] 1459번 카드 (우리캐피탈 롯데포인트플러스카드) 수집 완료

 49%|████▊     | 1459/2999 [27:57<28:53,  1.13s/it]

[성공] 1460번 카드 (웰릭스렌탈 Ⅱ카드) 수집 완료

 49%|████▊     | 1460/2999 [27:58<28:37,  1.12s/it]

[성공] 1461번 카드 (My Life 카드) 수집 완료

 49%|████▊     | 1461/2999 [27:59<28:53,  1.13s/it]

[성공] 1462번 카드 (GS샵&디앤샵 삼성지엔미포인트카드) 수집 완료

 49%|████▊     | 1462/2999 [28:01<28:50,  1.13s/it]

[성공] 1463번 카드 (신협 어부바 체크카드) 수집 완료

 49%|████▉     | 1463/2999 [28:02<28:39,  1.12s/it]

[성공] 1464번 카드 (바디프랜드 롯데카드) 수집 완료

 49%|████▉     | 1464/2999 [28:03<28:23,  1.11s/it]

[성공] 1465번 카드 (푸른저축은행 롯데체크카드) 수집 완료

 49%|████▉     | 1465/2999 [28:04<28:35,  1.12s/it]

[성공] 1466번 카드 (My flight SKYPASS Prime 카드) 수집 완료

 49%|████▉     | 1466/2999 [28:05<28:16,  1.11s/it]

[성공] 1467번 카드 (맘인 롯데카드) 수집 완료

 49%|████▉     | 1467/2999 [28:06<28:51,  1.13s/it]

[성공] 1468번 카드 (제주항공 Refresh Point KB국민카드) 수집 완료

 49%|████▉     | 1468/2999 [28:08<30:41,  1.20s/it]

[성공] 1469번 카드 (CUbig PAY 체크카드) 수집 완료

 49%|████▉     | 1469/2999 [28:09<34:12,  1.34s/it]

[성공] 1470번 카드 (우체국 롯데 비즈니스 카드) 수집 완료

 49%|████▉     | 1470/2999 [28:10<32:38,  1.28s/it]

[성공] 1471번 카드 (GS홈쇼핑 삼성티클래스카드) 수집 완료

 49%|████▉     | 1471/2999 [28:11<31:12,  1.23s/it]

[성공] 1472번 카드 (GS홈쇼핑 삼성애니패스포인트카드) 수집 완료

 49%|████▉     | 1472/2999 [28:13<30:15,  1.19s/it]

[성공] 1473번 카드 (GS샵&디앤샵 삼성애니패스포인트카드) 수집 완료

 49%|████▉     | 1473/2999 [28:14<29:32,  1.16s/it]

[성공] 1474번 카드 (G마켓 삼성티클래스앤오일카드) 수집 완료

 49%|████▉     | 1474/2999 [28:15<29:10,  1.15s/it]

[성공] 1475번 카드 (세이 삼성카드 S클래스) 수집 완료

 49%|████▉     | 1475/2999 [28:16<31:13,  1.23s/it]

[성공] 1476번 카드 (싸이월드 롯데체크카드) 수집 완료

 49%|████▉     | 1476/2999 [28:17<30:20,  1.20s/it]

[성공] 1477번 카드 (싸이월드 롯데카드) 수집 완료

 49%|████▉     | 1477/2999 [28:18<29:50,  1.18s/it]

[성공] 1478번 카드 (쌍용자동차 오토 플러스카드) 수집 완료

 49%|████▉     | 1478/2999 [28:20<32:04,  1.27s/it]

[성공] 1479번 카드 (썸뱅크 롯데 체크카드) 수집 완료

 49%|████▉     | 1479/2999 [28:21<30:45,  1.21s/it]

[성공] 1480번 카드 (썸뱅크 롯데백화점 카드) 수집 완료

 49%|████▉     | 1480/2999 [28:22<29:59,  1.18s/it]

[성공] 1481번 카드 (썸뱅크 롯데카드) 수집 완료

 49%|████▉     | 1481/2999 [28:23<29:20,  1.16s/it]

[성공] 1482번 카드 (씨앤앰 롯데DC플러스카드) 수집 완료

 49%|████▉     | 1482/2999 [28:24<29:06,  1.15s/it]

[성공] 1483번 카드 (아름다운가게 롯데카드) 수집 완료

 49%|████▉     | 1483/2999 [28:25<28:54,  1.14s/it]

[성공] 1484번 카드 (박승철헤어스투디오 롯데카드) 수집 완료

 49%|████▉     | 1484/2999 [28:27<29:50,  1.18s/it]

[성공] 1485번 카드 (벅스 롯데체크카드) 수집 완료

 50%|████▉     | 1485/2999 [28:28<29:13,  1.16s/it]

[성공] 1486번 카드 (벅스 롯데카드) 수집 완료

 50%|████▉     | 1486/2999 [28:29<29:17,  1.16s/it]

[성공] 1487번 카드 (IBK 무직타이거 카드(신용)) 수집 완료

 50%|████▉     | 1487/2999 [28:30<28:49,  1.14s/it]

[성공] 1488번 카드 (법률소비자연맹 포인트플러스 롯데체크카드) 수집 완료

 50%|████▉     | 1488/2999 [28:31<28:38,  1.14s/it]

[성공] 1489번 카드 (법률소비자연맹 포인트플러스 롯데카드) 수집 완료

 50%|████▉     | 1489/2999 [28:32<28:15,  1.12s/it]

[성공] 1490번 카드 (IBK 무직타이거 카드(체크)) 수집 완료

 50%|████▉     | 1490/2999 [28:33<28:26,  1.13s/it]

[성공] 1491번 카드 (베페 롯데카드) 수집 완료

 50%|████▉     | 1491/2999 [28:35<28:04,  1.12s/it]

[성공] 1492번 카드 (보령메디앙스 맘 & 데디(Mom & Daddy) 카드) 수집 완료

 50%|████▉     | 1492/2999 [28:36<28:00,  1.12s/it]

[성공] 1493번 카드 (위메프페이 체크카드) 수집 완료

 50%|████▉     | 1493/2999 [28:37<27:47,  1.11s/it]

[성공] 1494번 카드 (신라면세점 멤버십 삼성카드 S클래스) 수집 완료

 50%|████▉     | 1494/2999 [28:38<28:33,  1.14s/it]

[성공] 1495번 카드 (삼성화재 멤버십 삼성카드 S클래스) 수집 완료

 50%|████▉     | 1495/2999 [28:39<29:14,  1.17s/it]

[성공] 1496번 카드 (삼성화재theS 삼성카앤모아카드) 수집 완료

 50%|████▉     | 1496/2999 [28:40<29:39,  1.18s/it]

[성공] 1497번 카드 (삼성카드) 수집 완료

 50%|████▉     | 1497/2999 [28:42<29:26,  1.18s/it]

[성공] 1498번 카드 (SK에너지 삼성카드 4) 수집 완료

 50%|████▉     | 1498/2999 [28:43<28:45,  1.15s/it]

[성공] 1499번 카드 (삼성카드 4+) 수집 완료

 50%|████▉     | 1499/2999 [28:44<28:23,  1.14s/it]

[성공] 1500번 카드 (삼성카드 4 V2) 수집 완료

 50%|█████     | 1500/2999 [28:45<28:21,  1.14s/it]

[성공] 1501번 카드 (주니어라이프 체크카드) 수집 완료

 50%|█████     | 1501/2999 [28:46<28:04,  1.12s/it]

[성공] 1502번 카드 (청춘대로 싱글 레터링 체크카드(긁으면)) 수집 완료

 50%|█████     | 1502/2999 [28:47<27:59,  1.12s/it]

[성공] 1503번 카드 (북피니언 롯데카드) 수집 완료

 50%|█████     | 1503/2999 [28:49<29:53,  1.20s/it]

[성공] 1504번 카드 (청춘대로 싱글 레터링 체크카드(잘사는)) 수집 완료

 50%|█████     | 1504/2999 [28:50<29:04,  1.17s/it]

[성공] 1505번 카드 (청호나이스 KB국민카드) 수집 완료

 50%|█████     | 1505/2999 [28:51<29:36,  1.19s/it]

[성공] 1506번 카드 (삼성카드 4+ V2) 수집 완료

 50%|█████     | 1506/2999 [28:52<29:05,  1.17s/it]

[성공] 1507번 카드 (우체국 롯데체크카드) 수집 완료

 50%|█████     | 1507/2999 [28:53<28:58,  1.17s/it]

[성공] 1508번 카드 (동부저축은행 삼성체크카드) 수집 완료

 50%|█████     | 1508/2999 [28:54<28:24,  1.14s/it]

[성공] 1509번 카드 (불멸코리아 롯데체크카드) 수집 완료

 50%|█████     | 1509/2999 [28:55<28:02,  1.13s/it]

[성공] 1510번 카드 (코웨이Ⅱ 카드) 수집 완료

 50%|█████     | 1510/2999 [28:56<27:54,  1.12s/it]

[성공] 1511번 카드 (동부증권해피플러스CMA 삼성체크카드) 수집 완료

 50%|█████     | 1511/2999 [28:58<27:49,  1.12s/it]

[성공] 1512번 카드 (쿠쿠렌탈Ⅱ카드) 수집 완료

 50%|█████     | 1512/2999 [28:59<27:52,  1.12s/it]

[성공] 1513번 카드 (불멸코리아 롯데카드) 수집 완료

 50%|█████     | 1513/2999 [29:00<28:09,  1.14s/it]

[성공] 1514번 카드 (쿠쿠렌탈 티타늄카드) 수집 완료

 50%|█████     | 1514/2999 [29:01<29:05,  1.18s/it]

[성공] 1515번 카드 (SC은행 삼성애니패스포인트 체크카드) 수집 완료

 51%|█████     | 1515/2999 [29:02<28:27,  1.15s/it]

[성공] 1516번 카드 (우체국 롯데카드) 수집 완료

 51%|█████     | 1516/2999 [29:03<28:31,  1.15s/it]

[성공] 1517번 카드 (디지털멤버십 삼성유포인트카드) 수집 완료

 51%|█████     | 1517/2999 [29:04<28:16,  1.14s/it]

[성공] 1518번 카드 (위니아만도 롯데카드) 수집 완료

 51%|█████     | 1518/2999 [29:06<28:44,  1.16s/it]

[성공] 1519번 카드 (LG전자 렌탈 플러스 하나카드) 수집 완료

 51%|█████     | 1519/2999 [29:07<29:17,  1.19s/it]

[성공] 1520번 카드 (행복한대구경북티타늄카드) 수집 완료

 51%|█████     | 1520/2999 [29:08<29:06,  1.18s/it]

[성공] 1521번 카드 (CU big CLASSIC) 수집 완료

 51%|█████     | 1521/2999 [29:09<29:32,  1.20s/it]

[성공] 1522번 카드 (쇼핑 그린) 수집 완료

 51%|█████     | 1522/2999 [29:10<28:52,  1.17s/it]

[성공] 1523번 카드 (L.PAY 하나 체크카드) 수집 완료

 51%|█████     | 1523/2999 [29:12<29:42,  1.21s/it]

[성공] 1524번 카드 (Cubig 청춘) 수집 완료

 51%|█████     | 1524/2999 [29:13<29:04,  1.18s/it]

[성공] 1525번 카드 (Cubig SIMPLE(하이브리드형)) 수집 완료

 51%|█████     | 1525/2999 [29:14<29:12,  1.19s/it]

[성공] 1526번 카드 (K리그 축덕 Young Hana 체크카드 with OKcashbag) 수집 완료

 51%|█████     | 1526/2999 [29:15<29:58,  1.22s/it]

[성공] 1527번 카드 (KT Super 할부) 수집 완료

 51%|█████     | 1527/2999 [29:16<29:19,  1.20s/it]

[성공] 1528번 카드 (ROVL 다이아몬드(토탈마일)기업카드) 수집 완료

 51%|█████     | 1528/2999 [29:18<28:41,  1.17s/it]

[성공] 1529번 카드 (KT Super DC) 수집 완료

 51%|█████     | 1529/2999 [29:19<28:09,  1.15s/it]

[성공] 1530번 카드 (BS렌탈 플러스 하나카드) 수집 완료

 51%|█████     | 1530/2999 [29:20<27:53,  1.14s/it]

[성공] 1531번 카드 (Any PLUS SMTOWN &STORE 카드) 수집 완료

 51%|█████     | 1531/2999 [29:21<27:34,  1.13s/it]

[성공] 1532번 카드 (LGU+ 카드의정석 Ⅱ) 수집 완료

 51%|█████     | 1532/2999 [29:22<27:30,  1.12s/it]

[성공] 1533번 카드 (동양증권WCMA신세계 삼성애니패스포인트카드) 수집 완료

 51%|█████     | 1533/2999 [29:23<28:42,  1.17s/it]

[성공] 1534번 카드 (LIG 삼성티클래스앤오일카드) 수집 완료

 51%|█████     | 1534/2999 [29:24<28:16,  1.16s/it]

[성공] 1535번 카드 (ENVY 삼성애니패스포인트카드) 수집 완료

 51%|█████     | 1535/2999 [29:26<28:05,  1.15s/it]

[성공] 1536번 카드 (ENVY 삼성지엔미포인트카드) 수집 완료

 51%|█████     | 1536/2999 [29:27<28:08,  1.15s/it]

[성공] 1537번 카드 (D&Style 삼성지엔미포인트카드) 수집 완료

 51%|█████▏    | 1537/2999 [29:28<27:43,  1.14s/it]

[성공] 1538번 카드 (D&Life 삼성애니패스포인트카드) 수집 완료

 51%|█████▏    | 1538/2999 [29:29<27:48,  1.14s/it]

[성공] 1539번 카드 (SC제일은행 삼성카드 BIZ 4 V2) 수집 완료

 51%|█████▏    | 1539/2999 [29:30<27:49,  1.14s/it]

[성공] 1540번 카드 (비비드레스 롯데카드) 수집 완료

 51%|█████▏    | 1540/2999 [29:31<27:42,  1.14s/it]

[성공] 1541번 카드 (사랑의열매 롯데카드) 수집 완료

 51%|█████▏    | 1541/2999 [29:32<28:01,  1.15s/it]

[성공] 1542번 카드 (삼성CMA플러스 롯데체크카드) 수집 완료

 51%|█████▏    | 1542/2999 [29:34<27:42,  1.14s/it]

[성공] 1543번 카드 (KTX이마트 삼성카드) 수집 완료

 51%|█████▏    | 1543/2999 [29:35<27:14,  1.12s/it]

[성공] 1544번 카드 (해피포인트 KB국민카드) 수집 완료

 51%|█████▏    | 1544/2999 [29:36<26:56,  1.11s/it]

[성공] 1545번 카드 (SLR클럽 삼성티클래스카드) 수집 완료

 52%|█████▏    | 1545/2999 [29:37<27:36,  1.14s/it]

[성공] 1546번 카드 (T라이트 카드의정석) 수집 완료

 52%|█████▏    | 1546/2999 [29:38<27:16,  1.13s/it]

[성공] 1547번 카드 (SLR클럽 삼성애니패스포인트카드) 수집 완료

 52%|█████▏    | 1547/2999 [29:39<29:03,  1.20s/it]

[성공] 1548번 카드 (STM철도 삼성지엔미카드) 수집 완료

 52%|█████▏    | 1548/2999 [29:41<31:13,  1.29s/it]

[성공] 1549번 카드 (하나투어 KB국민카드) 수집 완료

 52%|█████▏    | 1549/2999 [29:42<29:45,  1.23s/it]

[성공] 1550번 카드 (구도일+100 롯데카드) 수집 완료

 52%|█████▏    | 1550/2999 [29:43<29:42,  1.23s/it]

[성공] 1551번 카드 (STM철도 삼성애니패스카드) 수집 완료

 52%|█████▏    | 1551/2999 [29:44<28:52,  1.20s/it]

[성공] 1552번 카드 (S-OIL 삼성카드 4 (포인트)) 수집 완료

 52%|█████▏    | 1552/2999 [29:46<30:58,  1.28s/it]

[성공] 1553번 카드 (SN KB국민은행 삼성애니패스포인트 체크카드) 수집 완료

 52%|█████▏    | 1553/2999 [29:47<29:59,  1.24s/it]

[성공] 1554번 카드 (대교 삼성카드 & POINT) 수집 완료

 52%|█████▏    | 1554/2999 [29:48<29:04,  1.21s/it]

[성공] 1555번 카드 (SKT 우리카드) 수집 완료

 52%|█████▏    | 1555/2999 [29:49<29:12,  1.21s/it]

[성공] 1556번 카드 (플렉스페이카드) 수집 완료

 52%|█████▏    | 1556/2999 [29:50<28:30,  1.19s/it]

[성공] 1557번 카드 (삼성 페이 삼성체크카드 & POINT) 수집 완료

 52%|█████▏    | 1557/2999 [29:52<28:24,  1.18s/it]

[성공] 1558번 카드 (탄탄대로 웰컴카드) 수집 완료

 52%|█████▏    | 1558/2999 [29:53<27:44,  1.16s/it]

[성공] 1559번 카드 (삼성아멕스카드) 수집 완료

 52%|█████▏    | 1559/2999 [29:54<27:32,  1.15s/it]

[성공] 1560번 카드 (삼성스마트오토 캐시백체크카드) 수집 완료

 52%|█████▏    | 1560/2999 [29:55<27:13,  1.14s/it]

[성공] 1561번 카드 (SK 세븐모바일라서 즐거운 카드) 수집 완료

 52%|█████▏    | 1561/2999 [29:56<27:07,  1.13s/it]

[성공] 1562번 카드 (삼성오일앤세이브플러스카드) 수집 완료

 52%|█████▏    | 1562/2999 [29:57<27:11,  1.14s/it]

[성공] 1563번 카드 (olleh CEO 우리카드) 수집 완료

 52%|█████▏    | 1563/2999 [29:58<27:23,  1.14s/it]

[성공] 1564번 카드 (삼성오일앤세이브플러스카드 (유류환급)) 수집 완료

 52%|█████▏    | 1564/2999 [30:00<27:11,  1.14s/it]

[성공] 1565번 카드 (썸(SUM)화물복지카드 (개인체크)) 수집 완료

 52%|█████▏    | 1565/2999 [30:01<26:58,  1.13s/it]

[성공] 1566번 카드 (삼성카드 애니패스 +) 수집 완료

 52%|█████▏    | 1566/2999 [30:02<26:50,  1.12s/it]

[성공] 1567번 카드 (WithWOORI보조금결제전용카드) 수집 완료

 52%|█████▏    | 1567/2999 [30:03<26:28,  1.11s/it]

[성공] 1568번 카드 (국방신협 우리카드) 수집 완료

 52%|█████▏    | 1568/2999 [30:04<26:21,  1.11s/it]

[성공] 1569번 카드 (KB국민 훈카드) 수집 완료

 52%|█████▏    | 1569/2999 [30:05<28:11,  1.18s/it]

[성공] 1570번 카드 (KB국민 민카드) 수집 완료

 52%|█████▏    | 1570/2999 [30:06<27:40,  1.16s/it]

[성공] 1571번 카드 (삼성카드 3) 수집 완료

 52%|█████▏    | 1571/2999 [30:08<28:09,  1.18s/it]

[성공] 1572번 카드 (탐나는전 체크카드) 수집 완료

 52%|█████▏    | 1572/2999 [30:09<27:36,  1.16s/it]

[성공] 1573번 카드 (티머니 체크카드) 수집 완료

 52%|█████▏    | 1573/2999 [30:10<27:20,  1.15s/it]

[성공] 1574번 카드 (e나라도움카드) 수집 완료

 52%|█████▏    | 1574/2999 [30:11<27:16,  1.15s/it]

[성공] 1575번 카드 (e나라도움체크카드) 수집 완료

 53%|█████▎    | 1575/2999 [30:12<27:40,  1.17s/it]

[성공] 1576번 카드 (Free&(프리앤)카드) 수집 완료

 53%|█████▎    | 1576/2999 [30:13<27:06,  1.14s/it]

[성공] 1577번 카드 (New후불하이패스카드) 수집 완료

 53%|█████▎    | 1577/2999 [30:14<27:04,  1.14s/it]

[성공] 1578번 카드 (삼성카드 3 V2) 수집 완료

 53%|█████▎    | 1578/2999 [30:16<26:54,  1.14s/it]

[성공] 1579번 카드 (삼성카드 BIZ 3) 수집 완료

 53%|█████▎    | 1579/2999 [30:17<26:41,  1.13s/it]

[성공] 1580번 카드 (삼성카드 3+) 수집 완료

 53%|█████▎    | 1580/2999 [30:18<26:46,  1.13s/it]

[성공] 1581번 카드 (삼성카드 3+ V2) 수집 완료

 53%|█████▎    | 1581/2999 [30:19<26:39,  1.13s/it]

[성공] 1582번 카드 (삼성카드 3+ (스카이패스)) 수집 완료

 53%|█████▎    | 1582/2999 [30:20<26:48,  1.14s/it]

[성공] 1583번 카드 (ROVL 시그니쳐(스카이패스)기업카드) 수집 완료

 53%|█████▎    | 1583/2999 [30:21<26:51,  1.14s/it]

[성공] 1584번 카드 (신협-신한카드 Hi-Point) 수집 완료

 53%|█████▎    | 1584/2999 [30:22<26:40,  1.13s/it]

[성공] 1585번 카드 (삼성디지털프라자 삼성티클래스카드) 수집 완료

 53%|█████▎    | 1585/2999 [30:23<26:35,  1.13s/it]

[성공] 1586번 카드 (신협-신한카드 Shopping) 수집 완료

 53%|█████▎    | 1586/2999 [30:25<26:27,  1.12s/it]

[성공] 1587번 카드 (11번가 삼성티클래스앤오일카드) 수집 완료

 53%|█████▎    | 1587/2999 [30:26<27:51,  1.18s/it]

[성공] 1588번 카드 (KB국민 정카드) 수집 완료

 53%|█████▎    | 1588/2999 [30:27<27:17,  1.16s/it]

[성공] 1589번 카드 (KB국민 음카드) 수집 완료

 53%|█████▎    | 1589/2999 [30:29<30:00,  1.28s/it]

[성공] 1590번 카드 (kt-현대카드M Edition3(라이트할부형)) 수집 완료

 53%|█████▎    | 1590/2999 [30:30<30:07,  1.28s/it]

[성공] 1591번 카드 (아모레퍼시픽 올림카드) 수집 완료

 53%|█████▎    | 1591/2999 [30:31<28:59,  1.24s/it]

[성공] 1592번 카드 (신협-신한카드 B.Big(삑)) 수집 완료

 53%|█████▎    | 1592/2999 [30:32<28:00,  1.19s/it]

[성공] 1593번 카드 (신협-신한카드 RPM+Platinum#) 수집 완료

 53%|█████▎    | 1593/2999 [30:33<27:20,  1.17s/it]

[성공] 1594번 카드 (세라젬 KB국민카드) 수집 완료

 53%|█████▎    | 1594/2999 [30:34<26:41,  1.14s/it]

[성공] 1595번 카드 (신협-신한카드 Love Platinum#) 수집 완료

 53%|█████▎    | 1595/2999 [30:36<27:46,  1.19s/it]

[성공] 1596번 카드 (kt-현대카드M Edition3(청구할인형2.0)) 수집 완료

 53%|█████▎    | 1596/2999 [30:37<27:11,  1.16s/it]

[성공] 1597번 카드 (신협-신한카드 Air One) 수집 완료

 53%|█████▎    | 1597/2999 [30:38<26:38,  1.14s/it]

[성공] 1598번 카드 (KB국민 SK매직 올림카드) 수집 완료

 53%|█████▎    | 1598/2999 [30:39<27:39,  1.18s/it]

[성공] 1599번 카드 (신협-신한카드 The CLASSIC+) 수집 완료

 53%|█████▎    | 1599/2999 [30:40<27:06,  1.16s/it]

[성공] 1600번 카드 (kt-현대카드M Edition3(청구할인형)) 수집 완료

 53%|█████▎    | 1600/2999 [30:41<26:50,  1.15s/it]

[성공] 1601번 카드 (kt M mobile-현대카드M Edition3) 수집 완료

 53%|█████▎    | 1601/2999 [30:42<26:34,  1.14s/it]

[Skip] 1602번 카드 정보가 존재하지 않습니다.

 53%|█████▎    | 1602/2999 [30:43<26:01,  1.12s/it]

[성공] 1603번 카드 (삼성마이키즈카드) 수집 완료

 53%|█████▎    | 1603/2999 [30:45<25:55,  1.11s/it]

[성공] 1604번 카드 (SK내트럭 유가보조금카드) 수집 완료

 53%|█████▎    | 1604/2999 [30:46<26:39,  1.15s/it]

[성공] 1605번 카드 (U+ 알뜰모바일-현대카드M Edition3) 수집 완료

 54%|█████▎    | 1605/2999 [30:47<26:55,  1.16s/it]

[성공] 1606번 카드 (삼성마이키즈플러스카드) 수집 완료

 54%|█████▎    | 1606/2999 [30:48<26:30,  1.14s/it]

[성공] 1607번 카드 (SK 7mobile-현대카드M Edition3) 수집 완료

 54%|█████▎    | 1607/2999 [30:49<27:03,  1.17s/it]

[성공] 1608번 카드 (SK 7mobile카드) 수집 완료

 54%|█████▎    | 1608/2999 [30:50<26:46,  1.15s/it]

[성공] 1609번 카드 (피에르 가니에르 인피니트 카드) 수집 완료

 54%|█████▎    | 1609/2999 [30:52<27:13,  1.18s/it]

[성공] 1610번 카드 (KB국민 티머니 노리 학생증체크카드(퍼플)) 수집 완료

 54%|█████▎    | 1610/2999 [30:53<26:48,  1.16s/it]

[성공] 1611번 카드 (PlayStation® - 현대카드M) 수집 완료

 54%|█████▎    | 1611/2999 [30:54<26:20,  1.14s/it]

[성공] 1612번 카드 (삼성빅앤빅카드) 수집 완료

 54%|█████▍    | 1612/2999 [30:55<26:13,  1.13s/it]

[Skip] 1613번 카드 정보가 존재하지 않습니다.

 54%|█████▍    | 1613/2999 [30:56<25:54,  1.12s/it]

[성공] 1614번 카드 (쿠쿠 프리멤버쉽 하나카드) 수집 완료

 54%|█████▍    | 1614/2999 [30:57<26:54,  1.17s/it]

[성공] 1615번 카드 (KB국민 티머니노리학생증 체크카드(세로형_퍼플)) 수집 완료

 54%|█████▍    | 1615/2999 [30:59<28:17,  1.23s/it]

[성공] 1616번 카드 (KB국민 티머니노리학생증 체크카드(블루_세로형)) 수집 완료

 54%|█████▍    | 1616/2999 [31:00<27:53,  1.21s/it]

[성공] 1617번 카드 (KB국민 티머니노리학생증 체크카드(그린_세로형)) 수집 완료

 54%|█████▍    | 1617/2999 [31:01<27:21,  1.19s/it]

[성공] 1618번 카드 (KB국민 티머니노리학생증 체크카드(그린)) 수집 완료

 54%|█████▍    | 1618/2999 [31:02<26:44,  1.16s/it]

[성공] 1619번 카드 (KB국민 티머니노리학생증 체크카드(블루)) 수집 완료

 54%|█████▍    | 1619/2999 [31:03<26:23,  1.15s/it]

[성공] 1620번 카드 (삼성빅보너스카드) 수집 완료

 54%|█████▍    | 1620/2999 [31:04<25:57,  1.13s/it]

[성공] 1621번 카드 (내(內) 카드) 수집 완료

 54%|█████▍    | 1621/2999 [31:05<25:52,  1.13s/it]

[성공] 1622번 카드 (필레오 롯데카드) 수집 완료

 54%|█████▍    | 1622/2999 [31:07<26:07,  1.14s/it]

[성공] 1623번 카드 (삼성빅보너스체크카드) 수집 완료

 54%|█████▍    | 1623/2999 [31:08<26:09,  1.14s/it]

[성공] 1624번 카드 (삼성마이골프카드) 수집 완료

 54%|█████▍    | 1624/2999 [31:09<25:59,  1.13s/it]

[성공] 1625번 카드 (삼성 리워즈 하나 신용카드) 수집 완료

 54%|█████▍    | 1625/2999 [31:10<25:37,  1.12s/it]

[Skip] 1626번 카드 정보가 존재하지 않습니다.

 54%|█████▍    | 1626/2999 [31:11<25:35,  1.12s/it]

[성공] 1627번 카드 (하기스몰 롯데카드) 수집 완료

 54%|█████▍    | 1627/2999 [31:12<25:31,  1.12s/it]

[성공] 1628번 카드 (삼성비즈니스매니저카드) 수집 완료

 54%|█████▍    | 1628/2999 [31:13<25:33,  1.12s/it]

[Skip] 1629번 카드 정보가 존재하지 않습니다.

 54%|█████▍    | 1629/2999 [31:14<25:11,  1.10s/it]

[성공] 1630번 카드 (한화생명 Family카드 (골프형)) 수집 완료

 54%|█████▍    | 1630/2999 [31:16<25:34,  1.12s/it]

[성공] 1631번 카드 (삼성비즈니스플래티늄카드) 수집 완료

 54%|█████▍    | 1631/2999 [31:17<25:33,  1.12s/it]

[성공] 1632번 카드 (위메이크프라이스 롯데포인트플러스카드) 수집 완료

 54%|█████▍    | 1632/2999 [31:18<25:38,  1.13s/it]

[성공] 1633번 카드 (하나은행 롯데포인트 플러스 GRANDE 체크카드) 수집 완료

 54%|█████▍    | 1633/2999 [31:19<25:25,  1.12s/it]

[성공] 1634번 카드 (하우머치 롯데카드) 수집 완료

 54%|█████▍    | 1634/2999 [31:20<25:15,  1.11s/it]

[성공] 1635번 카드 (하이카다이렉트 롯데포인트플러스카드) 수집 완료

 55%|█████▍    | 1635/2999 [31:21<25:21,  1.12s/it]

[성공] 1636번 카드 (한국납세자연맹 롯데포인트플러스카드) 수집 완료

 55%|█████▍    | 1636/2999 [31:22<25:09,  1.11s/it]

[성공] 1637번 카드 (삼성카드5) 수집 완료

 55%|█████▍    | 1637/2999 [31:23<25:06,  1.11s/it]

[성공] 1638번 카드 (백년지대계 삼성카드 5) 수집 완료

 55%|█████▍    | 1638/2999 [31:25<25:48,  1.14s/it]

[성공] 1639번 카드 (딸기가좋아 삼성카드 5) 수집 완료

 55%|█████▍    | 1639/2999 [31:26<26:01,  1.15s/it]

[성공] 1640번 카드 (삼성카드 5 V2) 수집 완료

 55%|█████▍    | 1640/2999 [31:27<25:48,  1.14s/it]

[성공] 1641번 카드 (삼성카드 5+) 수집 완료

 55%|█████▍    | 1641/2999 [31:28<29:16,  1.29s/it]

[성공] 1642번 카드 (북크 삼성카드 5) 수집 완료

 55%|█████▍    | 1642/2999 [31:30<28:02,  1.24s/it]

[성공] 1643번 카드 (Gvalley 삼성카드 5) 수집 완료

 55%|█████▍    | 1643/2999 [31:31<27:41,  1.23s/it]

[성공] 1644번 카드 (Gvalley 삼성카드 3) 수집 완료

 55%|█████▍    | 1644/2999 [31:32<27:45,  1.23s/it]

[성공] 1645번 카드 (백년지대계 삼성카드 7) 수집 완료

 55%|█████▍    | 1645/2999 [31:33<26:59,  1.20s/it]

[성공] 1646번 카드 (삼성카드 7 V2) 수집 완료

 55%|█████▍    | 1646/2999 [31:34<26:47,  1.19s/it]

[성공] 1647번 카드 (삼성카드 7+ V2) 수집 완료

 55%|█████▍    | 1647/2999 [31:35<26:20,  1.17s/it]

[성공] 1648번 카드 (NH올원 Direct&DB손해보험카드) 수집 완료

 55%|█████▍    | 1648/2999 [31:36<25:48,  1.15s/it]

[성공] 1649번 카드 (삼성쇼핑캐시백체크카드) 수집 완료

 55%|█████▍    | 1649/2999 [31:38<25:30,  1.13s/it]

[성공] 1650번 카드 (화물복지 삼성카드) 수집 완료

 55%|█████▌    | 1650/2999 [31:39<25:13,  1.12s/it]

[성공] 1651번 카드 (화물복지 삼성체크카드) 수집 완료

 55%|█████▌    | 1651/2999 [31:40<26:00,  1.16s/it]

[성공] 1652번 카드 (삼성루와드뱅카드) 수집 완료

 55%|█████▌    | 1652/2999 [31:41<25:37,  1.14s/it]

[성공] 1653번 카드 (트레이더스신세계 삼성카드 5) 수집 완료

 55%|█████▌    | 1653/2999 [31:42<25:28,  1.14s/it]

[성공] 1654번 카드 (트레이더스 삼성카드 BIZ) 수집 완료

 55%|█████▌    | 1654/2999 [31:43<25:34,  1.14s/it]

[성공] 1655번 카드 (큰수레 화물복지 삼성카드) 수집 완료

 55%|█████▌    | 1655/2999 [31:44<25:14,  1.13s/it]

[성공] 1656번 카드 (전자랜드 삼성카드 3 V2) 수집 완료

 55%|█████▌    | 1656/2999 [31:46<26:04,  1.17s/it]

[성공] 1657번 카드 (전우사랑 패밀리 삼성카드) 수집 완료

 55%|█████▌    | 1657/2999 [31:47<26:31,  1.19s/it]

[성공] 1658번 카드 (롯데관광 삼성빅앤빅카드) 수집 완료

 55%|█████▌    | 1658/2999 [31:48<25:59,  1.16s/it]

[성공] 1659번 카드 (전우사랑 삼성카드) 수집 완료

 55%|█████▌    | 1659/2999 [31:49<27:01,  1.21s/it]

[성공] 1660번 카드 (전국24시콜화물 화물복지 삼성카드) 수집 완료

 55%|█████▌    | 1660/2999 [31:50<26:11,  1.17s/it]

[성공] 1661번 카드 (웰스 삼성카드) 수집 완료

 55%|█████▌    | 1661/2999 [31:52<25:38,  1.15s/it]

[성공] 1662번 카드 (웰스 삼성카드(할부)) 수집 완료

 55%|█████▌    | 1662/2999 [31:53<26:13,  1.18s/it]

[성공] 1663번 카드 (에스원 안심 삼성카드 BIZ) 수집 완료

 55%|█████▌    | 1663/2999 [31:54<25:42,  1.15s/it]

[성공] 1664번 카드 (디큐브 삼성더아파트카드) 수집 완료

 55%|█████▌    | 1664/2999 [31:55<25:47,  1.16s/it]

[성공] 1665번 카드 (에버리치 삼성체크카드) 수집 완료

 56%|█████▌    | 1665/2999 [31:56<25:19,  1.14s/it]

[성공] 1666번 카드 (SK에너지 전국24시콜화물 화물복지 삼성카드) 수집 완료

 56%|█████▌    | 1666/2999 [31:57<25:15,  1.14s/it]

[성공] 1667번 카드 (SK에너지 큰수레 화물복지 삼성카드) 수집 완료

 56%|█████▌    | 1667/2999 [31:58<25:02,  1.13s/it]

[성공] 1668번 카드 (SK에너지 화물복지 삼성카드) 수집 완료

 56%|█████▌    | 1668/2999 [31:59<25:07,  1.13s/it]

[성공] 1669번 카드 (SK에너지 화물복지 삼성체크카드) 수집 완료

 56%|█████▌    | 1669/2999 [32:01<24:49,  1.12s/it]

[성공] 1670번 카드 (SK매직 삼성카드) 수집 완료

 56%|█████▌    | 1670/2999 [32:02<24:40,  1.11s/it]

[성공] 1671번 카드 (SK매직 삼성카드 (할부)) 수집 완료

 56%|█████▌    | 1671/2999 [32:03<24:43,  1.12s/it]

[성공] 1672번 카드 (삼성더아파트카드) 수집 완료

 56%|█████▌    | 1672/2999 [32:04<24:39,  1.11s/it]

[성공] 1673번 카드 (S-OIL 삼성카드 & POINT) 수집 완료

 56%|█████▌    | 1673/2999 [32:05<24:50,  1.12s/it]

[성공] 1674번 카드 (삼성다이닝캐시백체크카드) 수집 완료

 56%|█████▌    | 1674/2999 [32:06<24:36,  1.11s/it]

[성공] 1675번 카드 (T 라이트 삼성카드) 수집 완료

 56%|█████▌    | 1675/2999 [32:07<25:13,  1.14s/it]

[성공] 1676번 카드 (신세계인터내셔날 삼성카드) 수집 완료

 56%|█████▌    | 1676/2999 [32:09<25:09,  1.14s/it]

[성공] 1677번 카드 (삼성금융카드) 수집 완료

 56%|█████▌    | 1677/2999 [32:10<28:56,  1.31s/it]

[성공] 1678번 카드 (신세계이마트 삼성카드 7) 수집 완료

 56%|█████▌    | 1678/2999 [32:11<27:54,  1.27s/it]

[성공] 1679번 카드 (삼성로즈플래티늄카드) 수집 완료

 56%|█████▌    | 1679/2999 [32:13<29:13,  1.33s/it]

[성공] 1680번 카드 (삼성골프플래티늄카드) 수집 완료

 56%|█████▌    | 1680/2999 [32:14<30:02,  1.37s/it]

[성공] 1681번 카드 (한국새생명복지재단 롯데체크 카드) 수집 완료

 56%|█████▌    | 1681/2999 [32:15<28:14,  1.29s/it]

[성공] 1682번 카드 (한국새생명복지재단 롯데카드) 수집 완료

 56%|█████▌    | 1682/2999 [32:17<26:59,  1.23s/it]

[성공] 1683번 카드 (한국투자증권 CMA 롯데체크카드) 수집 완료

 56%|█████▌    | 1683/2999 [32:18<26:05,  1.19s/it]

[성공] 1684번 카드 (한샘 롯데카드) 수집 완료

 56%|█████▌    | 1684/2999 [32:19<26:54,  1.23s/it]

[성공] 1685번 카드 (아모레퍼시픽 뷰티포인트 롯데체크카드) 수집 완료

 56%|█████▌    | 1685/2999 [32:20<26:30,  1.21s/it]

[성공] 1686번 카드 (아모레퍼시픽 뷰티포인트 롯데카드) 수집 완료

 56%|█████▌    | 1686/2999 [32:21<26:56,  1.23s/it]

[성공] 1687번 카드 (아이랑 롯데체크카드) 수집 완료

 56%|█████▋    | 1687/2999 [32:23<26:18,  1.20s/it]

[성공] 1688번 카드 (아이랑 롯데카드) 수집 완료

 56%|█████▋    | 1688/2999 [32:24<25:38,  1.17s/it]

[성공] 1689번 카드 (아이북랜드 독서천재 롯데카드) 수집 완료

 56%|█████▋    | 1689/2999 [32:25<25:09,  1.15s/it]

[성공] 1690번 카드 (아이챌린지 롯데카드) 수집 완료

 56%|█████▋    | 1690/2999 [32:26<25:15,  1.16s/it]

[성공] 1691번 카드 (알라딘 Magic 롯데카드) 수집 완료

 56%|█████▋    | 1691/2999 [32:27<25:10,  1.15s/it]

[성공] 1692번 카드 (패션그룹 형지 롯데카드) 수집 완료

 56%|█████▋    | 1692/2999 [32:28<24:46,  1.14s/it]

[성공] 1693번 카드 (포인트플러스 Penta 카드) 수집 완료

 56%|█████▋    | 1693/2999 [32:29<24:38,  1.13s/it]

[성공] 1694번 카드 (행복한대한민국체크카드(비씨)) 수집 완료

 56%|█████▋    | 1694/2999 [32:31<25:49,  1.19s/it]

[성공] 1695번 카드 (한화생명 Family 카드 (문화형)) 수집 완료

 57%|█████▋    | 1695/2999 [32:32<25:53,  1.19s/it]

[성공] 1696번 카드 (우리성당카드 다모아포인트) 수집 완료

 57%|█████▋    | 1696/2999 [32:33<26:13,  1.21s/it]

[성공] 1697번 카드 (평생교육희망카드(비씨)) 수집 완료

 57%|█████▋    | 1697/2999 [32:34<25:26,  1.17s/it]

[성공] 1698번 카드 (中國 通(중국통)체크카드) 수집 완료

 57%|█████▋    | 1698/2999 [32:35<25:41,  1.18s/it]

[성공] 1699번 카드 (한화생명 Family 체크카드) 수집 완료

 57%|█████▋    | 1699/2999 [32:37<25:48,  1.19s/it]

[성공] 1700번 카드 (국기원 단증카드) 수집 완료

 57%|█████▋    | 1700/2999 [32:38<25:35,  1.18s/it]

[성공] 1701번 카드 (국제학생증체크카드) 수집 완료

 57%|█████▋    | 1701/2999 [32:39<25:02,  1.16s/it]

[성공] 1702번 카드 (FC EXPRESS 체크) 수집 완료

 57%|█████▋    | 1702/2999 [32:40<24:36,  1.14s/it]

[성공] 1703번 카드 (우리ONE 체크카드 국제ATM) 수집 완료

 57%|█████▋    | 1703/2999 [32:41<24:32,  1.14s/it]

[성공] 1704번 카드 (해병대 전우 롯데카드) 수집 완료

 57%|█████▋    | 1704/2999 [32:42<24:10,  1.12s/it]

[성공] 1705번 카드 (해병대 전우 롯데 포인트플러스 체크카드) 수집 완료

 57%|█████▋    | 1705/2999 [32:43<23:52,  1.11s/it]

[성공] 1706번 카드 (해병대 전우 롯데체크플러스 카드) 수집 완료

 57%|█████▋    | 1706/2999 [32:44<23:50,  1.11s/it]

[성공] 1707번 카드 (KATA가득한 할인카드) 수집 완료

 57%|█████▋    | 1707/2999 [32:46<24:47,  1.15s/it]

[성공] 1708번 카드 ([문화] The Family 동부카드) 수집 완료

 57%|█████▋    | 1708/2999 [32:47<24:47,  1.15s/it]

[성공] 1709번 카드 ([골프] The Family 동부카드) 수집 완료

 57%|█████▋    | 1709/2999 [32:48<24:40,  1.15s/it]

[성공] 1710번 카드 (카드의정석 HEROES) 수집 완료

 57%|█████▋    | 1710/2999 [32:49<24:20,  1.13s/it]

[성공] 1711번 카드 (삼성카드 1 (포인트)) 수집 완료

 57%|█████▋    | 1711/2999 [32:50<24:30,  1.14s/it]

[성공] 1712번 카드 (매직서비스 롯데카드) 수집 완료

 57%|█████▋    | 1712/2999 [32:51<24:01,  1.12s/it]

[성공] 1713번 카드 (카드의정석 Biz Platinum Discount) 수집 완료

 57%|█████▋    | 1713/2999 [32:52<24:06,  1.13s/it]

[성공] 1714번 카드 (세븐일레븐 멤버십롯데체크카드) 수집 완료

 57%|█████▋    | 1714/2999 [32:53<24:08,  1.13s/it]

[성공] 1715번 카드 (셀프페이 DC스마트 카드) 수집 완료

 57%|█████▋    | 1715/2999 [32:55<24:59,  1.17s/it]

[성공] 1716번 카드 (카드의정석 Biz Platinum) 수집 완료

 57%|█████▋    | 1716/2999 [32:56<24:32,  1.15s/it]

[Skip] 1717번 카드 정보가 존재하지 않습니다.

 57%|█████▋    | 1717/2999 [32:57<24:04,  1.13s/it]

[성공] 1718번 카드 (해피포인트 롯데카드) 수집 완료

 57%|█████▋    | 1718/2999 [32:58<23:50,  1.12s/it]

[성공] 1719번 카드 (맥스무비 롯데카드) 수집 완료

 57%|█████▋    | 1719/2999 [32:59<23:31,  1.10s/it]

[성공] 1720번 카드 (삼성카드 1 (아시아나)) 수집 완료

 57%|█████▋    | 1720/2999 [33:00<23:44,  1.11s/it]

[성공] 1721번 카드 (해피포인트 롯데체크카드) 수집 완료

 57%|█████▋    | 1721/2999 [33:01<23:32,  1.10s/it]

[성공] 1722번 카드 (쇼핑 세이브 카드) 수집 완료

 57%|█████▋    | 1722/2999 [33:02<23:43,  1.11s/it]

[성공] 1723번 카드 (삼성카드 1 (스카이패스)) 수집 완료

 57%|█████▋    | 1723/2999 [33:03<23:41,  1.11s/it]

[성공] 1724번 카드 (멋남 롯데카드) 수집 완료

 57%|█████▋    | 1724/2999 [33:05<23:38,  1.11s/it]

[성공] 1725번 카드 (수박씨닷컴 롯데포인트플러스카드) 수집 완료

 58%|█████▊    | 1725/2999 [33:06<23:28,  1.11s/it]

[성공] 1726번 카드 (그린카드 (서울형)) 수집 완료

 58%|█████▊    | 1726/2999 [33:07<23:22,  1.10s/it]

[성공] 1727번 카드 (삼성쇼핑플래티늄카드) 수집 완료

 58%|█████▊    | 1727/2999 [33:08<23:47,  1.12s/it]

[Skip] 1728번 카드 정보가 존재하지 않습니다.

 58%|█████▊    | 1728/2999 [33:09<23:28,  1.11s/it]

[성공] 1729번 카드 (그린카드 (전국형)) 수집 완료

 58%|█████▊    | 1729/2999 [33:10<23:50,  1.13s/it]

[Skip] 1730번 카드 정보가 존재하지 않습니다.

 58%|█████▊    | 1730/2999 [33:11<23:26,  1.11s/it]

[성공] 1731번 카드 (로얄블루1000카드 [SKYPASS]) 수집 완료

 58%|█████▊    | 1731/2999 [33:13<24:30,  1.16s/it]

[성공] 1732번 카드 (로얄블루1000카드 [ASIANA]) 수집 완료

 58%|█████▊    | 1732/2999 [33:14<24:11,  1.15s/it]

[Skip] 1733번 카드 정보가 존재하지 않습니다.

 58%|█████▊    | 1733/2999 [33:15<23:40,  1.12s/it]

[성공] 1734번 카드 (현대오일뱅크 드라이빙패스 카드) 수집 완료

 58%|█████▊    | 1734/2999 [33:16<23:28,  1.11s/it]

[Skip] 1735번 카드 정보가 존재하지 않습니다.

 58%|█████▊    | 1735/2999 [33:17<23:08,  1.10s/it]

[성공] 1736번 카드 (스마일 Seller카드) 수집 완료

 58%|█████▊    | 1736/2999 [33:18<23:19,  1.11s/it]

[Skip] 1737번 카드 정보가 존재하지 않습니다.

 58%|█████▊    | 1737/2999 [33:19<23:03,  1.10s/it]

[Skip] 1738번 카드 정보가 존재하지 않습니다.

 58%|█████▊    | 1738/2999 [33:20<22:59,  1.09s/it]

[Skip] 1739번 카드 정보가 존재하지 않습니다.

 58%|█████▊    | 1739/2999 [33:21<23:00,  1.10s/it]

[Skip] 1740번 카드 정보가 존재하지 않습니다.

 58%|█████▊    | 1740/2999 [33:22<22:58,  1.09s/it]

[성공] 1741번 카드 (ROYAL BLUE POINT) 수집 완료

 58%|█████▊    | 1741/2999 [33:23<23:05,  1.10s/it]

[성공] 1742번 카드 (신세계이마트 삼성카드 5) 수집 완료

 58%|█████▊    | 1742/2999 [33:25<23:10,  1.11s/it]

[성공] 1743번 카드 (신세계이마트 삼성카드 4 (포인트)) 수집 완료

 58%|█████▊    | 1743/2999 [33:26<23:08,  1.11s/it]

[성공] 1744번 카드 (신세계이마트 삼성카드 2) 수집 완료

 58%|█████▊    | 1744/2999 [33:27<23:44,  1.13s/it]

[성공] 1745번 카드 (신세계사이먼 프리미엄 아울렛 삼성카드) 수집 완료

 58%|█████▊    | 1745/2999 [33:28<23:46,  1.14s/it]

[성공] 1746번 카드 (신세계까사미아 삼성카드) 수집 완료

 58%|█████▊    | 1746/2999 [33:29<23:50,  1.14s/it]

[성공] 1747번 카드 (신세계 엑스포 삼성카드) 수집 완료

 58%|█████▊    | 1747/2999 [33:30<23:54,  1.15s/it]

[성공] 1748번 카드 (신세계 멘즈라이프 삼성카드) 수집 완료

 58%|█████▊    | 1748/2999 [33:32<24:54,  1.19s/it]

[성공] 1749번 카드 (신세계 대구라이프 삼성카드) 수집 완료

 58%|█████▊    | 1749/2999 [33:33<24:31,  1.18s/it]

[성공] 1750번 카드 (신세계KB국민은행 삼성체크카드) 수집 완료

 58%|█████▊    | 1750/2999 [33:34<24:07,  1.16s/it]

[성공] 1751번 카드 (신세계 삼성지엔미포인트 체크카드) 수집 완료

 58%|█████▊    | 1751/2999 [33:35<24:29,  1.18s/it]

[성공] 1752번 카드 (신세계 삼성애니패스포인트 체크카드) 수집 완료

 58%|█████▊    | 1752/2999 [33:36<24:13,  1.17s/it]

[성공] 1753번 카드 (나인걸 롯데카드) 수집 완료

 58%|█████▊    | 1753/2999 [33:37<23:49,  1.15s/it]

[성공] 1754번 카드 (뉴GS칼텍스 롯데카드) 수집 완료

 58%|█████▊    | 1754/2999 [33:39<25:10,  1.21s/it]

[성공] 1755번 카드 (뉴롯데면세점카드) 수집 완료

 59%|█████▊    | 1755/2999 [33:40<25:16,  1.22s/it]

[성공] 1756번 카드 (뉴롯데시네마 롯데체크카드) 수집 완료

 59%|█████▊    | 1756/2999 [33:41<25:20,  1.22s/it]

[성공] 1757번 카드 (뉴롯데시네마 포인트플러스카드) 수집 완료

 59%|█████▊    | 1757/2999 [33:42<24:40,  1.19s/it]

[성공] 1758번 카드 (올바른SAFE카드) 수집 완료

 59%|█████▊    | 1758/2999 [33:44<25:16,  1.22s/it]

[성공] 1759번 카드 (SC제일은행 아시아나 삼성지엔미카드) 수집 완료

 59%|█████▊    | 1759/2999 [33:45<24:57,  1.21s/it]

[성공] 1760번 카드 (현대해상하이카다이렉트 롯데카드) 수집 완료

 59%|█████▊    | 1760/2999 [33:46<24:24,  1.18s/it]

[성공] 1761번 카드 (SC제일은행 삼성카드 6 V2) 수집 완료

 59%|█████▊    | 1761/2999 [33:47<24:33,  1.19s/it]

[성공] 1762번 카드 (SC제일은행 삼성카드 4 V2) 수집 완료

 59%|█████▉    | 1762/2999 [33:48<24:51,  1.21s/it]

[성공] 1763번 카드 (올바른SAFE Platinum카드) 수집 완료

 59%|█████▉    | 1763/2999 [33:49<24:08,  1.17s/it]

[성공] 1764번 카드 (Gowid 롯데법인카드) 수집 완료

 59%|█████▉    | 1764/2999 [33:51<23:43,  1.15s/it]

[성공] 1765번 카드 (올바른 NEW HAVE체크카드) 수집 완료

 59%|█████▉    | 1765/2999 [33:52<24:29,  1.19s/it]

[성공] 1766번 카드 (한솔교육 롯데카드) 수집 완료

 59%|█████▉    | 1766/2999 [33:53<23:55,  1.16s/it]

[성공] 1767번 카드 (에코마일리지체크카드(비씨)) 수집 완료

 59%|█████▉    | 1767/2999 [33:54<23:25,  1.14s/it]

[성공] 1768번 카드 (ROYAL BLUE MILEAGE[SKYPASS]) 수집 완료

 59%|█████▉    | 1768/2999 [33:55<23:17,  1.14s/it]

[성공] 1769번 카드 (ROYAL BLUE MILEAGE[AsianaClub]) 수집 완료

 59%|█████▉    | 1769/2999 [33:56<23:22,  1.14s/it]

[성공] 1770번 카드 (한화 Smart CMA 롯데DC플러스 카드) 수집 완료

 59%|█████▉    | 1770/2999 [33:57<23:02,  1.12s/it]

[성공] 1771번 카드 (삼성카드 6 V2) 수집 완료

 59%|█████▉    | 1771/2999 [33:59<23:13,  1.13s/it]

[성공] 1772번 카드 (TAX SAVE 법인카드) 수집 완료

 59%|█████▉    | 1772/2999 [34:00<23:07,  1.13s/it]

[성공] 1773번 카드 (한화 Smart CMA 롯데포인트플러스카드) 수집 완료

 59%|█████▉    | 1773/2999 [34:01<23:54,  1.17s/it]

[성공] 1774번 카드 (삼성카드 6+) 수집 완료

 59%|█████▉    | 1774/2999 [34:02<25:02,  1.23s/it]

[성공] 1775번 카드 (삼성카드 2 V2) 수집 완료

 59%|█████▉    | 1775/2999 [34:03<24:23,  1.20s/it]

[성공] 1776번 카드 (결제 전용 특화 법인카드) 수집 완료

 59%|█████▉    | 1776/2999 [34:05<23:44,  1.17s/it]

[성공] 1777번 카드 (Gvalley 삼성카드 2) 수집 완료

 59%|█████▉    | 1777/2999 [34:06<23:41,  1.16s/it]

[성공] 1778번 카드 (해피머니 롯데카드) 수집 완료

 59%|█████▉    | 1778/2999 [34:07<23:18,  1.15s/it]

[성공] 1779번 카드 (농협OK체크카드(개인)) 수집 완료

 59%|█████▉    | 1779/2999 [34:08<22:58,  1.13s/it]

[성공] 1780번 카드 (국고보조금 법인카드) 수집 완료

 59%|█████▉    | 1780/2999 [34:09<23:12,  1.14s/it]

[성공] 1781번 카드 (한국잡월드 카드의정석 POINT 주거래) 수집 완료

 59%|█████▉    | 1781/2999 [34:10<23:01,  1.13s/it]

[성공] 1782번 카드 (더 플래티넘 법인카드) 수집 완료

 59%|█████▉    | 1782/2999 [34:12<25:26,  1.25s/it]

[성공] 1783번 카드 (SC제일은행 라이프 삼성카드) 수집 완료

 59%|█████▉    | 1783/2999 [34:13<24:35,  1.21s/it]

[성공] 1784번 카드 (그린체크카드(전국형)) 수집 완료

 59%|█████▉    | 1784/2999 [34:14<23:54,  1.18s/it]

[성공] 1785번 카드 (SC제일은행 디지털 삼성카드) 수집 완료

 60%|█████▉    | 1785/2999 [34:15<23:22,  1.16s/it]

[성공] 1786번 카드 (국민연금증카드) 수집 완료

 60%|█████▉    | 1786/2999 [34:16<23:15,  1.15s/it]

[성공] 1787번 카드 (NU 후불하이패스) 수집 완료

 60%|█████▉    | 1787/2999 [34:17<23:03,  1.14s/it]

[성공] 1788번 카드 (SC제일은행 드라이브 삼성카드) 수집 완료

 60%|█████▉    | 1788/2999 [34:18<23:19,  1.16s/it]

[성공] 1789번 카드 (S-OIL화물복지50) 수집 완료

 60%|█████▉    | 1789/2999 [34:20<22:50,  1.13s/it]

[성공] 1790번 카드 (해피오토 롯데카드) 수집 완료

 60%|█████▉    | 1790/2999 [34:21<23:23,  1.16s/it]

[성공] 1791번 카드 (SC제일은행 데일리 삼성카드) 수집 완료

 60%|█████▉    | 1791/2999 [34:22<23:11,  1.15s/it]

[성공] 1792번 카드 (삼성카드 2+) 수집 완료

 60%|█████▉    | 1792/2999 [34:23<23:13,  1.15s/it]

[성공] 1793번 카드 (SC제일은행 삼성체크카드 YOUNG) 수집 완료

 60%|█████▉    | 1793/2999 [34:24<23:30,  1.17s/it]

[성공] 1794번 카드 (카드의정석 POINT 주거래) 수집 완료

 60%|█████▉    | 1794/2999 [34:25<23:37,  1.18s/it]

[성공] 1795번 카드 (롯데 법인카드) 수집 완료

 60%|█████▉    | 1795/2999 [34:27<24:43,  1.23s/it]

[성공] 1796번 카드 (카드의정석 화물복지카드) 수집 완료

 60%|█████▉    | 1796/2999 [34:28<25:24,  1.27s/it]

[성공] 1797번 카드 (SC제일은행 삼성체크카드 CASHBACK) 수집 완료

 60%|█████▉    | 1797/2999 [34:29<24:36,  1.23s/it]

[성공] 1798번 카드 (현대렌탈케어 롯데카드) 수집 완료

 60%|█████▉    | 1798/2999 [34:30<23:58,  1.20s/it]

[성공] 1799번 카드 (삼성전자 멤버십 BLUE B 삼성카드 BIZ) 수집 완료

 60%|█████▉    | 1799/2999 [34:32<23:39,  1.18s/it]

[성공] 1800번 카드 (이제너두 카드의정석 DISCOUNT) 수집 완료

 60%|██████    | 1800/2999 [34:33<23:31,  1.18s/it]

[성공] 1801번 카드 (롯데 오토빌 법인카드) 수집 완료

 60%|██████    | 1801/2999 [34:34<23:05,  1.16s/it]

[성공] 1802번 카드 (삼성에스마일카드) 수집 완료

 60%|██████    | 1802/2999 [34:35<22:51,  1.15s/it]

[성공] 1803번 카드 (국민연금증체크카드) 수집 완료

 60%|██████    | 1803/2999 [34:36<23:27,  1.18s/it]

[성공] 1804번 카드 (공무원연금체크카드(퇴직)(비씨)) 수집 완료

 60%|██████    | 1804/2999 [34:37<22:54,  1.15s/it]

[성공] 1805번 카드 (우리V카드-知(지)) 수집 완료

 60%|██████    | 1805/2999 [34:38<22:57,  1.15s/it]

[성공] 1806번 카드 (롯데 티타늄 법인카드) 수집 완료

 60%|██████    | 1806/2999 [34:40<22:32,  1.13s/it]

[성공] 1807번 카드 (LineageM 신한카드 체크) 수집 완료

 60%|██████    | 1807/2999 [34:41<23:43,  1.19s/it]

[성공] 1808번 카드 (공무원연금체크카드(재직)(비씨)) 수집 완료

 60%|██████    | 1808/2999 [34:42<23:17,  1.17s/it]

[성공] 1809번 카드 (카드의정석 UniMile CHECK) 수집 완료

 60%|██████    | 1809/2999 [34:44<26:29,  1.34s/it]

[Skip] 1810번 카드 정보가 존재하지 않습니다.

 60%|██████    | 1810/2999 [34:45<26:10,  1.32s/it]

[성공] 1811번 카드 (삼성생명 삼성시그니처카드) 수집 완료

 60%|██████    | 1811/2999 [34:46<25:28,  1.29s/it]

[성공] 1812번 카드 (SC제일은행 삼성체크카드 POINT) 수집 완료

 60%|██████    | 1812/2999 [34:47<24:26,  1.24s/it]

[성공] 1813번 카드 (POP New 우리V카드) 수집 완료

 60%|██████    | 1813/2999 [34:49<24:27,  1.24s/it]

[성공] 1814번 카드 (삼성생명 삼성시그니처카드 (포인트0.5%)) 수집 완료

 60%|██████    | 1814/2999 [34:50<25:09,  1.27s/it]

[Skip] 1815번 카드 정보가 존재하지 않습니다.

 61%|██████    | 1815/2999 [34:51<23:54,  1.21s/it]

[성공] 1816번 카드 (카드의정석 시니어플러스) 수집 완료

 61%|██████    | 1816/2999 [34:53<26:37,  1.35s/it]

[성공] 1817번 카드 (삼성생명 삼성시그니처카드 (포인트1%)) 수집 완료

 61%|██████    | 1817/2999 [34:54<26:11,  1.33s/it]

[성공] 1818번 카드 (카드의정석 삼성화재 당신에게 좋은보험) 수집 완료

 61%|██████    | 1818/2999 [34:55<25:00,  1.27s/it]

[성공] 1819번 카드 (메리츠다이렉트 롯데 포인트플러스카드) 수집 완료

 61%|██████    | 1819/2999 [34:56<24:00,  1.22s/it]

[성공] 1820번 카드 (삼성생명 삼성시그니처카드 (스카이패스)) 수집 완료

 61%|██████    | 1820/2999 [34:57<23:15,  1.18s/it]

[성공] 1821번 카드 (삼성생명 삼성시그니처카드 (아시아나)) 수집 완료

 61%|██████    | 1821/2999 [34:59<23:30,  1.20s/it]

[성공] 1822번 카드 (메가패스 롯데카드) 수집 완료

 61%|██████    | 1822/2999 [35:00<23:10,  1.18s/it]

[성공] 1823번 카드 (YES24 우리V카드 知) 수집 완료

 61%|██████    | 1823/2999 [35:01<22:35,  1.15s/it]

[성공] 1824번 카드 (더존 삼성비즈퍼스트카드) 수집 완료

 61%|██████    | 1824/2999 [35:02<22:40,  1.16s/it]

[성공] 1825번 카드 (외식가족공제 신한카드 Hi-point MyShop) 수집 완료

 61%|██████    | 1825/2999 [35:03<22:23,  1.14s/it]

[성공] 1826번 카드 (모네타 롯데포인트플러스 카드) 수집 완료

 61%|██████    | 1826/2999 [35:04<22:01,  1.13s/it]

[성공] 1827번 카드 (위즈위드 롯데카드) 수집 완료

 61%|██████    | 1827/2999 [35:05<21:55,  1.12s/it]

[성공] 1828번 카드 (쿠쿠 렌탈프리멤버십 우리카드) 수집 완료

 61%|██████    | 1828/2999 [35:06<21:49,  1.12s/it]

[성공] 1829번 카드 (바디프랜드 카드) 수집 완료

 61%|██████    | 1829/2999 [35:07<21:41,  1.11s/it]

[성공] 1830번 카드 (현대해상 오토인슈 롯데카드) 수집 완료

 61%|██████    | 1830/2999 [35:09<21:36,  1.11s/it]

[성공] 1831번 카드 (유니클로 롯데카드) 수집 완료

 61%|██████    | 1831/2999 [35:10<21:48,  1.12s/it]

[성공] 1832번 카드 (후불 하이패스 카드) 수집 완료

 61%|██████    | 1832/2999 [35:11<21:41,  1.11s/it]

[성공] 1833번 카드 (신한카드 미래설계 4Tune 체크) 수집 완료

 61%|██████    | 1833/2999 [35:12<21:42,  1.12s/it]

[성공] 1834번 카드 (신한카드 Change-Up 체크) 수집 완료

 61%|██████    | 1834/2999 [35:13<21:37,  1.11s/it]

[성공] 1835번 카드 (개인택시운송자사업자 신한카드 T-플러스) 수집 완료

 61%|██████    | 1835/2999 [35:14<21:32,  1.11s/it]

[성공] 1836번 카드 (디앤샵 롯데포인트플러스카드) 수집 완료

 61%|██████    | 1836/2999 [35:15<22:11,  1.15s/it]

[성공] 1837번 카드 (후이즈 DC카드) 수집 완료

 61%|██████▏   | 1837/2999 [35:16<21:56,  1.13s/it]

[성공] 1838번 카드 (매일경제 NEW우리V카드) 수집 완료

 61%|██████▏   | 1838/2999 [35:18<22:07,  1.14s/it]

[성공] 1839번 카드 (AIA생명 롯데 리얼체크카드) 수집 완료

 61%|██████▏   | 1839/2999 [35:19<21:58,  1.14s/it]

[성공] 1840번 카드 (AIA생명 롯데 리얼카드) 수집 완료

 61%|██████▏   | 1840/2999 [35:20<21:36,  1.12s/it]

[성공] 1841번 카드 (AXA다이렉트 프라임 롯데카드) 수집 완료

 61%|██████▏   | 1841/2999 [35:21<21:26,  1.11s/it]

[성공] 1842번 카드 (라비다 DC 플러스 롯데카드) 수집 완료

 61%|██████▏   | 1842/2999 [35:22<21:50,  1.13s/it]

[성공] 1843번 카드 (라츠 롯데카드) 수집 완료

 61%|██████▏   | 1843/2999 [35:23<22:10,  1.15s/it]

[성공] 1844번 카드 (B롯데카드) 수집 완료

 61%|██████▏   | 1844/2999 [35:24<21:57,  1.14s/it]

[성공] 1845번 카드 (APT 우리知카드) 수집 완료

 62%|██████▏   | 1845/2999 [35:26<23:00,  1.20s/it]

[성공] 1846번 카드 (부자되세요 홈쇼핑카드) 수집 완료

 62%|██████▏   | 1846/2999 [35:27<22:53,  1.19s/it]

[성공] 1847번 카드 (카드의정석 넥센타이어렌탈 우리카드) 수집 완료

 62%|██████▏   | 1847/2999 [35:28<22:23,  1.17s/it]

[성공] 1848번 카드 (롯데렌터카 신차장 우리카드) 수집 완료

 62%|██████▏   | 1848/2999 [35:29<22:02,  1.15s/it]

[성공] 1849번 카드 (더케이 손해보험 롯데카드) 수집 완료

 62%|██████▏   | 1849/2999 [35:30<21:47,  1.14s/it]

[성공] 1850번 카드 (데일리카드) 수집 완료

 62%|██████▏   | 1850/2999 [35:32<22:58,  1.20s/it]

[성공] 1851번 카드 (GS칼텍스 화물복지카드) 수집 완료

 62%|██████▏   | 1851/2999 [35:33<22:26,  1.17s/it]

[성공] 1852번 카드 (카드의정석 JVM) 수집 완료

 62%|██████▏   | 1852/2999 [35:34<23:44,  1.24s/it]

[성공] 1853번 카드 (맑은 우리 카드) 수집 완료

 62%|██████▏   | 1853/2999 [35:35<22:56,  1.20s/it]

[성공] 1854번 카드 (ALL 다모아카드) 수집 완료

 62%|██████▏   | 1854/2999 [35:36<22:35,  1.18s/it]

[성공] 1855번 카드 (우리사장님(Power)카드) 수집 완료

 62%|██████▏   | 1855/2999 [35:37<22:08,  1.16s/it]

[성공] 1856번 카드 (카드의정석 하이마트) 수집 완료

 62%|██████▏   | 1856/2999 [35:39<21:52,  1.15s/it]

[성공] 1857번 카드 (동부생명 롯데카드) 수집 완료

 62%|██████▏   | 1857/2999 [35:40<22:13,  1.17s/it]

[성공] 1858번 카드 (딜라이브 롯데카드) 수집 완료

 62%|██████▏   | 1858/2999 [35:41<22:05,  1.16s/it]

[성공] 1859번 카드 (OK캐쉬백 위비할인카드) 수집 완료

 62%|██████▏   | 1859/2999 [35:42<21:50,  1.15s/it]

[성공] 1860번 카드 (RAUME O) 수집 완료

 62%|██████▏   | 1860/2999 [35:43<21:31,  1.13s/it]

[성공] 1861번 카드 (롭스 롯데카드) 수집 완료

 62%|██████▏   | 1861/2999 [35:44<21:32,  1.14s/it]

[성공] 1862번 카드 (롭스 선불캐시비 롯데체크카드) 수집 완료

 62%|██████▏   | 1862/2999 [35:45<21:52,  1.15s/it]

[성공] 1863번 카드 (롯데 I♡Jeju 카드) 수집 완료

 62%|██████▏   | 1863/2999 [35:47<21:59,  1.16s/it]

[성공] 1864번 카드 (롯데 weekly 체크카드(경기도 청소년 교통비 지원)) 수집 완료

 62%|██████▏   | 1864/2999 [35:48<21:41,  1.15s/it]

[성공] 1865번 카드 (RAUME O (스카이패스)) 수집 완료

 62%|██████▏   | 1865/2999 [35:49<21:32,  1.14s/it]

[성공] 1866번 카드 (RAUME O (아시아나)) 수집 완료

 62%|██████▏   | 1866/2999 [35:50<21:19,  1.13s/it]

[성공] 1867번 카드 (교원 웰스 우리카드) 수집 완료

 62%|██████▏   | 1867/2999 [35:51<21:58,  1.16s/it]

[성공] 1868번 카드 (라이나생명 라서즐거운카드) 수집 완료

 62%|██████▏   | 1868/2999 [35:52<21:45,  1.15s/it]

[성공] 1869번 카드 (신세계 THE S VIP) 수집 완료

 62%|██████▏   | 1869/2999 [35:54<22:29,  1.19s/it]

[성공] 1870번 카드 (신세계 THE S PRESTIGE 삼성카드) 수집 완료

 62%|██████▏   | 1870/2999 [35:55<21:54,  1.16s/it]

[성공] 1871번 카드 (제일아쿠아포티 라서 즐거운카드) 수집 완료

 62%|██████▏   | 1871/2999 [35:56<21:43,  1.16s/it]

[성공] 1872번 카드 (새마을금고 삼성체크카드) 수집 완료

 62%|██████▏   | 1872/2999 [35:57<21:23,  1.14s/it]

[성공] 1873번 카드 (대림케어 라서즐거운카드) 수집 완료

 62%|██████▏   | 1873/2999 [35:58<21:38,  1.15s/it]

[성공] 1874번 카드 (코웨이 우리카드) 수집 완료

 62%|██████▏   | 1874/2999 [35:59<21:26,  1.14s/it]

[성공] 1875번 카드 (헬러라서 즐거운카드) 수집 완료

 63%|██████▎   | 1875/2999 [36:00<21:14,  1.13s/it]

[성공] 1876번 카드 (새마을금고 삼성애니패스포인트체크카드) 수집 완료

 63%|██████▎   | 1876/2999 [36:02<21:18,  1.14s/it]

[성공] 1877번 카드 (우리 YG 신용카드) 수집 완료

 63%|██████▎   | 1877/2999 [36:03<22:08,  1.18s/it]

[성공] 1878번 카드 (동양매직 우리카드) 수집 완료

 63%|██████▎   | 1878/2999 [36:04<22:00,  1.18s/it]

[성공] 1879번 카드 (삼성오토캐시백체크카드) 수집 완료

 63%|██████▎   | 1879/2999 [36:05<21:37,  1.16s/it]

[성공] 1880번 카드 (한샘 라서즐거운 카드) 수집 완료

 63%|██████▎   | 1880/2999 [36:06<21:11,  1.14s/it]

[성공] 1881번 카드 (코웨이 Slim할부 우리카드) 수집 완료

 63%|██████▎   | 1881/2999 [36:07<20:58,  1.13s/it]

[성공] 1882번 카드 (삼성스토어 삼성카드) 수집 완료

 63%|██████▎   | 1882/2999 [36:08<20:59,  1.13s/it]

[성공] 1883번 카드 (PAYCO taptap) 수집 완료

 63%|██████▎   | 1883/2999 [36:10<20:53,  1.12s/it]

[성공] 1884번 카드 (라이프파트너 삼성카드) 수집 완료

 63%|██████▎   | 1884/2999 [36:11<20:40,  1.11s/it]

[성공] 1885번 카드 (삼성카드 BIZ 6 V2) 수집 완료

 63%|██████▎   | 1885/2999 [36:12<20:33,  1.11s/it]

[성공] 1886번 카드 (삼성 리워즈 삼성카드 taptap) 수집 완료

 63%|██████▎   | 1886/2999 [36:13<20:25,  1.10s/it]

[성공] 1887번 카드 (넷마블 신한카드) 수집 완료

 63%|██████▎   | 1887/2999 [36:14<20:57,  1.13s/it]

[Skip] 1888번 카드 정보가 존재하지 않습니다.

 63%|██████▎   | 1888/2999 [36:15<20:35,  1.11s/it]

[성공] 1889번 카드 (Toss taptap S) 수집 완료

 63%|██████▎   | 1889/2999 [36:16<20:25,  1.10s/it]

[성공] 1890번 카드 (세이 우리카드) 수집 완료

 63%|██████▎   | 1890/2999 [36:17<20:26,  1.11s/it]

[성공] 1891번 카드 (Syrup n 11ST 우리카드) 수집 완료

 63%|██████▎   | 1891/2999 [36:18<20:22,  1.10s/it]

[성공] 1892번 카드 (Every Mall카드) 수집 완료

 63%|██████▎   | 1892/2999 [36:19<20:16,  1.10s/it]

[성공] 1893번 카드 (우리 전통시장 W카드) 수집 완료

 63%|██████▎   | 1893/2999 [36:21<20:23,  1.11s/it]

[성공] 1894번 카드 (위니아대우 스마트 우리카드) 수집 완료

 63%|██████▎   | 1894/2999 [36:22<20:20,  1.10s/it]

[성공] 1895번 카드 (일룸 스마트 우리카드) 수집 완료

 63%|██████▎   | 1895/2999 [36:23<20:16,  1.10s/it]

[성공] 1896번 카드 (한샘 스마트 우리카드) 수집 완료

 63%|██████▎   | 1896/2999 [36:24<20:17,  1.10s/it]

[성공] 1897번 카드 (NEW BS렌탈 우리카드) 수집 완료

 63%|██████▎   | 1897/2999 [36:25<21:00,  1.14s/it]

[성공] 1898번 카드 (현대 HCN 라서즐거운카드) 수집 완료

 63%|██████▎   | 1898/2999 [36:26<20:40,  1.13s/it]

[성공] 1899번 카드 (New LG전자 베스트샵 PLUS 신한카드) 수집 완료

 63%|██████▎   | 1899/2999 [36:28<21:54,  1.19s/it]

[성공] 1900번 카드 (Win.K 체크카드) 수집 완료

 63%|██████▎   | 1900/2999 [36:29<21:22,  1.17s/it]

[성공] 1901번 카드 (현대렌탈케어 우리카드) 수집 완료

 63%|██████▎   | 1901/2999 [36:30<20:57,  1.14s/it]

[성공] 1902번 카드 (삼성카드 BIZ 4 V2) 수집 완료

 63%|██████▎   | 1902/2999 [36:31<20:44,  1.13s/it]

[성공] 1903번 카드 (부자되세요 더마일리지 체크카드) 수집 완료

 63%|██████▎   | 1903/2999 [36:32<20:32,  1.12s/it]

[성공] 1904번 카드 (THE O V2 (포인트)) 수집 완료

 63%|██████▎   | 1904/2999 [36:33<20:20,  1.11s/it]

[성공] 1905번 카드 (THE O V2 (아시아나)) 수집 완료

 64%|██████▎   | 1905/2999 [36:34<20:10,  1.11s/it]

[성공] 1906번 카드 (후불하이패스카드(비씨)) 수집 완료

 64%|██████▎   | 1906/2999 [36:35<20:04,  1.10s/it]

[성공] 1907번 카드 (우체국 우리동네plus 체크카드) 수집 완료

 64%|██████▎   | 1907/2999 [36:36<19:54,  1.09s/it]

[성공] 1908번 카드 (THE 1) 수집 완료

 64%|██████▎   | 1908/2999 [36:38<20:27,  1.13s/it]

[성공] 1909번 카드 (THE 1 (스카이패스)) 수집 완료

 64%|██████▎   | 1909/2999 [36:39<20:21,  1.12s/it]

[성공] 1910번 카드 (Joy더함카드(비씨)) 수집 완료

 64%|██████▎   | 1910/2999 [36:40<21:35,  1.19s/it]

[성공] 1911번 카드 (할인더함카드(비씨)) 수집 완료

 64%|██████▎   | 1911/2999 [36:41<21:09,  1.17s/it]

[성공] 1912번 카드 (유안타 Stock+ 체크카드) 수집 완료

 64%|██████▍   | 1912/2999 [36:42<21:02,  1.16s/it]

[성공] 1913번 카드 (THE 1 BIZ) 수집 완료

 64%|██████▍   | 1913/2999 [36:43<20:41,  1.14s/it]

[성공] 1914번 카드 (포인트더함카드(비씨)) 수집 완료

 64%|██████▍   | 1914/2999 [36:44<20:27,  1.13s/it]

[성공] 1915번 카드 (채움 후불하이패스카드(비씨)) 수집 완료

 64%|██████▍   | 1915/2999 [36:46<20:07,  1.11s/it]

[성공] 1916번 카드 (YoungPro NH투자증권 카드) 수집 완료

 64%|██████▍   | 1916/2999 [36:47<20:01,  1.11s/it]

[성공] 1917번 카드 (하나로카드) 수집 완료

 64%|██████▍   | 1917/2999 [36:48<19:56,  1.11s/it]

[성공] 1918번 카드 (유안타 W-CMA 롯데체크카드) 수집 완료

 64%|██████▍   | 1918/2999 [36:49<19:56,  1.11s/it]

[성공] 1919번 카드 (유안타 W-CMA 캐시백 롯데카드) 수집 완료

 64%|██████▍   | 1919/2999 [36:50<19:50,  1.10s/it]

[성공] 1920번 카드 (유안타 W-CMA 포인트플러스 롯데카드) 수집 완료

 64%|██████▍   | 1920/2999 [36:51<19:46,  1.10s/it]

[성공] 1921번 카드 (야구사랑 체크카드(LG트윈스)) 수집 완료

 64%|██████▍   | 1921/2999 [36:52<19:50,  1.10s/it]

[Skip] 1922번 카드 정보가 존재하지 않습니다.

 64%|██████▍   | 1922/2999 [36:53<19:37,  1.09s/it]

[성공] 1923번 카드 (DC Plus 카드) 수집 완료

 64%|██████▍   | 1923/2999 [36:54<19:35,  1.09s/it]

[Skip] 1924번 카드 정보가 존재하지 않습니다.

 64%|██████▍   | 1924/2999 [36:55<19:27,  1.09s/it]

[성공] 1925번 카드 (야구사랑 체크카드(SK와이번스)) 수집 완료

 64%|██████▍   | 1925/2999 [36:57<19:42,  1.10s/it]

[성공] 1926번 카드 (E1 LPG 롯데카드) 수집 완료

 64%|██████▍   | 1926/2999 [36:58<20:43,  1.16s/it]

[성공] 1927번 카드 (야구사랑 체크카드(기아타이거즈)) 수집 완료

 64%|██████▍   | 1927/2999 [36:59<20:26,  1.14s/it]

[성공] 1928번 카드 (야구사랑 체크카드(넥센히어로즈)) 수집 완료

 64%|██████▍   | 1928/2999 [37:00<20:23,  1.14s/it]

[성공] 1929번 카드 (야구사랑 체크카드(삼성라이온즈)) 수집 완료

 64%|██████▍   | 1929/2999 [37:01<20:20,  1.14s/it]

[성공] 1930번 카드 (야구사랑 체크카드(한화이글스)) 수집 완료

 64%|██████▍   | 1930/2999 [37:02<20:18,  1.14s/it]

[성공] 1931번 카드 (어바웃 롯데카드) 수집 완료

 64%|██████▍   | 1931/2999 [37:04<21:22,  1.20s/it]

[성공] 1932번 카드 (E1 LPG 롯데 체크카드) 수집 완료

 64%|██████▍   | 1932/2999 [37:05<21:00,  1.18s/it]

[성공] 1933번 카드 (베스트파트너 법인카드) 수집 완료

 64%|██████▍   | 1933/2999 [37:06<20:37,  1.16s/it]

[성공] 1934번 카드 (레일플러스 포인트 롯데카드) 수집 완료

 64%|██████▍   | 1934/2999 [37:07<20:17,  1.14s/it]

[성공] 1935번 카드 (비즈니스 법인카드) 수집 완료

 65%|██████▍   | 1935/2999 [37:08<20:02,  1.13s/it]

[성공] 1936번 카드 (로열30 인피니트 카드) 수집 완료

 65%|██████▍   | 1936/2999 [37:09<19:55,  1.12s/it]

[성공] 1937번 카드 (아멕스 센츄리온 법인카드) 수집 완료

 65%|██████▍   | 1937/2999 [37:10<19:46,  1.12s/it]

[성공] 1938번 카드 (롯데 AUTO 세이브 카드) 수집 완료

 65%|██████▍   | 1938/2999 [37:11<19:49,  1.12s/it]

[성공] 1939번 카드 (우리은행 롯데 오토빌 법인카드) 수집 완료

 65%|██████▍   | 1939/2999 [37:13<19:48,  1.12s/it]

[성공] 1940번 카드 (스카이패스카드) 수집 완료

 65%|██████▍   | 1940/2999 [37:14<19:42,  1.12s/it]

[성공] 1941번 카드 (농업경영체크카드) 수집 완료

 65%|██████▍   | 1941/2999 [37:15<19:33,  1.11s/it]

[성공] 1942번 카드 (우편요금 결제전용 카드(우체국)) 수집 완료

 65%|██████▍   | 1942/2999 [37:16<19:30,  1.11s/it]

[성공] 1943번 카드 (아시아나클럽카드) 수집 완료

 65%|██████▍   | 1943/2999 [37:17<19:37,  1.11s/it]

[성공] 1944번 카드 (엘포인트카드(비씨)) 수집 완료

 65%|██████▍   | 1944/2999 [37:18<19:37,  1.12s/it]

[성공] 1945번 카드 (팜코 카드) 수집 완료

 65%|██████▍   | 1945/2999 [37:19<20:03,  1.14s/it]

[성공] 1946번 카드 (I-biz 팜코카드) 수집 완료

 65%|██████▍   | 1946/2999 [37:20<20:03,  1.14s/it]

[성공] 1947번 카드 (전기료 결제전용 카드(체크)) 수집 완료

 65%|██████▍   | 1947/2999 [37:22<19:44,  1.13s/it]

[성공] 1948번 카드 (청년농업희망카드(비씨)) 수집 완료

 65%|██████▍   | 1948/2999 [37:23<19:35,  1.12s/it]

[성공] 1949번 카드 (IBK 후불 하이패스 카드(개인)) 수집 완료

 65%|██████▍   | 1949/2999 [37:24<19:25,  1.11s/it]

[성공] 1950번 카드 (IBK 후불 하이패스 카드(기업)) 수집 완료

 65%|██████▌   | 1950/2999 [37:25<19:20,  1.11s/it]

[성공] 1951번 카드 (청년농업희망체크카드(비씨)) 수집 완료

 65%|██████▌   | 1951/2999 [37:26<19:13,  1.10s/it]

[성공] 1952번 카드 (충남 다자녀행복키움카드(신용)) 수집 완료

 65%|██████▌   | 1952/2999 [37:27<19:33,  1.12s/it]

[성공] 1953번 카드 (다이아몬드 법인카드) 수집 완료

 65%|██████▌   | 1953/2999 [37:28<19:30,  1.12s/it]

[성공] 1954번 카드 (롯데 뉴라인 골드 아멕스카드) 수집 완료

 65%|██████▌   | 1954/2999 [37:29<19:32,  1.12s/it]

[성공] 1955번 카드 (충남 다자녀행복키움카드(체크)) 수집 완료

 65%|██████▌   | 1955/2999 [37:30<19:26,  1.12s/it]

[성공] 1956번 카드 (롯데 뉴라인 아멕스카드) 수집 완료

 65%|██████▌   | 1956/2999 [37:32<19:21,  1.11s/it]

[성공] 1957번 카드 (롯데 비즈니스 체크 카드) 수집 완료

 65%|██████▌   | 1957/2999 [37:33<19:38,  1.13s/it]

[성공] 1958번 카드 (롯데 체크플러스 카드) 수집 완료

 65%|██████▌   | 1958/2999 [37:34<19:36,  1.13s/it]

[성공] 1959번 카드 (롯데마트 DC100 카드) 수집 완료

 65%|██████▌   | 1959/2999 [37:35<19:22,  1.12s/it]

[성공] 1960번 카드 (모두모아 체크카드) 수집 완료

 65%|██████▌   | 1960/2999 [37:36<19:15,  1.11s/it]

[성공] 1961번 카드 (S1카드) 수집 완료

 65%|██████▌   | 1961/2999 [37:37<19:35,  1.13s/it]

[성공] 1962번 카드 (휴먼라이프 S1 수협카드) 수집 완료

 65%|██████▌   | 1962/2999 [37:38<19:27,  1.13s/it]

[성공] 1963번 카드 (Real Zero 체크카드) 수집 완료

 65%|██████▌   | 1963/2999 [37:39<19:21,  1.12s/it]

[성공] 1964번 카드 (KDB Choice 하이브리드 카드) 수집 완료

 65%|██████▌   | 1964/2999 [37:41<19:25,  1.13s/it]

[성공] 1965번 카드 (KDB SAMSUNGCARD 4) 수집 완료

 66%|██████▌   | 1965/2999 [37:42<19:42,  1.14s/it]

[성공] 1966번 카드 (스마트36 우리카드) 수집 완료

 66%|██████▌   | 1966/2999 [37:43<19:30,  1.13s/it]

[성공] 1967번 카드 (BeV Ⅸ 대한항공 카드) 수집 완료

 66%|██████▌   | 1967/2999 [37:44<19:23,  1.13s/it]

[성공] 1968번 카드 (리마크 우리카드) 수집 완료

 66%|██████▌   | 1968/2999 [37:45<19:11,  1.12s/it]

[성공] 1969번 카드 (리워드W신용카드) 수집 완료

 66%|██████▌   | 1969/2999 [37:46<19:19,  1.13s/it]

[성공] 1970번 카드 (리워드W체크카드) 수집 완료

 66%|██████▌   | 1970/2999 [37:47<19:06,  1.11s/it]

[성공] 1971번 카드 (GOODSHOT카드) 수집 완료

 66%|██████▌   | 1971/2999 [37:48<18:58,  1.11s/it]

[성공] 1972번 카드 (쿠쿠 Slim(슬림)할부 우리카드) 수집 완료

 66%|██████▌   | 1972/2999 [37:50<18:53,  1.10s/it]

[성공] 1973번 카드 (딜라이트(Delight)카드) 수집 완료

 66%|██████▌   | 1973/2999 [37:51<18:50,  1.10s/it]

[성공] 1974번 카드 (Lady라온카드) 수집 완료

 66%|██████▌   | 1974/2999 [37:52<18:48,  1.10s/it]

[성공] 1975번 카드 (마블 체크카드(에이스플러스체크카드)) 수집 완료

 66%|██████▌   | 1975/2999 [37:53<19:19,  1.13s/it]

[성공] 1976번 카드 (NH올원 시럽카드) 수집 완료

 66%|██████▌   | 1976/2999 [37:54<19:08,  1.12s/it]

[성공] 1977번 카드 (SB 팝 체크카드) 수집 완료

 66%|██████▌   | 1977/2999 [37:55<19:02,  1.12s/it]

[성공] 1978번 카드 (NH올원 시럽체크카드) 수집 완료

 66%|██████▌   | 1978/2999 [37:56<18:56,  1.11s/it]

[성공] 1979번 카드 (SB 팝 플러스 체크카드) 수집 완료

 66%|██████▌   | 1979/2999 [37:57<18:46,  1.10s/it]

[성공] 1980번 카드 (LG전자 베스트렌탈 우리카드) 수집 완료

 66%|██████▌   | 1980/2999 [37:58<18:34,  1.09s/it]

[성공] 1981번 카드 (SK매직 우리카드) 수집 완료

 66%|██████▌   | 1981/2999 [38:00<18:55,  1.12s/it]

[성공] 1982번 카드 (NEW 코웨이 우리카드) 수집 완료

 66%|██████▌   | 1982/2999 [38:01<18:53,  1.11s/it]

[성공] 1983번 카드 (Save&Safe(세이브앤세이프)카드(비씨)) 수집 완료

 66%|██████▌   | 1983/2999 [38:02<18:48,  1.11s/it]

[성공] 1984번 카드 (동양생명 우리카드) 수집 완료

 66%|██████▌   | 1984/2999 [38:03<18:45,  1.11s/it]

[성공] 1985번 카드 (내가그린카드) 수집 완료

 66%|██████▌   | 1985/2999 [38:04<18:46,  1.11s/it]

[성공] 1986번 카드 (SK매직 슬림할부 우리카드) 수집 완료

 66%|██████▌   | 1986/2999 [38:05<19:17,  1.14s/it]

[성공] 1987번 카드 (롯데마트 롯데카드) 수집 완료

 66%|██████▋   | 1987/2999 [38:07<20:42,  1.23s/it]

[성공] 1988번 카드 (함께그린카드) 수집 완료

 66%|██████▋   | 1988/2999 [38:08<20:06,  1.19s/it]

[성공] 1989번 카드 (예다함 우리카드) 수집 완료

 66%|██████▋   | 1989/2999 [38:09<19:39,  1.17s/it]

[성공] 1990번 카드 (엉 카드) 수집 완료

 66%|██████▋   | 1990/2999 [38:10<19:27,  1.16s/it]

[성공] 1991번 카드 (BeV Ⅸ 토탈마일 카드) 수집 완료

 66%|██████▋   | 1991/2999 [38:11<19:17,  1.15s/it]

[성공] 1992번 카드 (청호나이스우리카드) 수집 완료

 66%|██████▋   | 1992/2999 [38:12<18:54,  1.13s/it]

[성공] 1993번 카드 (롯데백화점 AVENUEL 카드) 수집 완료

 66%|██████▋   | 1993/2999 [38:13<18:42,  1.12s/it]

[성공] 1994번 카드 (BS렌탈 우리카드) 수집 완료

 66%|██████▋   | 1994/2999 [38:14<18:38,  1.11s/it]

[성공] 1995번 카드 (LIME 체크카드) 수집 완료

 67%|██████▋   | 1995/2999 [38:15<18:27,  1.10s/it]

[성공] 1996번 카드 (NH올원 LG전자BEST카드) 수집 완료

 67%|██████▋   | 1996/2999 [38:17<18:34,  1.11s/it]

[성공] 1997번 카드 (프리드라이프 우리카드) 수집 완료

 67%|██████▋   | 1997/2999 [38:18<18:31,  1.11s/it]

[성공] 1998번 카드 (NH올원 NH저축은행카드) 수집 완료

 67%|██████▋   | 1998/2999 [38:19<18:34,  1.11s/it]

[성공] 1999번 카드 (바디프랜드 Slim(슬림)할부 우리카드) 수집 완료

 67%|██████▋   | 1999/2999 [38:20<18:40,  1.12s/it]

[성공] 2000번 카드 (롯데백화점 CLUB L 카드) 수집 완료

 67%|██████▋   | 2000/2999 [38:21<18:31,  1.11s/it]

[성공] 2001번 카드 (꿀카드) 수집 완료

 67%|██████▋   | 2001/2999 [38:22<19:01,  1.14s/it]

[성공] 2002번 카드 (DB손해보험 다이렉트 롯데카드) 수집 완료

 67%|██████▋   | 2002/2999 [38:23<19:05,  1.15s/it]

[성공] 2003번 카드 (E-POINT 롯데카드) 수집 완료

 67%|██████▋   | 2003/2999 [38:25<19:00,  1.14s/it]

[성공] 2004번 카드 (스마트 U 카드) 수집 완료

 67%|██████▋   | 2004/2999 [38:26<19:14,  1.16s/it]

[성공] 2005번 카드 (GS&POINT 롯데카드) 수집 완료

 67%|██████▋   | 2005/2999 [38:27<18:49,  1.14s/it]

[성공] 2006번 카드 (청호나이스 Slim할부 우리카드) 수집 완료

 67%|██████▋   | 2006/2999 [38:28<19:42,  1.19s/it]

[성공] 2007번 카드 (LG전자 라서즐거운 카드) 수집 완료

 67%|██████▋   | 2007/2999 [38:29<20:03,  1.21s/it]

[성공] 2008번 카드 (스마트리빙 코웨이 롯데카드) 수집 완료

 67%|██████▋   | 2008/2999 [38:31<19:51,  1.20s/it]

[성공] 2009번 카드 (I LOVE SEOUL 관리공단 나눔 롯데카드) 수집 완료

 67%|██████▋   | 2009/2999 [38:32<19:31,  1.18s/it]

[성공] 2010번 카드 (SKYPASS카드(비씨)) 수집 완료

 67%|██████▋   | 2010/2999 [38:33<20:05,  1.22s/it]

[성공] 2011번 카드 (I♥Busan 체크카드) 수집 완료

 67%|██████▋   | 2011/2999 [38:34<19:44,  1.20s/it]

[성공] 2012번 카드 (NH올원 NH투자증권체크카드) 수집 완료

 67%|██████▋   | 2012/2999 [38:35<19:25,  1.18s/it]

[성공] 2013번 카드 (I♥Busan 카드) 수집 완료

 67%|██████▋   | 2013/2999 [38:36<18:59,  1.16s/it]

[성공] 2014번 카드 (NH올원 NH투자증권카드) 수집 완료

 67%|██████▋   | 2014/2999 [38:38<19:03,  1.16s/it]

[성공] 2015번 카드 (TITANIUM(티타늄)카드(POINT)) 수집 완료

 67%|██████▋   | 2015/2999 [38:39<20:15,  1.23s/it]

[성공] 2016번 카드 (Jin Air - 롯데카드) 수집 완료

 67%|██████▋   | 2016/2999 [38:40<19:37,  1.20s/it]

[성공] 2017번 카드 (TITANIUM(티타늄)카드(SKYPASS)) 수집 완료

 67%|██████▋   | 2017/2999 [38:41<19:22,  1.18s/it]

[성공] 2018번 카드 (이가자헤어비스 롯데포인트플러스 카드) 수집 완료

 67%|██████▋   | 2018/2999 [38:43<20:12,  1.24s/it]

[성공] 2019번 카드 (NH올원 Rental&넥센타이어카드) 수집 완료

 67%|██████▋   | 2019/2999 [38:44<19:25,  1.19s/it]

[성공] 2020번 카드 (KT GiGA APT 롯데카드) 수집 완료

 67%|██████▋   | 2020/2999 [38:45<18:58,  1.16s/it]

[성공] 2021번 카드 (NH올원 Rental&바디프랜드카드) 수집 완료

 67%|██████▋   | 2021/2999 [38:46<18:34,  1.14s/it]

[성공] 2022번 카드 (LIKIT all 체크플러스 카드) 수집 완료

 67%|██████▋   | 2022/2999 [38:47<18:22,  1.13s/it]

[성공] 2023번 카드 (NH올원 Rental&코웨이카드) 수집 완료

 67%|██████▋   | 2023/2999 [38:48<18:25,  1.13s/it]

[성공] 2024번 카드 (LIKIT fun 체크플러스 카드) 수집 완료

 67%|██████▋   | 2024/2999 [38:49<18:10,  1.12s/it]

[성공] 2025번 카드 (LIKIT on 체크플러스 카드) 수집 완료

 68%|██████▊   | 2025/2999 [38:50<18:21,  1.13s/it]

[성공] 2026번 카드 (카카오페이 체크카드) 수집 완료

 68%|██████▊   | 2026/2999 [38:52<18:18,  1.13s/it]

[성공] 2027번 카드 (IBK-Syrup카드[체크]) 수집 완료

 68%|██████▊   | 2027/2999 [38:53<18:03,  1.12s/it]

[성공] 2028번 카드 (LOCA in BUSAN) 수집 완료

 68%|██████▊   | 2028/2999 [38:54<17:58,  1.11s/it]

[성공] 2029번 카드 (이베이옥션 롯데카드) 수집 완료

 68%|██████▊   | 2029/2999 [38:55<17:54,  1.11s/it]

[성공] 2030번 카드 (LOCA MONEY 비즈니스 카드) 수집 완료

 68%|██████▊   | 2030/2999 [38:56<17:55,  1.11s/it]

[성공] 2031번 카드 (에스케이(SK) 주유전용 기업카드) 수집 완료

 68%|██████▊   | 2031/2999 [38:57<17:55,  1.11s/it]

[성공] 2032번 카드 (주유전용 기업카드) 수집 완료

 68%|██████▊   | 2032/2999 [38:58<17:48,  1.10s/it]

[성공] 2033번 카드 (공공기관 클린카드 코퍼레이트) 수집 완료

 68%|██████▊   | 2033/2999 [38:59<17:42,  1.10s/it]

[성공] 2034번 카드 (롯데 Best Drive 포인트플러스카드) 수집 완료

 68%|██████▊   | 2034/2999 [39:00<17:43,  1.10s/it]

[성공] 2035번 카드 (IBK hi-pass&oil카드) 수집 완료

 68%|██████▊   | 2035/2999 [39:01<17:43,  1.10s/it]

[성공] 2036번 카드 (NH올원 Shopping&AMOREPACIFIC카드) 수집 완료

 68%|██████▊   | 2036/2999 [39:03<17:40,  1.10s/it]

[성공] 2037번 카드 (이유다이렉트 롯데포인트플러스카드) 수집 완료

 68%|██████▊   | 2037/2999 [39:04<17:52,  1.11s/it]

[성공] 2038번 카드 (동반성공카드) 수집 완료

 68%|██████▊   | 2038/2999 [39:05<18:11,  1.14s/it]

[성공] 2039번 카드 (인슈넷 롯데카드) 수집 완료

 68%|██████▊   | 2039/2999 [39:06<18:05,  1.13s/it]

[성공] 2040번 카드 (NH올원 Shopping&INTERPARK카드) 수집 완료

 68%|██████▊   | 2040/2999 [39:07<18:02,  1.13s/it]

[성공] 2041번 카드 (NH올원 Shopping&TLC카드) 수집 완료

 68%|██████▊   | 2041/2999 [39:09<19:49,  1.24s/it]

[성공] 2042번 카드 (Oh!Point 더블체크카드(비씨)) 수집 완료

 68%|██████▊   | 2042/2999 [39:10<20:02,  1.26s/it]

[Skip] 2043번 카드 정보가 존재하지 않습니다.

 68%|██████▊   | 2043/2999 [39:11<19:12,  1.21s/it]

[성공] 2044번 카드 (롯데 Two in One 카드) 수집 완료

 68%|██████▊   | 2044/2999 [39:12<18:51,  1.19s/it]

[성공] 2045번 카드 (인스니즈 롯데 포인트플러스 카드) 수집 완료

 68%|██████▊   | 2045/2999 [39:13<18:31,  1.17s/it]

[성공] 2046번 카드 (택시 운송사업자 법인카드) 수집 완료

 68%|██████▊   | 2046/2999 [39:14<18:10,  1.14s/it]

[성공] 2047번 카드 (일상의 기쁨 (주)자란다 제휴카드) 수집 완료

 68%|██████▊   | 2047/2999 [39:15<18:03,  1.14s/it]

[성공] 2048번 카드 (나의알파 국민연금안심 체크카드) 수집 완료

 68%|██████▊   | 2048/2999 [39:17<18:20,  1.16s/it]

[성공] 2049번 카드 (롯데렌터카 AUTO 카드) 수집 완료

 68%|██████▊   | 2049/2999 [39:18<18:15,  1.15s/it]

[성공] 2050번 카드 (한세대학교 나의알파 체크(TOP 포인트)) 수집 완료

 68%|██████▊   | 2050/2999 [39:19<19:01,  1.20s/it]

[성공] 2051번 카드 (나의알파 체크카드) 수집 완료

 68%|██████▊   | 2051/2999 [39:20<18:35,  1.18s/it]

[성공] 2052번 카드 (나의 알파 행복지킴이 체크카드) 수집 완료

 68%|██████▊   | 2052/2999 [39:21<18:09,  1.15s/it]

[성공] 2053번 카드 (롯데백화점 LENITH 카드) 수집 완료

 68%|██████▊   | 2053/2999 [39:23<18:21,  1.16s/it]

[성공] 2054번 카드 (PLATINUM(플래티늄)카드(MULTI)) 수집 완료

 68%|██████▊   | 2054/2999 [39:24<18:06,  1.15s/it]

[성공] 2055번 카드 (THE Fine 플래티늄 카드(대한항공)) 수집 완료

 69%|██████▊   | 2055/2999 [39:25<18:05,  1.15s/it]

[성공] 2056번 카드 (THE Fine 플래티늄 카드(아시아나클럽)) 수집 완료

 69%|██████▊   | 2056/2999 [39:26<18:36,  1.18s/it]

[성공] 2057번 카드 (Business Sky 기업카드) 수집 완료

 69%|██████▊   | 2057/2999 [39:27<18:45,  1.19s/it]

[성공] 2058번 카드 (참! 좋은 다이소카드(체크)) 수집 완료

 69%|██████▊   | 2058/2999 [39:29<19:24,  1.24s/it]

[성공] 2059번 카드 (롯데아울렛 롯데카드) 수집 완료

 69%|██████▊   | 2059/2999 [39:30<19:54,  1.27s/it]

[성공] 2060번 카드 (롯데체크카드) 수집 완료

 69%|██████▊   | 2060/2999 [39:31<20:10,  1.29s/it]

[성공] 2061번 카드 (AK IBK체크카드) 수집 완료

 69%|██████▊   | 2061/2999 [39:32<19:16,  1.23s/it]

[성공] 2062번 카드 (PLATINUM(플래티늄)카드(SKYPASS)) 수집 완료

 69%|██████▉   | 2062/2999 [39:34<18:59,  1.22s/it]

[성공] 2063번 카드 (PLATINUM(플래티늄)카드(Asiana Club)) 수집 완료

 69%|██████▉   | 2063/2999 [39:35<18:33,  1.19s/it]

[성공] 2064번 카드 (Premium Top(프리미엄탑)카드(비씨)) 수집 완료

 69%|██████▉   | 2064/2999 [39:36<18:04,  1.16s/it]

[성공] 2065번 카드 (롯데포인트플러스 하이브리드카드) 수집 완료

 69%|██████▉   | 2065/2999 [39:37<17:45,  1.14s/it]

[성공] 2066번 카드 ("안녕"카드(체크)) 수집 완료

 69%|██████▉   | 2066/2999 [39:38<17:31,  1.13s/it]

[성공] 2067번 카드 (메가 멤버스 롯데카드) 수집 완료

 69%|██████▉   | 2067/2999 [39:39<17:27,  1.12s/it]

[성공] 2068번 카드 (공무원연금카드(재직)(비씨)) 수집 완료

 69%|██████▉   | 2068/2999 [39:40<17:28,  1.13s/it]

[성공] 2069번 카드 (반디앤루니스 롯데카드) 수집 완료

 69%|██████▉   | 2069/2999 [39:41<17:35,  1.14s/it]

[성공] 2070번 카드 (뱅크샐러드 빨대카드) 수집 완료

 69%|██████▉   | 2070/2999 [39:43<17:32,  1.13s/it]

[성공] 2071번 카드 (삼성페이 롯데카드) 수집 완료

 69%|██████▉   | 2071/2999 [39:44<17:18,  1.12s/it]

[성공] 2072번 카드 (시장愛 체크카드) 수집 완료

 69%|██████▉   | 2072/2999 [39:45<17:08,  1.11s/it]

[성공] 2073번 카드 (청춘날다 체크카드) 수집 완료

 69%|██████▉   | 2073/2999 [39:46<16:59,  1.10s/it]

[성공] 2074번 카드 (ON˟WE BARE BEARS 체크카드) 수집 완료

 69%|██████▉   | 2074/2999 [39:47<16:58,  1.10s/it]

[성공] 2075번 카드 (WITH 체크카드) 수집 완료

 69%|██████▉   | 2075/2999 [39:48<17:03,  1.11s/it]

[성공] 2076번 카드 (WITH 후불교통 체크카드) 수집 완료

 69%|██████▉   | 2076/2999 [39:49<17:05,  1.11s/it]

[성공] 2077번 카드 (ON 체크카드) 수집 완료

 69%|██████▉   | 2077/2999 [39:50<17:12,  1.12s/it]

[성공] 2078번 카드 (ON 후불교통 체크카드) 수집 완료

 69%|██████▉   | 2078/2999 [39:51<17:10,  1.12s/it]

[성공] 2079번 카드 (부자되세요 홈쇼핑 체크카드) 수집 완료

 69%|██████▉   | 2079/2999 [39:52<17:09,  1.12s/it]

[성공] 2080번 카드 (PEACH 체크카드) 수집 완료

 69%|██████▉   | 2080/2999 [39:54<17:00,  1.11s/it]

[성공] 2081번 카드 (MINT 체크카드) 수집 완료

 69%|██████▉   | 2081/2999 [39:55<16:54,  1.10s/it]

[성공] 2082번 카드 (IN 체크카드) 수집 완료

 69%|██████▉   | 2082/2999 [39:56<17:03,  1.12s/it]

[성공] 2083번 카드 (ForU(油) 체크카드) 수집 완료

 69%|██████▉   | 2083/2999 [39:57<17:35,  1.15s/it]

[성공] 2084번 카드 (MG Life 체크카드) 수집 완료

 69%|██████▉   | 2084/2999 [39:59<19:15,  1.26s/it]

[성공] 2085번 카드 (MG Point 체크카드) 수집 완료

 70%|██████▉   | 2085/2999 [40:00<20:23,  1.34s/it]

[성공] 2086번 카드 (MG Point2 체크카드) 수집 완료

 70%|██████▉   | 2086/2999 [40:01<19:10,  1.26s/it]

[Skip] 2087번 카드 정보가 존재하지 않습니다.

 70%|██████▉   | 2087/2999 [40:02<18:18,  1.20s/it]

[성공] 2088번 카드 (롯데교통카드) 수집 완료

 70%|██████▉   | 2088/2999 [40:03<17:53,  1.18s/it]

[성공] 2089번 카드 (글로벌 페이(블루) 체크카드) 수집 완료

 70%|██████▉   | 2089/2999 [40:04<17:36,  1.16s/it]

[성공] 2090번 카드 (신한카드 The PREMIER GOLD EDITION (스카이패스)) 수집 완료

 70%|██████▉   | 2090/2999 [40:06<18:22,  1.21s/it]

[성공] 2091번 카드 (CLUB1카드 200) 수집 완료

 70%|██████▉   | 2091/2999 [40:07<18:41,  1.24s/it]

[성공] 2092번 카드 (다원 체크카드) 수집 완료

 70%|██████▉   | 2092/2999 [40:08<18:00,  1.19s/it]

[성공] 2093번 카드 (L.CLASS L60 (스카이패스형)) 수집 완료

 70%|██████▉   | 2093/2999 [40:09<18:13,  1.21s/it]

[성공] 2094번 카드 (카카오페이 체크카드) 수집 완료

 70%|██████▉   | 2094/2999 [40:11<17:40,  1.17s/it]

[성공] 2095번 카드 (CREAM 체크카드) 수집 완료

 70%|██████▉   | 2095/2999 [40:12<17:20,  1.15s/it]

[성공] 2096번 카드 (CREAM Hybrid 체크카드) 수집 완료

 70%|██████▉   | 2096/2999 [40:13<17:26,  1.16s/it]

[성공] 2097번 카드 (신한카드 The PREMIER GOLD EDITION (아시아나클럽)) 수집 완료

 70%|██████▉   | 2097/2999 [40:14<17:16,  1.15s/it]

[성공] 2098번 카드 (공무원연금카드(퇴직)(비씨)) 수집 완료

 70%|██████▉   | 2098/2999 [40:15<17:03,  1.14s/it]

[성공] 2099번 카드 (에코마일리지카드(비씨)) 수집 완료

 70%|██████▉   | 2099/2999 [40:16<16:53,  1.13s/it]

[성공] 2100번 카드 (New 경기 i-PLUS카드(신용)) 수집 완료

 70%|███████   | 2100/2999 [40:17<16:51,  1.13s/it]

[성공] 2101번 카드 (경남 아이다누리카드(신용)) 수집 완료

 70%|███████   | 2101/2999 [40:18<16:49,  1.12s/it]

[성공] 2102번 카드 (경남 아이다누리카드(체크)) 수집 완료

 70%|███████   | 2102/2999 [40:19<16:44,  1.12s/it]

[성공] 2103번 카드 (인천New아이모아카드(신용)) 수집 완료

 70%|███████   | 2103/2999 [40:21<16:39,  1.12s/it]

[성공] 2104번 카드 (L.CLASS L60 (L.POINT형)) 수집 완료

 70%|███████   | 2104/2999 [40:22<16:33,  1.11s/it]

[성공] 2105번 카드 (롯데면세점 롯데 아멕스 골드 카드) 수집 완료

 70%|███████   | 2105/2999 [40:23<16:35,  1.11s/it]

[성공] 2106번 카드 (L.CLASS L60 (아시아나클럽형)) 수집 완료

 70%|███████   | 2106/2999 [40:24<16:57,  1.14s/it]

[성공] 2107번 카드 (인천New아이모아카드(체크)) 수집 완료

 70%|███████   | 2107/2999 [40:25<16:46,  1.13s/it]

[성공] 2108번 카드 (인스니즈 롯데하이패스카드) 수집 완료

 70%|███████   | 2108/2999 [40:26<16:45,  1.13s/it]

[성공] 2109번 카드 (롯데닷컴 Smart PLUS 카드) 수집 완료

 70%|███████   | 2109/2999 [40:27<16:40,  1.12s/it]

[성공] 2110번 카드 (롯데 플래티넘 법인카드) 수집 완료

 70%|███████   | 2110/2999 [40:28<16:43,  1.13s/it]

[성공] 2111번 카드 (New제주아이사랑행복카드(신용)) 수집 완료

 70%|███████   | 2111/2999 [40:30<16:39,  1.13s/it]

[성공] 2112번 카드 (New제주아이사랑행복카드(체크)) 수집 완료

 70%|███████   | 2112/2999 [40:31<16:44,  1.13s/it]

[성공] 2113번 카드 (인터파크 롯데포인트플러스 카드) 수집 완료

 70%|███████   | 2113/2999 [40:32<16:47,  1.14s/it]

[성공] 2114번 카드 (인터파크 멤버스 체크카드) 수집 완료

 70%|███████   | 2114/2999 [40:33<16:38,  1.13s/it]

[성공] 2115번 카드 (일동후디스 롯데 아이랑카드) 수집 완료

 71%|███████   | 2115/2999 [40:34<16:28,  1.12s/it]

[성공] 2116번 카드 (일동후디스 롯데 포인트플러스 카드) 수집 완료

 71%|███████   | 2116/2999 [40:35<17:02,  1.16s/it]

[성공] 2117번 카드 (롯데 SKYPASS 플래티넘 법인카드) 수집 완료

 71%|███████   | 2117/2999 [40:36<16:46,  1.14s/it]

[성공] 2118번 카드 (아시아나 마일리지카드) 수집 완료

 71%|███████   | 2118/2999 [40:38<16:33,  1.13s/it]

[성공] 2119번 카드 (롯데 아시아나클럽 플래티넘 법인카드) 수집 완료

 71%|███████   | 2119/2999 [40:39<16:27,  1.12s/it]

[성공] 2120번 카드 (자유투어 롯데카드) 수집 완료

 71%|███████   | 2120/2999 [40:40<17:06,  1.17s/it]

[성공] 2121번 카드 (자이언츠 롯데카드) 수집 완료

 71%|███████   | 2121/2999 [40:41<16:48,  1.15s/it]

[성공] 2122번 카드 (J드라이빙카드) 수집 완료

 71%|███████   | 2122/2999 [40:42<17:15,  1.18s/it]

[성공] 2123번 카드 (재미나라 맘&데디 롯데카드) 수집 완료

 71%|███████   | 2123/2999 [40:43<17:00,  1.17s/it]

[성공] 2124번 카드 (강원 청년 카드(채움)) 수집 완료

 71%|███████   | 2124/2999 [40:45<16:48,  1.15s/it]

[성공] 2125번 카드 (삼성화재 다이렉트 롯데카드) 수집 완료

 71%|███████   | 2125/2999 [40:46<16:35,  1.14s/it]

[성공] 2126번 카드 (경남 청년드림카드) 수집 완료

 71%|███████   | 2126/2999 [40:47<16:45,  1.15s/it]

[성공] 2127번 카드 (JEJUJINI Air Money카드) 수집 완료

 71%|███████   | 2127/2999 [40:48<16:47,  1.16s/it]

[성공] 2128번 카드 (ON PLATINUM카드(스카이패스)) 수집 완료

 71%|███████   | 2128/2999 [40:49<17:06,  1.18s/it]

[성공] 2129번 카드 (세계자연유산 I♡Jeju 카드) 수집 완료

 71%|███████   | 2129/2999 [40:50<17:15,  1.19s/it]

[성공] 2130번 카드 (ON PLATINUM카드(아시아나클럽)) 수집 완료

 71%|███████   | 2130/2999 [40:52<17:06,  1.18s/it]

[성공] 2131번 카드 (ON PLATINUM카드(포인트)) 수집 완료

 71%|███████   | 2131/2999 [40:53<17:10,  1.19s/it]

[성공] 2132번 카드 (제주 삼다수카드(신용)) 수집 완료

 71%|███████   | 2132/2999 [40:54<17:00,  1.18s/it]

[성공] 2133번 카드 (롯데 하이마트 카드) 수집 완료

 71%|███████   | 2133/2999 [40:55<16:38,  1.15s/it]

[Skip] 2134번 카드 정보가 존재하지 않습니다.

 71%|███████   | 2134/2999 [40:56<16:16,  1.13s/it]

[성공] 2135번 카드 (롯데 트래블 패스 카드) 수집 완료

 71%|███████   | 2135/2999 [40:57<16:07,  1.12s/it]

[성공] 2136번 카드 (롯데 캐시비 플러스카드) 수집 완료

 71%|███████   | 2136/2999 [40:58<16:35,  1.15s/it]

[성공] 2137번 카드 (전북방송-롯데카드) 수집 완료

 71%|███████▏  | 2137/2999 [41:00<16:25,  1.14s/it]

[성공] 2138번 카드 (롯데 Smart Consumer 카드) 수집 완료

 71%|███████▏  | 2138/2999 [41:01<16:15,  1.13s/it]

[성공] 2139번 카드 (세븐일레븐 멤버쉽롯데카드) 수집 완료

 71%|███████▏  | 2139/2999 [41:02<16:10,  1.13s/it]

[성공] 2140번 카드 (쇼퍼홀릭 롯데홈쇼핑 롯데체크카드) 수집 완료

 71%|███████▏  | 2140/2999 [41:03<17:11,  1.20s/it]

[성공] 2141번 카드 (쇼퍼홀릭 롯데홈쇼핑 롯데카드) 수집 완료

 71%|███████▏  | 2141/2999 [41:05<17:42,  1.24s/it]

[성공] 2142번 카드 (쉐보레 오토 롯데카드) 수집 완료

 71%|███████▏  | 2142/2999 [41:06<17:02,  1.19s/it]

[성공] 2143번 카드 (쉐보레오토 체크카드) 수집 완료

 71%|███████▏  | 2143/2999 [41:07<16:52,  1.18s/it]

[성공] 2144번 카드 (쌍용자동차 AUTO 롯데카드) 수집 완료

 71%|███████▏  | 2144/2999 [41:08<17:01,  1.19s/it]

[성공] 2145번 카드 (에이스침대 스페셜 롯데카드) 수집 완료

 72%|███████▏  | 2145/2999 [41:09<16:40,  1.17s/it]

[성공] 2146번 카드 (웅진씽크빅 롯데카드) 수집 완료

 72%|███████▏  | 2146/2999 [41:10<16:54,  1.19s/it]

[성공] 2147번 카드 (위클리 VISA 롯데체크카드) 수집 완료

 72%|███████▏  | 2147/2999 [41:11<16:34,  1.17s/it]

[성공] 2148번 카드 (KCTV알뜰카드) 수집 완료

 72%|███████▏  | 2148/2999 [41:13<16:23,  1.16s/it]

[성공] 2149번 카드 (이랜드리테일 롯데카드) 수집 완료

 72%|███████▏  | 2149/2999 [41:14<16:18,  1.15s/it]

[성공] 2150번 카드 (국민행복카드) 수집 완료

 72%|███████▏  | 2150/2999 [41:15<16:16,  1.15s/it]

[성공] 2151번 카드 (제주그린카드) 수집 완료

 72%|███████▏  | 2151/2999 [41:16<16:22,  1.16s/it]

[성공] 2152번 카드 (지금샵 롯데카드) 수집 완료

 72%|███████▏  | 2152/2999 [41:17<16:12,  1.15s/it]

[성공] 2153번 카드 (제주교통복지카드) 수집 완료

 72%|███████▏  | 2153/2999 [41:19<17:01,  1.21s/it]

[성공] 2154번 카드 (캐시백 플러스 카드(교통+통신)) 수집 완료

 72%|███████▏  | 2154/2999 [41:20<17:09,  1.22s/it]

[성공] 2155번 카드 (캐시백 플러스 카드(백화점+마트)) 수집 완료

 72%|███████▏  | 2155/2999 [41:21<16:39,  1.18s/it]

[성공] 2156번 카드 (용인시민카드(체크)) 수집 완료

 72%|███████▏  | 2156/2999 [41:22<17:02,  1.21s/it]

[성공] 2157번 카드 (전자랜드 롯데카드) 수집 완료

 72%|███████▏  | 2157/2999 [41:23<17:27,  1.24s/it]

[성공] 2158번 카드 (정원 e샵 롯데카드) 수집 완료

 72%|███████▏  | 2158/2999 [41:25<16:49,  1.20s/it]

[성공] 2159번 카드 (롯데 Touch카드(스틱형)) 수집 완료

 72%|███████▏  | 2159/2999 [41:26<16:20,  1.17s/it]

[성공] 2160번 카드 (롯데 Touch카드(카드형)) 수집 완료

 72%|███████▏  | 2160/2999 [41:27<16:52,  1.21s/it]

[성공] 2161번 카드 (IBK 나의알파에듀카드) 수집 완료

 72%|███████▏  | 2161/2999 [41:28<16:55,  1.21s/it]

[성공] 2162번 카드 (제주항공 롯데카드) 수집 완료

 72%|███████▏  | 2162/2999 [41:29<16:33,  1.19s/it]

[성공] 2163번 카드 (롯데 VEEX 카드) 수집 완료

 72%|███████▏  | 2163/2999 [41:30<16:09,  1.16s/it]

[성공] 2164번 카드 (종가푸드샵 DC플러스카드) 수집 완료

 72%|███████▏  | 2164/2999 [41:32<16:05,  1.16s/it]

[성공] 2165번 카드 (제주삼다수 체크카드) 수집 완료

 72%|███████▏  | 2165/2999 [41:33<15:48,  1.14s/it]

[성공] 2166번 카드 (쥬비스 롯데포인트 플러스 카드) 수집 완료

 72%|███████▏  | 2166/2999 [41:34<15:53,  1.15s/it]

[성공] 2167번 카드 (천재교육 롯데카드) 수집 완료

 72%|███████▏  | 2167/2999 [41:35<15:39,  1.13s/it]

[성공] 2168번 카드 (청호나이스 롯데카드) 수집 완료

 72%|███████▏  | 2168/2999 [41:36<15:33,  1.12s/it]

[성공] 2169번 카드 (롯데 메가포인트 카드) 수집 완료

 72%|███████▏  | 2169/2999 [41:37<15:20,  1.11s/it]

[성공] 2170번 카드 (부자되세요 더마일리지카드) 수집 완료

 72%|███████▏  | 2170/2999 [41:38<15:19,  1.11s/it]

[성공] 2171번 카드 (인피니트 카드) 수집 완료

 72%|███████▏  | 2171/2999 [41:39<15:18,  1.11s/it]

[성공] 2172번 카드 (탐나는J체크카드) 수집 완료

 72%|███████▏  | 2172/2999 [41:41<15:47,  1.15s/it]

[성공] 2173번 카드 (국민행복체크카드) 수집 완료

 72%|███████▏  | 2173/2999 [41:42<16:29,  1.20s/it]

[성공] 2174번 카드 (제주그린체크카드) 수집 완료

 72%|███████▏  | 2174/2999 [41:43<16:16,  1.18s/it]

[성공] 2175번 카드 (SK OIL&LPG 카드) 수집 완료

 73%|███████▎  | 2175/2999 [41:44<15:54,  1.16s/it]

[성공] 2176번 카드 (내사랑 전주 카드) 수집 완료

 73%|███████▎  | 2176/2999 [41:45<15:31,  1.13s/it]

[성공] 2177번 카드 (1st Link On 카드) 수집 완료

 73%|███████▎  | 2177/2999 [41:46<15:19,  1.12s/it]

[성공] 2178번 카드 (1st TRIPLE 카드) 수집 완료

 73%|███████▎  | 2178/2999 [41:47<15:35,  1.14s/it]

[성공] 2179번 카드 (1st 카드(레드)) 수집 완료

 73%|███████▎  | 2179/2999 [41:49<15:37,  1.14s/it]

[성공] 2180번 카드 (1st TRIPLE Platinum 카드) 수집 완료

 73%|███████▎  | 2180/2999 [41:50<16:05,  1.18s/it]

[성공] 2181번 카드 (1st 플래티늄 카드) 수집 완료

 73%|███████▎  | 2181/2999 [41:51<16:19,  1.20s/it]

[성공] 2182번 카드 (롯데 모바일 플러스 카드) 수집 완료

 73%|███████▎  | 2182/2999 [41:52<17:04,  1.25s/it]

[성공] 2183번 카드 (1st 플래티늄+ 카드) 수집 완료

 73%|███████▎  | 2183/2999 [41:54<17:54,  1.32s/it]

[성공] 2184번 카드 (둘과넷 카드) 수집 완료

 73%|███████▎  | 2184/2999 [41:55<18:05,  1.33s/it]

[성공] 2185번 카드 (NEW AUTO+) 수집 완료

 73%|███████▎  | 2185/2999 [41:56<17:19,  1.28s/it]

[성공] 2186번 카드 (롯데 비즈니스 카드) 수집 완료

 73%|███████▎  | 2186/2999 [41:58<17:13,  1.27s/it]

[성공] 2187번 카드 (롯데 야구사랑 체크카드) 수집 완료

 73%|███████▎  | 2187/2999 [41:59<16:53,  1.25s/it]

[성공] 2188번 카드 (롯데 야구사랑카드) 수집 완료

 73%|███████▎  | 2188/2999 [42:00<17:15,  1.28s/it]

[성공] 2189번 카드 (1st TRIPLE 체크카드) 수집 완료

 73%|███████▎  | 2189/2999 [42:01<16:37,  1.23s/it]

[성공] 2190번 카드 (해피포인트 체크카드) 수집 완료

 73%|███████▎  | 2190/2999 [42:02<16:08,  1.20s/it]

[성공] 2191번 카드 (Smart Cashback 체크카드) 수집 완료

 73%|███████▎  | 2191/2999 [42:04<15:42,  1.17s/it]

[성공] 2192번 카드 (국민행복 체크카드) 수집 완료

 73%|███████▎  | 2192/2999 [42:05<15:29,  1.15s/it]

[성공] 2193번 카드 (유안타 CMA+ 체크카드) 수집 완료

 73%|███████▎  | 2193/2999 [42:06<15:17,  1.14s/it]

[성공] 2194번 카드 (유안타 Daily+ 체크카드) 수집 완료

 73%|███████▎  | 2194/2999 [42:07<15:34,  1.16s/it]

[성공] 2195번 카드 (Kia Members 신용카드 Edition2) 수집 완료

 73%|███████▎  | 2195/2999 [42:08<15:22,  1.15s/it]

[성공] 2196번 카드 (Kia Members 전기차 신용카드) 수집 완료

 73%|███████▎  | 2196/2999 [42:09<15:13,  1.14s/it]

[성공] 2197번 카드 (현대카드M CHECK-경차전용카드(유류세 환급)) 수집 완료

 73%|███████▎  | 2197/2999 [42:10<15:08,  1.13s/it]

[성공] 2198번 카드 (캐롯손해보험-현대카드M Edition3) 수집 완료

 73%|███████▎  | 2198/2999 [42:11<15:04,  1.13s/it]

[성공] 2199번 카드 (산림조합-현대카드M(청구할인형)) 수집 완료

 73%|███████▎  | 2199/2999 [42:13<14:59,  1.12s/it]

[성공] 2200번 카드 (카카오페이카드2) 수집 완료

 73%|███████▎  | 2200/2999 [42:14<15:00,  1.13s/it]

[Error] 2201번 카드 정보 요청 실패 (상태 코드: 502)

 73%|███████▎  | 2201/2999 [42:15<14:55,  1.12s/it]

[성공] 2202번 카드 (롯데 야구사랑카드(SK와이번스)) 수집 완료

 73%|███████▎  | 2202/2999 [42:16<16:04,  1.21s/it]

[성공] 2203번 카드 (롯데 야구사랑카드(기아타이거즈)) 수집 완료

 73%|███████▎  | 2203/2999 [42:17<15:51,  1.19s/it]

[성공] 2204번 카드 (롯데 야구사랑카드(넥센히어로즈)) 수집 완료

 73%|███████▎  | 2204/2999 [42:19<15:25,  1.16s/it]

[성공] 2205번 카드 (롯데 야구사랑카드(삼성라이온즈)) 수집 완료

 74%|███████▎  | 2205/2999 [42:20<15:11,  1.15s/it]

[성공] 2206번 카드 (롯데 야구사랑카드(한화이글스)) 수집 완료

 74%|███████▎  | 2206/2999 [42:21<15:36,  1.18s/it]

[성공] 2207번 카드 (롯데 엔크린 카드) 수집 완료

 74%|███████▎  | 2207/2999 [42:22<15:17,  1.16s/it]

[성공] 2208번 카드 (롯데 영플 체크 후불 교통카드) 수집 완료

 74%|███████▎  | 2208/2999 [42:23<15:07,  1.15s/it]

[성공] 2209번 카드 (롯데 캐시비 체크카드) 수집 완료

 74%|███████▎  | 2209/2999 [42:24<15:03,  1.14s/it]

[성공] 2210번 카드 (블랙핑크 카드) 수집 완료

 74%|███████▎  | 2210/2999 [42:25<15:05,  1.15s/it]

[성공] 2211번 카드 (케이뱅크 SIMPLE 카드) 수집 완료

 74%|███████▎  | 2211/2999 [42:27<16:20,  1.24s/it]

[성공] 2212번 카드 (챔피언 체크카드) 수집 완료

 74%|███████▍  | 2212/2999 [42:28<15:47,  1.20s/it]

[성공] 2213번 카드 (쏙쏙 체크카드) 수집 완료

 74%|███████▍  | 2213/2999 [42:29<15:19,  1.17s/it]

[성공] 2214번 카드 (Syrup Membership Wealth 마이카드(체크)) 수집 완료

 74%|███████▍  | 2214/2999 [42:30<14:57,  1.14s/it]

[성공] 2215번 카드 (LUNCH 체크카드) 수집 완료

 74%|███████▍  | 2215/2999 [42:31<14:51,  1.14s/it]

[성공] 2216번 카드 (미래에셋증권 체크카드(할인 2)) 수집 완료

 74%|███████▍  | 2216/2999 [42:32<14:38,  1.12s/it]

[성공] 2217번 카드 (미래에셋증권 체크카드 (캐시백 2)) 수집 완료

 74%|███████▍  | 2217/2999 [42:33<14:29,  1.11s/it]

[성공] 2218번 카드 (NAMUH 체크카드) 수집 완료

 74%|███████▍  | 2218/2999 [42:35<14:52,  1.14s/it]

[성공] 2219번 카드 (able 카드 Ⅱ) 수집 완료

 74%|███████▍  | 2219/2999 [42:36<14:45,  1.13s/it]

[성공] 2220번 카드 (DB금융투자 해피플러스 체크카드) 수집 완료

 74%|███████▍  | 2220/2999 [42:37<14:34,  1.12s/it]

[성공] 2221번 카드 (DB 캐쉬백 3.1 체크카드) 수집 완료

 74%|███████▍  | 2221/2999 [42:38<14:25,  1.11s/it]

[성공] 2222번 카드 (한국투자 the More 체크카드) 수집 완료

 74%|███████▍  | 2222/2999 [42:39<14:19,  1.11s/it]

[성공] 2223번 카드 (able 아이맥스카드) 수집 완료

 74%|███████▍  | 2223/2999 [42:40<14:15,  1.10s/it]

[성공] 2224번 카드 (able 시럽카드) 수집 완료

 74%|███████▍  | 2224/2999 [42:41<14:12,  1.10s/it]

[성공] 2225번 카드 (able Premier Members 카드) 수집 완료

 74%|███████▍  | 2225/2999 [42:42<14:11,  1.10s/it]

[성공] 2226번 카드 (카카오뱅크 롯데카드) 수집 완료

 74%|███████▍  | 2226/2999 [42:43<14:18,  1.11s/it]

[성공] 2227번 카드 (영리한 PLUS 체크카드) 수집 완료

 74%|███████▍  | 2227/2999 [42:45<14:57,  1.16s/it]

[성공] 2228번 카드 (LOCA LIKIT) 수집 완료

 74%|███████▍  | 2228/2999 [42:46<15:04,  1.17s/it]

[Skip] 2229번 카드 정보가 존재하지 않습니다.

 74%|███████▍  | 2229/2999 [42:47<14:39,  1.14s/it]

[성공] 2230번 카드 (LOCA 100 Life) 수집 완료

 74%|███████▍  | 2230/2999 [42:48<14:31,  1.13s/it]

[Skip] 2231번 카드 정보가 존재하지 않습니다.

 74%|███████▍  | 2231/2999 [42:49<14:22,  1.12s/it]

[성공] 2232번 카드 (1Q Daily+[40주년 에디션]) 수집 완료

 74%|███████▍  | 2232/2999 [42:51<14:53,  1.16s/it]

[성공] 2233번 카드 (네이버 현대카드) 수집 완료

 74%|███████▍  | 2233/2999 [42:52<14:44,  1.16s/it]

[성공] 2234번 카드 (삼성 iD ALL 카드) 수집 완료

 74%|███████▍  | 2234/2999 [42:53<15:07,  1.19s/it]

[성공] 2235번 카드 (삼성 iD ON 카드) 수집 완료

 75%|███████▍  | 2235/2999 [42:54<15:01,  1.18s/it]

[성공] 2236번 카드 (신한카드 My TeenS) 수집 완료

 75%|███████▍  | 2236/2999 [42:55<15:33,  1.22s/it]

[성공] 2237번 카드 (하나 스카이패스 아멕스 플래티늄 카드) 수집 완료

 75%|███████▍  | 2237/2999 [42:56<15:02,  1.18s/it]

[성공] 2238번 카드 (롯데월드카드) 수집 완료

 75%|███████▍  | 2238/2999 [42:58<15:56,  1.26s/it]

[Skip] 2239번 카드 정보가 존재하지 않습니다.

 75%|███████▍  | 2239/2999 [42:59<15:14,  1.20s/it]

[성공] 2240번 카드 (위버스 신한카드(BTS)) 수집 완료

 75%|███████▍  | 2240/2999 [43:00<15:47,  1.25s/it]

[성공] 2241번 카드 (Kakaopage 롯데카드) 수집 완료

 75%|███████▍  | 2241/2999 [43:01<15:14,  1.21s/it]

[성공] 2242번 카드 (에너지플러스카드 Edition2) 수집 완료

 75%|███████▍  | 2242/2999 [43:03<15:45,  1.25s/it]

[성공] 2243번 카드 (GS Prime 신한카드) 수집 완료

 75%|███████▍  | 2243/2999 [43:04<15:22,  1.22s/it]

[성공] 2244번 카드 (위버스 신한카드 체크(BTS)) 수집 완료

 75%|███████▍  | 2244/2999 [43:05<15:20,  1.22s/it]

[성공] 2245번 카드 (위버스 신한카드 체크(TXT)) 수집 완료

 75%|███████▍  | 2245/2999 [43:07<16:28,  1.31s/it]

[성공] 2246번 카드 (위버스 신한카드 체크(ENHYPEN)) 수집 완료

 75%|███████▍  | 2246/2999 [43:08<16:02,  1.28s/it]

[성공] 2247번 카드 (위버스 신한카드 체크(SEVENTEEN)) 수집 완료

 75%|███████▍  | 2247/2999 [43:09<15:57,  1.27s/it]

[성공] 2248번 카드 (위버스 신한카드(ENHYPEN)) 수집 완료

 75%|███████▍  | 2248/2999 [43:10<16:08,  1.29s/it]

[성공] 2249번 카드 (위버스 신한카드(SEVENTEEN)) 수집 완료

 75%|███████▍  | 2249/2999 [43:12<15:42,  1.26s/it]

[성공] 2250번 카드 (위버스 신한카드(TXT)) 수집 완료

 75%|███████▌  | 2250/2999 [43:13<16:09,  1.29s/it]

[성공] 2251번 카드 (오케이몰 우리카드) 수집 완료

 75%|███████▌  | 2251/2999 [43:14<15:52,  1.27s/it]

[성공] 2252번 카드 (NH1961카드) 수집 완료

 75%|███████▌  | 2252/2999 [43:16<15:52,  1.28s/it]

[성공] 2253번 카드 (SOHO 다사로이카드) 수집 완료

 75%|███████▌  | 2253/2999 [43:17<15:27,  1.24s/it]

[성공] 2254번 카드 (SOHO 다사로이+카드) 수집 완료

 75%|███████▌  | 2254/2999 [43:18<15:01,  1.21s/it]

[성공] 2255번 카드 (KB Pay 챌린지카드) 수집 완료

 75%|███████▌  | 2255/2999 [43:19<14:39,  1.18s/it]

[성공] 2256번 카드 (KB Pay 챌린지+카드) 수집 완료

 75%|███████▌  | 2256/2999 [43:20<14:19,  1.16s/it]

[성공] 2257번 카드 (삼성 모바일플러스카드) 수집 완료

 75%|███████▌  | 2257/2999 [43:21<14:44,  1.19s/it]

[성공] 2258번 카드 (#Pay 신한카드) 수집 완료

 75%|███████▌  | 2258/2999 [43:22<14:32,  1.18s/it]

[성공] 2259번 카드 (the Red Edition5) 수집 완료

 75%|███████▌  | 2259/2999 [43:24<14:41,  1.19s/it]

[성공] 2260번 카드 (the Green Edition2) 수집 완료

 75%|███████▌  | 2260/2999 [43:25<14:27,  1.17s/it]

[성공] 2261번 카드 (LOCA LIKIT 1.2) 수집 완료

 75%|███████▌  | 2261/2999 [43:26<14:17,  1.16s/it]

[성공] 2262번 카드 (LOCA LIKIT Eat) 수집 완료

 75%|███████▌  | 2262/2999 [43:29<19:28,  1.59s/it]

[성공] 2263번 카드 (LOCA LIKIT Play) 수집 완료

 75%|███████▌  | 2263/2999 [43:30<19:09,  1.56s/it]

[성공] 2264번 카드 (LOCA LIKIT Shop) 수집 완료

 75%|███████▌  | 2264/2999 [43:32<19:40,  1.61s/it]

[성공] 2265번 카드 (롯데홈쇼핑 벨리곰 카드) 수집 완료

 76%|███████▌  | 2265/2999 [43:34<20:08,  1.65s/it]

[성공] 2266번 카드 (NU Biz) 수집 완료

 76%|███████▌  | 2266/2999 [43:35<19:52,  1.63s/it]

[성공] 2267번 카드 (L.PAY 신한카드) 수집 완료

 76%|███████▌  | 2267/2999 [43:37<21:20,  1.75s/it]

[Skip] 2268번 카드 정보가 존재하지 않습니다.

 76%|███████▌  | 2268/2999 [43:38<18:55,  1.55s/it]

[성공] 2269번 카드 (토스뱅크 체크카드) 수집 완료

 76%|███████▌  | 2269/2999 [43:40<19:39,  1.62s/it]

[성공] 2270번 카드 (하나은행 밀리언달러 카드) 수집 완료

 76%|███████▌  | 2270/2999 [43:42<19:54,  1.64s/it]

[성공] 2271번 카드 (밸런스 카드) 수집 완료

 76%|███████▌  | 2271/2999 [43:43<19:37,  1.62s/it]

[성공] 2272번 카드 (신한 Meme(밈) 카드) 수집 완료

 76%|███████▌  | 2272/2999 [43:45<20:38,  1.70s/it]

[성공] 2273번 카드 (Indi-visual 카드(김계란카드)) 수집 완료

 76%|███████▌  | 2273/2999 [43:46<18:48,  1.55s/it]

[성공] 2274번 카드 (Indi-visual 카드(오은영카드)) 수집 완료

 76%|███████▌  | 2274/2999 [43:47<17:16,  1.43s/it]

[성공] 2275번 카드 (Indi-visual 카드(강형욱카드)) 수집 완료

 76%|███████▌  | 2275/2999 [43:49<16:49,  1.39s/it]

[성공] 2276번 카드 (Indi-visual 카드(임블리카드)) 수집 완료

 76%|███████▌  | 2276/2999 [43:50<16:11,  1.34s/it]

[성공] 2277번 카드 (요기패스 신용카드) 수집 완료

 76%|███████▌  | 2277/2999 [43:52<16:56,  1.41s/it]

[성공] 2278번 카드 (NS홈쇼핑 삼성카드) 수집 완료

 76%|███████▌  | 2278/2999 [43:53<17:01,  1.42s/it]

[성공] 2279번 카드 (신세계 아울렛 BENEFIT 삼성카드) 수집 완료

 76%|███████▌  | 2279/2999 [43:55<17:36,  1.47s/it]

[성공] 2280번 카드 (American Express The Platinum Card®) 수집 완료

 76%|███████▌  | 2280/2999 [43:56<18:32,  1.55s/it]

[성공] 2281번 카드 (American Express® Gold Card) 수집 완료

 76%|███████▌  | 2281/2999 [43:59<20:52,  1.74s/it]

[성공] 2282번 카드 (American Express® Green Card) 수집 완료

 76%|███████▌  | 2282/2999 [44:00<20:39,  1.73s/it]

[성공] 2283번 카드 (롯데렌터카 신차장 EV+ 우리카드) 수집 완료

 76%|███████▌  | 2283/2999 [44:01<18:41,  1.57s/it]

[성공] 2284번 카드 (EV카드) 수집 완료

 76%|███████▌  | 2284/2999 [44:03<17:00,  1.43s/it]

[성공] 2285번 카드 (Voluntas 자원봉사자 우리체크) 수집 완료

 76%|███████▌  | 2285/2999 [44:04<15:59,  1.34s/it]

[성공] 2286번 카드 (NU Uniq point) 수집 완료

 76%|███████▌  | 2286/2999 [44:05<15:10,  1.28s/it]

[성공] 2287번 카드 (현대카드 MX Black) 수집 완료

 76%|███████▋  | 2287/2999 [44:06<14:35,  1.23s/it]

[성공] 2288번 카드 (모두의 신세계 하나카드) 수집 완료

 76%|███████▋  | 2288/2999 [44:07<14:37,  1.23s/it]

[성공] 2289번 카드 (삼성 iD EV 카드) 수집 완료

 76%|███████▋  | 2289/2999 [44:08<14:16,  1.21s/it]

[성공] 2290번 카드 (삼성 iD ENERGY 카드) 수집 완료

 76%|███████▋  | 2290/2999 [44:09<13:57,  1.18s/it]

[성공] 2291번 카드 (메리어트 본보이™ 더 클래식 신한카드) 수집 완료

 76%|███████▋  | 2291/2999 [44:11<14:00,  1.19s/it]

[성공] 2292번 카드 (현대카드 MY BUSINESS ZERO Food&Drink) 수집 완료

 76%|███████▋  | 2292/2999 [44:12<13:51,  1.18s/it]

[성공] 2293번 카드 (현대카드 MY BUSINESS ZERO Retail&Service) 수집 완료

 76%|███████▋  | 2293/2999 [44:13<13:36,  1.16s/it]

[성공] 2294번 카드 (현대카드 MY BUSINESS ZERO Online Seller) 수집 완료

 76%|███████▋  | 2294/2999 [44:14<13:48,  1.18s/it]

[Skip] 2295번 카드 정보가 존재하지 않습니다.

 77%|███████▋  | 2295/2999 [44:15<13:24,  1.14s/it]

[성공] 2296번 카드 (톡톡M 카드) 수집 완료

 77%|███████▋  | 2296/2999 [44:16<13:19,  1.14s/it]

[성공] 2297번 카드 (톡톡F 카드) 수집 완료

 77%|███████▋  | 2297/2999 [44:17<13:21,  1.14s/it]

[성공] 2298번 카드 (톡톡O 카드) 수집 완료

 77%|███████▋  | 2298/2999 [44:19<13:23,  1.15s/it]

[성공] 2299번 카드 (톡톡D 카드) 수집 완료

 77%|███████▋  | 2299/2999 [44:20<13:20,  1.14s/it]

[성공] 2300번 카드 (내맘대로 쁨 카드) 수집 완료

 77%|███████▋  | 2300/2999 [44:21<13:17,  1.14s/it]

[성공] 2301번 카드 (원스토어 1 하나카드) 수집 완료

 77%|███████▋  | 2301/2999 [44:22<13:13,  1.14s/it]

[성공] 2302번 카드 (T우주 신한카드) 수집 완료

 77%|███████▋  | 2302/2999 [44:23<13:11,  1.13s/it]

[성공] 2303번 카드 (카카오페이카드3) 수집 완료

 77%|███████▋  | 2303/2999 [44:24<13:15,  1.14s/it]

[성공] 2304번 카드 (신한카드 Eats More(이츠모아)) 수집 완료

 77%|███████▋  | 2304/2999 [44:26<13:27,  1.16s/it]

[성공] 2305번 카드 (별다줄카드) 수집 완료

 77%|███████▋  | 2305/2999 [44:27<13:47,  1.19s/it]

[성공] 2306번 카드 (L.PAY by 롤라카드(신용)) 수집 완료

 77%|███████▋  | 2306/2999 [44:28<13:26,  1.16s/it]

[성공] 2307번 카드 (L.PAY by 롤라카드(체크)) 수집 완료

 77%|███████▋  | 2307/2999 [44:29<13:12,  1.15s/it]

[성공] 2308번 카드 (로스트아크 카드) 수집 완료

 77%|███████▋  | 2308/2999 [44:30<13:04,  1.13s/it]

[성공] 2309번 카드 (톡톡 구독카드) 수집 완료

 77%|███████▋  | 2309/2999 [44:31<12:58,  1.13s/it]

[성공] 2310번 카드 (PAYCO 포인트 카드) 수집 완료

 77%|███████▋  | 2310/2999 [44:32<12:55,  1.13s/it]

[성공] 2311번 카드 (럭키 더블카드) 수집 완료

 77%|███████▋  | 2311/2999 [44:33<12:56,  1.13s/it]

[성공] 2312번 카드 (럭키 유카드) 수집 완료

 77%|███████▋  | 2312/2999 [44:35<12:48,  1.12s/it]

[성공] 2313번 카드 (나마네카드) 수집 완료

 77%|███████▋  | 2313/2999 [44:36<12:43,  1.11s/it]

[성공] 2314번 카드 (토스유스카드(USS)) 수집 완료

 77%|███████▋  | 2314/2999 [44:37<13:11,  1.15s/it]

[성공] 2315번 카드 (한패스카드) 수집 완료

 77%|███████▋  | 2315/2999 [44:38<12:57,  1.14s/it]

[성공] 2316번 카드 (차이 신용카드) 수집 완료

 77%|███████▋  | 2316/2999 [44:39<14:02,  1.23s/it]

[성공] 2317번 카드 (차이 체크카드) 수집 완료

 77%|███████▋  | 2317/2999 [44:41<13:34,  1.19s/it]

[성공] 2318번 카드 (핀크카드) 수집 완료

 77%|███████▋  | 2318/2999 [44:42<13:16,  1.17s/it]

[성공] 2319번 카드 (다날-유니온페이 모바일카드) 수집 완료

 77%|███████▋  | 2319/2999 [44:43<12:59,  1.15s/it]

[성공] 2320번 카드 (트래블페이 충전카드) 수집 완료

 77%|███████▋  | 2320/2999 [44:44<13:21,  1.18s/it]

[성공] 2321번 카드 (모빌카드) 수집 완료

 77%|███████▋  | 2321/2999 [44:45<13:17,  1.18s/it]

[성공] 2322번 카드 (티니패스 카드) 수집 완료

 77%|███████▋  | 2322/2999 [44:46<13:24,  1.19s/it]

[성공] 2323번 카드 (아이부자 카드) 수집 완료

 77%|███████▋  | 2323/2999 [44:48<13:18,  1.18s/it]

[성공] 2324번 카드 (삼성 BIZ iD BENEFIT카드) 수집 완료

 77%|███████▋  | 2324/2999 [44:49<14:09,  1.26s/it]

[성공] 2325번 카드 (프레딧 하나카드) 수집 완료

 78%|███████▊  | 2325/2999 [44:50<14:01,  1.25s/it]

[성공] 2326번 카드 (해피포인트 해피리워드 카드) 수집 완료

 78%|███████▊  | 2326/2999 [44:51<13:39,  1.22s/it]

[성공] 2327번 카드 (스카이패스 티타늄 카드) 수집 완료

 78%|███████▊  | 2327/2999 [44:52<13:19,  1.19s/it]

[Skip] 2328번 카드 정보가 존재하지 않습니다.

 78%|███████▊  | 2328/2999 [44:54<12:56,  1.16s/it]

[성공] 2329번 카드 (핀트 카드) 수집 완료

 78%|███████▊  | 2329/2999 [44:55<12:47,  1.15s/it]

[성공] 2330번 카드 (LOCA 365 카드) 수집 완료

 78%|███████▊  | 2330/2999 [44:56<13:30,  1.21s/it]

[성공] 2331번 카드 (땡겨요 신한카드) 수집 완료

 78%|███████▊  | 2331/2999 [44:57<13:10,  1.18s/it]

[성공] 2332번 카드 (KB국민 우리동네 체크카드) 수집 완료

 78%|███████▊  | 2332/2999 [44:58<13:08,  1.18s/it]

[성공] 2333번 카드 (땡겨요 신한카드 체크) 수집 완료

 78%|███████▊  | 2333/2999 [45:00<13:23,  1.21s/it]

[성공] 2334번 카드 (땡겨요 신한카드 체크(라이더형)) 수집 완료

 78%|███████▊  | 2334/2999 [45:01<13:28,  1.22s/it]

[성공] 2335번 카드 (해피리워드 체크카드) 수집 완료

 78%|███████▊  | 2335/2999 [45:02<14:08,  1.28s/it]

[성공] 2336번 카드 (올바른지구 카드) 수집 완료

 78%|███████▊  | 2336/2999 [45:04<14:15,  1.29s/it]

[Skip] 2337번 카드 정보가 존재하지 않습니다.

 78%|███████▊  | 2337/2999 [45:05<13:33,  1.23s/it]

[성공] 2338번 카드 (신한카드 Way 체크) 수집 완료

 78%|███████▊  | 2338/2999 [45:06<13:13,  1.20s/it]

[성공] 2339번 카드 (CEO카드) 수집 완료

 78%|███████▊  | 2339/2999 [45:07<13:03,  1.19s/it]

[성공] 2340번 카드 (쇼핑& 카드) 수집 완료

 78%|███████▊  | 2340/2999 [45:08<13:06,  1.19s/it]

[Skip] 2341번 카드 정보가 존재하지 않습니다.

 78%|███████▊  | 2341/2999 [45:09<12:44,  1.16s/it]

[성공] 2342번 카드 (투썸플레이스 신한카드 체크) 수집 완료

 78%|███████▊  | 2342/2999 [45:10<12:50,  1.17s/it]

[성공] 2343번 카드 (신한카드 On 체크) 수집 완료

 78%|███████▊  | 2343/2999 [45:12<12:42,  1.16s/it]

[성공] 2344번 카드 (현대백화점카드) 수집 완료

 78%|███████▊  | 2344/2999 [45:13<12:33,  1.15s/it]

[성공] 2345번 카드 (현대백화점 Fit카드) 수집 완료

 78%|███████▊  | 2345/2999 [45:14<12:26,  1.14s/it]

[성공] 2346번 카드 (BC 바로 클리어 플러스) 수집 완료

 78%|███████▊  | 2346/2999 [45:15<12:26,  1.14s/it]

[성공] 2347번 카드 (BC 바로 리워드 플러스) 수집 완료

 78%|███████▊  | 2347/2999 [45:16<12:28,  1.15s/it]

[성공] 2348번 카드 (BC 바로 페이백 플러스) 수집 완료

 78%|███████▊  | 2348/2999 [45:17<12:28,  1.15s/it]

[성공] 2349번 카드 (모니모카드) 수집 완료

 78%|███████▊  | 2349/2999 [45:18<12:31,  1.16s/it]

[성공] 2350번 카드 (부자되세요 덤카드) 수집 완료

 78%|███████▊  | 2350/2999 [45:20<12:25,  1.15s/it]

[성공] 2351번 카드 (부자되세요 홈쇼핑카드) 수집 완료

 78%|███████▊  | 2351/2999 [45:21<13:25,  1.24s/it]

[성공] 2352번 카드 (&POP 카드) 수집 완료

 78%|███████▊  | 2352/2999 [45:22<13:01,  1.21s/it]

[성공] 2353번 카드 (NU Blanc) 수집 완료

 78%|███████▊  | 2353/2999 [45:23<12:45,  1.18s/it]

[성공] 2354번 카드 (NU Uniq) 수집 완료

 78%|███████▊  | 2354/2999 [45:25<13:05,  1.22s/it]

[성공] 2355번 카드 (레고랜드카드) 수집 완료

 79%|███████▊  | 2355/2999 [45:26<12:48,  1.19s/it]

[성공] 2356번 카드 (레고랜드 체크카드) 수집 완료

 79%|███████▊  | 2356/2999 [45:27<12:37,  1.18s/it]

[성공] 2357번 카드 (레고랜드매니아카드) 수집 완료

 79%|███████▊  | 2357/2999 [45:28<12:37,  1.18s/it]

[성공] 2358번 카드 (삼성 iD EDU 카드) 수집 완료

 79%|███████▊  | 2358/2999 [45:29<12:30,  1.17s/it]

[성공] 2359번 카드 (Hyundai Mobilty카드(상용차)) 수집 완료

 79%|███████▊  | 2359/2999 [45:30<12:14,  1.15s/it]

[성공] 2360번 카드 (LOCA in MEGACITY) 수집 완료

 79%|███████▊  | 2360/2999 [45:31<12:03,  1.13s/it]

[성공] 2361번 카드 (케이뱅크 롯데카드) 수집 완료

 79%|███████▊  | 2361/2999 [45:33<12:22,  1.16s/it]

[성공] 2362번 카드 (페이북 머니 체크카드) 수집 완료

 79%|███████▉  | 2362/2999 [45:34<12:18,  1.16s/it]

[성공] 2363번 카드 (wavve카드) 수집 완료

 79%|███████▉  | 2363/2999 [45:35<12:51,  1.21s/it]

[성공] 2364번 카드 (iD MOVE카드) 수집 완료

 79%|███████▉  | 2364/2999 [45:36<12:28,  1.18s/it]

[성공] 2365번 카드 (닥터구디 T&R(티앤알) 카드) 수집 완료

 79%|███████▉  | 2365/2999 [45:37<12:14,  1.16s/it]

[성공] 2366번 카드 (SOHO 다사로이OIL카드) 수집 완료

 79%|███████▉  | 2366/2999 [45:39<12:21,  1.17s/it]

[성공] 2367번 카드 (현대백화점 해피포인트카드) 수집 완료

 79%|███████▉  | 2367/2999 [45:40<13:19,  1.27s/it]

[성공] 2368번 카드 (현대백화점 현대오일뱅크카드) 수집 완료

 79%|███████▉  | 2368/2999 [45:41<13:00,  1.24s/it]

[성공] 2369번 카드 (Happy 디지털카드) 수집 완료

 79%|███████▉  | 2369/2999 [45:42<12:32,  1.19s/it]

[성공] 2370번 카드 (NU Uniq Check) 수집 완료

 79%|███████▉  | 2370/2999 [45:44<12:35,  1.20s/it]

[성공] 2371번 카드 (신한카드 플리) 수집 완료

 79%|███████▉  | 2371/2999 [45:45<12:46,  1.22s/it]

[성공] 2372번 카드 (신한카드 플리(체크)) 수집 완료

 79%|███████▉  | 2372/2999 [45:46<12:39,  1.21s/it]

[성공] 2373번 카드 (신한카드 On 체크(쥬라기)) 수집 완료

 79%|███████▉  | 2373/2999 [45:47<12:22,  1.19s/it]

[성공] 2374번 카드 (신한카드 Way 체크(쥬라기)) 수집 완료

 79%|███████▉  | 2374/2999 [45:48<12:15,  1.18s/it]

[Skip] 2375번 카드 정보가 존재하지 않습니다.

 79%|███████▉  | 2375/2999 [45:49<12:11,  1.17s/it]

[성공] 2376번 카드 (삼성 iD SIMPLE 카드) 수집 완료

 79%|███████▉  | 2376/2999 [45:51<12:13,  1.18s/it]

[성공] 2377번 카드 (톡톡 my point카드) 수집 완료

 79%|███████▉  | 2377/2999 [45:52<12:19,  1.19s/it]

[성공] 2378번 카드 (톡톡 my living카드) 수집 완료

 79%|███████▉  | 2378/2999 [45:53<12:06,  1.17s/it]

[성공] 2379번 카드 (신한카드 On 체크(잔망루피)) 수집 완료

 79%|███████▉  | 2379/2999 [45:54<12:22,  1.20s/it]

[성공] 2380번 카드 (신세계 BC 바로 콰트로 플러스) 수집 완료

 79%|███████▉  | 2380/2999 [45:55<12:02,  1.17s/it]

[성공] 2381번 카드 (신세계 BC 바로 아시아나 플러스) 수집 완료

 79%|███████▉  | 2381/2999 [45:56<11:54,  1.16s/it]

[성공] 2382번 카드 (신세계 BC 바로 리워드 플러스) 수집 완료

 79%|███████▉  | 2382/2999 [45:58<11:44,  1.14s/it]

[성공] 2383번 카드 (신세계 BC 바로 SEVEN FLEX) 수집 완료

 79%|███████▉  | 2383/2999 [45:59<11:43,  1.14s/it]

[성공] 2384번 카드 (신세계 BC 바로 클리어 플러스) 수집 완료

 79%|███████▉  | 2384/2999 [46:00<11:42,  1.14s/it]

[성공] 2385번 카드 (Flex카드 몽블랑 에디션) 수집 완료

 80%|███████▉  | 2385/2999 [46:01<11:38,  1.14s/it]

[성공] 2386번 카드 (티머니 Pay & GO 신한카드) 수집 완료

 80%|███████▉  | 2386/2999 [46:02<11:40,  1.14s/it]

[Skip] 2387번 카드 정보가 존재하지 않습니다.

 80%|███████▉  | 2387/2999 [46:03<11:27,  1.12s/it]

[성공] 2388번 카드 (넥슨 현대카드 UNLIMITED) 수집 완료

 80%|███████▉  | 2388/2999 [46:04<11:26,  1.12s/it]

[성공] 2389번 카드 (넥슨 현대카드) 수집 완료

 80%|███████▉  | 2389/2999 [46:06<12:13,  1.20s/it]

[성공] 2390번 카드 (넥슨 현대카드Check) 수집 완료

 80%|███████▉  | 2390/2999 [46:07<12:42,  1.25s/it]

[Skip] 2391번 카드 정보가 존재하지 않습니다.

 80%|███████▉  | 2391/2999 [46:08<12:16,  1.21s/it]

[성공] 2392번 카드 (CJ 삼성 iD 카드) 수집 완료

 80%|███████▉  | 2392/2999 [46:10<12:35,  1.25s/it]

[성공] 2393번 카드 (SSG.COM 카드 Edition2) 수집 완료

 80%|███████▉  | 2393/2999 [46:11<13:54,  1.38s/it]

[성공] 2394번 카드 (트래블로그 체크카드) 수집 완료

 80%|███████▉  | 2394/2999 [46:13<15:17,  1.52s/it]

[성공] 2395번 카드 (LOCA 나누기 카드) 수집 완료

 80%|███████▉  | 2395/2999 [46:14<14:54,  1.48s/it]

[성공] 2396번 카드 (Diners Club POINT) 수집 완료

 80%|███████▉  | 2396/2999 [46:16<15:47,  1.57s/it]

[성공] 2397번 카드 (Diners Club MILEAGE) 수집 완료

 80%|███████▉  | 2397/2999 [46:18<15:47,  1.57s/it]

[성공] 2398번 카드 (신세계 더 마일리지 삼성카드 (스카이패스)) 수집 완료

 80%|███████▉  | 2398/2999 [46:19<15:15,  1.52s/it]

[성공] 2399번 카드 (리브 NEXT카드) 수집 완료

 80%|███████▉  | 2399/2999 [46:21<14:52,  1.49s/it]

[성공] 2400번 카드 (밥바라밥 페이북머니 체크카드) 수집 완료

 80%|████████  | 2400/2999 [46:22<14:22,  1.44s/it]

[성공] 2401번 카드 (NU Nature) 수집 완료

 80%|████████  | 2401/2999 [46:23<14:32,  1.46s/it]

[성공] 2402번 카드 (GS리테일 NH농협카드) 수집 완료

 80%|████████  | 2402/2999 [46:25<14:08,  1.42s/it]

[성공] 2403번 카드 (NU I&U) 수집 완료

 80%|████████  | 2403/2999 [46:27<15:16,  1.54s/it]

[성공] 2404번 카드 (코오롱몰 우리카드) 수집 완료

 80%|████████  | 2404/2999 [46:28<15:32,  1.57s/it]

[성공] 2405번 카드 (#any 하나카드) 수집 완료

 80%|████████  | 2405/2999 [46:30<15:28,  1.56s/it]

[성공] 2406번 카드 (하나 CLUB H 아메리칸 익스프레스 리저브 카드) 수집 완료

 80%|████████  | 2406/2999 [46:31<15:50,  1.60s/it]

[성공] 2407번 카드 (삼성 iD PET 카드) 수집 완료

 80%|████████  | 2407/2999 [46:33<16:17,  1.65s/it]

[성공] 2408번 카드 (올바른HOMETOWN카드) 수집 완료

 80%|████████  | 2408/2999 [46:35<16:15,  1.65s/it]

[성공] 2409번 카드 (#MY WAY 카드) 수집 완료

 80%|████████  | 2409/2999 [46:36<15:34,  1.58s/it]

[성공] 2410번 카드 (New 제주항공 하나카드) 수집 완료

 80%|████████  | 2410/2999 [46:37<14:11,  1.45s/it]

[성공] 2411번 카드 (슈퍼쇼퍼카드) 수집 완료

 80%|████████  | 2411/2999 [46:39<13:23,  1.37s/it]

[성공] 2412번 카드 (아멕스 플래티넘 아시아나클럽 롯데카드) 수집 완료

 80%|████████  | 2412/2999 [46:40<12:48,  1.31s/it]

[Skip] 2413번 카드 정보가 존재하지 않습니다.

 80%|████████  | 2413/2999 [46:41<12:05,  1.24s/it]

[성공] 2414번 카드 (인플카 현대카드) 수집 완료

 80%|████████  | 2414/2999 [46:42<12:03,  1.24s/it]

[Skip] 2415번 카드 정보가 존재하지 않습니다.

 81%|████████  | 2415/2999 [46:43<11:34,  1.19s/it]

[성공] 2416번 카드 (이마트II KB국민카드(옐로우)) 수집 완료

 81%|████████  | 2416/2999 [46:44<11:24,  1.17s/it]

[성공] 2417번 카드 (인플카 현대카드 CHECK) 수집 완료

 81%|████████  | 2417/2999 [46:46<11:24,  1.18s/it]

[성공] 2418번 카드 (始發(시발)카드) 수집 완료

 81%|████████  | 2418/2999 [46:47<11:18,  1.17s/it]

[성공] 2419번 카드 (삼성 iD POCKET 카드) 수집 완료

 81%|████████  | 2419/2999 [46:48<11:10,  1.16s/it]

[성공] 2420번 카드 (카카오뱅크 개인사업자 삼성카드) 수집 완료

 81%|████████  | 2420/2999 [46:49<11:04,  1.15s/it]

[성공] 2421번 카드 (카카오뱅크 개인사업자 체크카드) 수집 완료

 81%|████████  | 2421/2999 [46:50<11:03,  1.15s/it]

[성공] 2422번 카드 (노리2 체크카드(KB Pay)) 수집 완료

 81%|████████  | 2422/2999 [46:51<11:05,  1.15s/it]

[성공] 2423번 카드 (노리2 체크카드(Global)) 수집 완료

 81%|████████  | 2423/2999 [46:53<11:39,  1.21s/it]

[성공] 2424번 카드 (LOCA X 구독) 수집 완료

 81%|████████  | 2424/2999 [46:54<11:17,  1.18s/it]

[성공] 2425번 카드 (MY 체크카드) 수집 완료

 81%|████████  | 2425/2999 [46:55<11:28,  1.20s/it]

[Skip] 2426번 카드 정보가 존재하지 않습니다.

 81%|████████  | 2426/2999 [46:56<11:20,  1.19s/it]

[성공] 2427번 카드 (zgm.the pay카드) 수집 완료

 81%|████████  | 2427/2999 [46:57<11:06,  1.17s/it]

[성공] 2428번 카드 (zgm.streaming카드) 수집 완료

 81%|████████  | 2428/2999 [46:58<10:55,  1.15s/it]

[성공] 2429번 카드 (삼프로TV 하나카드) 수집 완료

 81%|████████  | 2429/2999 [46:59<10:49,  1.14s/it]

[성공] 2430번 카드 (SC제일은행-현대카드 M CHECK) 수집 완료

 81%|████████  | 2430/2999 [47:01<10:40,  1.12s/it]

[성공] 2431번 카드 (SC제일은행-현대카드 X CHECK) 수집 완료

 81%|████████  | 2431/2999 [47:02<10:35,  1.12s/it]

[성공] 2432번 카드 (네이버페이 머니 하나 체크카드) 수집 완료

 81%|████████  | 2432/2999 [47:03<10:27,  1.11s/it]

[성공] 2433번 카드 (네이버페이 쇼핑엔로카) 수집 완료

 81%|████████  | 2433/2999 [47:04<10:26,  1.11s/it]

[성공] 2434번 카드 (갤러리아 KB국민카드) 수집 완료

 81%|████████  | 2434/2999 [47:05<10:26,  1.11s/it]

[성공] 2435번 카드 (신한카드 EVerywhere) 수집 완료

 81%|████████  | 2435/2999 [47:06<11:14,  1.20s/it]

[성공] 2436번 카드 (the Red Stripe) 수집 완료

 81%|████████  | 2436/2999 [47:07<11:06,  1.18s/it]

[성공] 2437번 카드 (GS리테일 NH농협체크카드) 수집 완료

 81%|████████▏ | 2437/2999 [47:09<11:00,  1.17s/it]

[성공] 2438번 카드 (IBK DC히어로즈 카드(체크)) 수집 완료

 81%|████████▏ | 2438/2999 [47:10<11:05,  1.19s/it]

[성공] 2439번 카드 (케이뱅크 Hi teen 카드) 수집 완료

 81%|████████▏ | 2439/2999 [47:11<10:51,  1.16s/it]

[성공] 2440번 카드 (KB ALL 카드) 수집 완료

 81%|████████▏ | 2440/2999 [47:12<10:41,  1.15s/it]

[성공] 2441번 카드 (KB국민 My WE:SH 카드) 수집 완료

 81%|████████▏ | 2441/2999 [47:13<10:43,  1.15s/it]

[성공] 2442번 카드 (KB국민 Our WE:SH 카드) 수집 완료

 81%|████████▏ | 2442/2999 [47:14<10:39,  1.15s/it]

[성공] 2443번 카드 (GOODGAME 체크카드) 수집 완료

 81%|████████▏ | 2443/2999 [47:15<10:30,  1.13s/it]

[성공] 2444번 카드 (롯데마트&MAXX 카드) 수집 완료

 81%|████████▏ | 2444/2999 [47:17<11:01,  1.19s/it]

[성공] 2445번 카드 (원더카드 2.0 DAILY) 수집 완료

 82%|████████▏ | 2445/2999 [47:18<10:49,  1.17s/it]

[성공] 2446번 카드 (원더카드 FREE) 수집 완료

 82%|████████▏ | 2446/2999 [47:19<10:39,  1.16s/it]

[성공] 2447번 카드 (원더카드 2.0 LIVING) 수집 완료

 82%|████████▏ | 2447/2999 [47:20<10:32,  1.15s/it]

[성공] 2448번 카드 (원더카드 HAPPY) 수집 완료

 82%|████████▏ | 2448/2999 [47:21<10:29,  1.14s/it]

[성공] 2449번 카드 (원더카드 2.0 T) 수집 완료

 82%|████████▏ | 2449/2999 [47:22<10:23,  1.13s/it]

[성공] 2450번 카드 (HERITAGE Smart [할인형]) 수집 완료

 82%|████████▏ | 2450/2999 [47:24<10:25,  1.14s/it]

[성공] 2451번 카드 (HERITAGE Smart [대한항공 마일리지형]) 수집 완료

 82%|████████▏ | 2451/2999 [47:25<10:25,  1.14s/it]

[성공] 2452번 카드 (카카오뱅크 하나카드) 수집 완료

 82%|████████▏ | 2452/2999 [47:26<10:25,  1.14s/it]

[성공] 2453번 카드 (신한카드 구독 좋아요) 수집 완료

 82%|████████▏ | 2453/2999 [47:27<10:25,  1.15s/it]

[성공] 2454번 카드 (트리플카드) 수집 완료

 82%|████████▏ | 2454/2999 [47:28<10:27,  1.15s/it]

[성공] 2455번 카드 (카카오뱅크 우리카드) 수집 완료

 82%|████████▏ | 2455/2999 [47:29<10:18,  1.14s/it]

[성공] 2456번 카드 (토스뱅크 모임카드) 수집 완료

 82%|████████▏ | 2456/2999 [47:30<10:14,  1.13s/it]

[성공] 2457번 카드 (캐롯손해보험 롯데카드) 수집 완료

 82%|████████▏ | 2457/2999 [47:32<10:20,  1.14s/it]

[성공] 2458번 카드 (BC 바로 에어 플러스 스카이패스) 수집 완료

 82%|████████▏ | 2458/2999 [47:33<10:11,  1.13s/it]

[성공] 2459번 카드 (삼성 iD NOMAD 카드) 수집 완료

 82%|████████▏ | 2459/2999 [47:34<10:06,  1.12s/it]

[성공] 2460번 카드 (THE iD. PLATINUM(포인트)) 수집 완료

 82%|████████▏ | 2460/2999 [47:35<10:11,  1.13s/it]

[성공] 2461번 카드 (THE iD. TITANIUM(포인트)) 수집 완료

 82%|████████▏ | 2461/2999 [47:36<10:19,  1.15s/it]

[성공] 2462번 카드 (신세계 푸빌라 BC바로카드) 수집 완료

 82%|████████▏ | 2462/2999 [47:37<10:10,  1.14s/it]

[성공] 2463번 카드 (LOCA Mobility 반띵 카드) 수집 완료

 82%|████████▏ | 2463/2999 [47:38<10:03,  1.13s/it]

[성공] 2464번 카드 (zgm.휴가중카드) 수집 완료

 82%|████████▏ | 2464/2999 [47:39<10:09,  1.14s/it]

[성공] 2465번 카드 (신세계 the Mile 하나카드) 수집 완료

 82%|████████▏ | 2465/2999 [47:41<10:02,  1.13s/it]

[성공] 2466번 카드 (이디야 하나카드) 수집 완료

 82%|████████▏ | 2466/2999 [47:42<09:55,  1.12s/it]

[성공] 2467번 카드 (신한카드 알뜰More(알뜰모아)) 수집 완료

 82%|████████▏ | 2467/2999 [47:43<09:53,  1.12s/it]

[성공] 2468번 카드 (KMVNO 알뜰폰 카드) 수집 완료

 82%|████████▏ | 2468/2999 [47:44<09:47,  1.11s/it]

[성공] 2469번 카드 (나무 롯데카드) 수집 완료

 82%|████████▏ | 2469/2999 [47:45<09:56,  1.13s/it]

[성공] 2470번 카드 (TRADERS CLUB 삼성카드) 수집 완료

 82%|████████▏ | 2470/2999 [47:46<09:49,  1.11s/it]

[성공] 2471번 카드 (신한카드 Way 체크(최고심)) 수집 완료

 82%|████████▏ | 2471/2999 [47:47<09:50,  1.12s/it]

[성공] 2472번 카드 (SKT-현대카드M Edition3(라이트할부형2.0)) 수집 완료

 82%|████████▏ | 2472/2999 [47:48<09:51,  1.12s/it]

[성공] 2473번 카드 (MY RENTAL+ 롯데카드) 수집 완료

 82%|████████▏ | 2473/2999 [47:49<09:45,  1.11s/it]

[성공] 2474번 카드 (T-economy KB국민카드) 수집 완료

 82%|████████▏ | 2474/2999 [47:51<09:43,  1.11s/it]

[성공] 2475번 카드 (하나로 전자카드 메가캐쉬백 더드림 체크카드) 수집 완료

 83%|████████▎ | 2475/2999 [47:52<09:37,  1.10s/it]

[성공] 2476번 카드 (NU AUTO 우리카드) 수집 완료

 83%|████████▎ | 2476/2999 [47:53<09:45,  1.12s/it]

[성공] 2477번 카드 (T나는혜택 삼성카드) 수집 완료

 83%|████████▎ | 2477/2999 [47:54<09:45,  1.12s/it]

[Skip] 2478번 카드 정보가 존재하지 않습니다.

 83%|████████▎ | 2478/2999 [47:55<09:38,  1.11s/it]

[성공] 2479번 카드 (제주신화월드 신한카드) 수집 완료

 83%|████████▎ | 2479/2999 [47:56<09:54,  1.14s/it]

[성공] 2480번 카드 (수소차 충전할인 신한카드) 수집 완료

 83%|████████▎ | 2480/2999 [47:58<10:41,  1.24s/it]

[성공] 2481번 카드 (신한 햇살론카드) 수집 완료

 83%|████████▎ | 2481/2999 [47:59<10:22,  1.20s/it]

[성공] 2482번 카드 (I-ALL) 수집 완료

 83%|████████▎ | 2482/2999 [48:00<10:04,  1.17s/it]

[성공] 2483번 카드 (IBK DC히어로즈 카드(신용)) 수집 완료

 83%|████████▎ | 2483/2999 [48:01<09:50,  1.14s/it]

[성공] 2484번 카드 (kt SUPER+ 카드) 수집 완료

 83%|████████▎ | 2484/2999 [48:02<09:38,  1.12s/it]

[성공] 2485번 카드 (kt SUPER 카드) 수집 완료

 83%|████████▎ | 2485/2999 [48:03<09:31,  1.11s/it]

[성공] 2486번 카드 (LFmall 신용카드) 수집 완료

 83%|████████▎ | 2486/2999 [48:04<09:34,  1.12s/it]

[성공] 2487번 카드 (CGV 우리카드) 수집 완료

 83%|████████▎ | 2487/2999 [48:05<09:41,  1.14s/it]

[성공] 2488번 카드 (베베쿡 신한카드) 수집 완료

 83%|████████▎ | 2488/2999 [48:07<09:58,  1.17s/it]

[성공] 2489번 카드 (K-FIRST (모바일전용)) 수집 완료

 83%|████████▎ | 2489/2999 [48:08<09:51,  1.16s/it]

[성공] 2490번 카드 (나무 NH농협카드) 수집 완료

 83%|████████▎ | 2490/2999 [48:09<09:50,  1.16s/it]

[성공] 2491번 카드 (신한카드 플리(산리오캐릭터즈)) 수집 완료

 83%|████████▎ | 2491/2999 [48:10<09:52,  1.17s/it]

[성공] 2492번 카드 (신한카드 플리 체크(산리오캐릭터즈)) 수집 완료

 83%|████████▎ | 2492/2999 [48:11<09:46,  1.16s/it]

[성공] 2493번 카드 (zgm.rounding카드) 수집 완료

 83%|████████▎ | 2493/2999 [48:12<09:37,  1.14s/it]

[성공] 2494번 카드 (H.Point 우리카드) 수집 완료

 83%|████████▎ | 2494/2999 [48:14<09:30,  1.13s/it]

[성공] 2495번 카드 (신세계 The BLOSSOM 신한카드) 수집 완료

 83%|████████▎ | 2495/2999 [48:15<09:42,  1.16s/it]

[성공] 2496번 카드 (신세계사이먼 프리미엄 아울렛 신한카드) 수집 완료

 83%|████████▎ | 2496/2999 [48:16<09:35,  1.14s/it]

[성공] 2497번 카드 (LG BEST SHOP 486 신한카드) 수집 완료

 83%|████████▎ | 2497/2999 [48:17<09:25,  1.13s/it]

[Skip] 2498번 카드 정보가 존재하지 않습니다.

 83%|████████▎ | 2498/2999 [48:18<09:16,  1.11s/it]

[Skip] 2499번 카드 정보가 존재하지 않습니다.

 83%|████████▎ | 2499/2999 [48:19<09:19,  1.12s/it]

[Skip] 2500번 카드 정보가 존재하지 않습니다.

 83%|████████▎ | 2500/2999 [48:20<09:10,  1.10s/it]

[성공] 2501번 카드 (부자되세요 The Oil 카드) 수집 완료

 83%|████████▎ | 2501/2999 [48:21<09:08,  1.10s/it]

[성공] 2502번 카드 (UPTURN카드) 수집 완료

 83%|████████▎ | 2502/2999 [48:23<09:20,  1.13s/it]

[성공] 2503번 카드 (키자니아 에듀카드) 수집 완료

 83%|████████▎ | 2503/2999 [48:24<09:16,  1.12s/it]

[성공] 2504번 카드 (팟(pod) 카드) 수집 완료

 83%|████████▎ | 2504/2999 [48:25<09:31,  1.15s/it]

[성공] 2505번 카드 (오늘은e 신용카드) 수집 완료

 84%|████████▎ | 2505/2999 [48:26<09:30,  1.15s/it]

[성공] 2506번 카드 (오늘은e 체크카드) 수집 완료

 84%|████████▎ | 2506/2999 [48:27<09:26,  1.15s/it]

[성공] 2507번 카드 (2030 언택트 체크카드) 수집 완료

 84%|████████▎ | 2507/2999 [48:28<09:18,  1.13s/it]

[성공] 2508번 카드 (올유닛 체크카드) 수집 완료

 84%|████████▎ | 2508/2999 [48:29<09:12,  1.12s/it]

[성공] 2509번 카드 (에어머니 체크카드) 수집 완료

 84%|████████▎ | 2509/2999 [48:30<09:07,  1.12s/it]

[성공] 2510번 카드 (미타임 체크카드) 수집 완료

 84%|████████▎ | 2510/2999 [48:32<09:24,  1.15s/it]

[성공] 2511번 카드 (신한카드 봄) 수집 완료

 84%|████████▎ | 2511/2999 [48:33<09:14,  1.14s/it]

[성공] 2512번 카드 (신한카드 봄(체크)) 수집 완료

 84%|████████▍ | 2512/2999 [48:34<09:13,  1.14s/it]

[성공] 2513번 카드 (zgm.고향으로카드) 수집 완료

 84%|████████▍ | 2513/2999 [48:35<09:17,  1.15s/it]

[성공] 2514번 카드 (미래에셋 현대카드 Silver) 수집 완료

 84%|████████▍ | 2514/2999 [48:36<09:13,  1.14s/it]

[성공] 2515번 카드 (미래에셋 현대카드 Gold) 수집 완료

 84%|████████▍ | 2515/2999 [48:37<09:09,  1.13s/it]

[성공] 2516번 카드 (미래에셋 현대카드 Diamond) 수집 완료

 84%|████████▍ | 2516/2999 [48:38<09:04,  1.13s/it]

[성공] 2517번 카드 (네이버웹툰 삼성 iD 카드) 수집 완료

 84%|████████▍ | 2517/2999 [48:40<09:00,  1.12s/it]

[성공] 2518번 카드 (컬리카드) 수집 완료

 84%|████████▍ | 2518/2999 [48:41<08:58,  1.12s/it]

[성공] 2519번 카드 (개이득 체크카드) 수집 완료

 84%|████████▍ | 2519/2999 [48:42<08:53,  1.11s/it]

[Skip] 2520번 카드 정보가 존재하지 않습니다.

 84%|████████▍ | 2520/2999 [48:43<08:45,  1.10s/it]

[성공] 2521번 카드 (NOL 카드) 수집 완료

 84%|████████▍ | 2521/2999 [48:44<08:45,  1.10s/it]

[성공] 2522번 카드 (KT NU우리카드) 수집 완료

 84%|████████▍ | 2522/2999 [48:45<08:41,  1.09s/it]

[성공] 2523번 카드 (LG U+ 우리카드) 수집 완료

 84%|████████▍ | 2523/2999 [48:46<08:44,  1.10s/it]

[Skip] 2524번 카드 정보가 존재하지 않습니다.

 84%|████████▍ | 2524/2999 [48:47<08:37,  1.09s/it]

[성공] 2525번 카드 (만나 우리카드) 수집 완료

 84%|████████▍ | 2525/2999 [48:48<08:35,  1.09s/it]

[성공] 2526번 카드 (LG트윈스 신한카드) 수집 완료

 84%|████████▍ | 2526/2999 [48:49<08:34,  1.09s/it]

[성공] 2527번 카드 (신한카드 Pick I 체크) 수집 완료

 84%|████████▍ | 2527/2999 [48:51<09:21,  1.19s/it]

[성공] 2528번 카드 (신한카드 Pick E 체크) 수집 완료

 84%|████████▍ | 2528/2999 [48:52<09:07,  1.16s/it]

[성공] 2529번 카드 (트래블로그 신용카드) 수집 완료

 84%|████████▍ | 2529/2999 [48:53<09:00,  1.15s/it]

[성공] 2530번 카드 (총무 체크카드) 수집 완료

 84%|████████▍ | 2530/2999 [48:54<08:57,  1.15s/it]

[Skip] 2531번 카드 정보가 존재하지 않습니다.

 84%|████████▍ | 2531/2999 [48:55<08:47,  1.13s/it]

[성공] 2532번 카드 (신한카드 Globus) 수집 완료

 84%|████████▍ | 2532/2999 [48:57<09:03,  1.16s/it]

[성공] 2533번 카드 (에너지 더블 카드) 수집 완료

 84%|████████▍ | 2533/2999 [48:58<09:06,  1.17s/it]

[성공] 2534번 카드 (삼성 iD VITA 카드) 수집 완료

 84%|████████▍ | 2534/2999 [48:59<09:01,  1.16s/it]

[성공] 2535번 카드 (K-22(Point)) 수집 완료

 85%|████████▍ | 2535/2999 [49:00<08:54,  1.15s/it]

[성공] 2536번 카드 (K-22(Mileage)) 수집 완료

 85%|████████▍ | 2536/2999 [49:01<08:47,  1.14s/it]

[성공] 2537번 카드 (LOCA for 롯데마트) 수집 완료

 85%|████████▍ | 2537/2999 [49:02<08:39,  1.12s/it]

[성공] 2538번 카드 (LOCA CLASSIC 롯데마트) 수집 완료

 85%|████████▍ | 2538/2999 [49:03<08:33,  1.11s/it]

[성공] 2539번 카드 (MY S-OIL 삼성카드) 수집 완료

 85%|████████▍ | 2539/2999 [49:04<08:32,  1.11s/it]

[성공] 2540번 카드 (HERITAGE Exclusive) 수집 완료

 85%|████████▍ | 2540/2999 [49:05<08:31,  1.11s/it]

[성공] 2541번 카드 (HERITAGE Reserve(스카이패스형)) 수집 완료

 85%|████████▍ | 2541/2999 [49:07<08:43,  1.14s/it]

[성공] 2542번 카드 (HERITAGE Reserve(포인트형)) 수집 완료

 85%|████████▍ | 2542/2999 [49:08<08:37,  1.13s/it]

[성공] 2543번 카드 (신세계 THE S VIP) 수집 완료

 85%|████████▍ | 2543/2999 [49:09<08:50,  1.16s/it]

[성공] 2544번 카드 (zgm.play카드) 수집 완료

 85%|████████▍ | 2544/2999 [49:10<09:16,  1.22s/it]

[성공] 2545번 카드 (zgm.play++카드) 수집 완료

 85%|████████▍ | 2545/2999 [49:12<09:44,  1.29s/it]

[성공] 2546번 카드 (신한카드 Pick E 선불) 수집 완료

 85%|████████▍ | 2546/2999 [49:13<09:20,  1.24s/it]

[성공] 2547번 카드 (신한카드 Pick I 선불) 수집 완료

 85%|████████▍ | 2547/2999 [49:14<09:10,  1.22s/it]

[성공] 2548번 카드 (e hi-pass 카드(현대차)) 수집 완료

 85%|████████▍ | 2548/2999 [49:15<08:51,  1.18s/it]

[성공] 2549번 카드 (신한카드 KaPick) 수집 완료

 85%|████████▍ | 2549/2999 [49:16<08:39,  1.15s/it]

[성공] 2550번 카드 (노리2 체크카드(Play)) 수집 완료

 85%|████████▌ | 2550/2999 [49:18<08:46,  1.17s/it]

[성공] 2551번 카드 (카드의정석 EVERY 1) 수집 완료

 85%|████████▌ | 2551/2999 [49:19<08:37,  1.16s/it]

[성공] 2552번 카드 (카드의정석 EVERY CHECK) 수집 완료

 85%|████████▌ | 2552/2999 [49:20<09:11,  1.23s/it]

[성공] 2553번 카드 (카드의정석 EVERY MILE SKYPASS) 수집 완료

 85%|████████▌ | 2553/2999 [49:21<08:56,  1.20s/it]

[성공] 2554번 카드 (밀리언달러 하나카드) 수집 완료

 85%|████████▌ | 2554/2999 [49:22<08:49,  1.19s/it]

[성공] 2555번 카드 (K-패스카드) 수집 완료

 85%|████████▌ | 2555/2999 [49:24<09:10,  1.24s/it]

[성공] 2556번 카드 (K-패스체크카드) 수집 완료

 85%|████████▌ | 2556/2999 [49:25<08:52,  1.20s/it]

[성공] 2557번 카드 (K-패스 카드) 수집 완료

 85%|████████▌ | 2557/2999 [49:26<08:54,  1.21s/it]

[성공] 2558번 카드 (K-패스 삼성카드) 수집 완료

 85%|████████▌ | 2558/2999 [49:27<08:45,  1.19s/it]

[성공] 2559번 카드 (K-패스 (신용)) 수집 완료

 85%|████████▌ | 2559/2999 [49:28<08:39,  1.18s/it]

[성공] 2560번 카드 (K-패스카드(신용)) 수집 완료

 85%|████████▌ | 2560/2999 [49:29<08:31,  1.16s/it]

[성공] 2561번 카드 (K-패스카드(체크)) 수집 완료

 85%|████████▌ | 2561/2999 [49:31<08:36,  1.18s/it]

[성공] 2562번 카드 (K-패스(체크)) 수집 완료

 85%|████████▌ | 2562/2999 [49:32<08:29,  1.17s/it]

[성공] 2563번 카드 (K-패스 삼성체크카드) 수집 완료

 85%|████████▌ | 2563/2999 [49:33<08:22,  1.15s/it]

[성공] 2564번 카드 ([광주] K-그린카드v2) 수집 완료

 85%|████████▌ | 2564/2999 [49:34<08:30,  1.17s/it]

[성공] 2565번 카드 (I-PET) 수집 완료

 86%|████████▌ | 2565/2999 [49:35<08:25,  1.17s/it]

[성공] 2566번 카드 (Trip to 로카) 수집 완료

 86%|████████▌ | 2566/2999 [49:37<08:41,  1.21s/it]

[성공] 2567번 카드 (우리동네GS 삼성카드) 수집 완료

 86%|████████▌ | 2567/2999 [49:38<08:28,  1.18s/it]

[성공] 2568번 카드 (TMAP & LOGI 행복 체크카드) 수집 완료

 86%|████████▌ | 2568/2999 [49:39<08:18,  1.16s/it]

[성공] 2569번 카드 (트래블월렛 우리카드) 수집 완료

 86%|████████▌ | 2569/2999 [49:40<08:28,  1.18s/it]

[성공] 2570번 카드 (카드의정석 오하CHECK) 수집 완료

 86%|████████▌ | 2570/2999 [49:41<08:27,  1.18s/it]

[성공] 2571번 카드 (엠베스트 엘리하이 삼성카드) 수집 완료

 86%|████████▌ | 2571/2999 [49:42<08:17,  1.16s/it]

[성공] 2572번 카드 (Mile1 하나카드) 수집 완료

 86%|████████▌ | 2572/2999 [49:44<08:12,  1.15s/it]

[Skip] 2573번 카드 정보가 존재하지 않습니다.

 86%|████████▌ | 2573/2999 [49:45<08:10,  1.15s/it]

[Skip] 2574번 카드 정보가 존재하지 않습니다.

 86%|████████▌ | 2574/2999 [49:46<07:59,  1.13s/it]

[Skip] 2575번 카드 정보가 존재하지 않습니다.

 86%|████████▌ | 2575/2999 [49:47<07:52,  1.11s/it]

[Skip] 2576번 카드 정보가 존재하지 않습니다.

 86%|████████▌ | 2576/2999 [49:48<07:46,  1.10s/it]

[Skip] 2577번 카드 정보가 존재하지 않습니다.

 86%|████████▌ | 2577/2999 [49:49<07:43,  1.10s/it]

[Skip] 2578번 카드 정보가 존재하지 않습니다.

 86%|████████▌ | 2578/2999 [49:50<07:40,  1.09s/it]

[Skip] 2579번 카드 정보가 존재하지 않습니다.

 86%|████████▌ | 2579/2999 [49:51<07:37,  1.09s/it]

[Skip] 2580번 카드 정보가 존재하지 않습니다.

 86%|████████▌ | 2580/2999 [49:52<07:35,  1.09s/it]

[Skip] 2581번 카드 정보가 존재하지 않습니다.

 86%|████████▌ | 2581/2999 [49:53<07:34,  1.09s/it]

[성공] 2582번 카드 (트래블제로카드) 수집 완료

 86%|████████▌ | 2582/2999 [49:54<07:41,  1.11s/it]

[성공] 2583번 카드 (PAYCO 36 우리카드) 수집 완료

 86%|████████▌ | 2583/2999 [49:56<07:41,  1.11s/it]

[Skip] 2584번 카드 정보가 존재하지 않습니다.

 86%|████████▌ | 2584/2999 [49:57<07:36,  1.10s/it]

[성공] 2585번 카드 (신한카드 Way 체크(미니언즈 여름)) 수집 완료

 86%|████████▌ | 2585/2999 [49:58<07:41,  1.11s/it]

[성공] 2586번 카드 (티니 카드) 수집 완료

 86%|████████▌ | 2586/2999 [49:59<07:39,  1.11s/it]

[성공] 2587번 카드 (카드의정석 EVERY 1 (망그러진곰 Edition)) 수집 완료

 86%|████████▋ | 2587/2999 [50:00<07:39,  1.12s/it]

[성공] 2588번 카드 (스타플러스 체크카드) 수집 완료

 86%|████████▋ | 2588/2999 [50:02<08:25,  1.23s/it]

[성공] 2589번 카드 (GS Prime 신한카드 체크) 수집 완료

 86%|████████▋ | 2589/2999 [50:03<08:26,  1.24s/it]

[성공] 2590번 카드 (BC 바로 에어 플러스 아시아나) 수집 완료

 86%|████████▋ | 2590/2999 [50:04<08:13,  1.21s/it]

[성공] 2591번 카드 (BC 바로 On&Off 카드) 수집 완료

 86%|████████▋ | 2591/2999 [50:05<08:03,  1.18s/it]

[성공] 2592번 카드 (싱가포르항공 크리스플라이어 더 베스트 신한카드) 수집 완료

 86%|████████▋ | 2592/2999 [50:06<08:00,  1.18s/it]

[성공] 2593번 카드 (zgm.일본여행중 카드) 수집 완료

 86%|████████▋ | 2593/2999 [50:08<08:14,  1.22s/it]

[성공] 2594번 카드 (아시아나 듀얼마일리지 롯데카드) 수집 완료

 86%|████████▋ | 2594/2999 [50:09<08:13,  1.22s/it]

[성공] 2595번 카드 (랭킹닭컴 신용카드) 수집 완료

 87%|████████▋ | 2595/2999 [50:10<08:11,  1.22s/it]

[성공] 2596번 카드 (신한카드 봄(도구리)) 수집 완료

 87%|████████▋ | 2596/2999 [50:11<07:58,  1.19s/it]

[성공] 2597번 카드 (신한카드 봄 체크(도구리)) 수집 완료

 87%|████████▋ | 2597/2999 [50:12<07:49,  1.17s/it]

[성공] 2598번 카드 (CJ ONE 프리즘 신한카드) 수집 완료

 87%|████████▋ | 2598/2999 [50:13<07:45,  1.16s/it]

[Skip] 2599번 카드 정보가 존재하지 않습니다.

 87%|████████▋ | 2599/2999 [50:14<07:34,  1.14s/it]

[Skip] 2600번 카드 정보가 존재하지 않습니다.

 87%|████████▋ | 2600/2999 [50:16<07:27,  1.12s/it]

[성공] 2601번 카드 (더나은 체크카드) 수집 완료

 87%|████████▋ | 2601/2999 [50:17<07:23,  1.11s/it]

[성공] 2602번 카드 (SPOTV NOW 신한카드 구독 좋아요) 수집 완료

 87%|████████▋ | 2602/2999 [50:18<07:24,  1.12s/it]

[성공] 2603번 카드 (KB차차차 신용카드) 수집 완료

 87%|████████▋ | 2603/2999 [50:19<07:42,  1.17s/it]

[성공] 2604번 카드 (토심이 첵첵 체크카드) 수집 완료

 87%|████████▋ | 2604/2999 [50:20<07:37,  1.16s/it]

[성공] 2605번 카드 (TMAP KB국민카드) 수집 완료

 87%|████████▋ | 2605/2999 [50:21<07:29,  1.14s/it]

[성공] 2606번 카드 (신한라이프 THE PRIDE 신한카드) 수집 완료

 87%|████████▋ | 2606/2999 [50:22<07:32,  1.15s/it]

[성공] 2607번 카드 (kt DC PLUS) 수집 완료

 87%|████████▋ | 2607/2999 [50:24<07:22,  1.13s/it]

[성공] 2608번 카드 (대성학원 신한카드) 수집 완료

 87%|████████▋ | 2608/2999 [50:25<07:21,  1.13s/it]

[성공] 2609번 카드 (쿠팡 와우카드) 수집 완료

 87%|████████▋ | 2609/2999 [50:26<07:33,  1.16s/it]

[성공] 2610번 카드 (I-어디로든 그린카드) 수집 완료

 87%|████████▋ | 2610/2999 [50:27<07:27,  1.15s/it]

[성공] 2611번 카드 (신한카드 Applus) 수집 완료

 87%|████████▋ | 2611/2999 [50:28<07:22,  1.14s/it]

[성공] 2612번 카드 (ALL 우리카드 Premium) 수집 완료

 87%|████████▋ | 2612/2999 [50:29<07:33,  1.17s/it]

[성공] 2613번 카드 (ALL 우리카드 Infinite) 수집 완료

 87%|████████▋ | 2613/2999 [50:31<07:31,  1.17s/it]

[성공] 2614번 카드 (KB Pay 머니백카드) 수집 완료

 87%|████████▋ | 2614/2999 [50:32<07:23,  1.15s/it]

[성공] 2615번 카드 (IBK KaPick) 수집 완료

 87%|████████▋ | 2615/2999 [50:33<07:29,  1.17s/it]

[성공] 2616번 카드 (어디로든 그린카드) 수집 완료

 87%|████████▋ | 2616/2999 [50:34<07:29,  1.17s/it]

[성공] 2617번 카드 (어디로든 그린카드) 수집 완료

 87%|████████▋ | 2617/2999 [50:36<08:19,  1.31s/it]

[성공] 2618번 카드 (삼성 iD AUTO 카드) 수집 완료

 87%|████████▋ | 2618/2999 [50:37<07:58,  1.26s/it]

[성공] 2619번 카드 (DGB어디로든그린카드) 수집 완료

 87%|████████▋ | 2619/2999 [50:38<07:40,  1.21s/it]

[성공] 2620번 카드 (NH 무럭이 체크카드) 수집 완료

 87%|████████▋ | 2620/2999 [50:39<07:34,  1.20s/it]

[성공] 2621번 카드 (어디로든 그린체크카드) 수집 완료

 87%|████████▋ | 2621/2999 [50:40<07:53,  1.25s/it]

[성공] 2622번 카드 (어디로든 그린카드) 수집 완료

 87%|████████▋ | 2622/2999 [50:42<07:44,  1.23s/it]

[성공] 2623번 카드 (American Express Rose Gold KB Kookmin Card) 수집 완료

 87%|████████▋ | 2623/2999 [50:43<07:27,  1.19s/it]

[성공] 2624번 카드 (American Express Blue KB Kookmin Card) 수집 완료

 87%|████████▋ | 2624/2999 [50:44<07:20,  1.18s/it]

[성공] 2625번 카드 (토스 USS NEXT 체크카드) 수집 완료

 88%|████████▊ | 2625/2999 [50:45<07:12,  1.16s/it]

[성공] 2626번 카드 (네이버페이 머니카드) 수집 완료

 88%|████████▊ | 2626/2999 [50:46<07:04,  1.14s/it]

[성공] 2627번 카드 (TWO CHAIRS) 수집 완료

 88%|████████▊ | 2627/2999 [50:47<07:24,  1.19s/it]

[성공] 2628번 카드 (브라보(Bravo) 체크카드) 수집 완료

 88%|████████▊ | 2628/2999 [50:49<07:14,  1.17s/it]

[성공] 2629번 카드 (Smilecard Edition3) 수집 완료

 88%|████████▊ | 2629/2999 [50:50<07:22,  1.20s/it]

[성공] 2630번 카드 (에버랜드 판다카드(푸바오 에디션)) 수집 완료

 88%|████████▊ | 2630/2999 [50:51<07:12,  1.17s/it]

[성공] 2631번 카드 (모니모A 카드) 수집 완료

 88%|████████▊ | 2631/2999 [50:53<08:14,  1.34s/it]

[성공] 2632번 카드 (디지로카 London) 수집 완료

 88%|████████▊ | 2632/2999 [50:54<08:17,  1.36s/it]

[성공] 2633번 카드 (디지로카 Paris) 수집 완료

 88%|████████▊ | 2633/2999 [50:55<07:48,  1.28s/it]

[성공] 2634번 카드 (디지로카 Monaco) 수집 완료

 88%|████████▊ | 2634/2999 [50:56<07:28,  1.23s/it]

[성공] 2635번 카드 (Triple in LOCA) 수집 완료

 88%|████████▊ | 2635/2999 [50:57<07:18,  1.20s/it]

[성공] 2636번 카드 (LOCA Professional) 수집 완료

 88%|████████▊ | 2636/2999 [50:59<07:27,  1.23s/it]

[성공] 2637번 카드 (카카오페이 신한 라이언 체크) 수집 완료

 88%|████████▊ | 2637/2999 [51:00<07:21,  1.22s/it]

[성공] 2638번 카드 (카카오페이 신한 춘식이 체크) 수집 완료

 88%|████████▊ | 2638/2999 [51:01<07:29,  1.25s/it]

[성공] 2639번 카드 (카드의정석 DON CHECK) 수집 완료

 88%|████████▊ | 2639/2999 [51:02<07:14,  1.21s/it]

[성공] 2640번 카드 (코스트코 리워드 현대카드 Edition2) 수집 완료

 88%|████████▊ | 2640/2999 [51:03<07:04,  1.18s/it]

[성공] 2641번 카드 (어디로든 그린카드 X LOCA) 수집 완료

 88%|████████▊ | 2641/2999 [51:05<06:55,  1.16s/it]

[성공] 2642번 카드 (에너지플러스카드 Edition3) 수집 완료

 88%|████████▊ | 2642/2999 [51:06<06:57,  1.17s/it]

[성공] 2643번 카드 (MULTI Any 체크카드) 수집 완료

 88%|████████▊ | 2643/2999 [51:07<06:56,  1.17s/it]

[성공] 2644번 카드 (GOAT BC 바로카드) 수집 완료

 88%|████████▊ | 2644/2999 [51:08<06:49,  1.15s/it]

[성공] 2645번 카드 (ZipL 신용카드) 수집 완료

 88%|████████▊ | 2645/2999 [51:09<06:59,  1.19s/it]

[성공] 2646번 카드 (현대카드ZERO Edition3(할인형)) 수집 완료

 88%|████████▊ | 2646/2999 [51:10<06:52,  1.17s/it]

[성공] 2647번 카드 (현대카드ZERO Edition3(포인트형)) 수집 완료

 88%|████████▊ | 2647/2999 [51:12<06:49,  1.16s/it]

[성공] 2648번 카드 (zgm shopping카드) 수집 완료

 88%|████████▊ | 2648/2999 [51:13<07:05,  1.21s/it]

[성공] 2649번 카드 (zgm living카드) 수집 완료

 88%|████████▊ | 2649/2999 [51:14<06:55,  1.19s/it]

[성공] 2650번 카드 (머니트리카드) 수집 완료

 88%|████████▊ | 2650/2999 [51:15<06:58,  1.20s/it]

[성공] 2651번 카드 (W컨셉 삼성카드) 수집 완료

 88%|████████▊ | 2651/2999 [51:16<07:01,  1.21s/it]

[성공] 2652번 카드 (에버랜드 삼성카드) 수집 완료

 88%|████████▊ | 2652/2999 [51:18<06:59,  1.21s/it]

[성공] 2653번 카드 (010PAY 우리카드) 수집 완료

 88%|████████▊ | 2653/2999 [51:19<06:59,  1.21s/it]

[성공] 2654번 카드 (원더카드 2.0 LIFE) 수집 완료

 88%|████████▊ | 2654/2999 [51:20<06:49,  1.19s/it]

[성공] 2655번 카드 (DA카드의정석Ⅱ) 수집 완료

 89%|████████▊ | 2655/2999 [51:21<06:44,  1.18s/it]

[성공] 2656번 카드 (춘식이 모바일 로카) 수집 완료

 89%|████████▊ | 2656/2999 [51:22<06:51,  1.20s/it]

[성공] 2657번 카드 (JADE Classic) 수집 완료

 89%|████████▊ | 2657/2999 [51:24<07:40,  1.35s/it]

[성공] 2658번 카드 (I-나눔) 수집 완료

 89%|████████▊ | 2658/2999 [51:25<07:44,  1.36s/it]

[성공] 2659번 카드 (보험엔로카) 수집 완료

 89%|████████▊ | 2659/2999 [51:27<07:39,  1.35s/it]

[Skip] 2660번 카드 정보가 존재하지 않습니다.

 89%|████████▊ | 2660/2999 [51:28<07:10,  1.27s/it]

[성공] 2661번 카드 (삼성 iD PLUG-IN 카드) 수집 완료

 89%|████████▊ | 2661/2999 [51:29<06:52,  1.22s/it]

[성공] 2662번 카드 (American Express® Green Card Edition2) 수집 완료

 89%|████████▉ | 2662/2999 [51:30<06:42,  1.19s/it]

[성공] 2663번 카드 (American Express® Gold Card Edition2) 수집 완료

 89%|████████▉ | 2663/2999 [51:31<06:40,  1.19s/it]

[성공] 2664번 카드 (American Express The Platinum Card®Edition2) 수집 완료

 89%|████████▉ | 2664/2999 [51:32<06:37,  1.19s/it]

[성공] 2665번 카드 (폼 체크카드) 수집 완료

 89%|████████▉ | 2665/2999 [51:34<06:30,  1.17s/it]

[성공] 2666번 카드 (신한카드 Point Plan) 수집 완료

 89%|████████▉ | 2666/2999 [51:35<06:28,  1.17s/it]

[성공] 2667번 카드 (신한카드 SOL트래블 체크) 수집 완료

 89%|████████▉ | 2667/2999 [51:36<06:25,  1.16s/it]

[성공] 2668번 카드 (탐나는전 체크카드) 수집 완료

 89%|████████▉ | 2668/2999 [51:37<06:20,  1.15s/it]

[성공] 2669번 카드 (현대카드 M) 수집 완료

 89%|████████▉ | 2669/2999 [51:39<06:57,  1.27s/it]

[성공] 2670번 카드 (현대카드 MM) 수집 완료

 89%|████████▉ | 2670/2999 [51:40<06:42,  1.22s/it]

[성공] 2671번 카드 (원더 K리그 축덕카드) 수집 완료

 89%|████████▉ | 2671/2999 [51:41<06:32,  1.20s/it]

[성공] 2672번 카드 (樂SEA(락시)) 수집 완료

 89%|████████▉ | 2672/2999 [51:42<06:21,  1.17s/it]

[성공] 2673번 카드 (신한카드 Point Plan 체크) 수집 완료

 89%|████████▉ | 2673/2999 [51:43<06:15,  1.15s/it]

[성공] 2674번 카드 (I-Mileage (대한항공)) 수집 완료

 89%|████████▉ | 2674/2999 [51:44<06:17,  1.16s/it]

[성공] 2675번 카드 (I-Mileage (아시아나)) 수집 완료

 89%|████████▉ | 2675/2999 [51:45<06:09,  1.14s/it]

[성공] 2676번 카드 (삼성 iD GLOBAL 카드) 수집 완료

 89%|████████▉ | 2676/2999 [51:47<06:16,  1.16s/it]

[성공] 2677번 카드 (카드의정석 Dear, Shopper(디어쇼퍼)) 수집 완료

 89%|████████▉ | 2677/2999 [51:48<06:12,  1.16s/it]

[성공] 2678번 카드 (카드의정석 Dear, Traveler(디어트래블러)) 수집 완료

 89%|████████▉ | 2678/2999 [51:49<06:09,  1.15s/it]

[성공] 2679번 카드 (현대카드 X) 수집 완료

 89%|████████▉ | 2679/2999 [51:50<06:44,  1.27s/it]

[성공] 2680번 카드 (현대카드Z work Edition2) 수집 완료

 89%|████████▉ | 2680/2999 [51:52<07:33,  1.42s/it]

[성공] 2681번 카드 (K-패스 하나 신용카드) 수집 완료

 89%|████████▉ | 2681/2999 [51:53<07:06,  1.34s/it]

[성공] 2682번 카드 (K-패스 하나 체크카드) 수집 완료

 89%|████████▉ | 2682/2999 [51:55<06:56,  1.32s/it]

[성공] 2683번 카드 (현대카드Z family Edition2) 수집 완료

 89%|████████▉ | 2683/2999 [51:56<07:08,  1.36s/it]

[성공] 2684번 카드 (현대카드Z play) 수집 완료

 89%|████████▉ | 2684/2999 [51:57<06:46,  1.29s/it]

[성공] 2685번 카드 (WE:SH Travel) 수집 완료

 90%|████████▉ | 2685/2999 [51:59<06:58,  1.33s/it]

[성공] 2686번 카드 (D4카드의정석Ⅱ) 수집 완료

 90%|████████▉ | 2686/2999 [52:00<06:45,  1.29s/it]

[성공] 2687번 카드 (카드의정석 SHOPPING+) 수집 완료

 90%|████████▉ | 2687/2999 [52:01<06:48,  1.31s/it]

[성공] 2688번 카드 (카드의정석 I&U+) 수집 완료

 90%|████████▉ | 2688/2999 [52:02<06:30,  1.26s/it]

[성공] 2689번 카드 (카드의정석 EVERY POINT) 수집 완료

 90%|████████▉ | 2689/2999 [52:03<06:18,  1.22s/it]

[성공] 2690번 카드 (K-패스 신한카드) 수집 완료

 90%|████████▉ | 2690/2999 [52:05<06:12,  1.21s/it]

[성공] 2691번 카드 (트래블러스 체크카드(토심이)) 수집 완료

 90%|████████▉ | 2691/2999 [52:06<06:24,  1.25s/it]

[성공] 2692번 카드 (현대카드 Summit) 수집 완료

 90%|████████▉ | 2692/2999 [52:07<06:36,  1.29s/it]

[성공] 2693번 카드 (K-패스 신한카드 체크) 수집 완료

 90%|████████▉ | 2693/2999 [52:09<06:30,  1.28s/it]

[성공] 2694번 카드 (신한카드 처음) 수집 완료

 90%|████████▉ | 2694/2999 [52:10<06:30,  1.28s/it]

[성공] 2695번 카드 (다둥이 행복카드) 수집 완료

 90%|████████▉ | 2695/2999 [52:11<06:18,  1.24s/it]

[성공] 2696번 카드 (카드의정석 햇살론카드) 수집 완료

 90%|████████▉ | 2696/2999 [52:12<06:05,  1.21s/it]

[성공] 2697번 카드 (현대카드 MX Black Edition2) 수집 완료

 90%|████████▉ | 2697/2999 [52:13<05:59,  1.19s/it]

[성공] 2698번 카드 (zgm point카드) 수집 완료

 90%|████████▉ | 2698/2999 [52:14<05:50,  1.16s/it]

[성공] 2699번 카드 (카드의정석 TEN) 수집 완료

 90%|████████▉ | 2699/2999 [52:16<05:49,  1.17s/it]

[성공] 2700번 카드 (위비트래블 체크카드) 수집 완료

 90%|█████████ | 2700/2999 [52:17<05:47,  1.16s/it]

[성공] 2701번 카드 (하나투어 삼성카드) 수집 완료

 90%|█████████ | 2701/2999 [52:18<05:47,  1.17s/it]

[성공] 2702번 카드 (삼성 iD CLASSY 카드) 수집 완료

 90%|█████████ | 2702/2999 [52:19<05:44,  1.16s/it]

[성공] 2703번 카드 (JADE Prime) 수집 완료

 90%|█████████ | 2703/2999 [52:20<05:46,  1.17s/it]

[성공] 2704번 카드 (JADE First) 수집 완료

 90%|█████████ | 2704/2999 [52:22<05:54,  1.20s/it]

[성공] 2705번 카드 (JADE First Centum) 수집 완료

 90%|█████████ | 2705/2999 [52:23<06:04,  1.24s/it]

[성공] 2706번 카드 (zgm 할인카드) 수집 완료

 90%|█████████ | 2706/2999 [52:24<06:09,  1.26s/it]

[성공] 2707번 카드 (디지로카 Las Vegas) 수집 완료

 90%|█████████ | 2707/2999 [52:25<05:57,  1.22s/it]

[성공] 2708번 카드 (WE:SH Daily 카드) 수집 완료

 90%|█████████ | 2708/2999 [52:27<06:03,  1.25s/it]

[성공] 2709번 카드 (대한항공카드 060) 수집 완료

 90%|█████████ | 2709/2999 [52:28<05:55,  1.23s/it]

[성공] 2710번 카드 (대한항공카드 120) 수집 완료

 90%|█████████ | 2710/2999 [52:29<05:45,  1.20s/it]

[성공] 2711번 카드 (대한항공카드 300) 수집 완료

 90%|█████████ | 2711/2999 [52:30<05:39,  1.18s/it]

[성공] 2712번 카드 (대한항공카드 the First Edition2) 수집 완료

 90%|█████████ | 2712/2999 [52:31<05:36,  1.17s/it]

[성공] 2713번 카드 (디지로카 Pet) 수집 완료

 90%|█████████ | 2713/2999 [52:32<05:29,  1.15s/it]

[성공] 2714번 카드 (디지로카 Edu) 수집 완료

 90%|█████████ | 2714/2999 [52:34<05:40,  1.20s/it]

[성공] 2715번 카드 (디지로카 Wellness) 수집 완료

 91%|█████████ | 2715/2999 [52:35<05:32,  1.17s/it]

[성공] 2716번 카드 (디지로카 Golf) 수집 완료

 91%|█████████ | 2716/2999 [52:36<05:24,  1.15s/it]

[성공] 2717번 카드 (디지로카 Auto) 수집 완료

 91%|█████████ | 2717/2999 [52:37<05:21,  1.14s/it]

[성공] 2718번 카드 (모바일엔디지로카) 수집 완료

 91%|█████████ | 2718/2999 [52:38<05:19,  1.14s/it]

[성공] 2719번 카드 (카드의정석 EVERY DISCOUNT) 수집 완료

 91%|█████████ | 2719/2999 [52:39<05:35,  1.20s/it]

[Skip] 2720번 카드 정보가 존재하지 않습니다.

 91%|█████████ | 2720/2999 [52:40<05:24,  1.16s/it]

[성공] 2721번 카드 (당근머니 하나 체크카드) 수집 완료

 91%|█████████ | 2721/2999 [52:42<05:21,  1.16s/it]

[성공] 2722번 카드 (신한카드 SOL트래블) 수집 완료

 91%|█████████ | 2722/2999 [52:43<05:21,  1.16s/it]

[성공] 2723번 카드 (롯데카드 KaPick) 수집 완료

 91%|█████████ | 2723/2999 [52:44<05:16,  1.15s/it]

[성공] 2724번 카드 (BC 바로 KaPick) 수집 완료

 91%|█████████ | 2724/2999 [52:45<05:39,  1.23s/it]

[성공] 2725번 카드 (배민 한그릇카드) 수집 완료

 91%|█████████ | 2725/2999 [52:46<05:30,  1.21s/it]

[성공] 2726번 카드 (배민 곱빼기카드) 수집 완료

 91%|█████████ | 2726/2999 [52:48<05:21,  1.18s/it]

[성공] 2727번 카드 (NH트래블리체크카드) 수집 완료

 91%|█████████ | 2727/2999 [52:49<05:29,  1.21s/it]

[성공] 2728번 카드 (BC 바로 MACAO 카드) 수집 완료

 91%|█████████ | 2728/2999 [52:50<05:26,  1.20s/it]

[성공] 2729번 카드 (트래블로그 SKYPASS 신용카드) 수집 완료

 91%|█████████ | 2729/2999 [52:51<05:34,  1.24s/it]

[성공] 2730번 카드 (트래블로그 PRESTIGE 신용카드) 수집 완료

 91%|█████████ | 2730/2999 [52:52<05:23,  1.20s/it]

[성공] 2731번 카드 (신한카드 Point Plan+) 수집 완료

 91%|█████████ | 2731/2999 [52:54<05:20,  1.20s/it]

[성공] 2732번 카드 (토스뱅크 하나카드 Wide) 수집 완료

 91%|█████████ | 2732/2999 [52:55<05:17,  1.19s/it]

[성공] 2733번 카드 (원더 Co brand(집업) 제휴 카드) 수집 완료

 91%|█████████ | 2733/2999 [52:56<05:10,  1.17s/it]

[성공] 2734번 카드 (코웨이 IBK카드) 수집 완료

 91%|█████████ | 2734/2999 [52:57<05:03,  1.15s/it]

[성공] 2735번 카드 (신한카드 Edu Plan+) 수집 완료

 91%|█████████ | 2735/2999 [52:58<05:07,  1.17s/it]

[성공] 2736번 카드 (현대홈쇼핑 현대카드) 수집 완료

 91%|█████████ | 2736/2999 [52:59<05:04,  1.16s/it]

[성공] 2737번 카드 (the Red (항공 마일리지형)) 수집 완료

 91%|█████████▏| 2737/2999 [53:01<05:01,  1.15s/it]

[성공] 2738번 카드 (SILVER FOR LOTTE DEPARTMENT STORE) 수집 완료

 91%|█████████▏| 2738/2999 [53:02<04:57,  1.14s/it]

[성공] 2739번 카드 (GOLD FOR LOTTE DEPARTMENT STORE) 수집 완료

 91%|█████████▏| 2739/2999 [53:03<04:59,  1.15s/it]

[성공] 2740번 카드 (트래블GO 체크카드) 수집 완료

 91%|█████████▏| 2740/2999 [53:04<05:11,  1.20s/it]

[성공] 2741번 카드 (KT 가족만족 할부 신한카드) 수집 완료

 91%|█████████▏| 2741/2999 [53:05<05:03,  1.18s/it]

[성공] 2742번 카드 (카드의정석 EVERYDAY CHECK) 수집 완료

 91%|█████████▏| 2742/2999 [53:06<05:04,  1.19s/it]

[성공] 2743번 카드 (3 Body-A 현대카드) 수집 완료

 91%|█████████▏| 2743/2999 [53:08<04:58,  1.17s/it]

[성공] 2744번 카드 (EV 카드) 수집 완료

 91%|█████████▏| 2744/2999 [53:09<04:53,  1.15s/it]

[성공] 2745번 카드 (더담은 체크카드) 수집 완료

 92%|█████████▏| 2745/2999 [53:10<04:50,  1.14s/it]

[성공] 2746번 카드 (삼성 iD ONE 카드) 수집 완료

 92%|█████████▏| 2746/2999 [53:11<04:48,  1.14s/it]

[성공] 2747번 카드 (신한카드 The Pet) 수집 완료

 92%|█████████▏| 2747/2999 [53:12<04:52,  1.16s/it]

[성공] 2748번 카드 (신한카드 The Premium Pet) 수집 완료

 92%|█████████▏| 2748/2999 [53:13<04:54,  1.17s/it]

[성공] 2749번 카드 (ONE 체크카드) 수집 완료

 92%|█████████▏| 2749/2999 [53:15<04:50,  1.16s/it]

[성공] 2750번 카드 (달달 하나 체크카드) 수집 완료

 92%|█████████▏| 2750/2999 [53:16<04:46,  1.15s/it]

[성공] 2751번 카드 (the Red (M포인트형)) 수집 완료

 92%|█████████▏| 2751/2999 [53:17<04:44,  1.15s/it]

[성공] 2752번 카드 (the Pink Edition2) 수집 완료

 92%|█████████▏| 2752/2999 [53:18<04:45,  1.16s/it]

[성공] 2753번 카드 (the Green Edition3) 수집 완료

 92%|█████████▏| 2753/2999 [53:19<04:44,  1.16s/it]

[Skip] 2754번 카드 정보가 존재하지 않습니다.

 92%|█████████▏| 2754/2999 [53:20<04:38,  1.14s/it]

[성공] 2755번 카드 (the Red Stripe Edition2) 수집 완료

 92%|█████████▏| 2755/2999 [53:21<04:36,  1.13s/it]

[성공] 2756번 카드 (the Purple) 수집 완료

 92%|█████████▏| 2756/2999 [53:22<04:33,  1.12s/it]

[성공] 2757번 카드 (the black) 수집 완료

 92%|█████████▏| 2757/2999 [53:24<04:31,  1.12s/it]

[성공] 2758번 카드 (춘식이달달체크카드) 수집 완료

 92%|█████████▏| 2758/2999 [53:25<04:30,  1.12s/it]

[성공] 2759번 카드 (신한카드 처음(ANNIVERSE)) 수집 완료

 92%|█████████▏| 2759/2999 [53:26<04:33,  1.14s/it]

[성공] 2760번 카드 (카드의정석 칼퇴 CHECK) 수집 완료

 92%|█████████▏| 2760/2999 [53:27<04:30,  1.13s/it]

[성공] 2761번 카드 (KB국민카드 KaPick) 수집 완료

 92%|█████████▏| 2761/2999 [53:28<04:29,  1.13s/it]

[성공] 2762번 카드 (THE iD. TITANIUM (아시아나)) 수집 완료

 92%|█████████▏| 2762/2999 [53:29<04:36,  1.17s/it]

[성공] 2763번 카드 (CU Npay 카드) 수집 완료

 92%|█████████▏| 2763/2999 [53:30<04:31,  1.15s/it]

[성공] 2764번 카드 (올리브영 현대카드) 수집 완료

 92%|█████████▏| 2764/2999 [53:32<04:27,  1.14s/it]

[성공] 2765번 카드 (LOCA X 기후동행카드) 수집 완료

 92%|█████████▏| 2765/2999 [53:33<04:25,  1.13s/it]

[성공] 2766번 카드 (신한 후불 기후동행 신용카드) 수집 완료

 92%|█████████▏| 2766/2999 [53:34<04:36,  1.19s/it]

[성공] 2767번 카드 (신한 후불 기후동행 체크카드) 수집 완료

 92%|█████████▏| 2767/2999 [53:35<04:46,  1.23s/it]

[성공] 2768번 카드 (하나 기후동행체크카드) 수집 완료

 92%|█████████▏| 2768/2999 [53:36<04:35,  1.19s/it]

[성공] 2769번 카드 (KB국민 기후동행카드) 수집 완료

 92%|█████████▏| 2769/2999 [53:38<04:29,  1.17s/it]

[성공] 2770번 카드 (KB국민 기후동행체크카드) 수집 완료

 92%|█████████▏| 2770/2999 [53:39<04:27,  1.17s/it]

[성공] 2771번 카드 (기후동행 삼성카드) 수집 완료

 92%|█████████▏| 2771/2999 [53:40<04:44,  1.25s/it]

[성공] 2772번 카드 (기후동행카드(신용)) 수집 완료

 92%|█████████▏| 2772/2999 [53:41<04:33,  1.21s/it]

[성공] 2773번 카드 (기후동행카드(체크)) 수집 완료

 92%|█████████▏| 2773/2999 [53:43<04:33,  1.21s/it]

[성공] 2774번 카드 (BC 바로 기후동행카드) 수집 완료

 92%|█████████▏| 2774/2999 [53:44<04:34,  1.22s/it]

[성공] 2775번 카드 (카카오페이 트래블로그 체크카드) 수집 완료

 93%|█████████▎| 2775/2999 [53:45<04:27,  1.19s/it]

[성공] 2776번 카드 (이마트 e카드 Plus) 수집 완료

 93%|█████████▎| 2776/2999 [53:46<04:20,  1.17s/it]

[성공] 2777번 카드 (이마트 e카드 Basic) 수집 완료

 93%|█████████▎| 2777/2999 [53:47<04:19,  1.17s/it]

[성공] 2778번 카드 (IBK포인트3.8(신용)) 수집 완료

 93%|█████████▎| 2778/2999 [53:48<04:16,  1.16s/it]

[성공] 2779번 카드 (IBK포인트(신용)) 수집 완료

 93%|█████████▎| 2779/2999 [53:49<04:12,  1.15s/it]

[성공] 2780번 카드 (HERITAGE Classic [할인형]) 수집 완료

 93%|█████████▎| 2780/2999 [53:51<04:14,  1.16s/it]

[성공] 2781번 카드 (HERITAGE Classic [스카이패스형]) 수집 완료

 93%|█████████▎| 2781/2999 [53:52<04:11,  1.15s/it]

[성공] 2782번 카드 (현대카드 Teens) 수집 완료

 93%|█████████▎| 2782/2999 [53:53<04:06,  1.14s/it]

[성공] 2783번 카드 (IBK포인트(체크)) 수집 완료

 93%|█████████▎| 2783/2999 [53:54<04:07,  1.14s/it]

[성공] 2784번 카드 (K-패스 우리카드) 수집 완료

 93%|█████████▎| 2784/2999 [53:55<04:07,  1.15s/it]

[성공] 2785번 카드 (힐튼 아너스 아멕스) 수집 완료

 93%|█████████▎| 2785/2999 [53:56<04:04,  1.14s/it]

[성공] 2786번 카드 (힐튼 아너스 아멕스 프리미엄) 수집 완료

 93%|█████████▎| 2786/2999 [53:57<04:01,  1.14s/it]

[성공] 2787번 카드 (LGE.COM 신한카드) 수집 완료

 93%|█████████▎| 2787/2999 [53:59<03:59,  1.13s/it]

[성공] 2788번 카드 (신한카드 The ACE BLUE LABEL) 수집 완료

 93%|█████████▎| 2788/2999 [54:00<04:00,  1.14s/it]

[성공] 2789번 카드 (에버온 EV 카드) 수집 완료

 93%|█████████▎| 2789/2999 [54:01<03:57,  1.13s/it]

[성공] 2790번 카드 (현대카드 Summit CE) 수집 완료

 93%|█████████▎| 2790/2999 [54:02<03:55,  1.12s/it]

[성공] 2791번 카드 (현대카드 Boutique - Velvet) 수집 완료

 93%|█████████▎| 2791/2999 [54:03<03:53,  1.12s/it]

[성공] 2792번 카드 (현대카드 Boutique - Satin) 수집 완료

 93%|█████████▎| 2792/2999 [54:04<03:53,  1.13s/it]

[성공] 2793번 카드 (현대카드 Boutique - Copper) 수집 완료

 93%|█████████▎| 2793/2999 [54:05<03:52,  1.13s/it]

[성공] 2794번 카드 (네이버 현대카드 Edition2) 수집 완료

 93%|█████████▎| 2794/2999 [54:06<03:49,  1.12s/it]

[성공] 2795번 카드 (올라운드카드) 수집 완료

 93%|█████████▎| 2795/2999 [54:08<03:49,  1.12s/it]

[성공] 2796번 카드 (롯데카드 TELLO SE) 수집 완료

 93%|█████████▎| 2796/2999 [54:09<03:48,  1.13s/it]

[성공] 2797번 카드 (SKT T다운 하나카드) 수집 완료

 93%|█████████▎| 2797/2999 [54:10<03:45,  1.12s/it]

[성공] 2798번 카드 (LG전자 스페셜 롯데카드) 수집 완료

 93%|█████████▎| 2798/2999 [54:11<03:43,  1.11s/it]

[성공] 2799번 카드 (K-패스엔로카) 수집 완료

 93%|█████████▎| 2799/2999 [54:12<03:42,  1.11s/it]

[성공] 2800번 카드 (LGU+더 심플 하나카드) 수집 완료

 93%|█████████▎| 2800/2999 [54:13<03:39,  1.10s/it]

[성공] 2801번 카드 (롯데하이마트 Hi-Class 롯데카드) 수집 완료

 93%|█████████▎| 2801/2999 [54:14<03:36,  1.09s/it]

[성공] 2802번 카드 (LG U+ NU 우리카드 Ⅱ) 수집 완료

 93%|█████████▎| 2802/2999 [54:15<03:38,  1.11s/it]

[성공] 2803번 카드 (T 라이트 KB국민카드) 수집 완료

 93%|█████████▎| 2803/2999 [54:16<03:37,  1.11s/it]

[성공] 2804번 카드 (LG전자 구독애 GS칼텍스 신한카드 Shine) 수집 완료

 93%|█████████▎| 2804/2999 [54:18<03:37,  1.11s/it]

[성공] 2805번 카드 (토스페이 플러스 신한카드) 수집 완료

 94%|█████████▎| 2805/2999 [54:19<03:37,  1.12s/it]

[성공] 2806번 카드 (토스페이 플러스 KB카드) 수집 완료

 94%|█████████▎| 2806/2999 [54:20<03:35,  1.12s/it]

[성공] 2807번 카드 (신한카드 The BEST-XO) 수집 완료

 94%|█████████▎| 2807/2999 [54:21<03:38,  1.14s/it]

[성공] 2808번 카드 (딩딩 체크카드) 수집 완료

 94%|█████████▎| 2808/2999 [54:22<03:37,  1.14s/it]

[성공] 2809번 카드 (Young Hana+ 체크카드) 수집 완료

 94%|█████████▎| 2809/2999 [54:23<03:39,  1.15s/it]

[성공] 2810번 카드 (더 심플 체크카드) 수집 완료

 94%|█████████▎| 2810/2999 [54:24<03:35,  1.14s/it]

[성공] 2811번 카드 (더 심플 하나카드) 수집 완료

 94%|█████████▎| 2811/2999 [54:25<03:32,  1.13s/it]

[성공] 2812번 카드 (zgm.고향으로 체크) 수집 완료

 94%|█████████▍| 2812/2999 [54:27<03:44,  1.20s/it]

[성공] 2813번 카드 (NH1961체크카드) 수집 완료

 94%|█████████▍| 2813/2999 [54:28<03:48,  1.23s/it]

[성공] 2814번 카드 (카카오뱅크 모임 체크카드) 수집 완료

 94%|█████████▍| 2814/2999 [54:29<03:40,  1.19s/it]

[Skip] 2815번 카드 정보가 존재하지 않습니다.

 94%|█████████▍| 2815/2999 [54:30<03:32,  1.15s/it]

[성공] 2816번 카드 (1ST A-CHECK카드) 수집 완료

 94%|█████████▍| 2816/2999 [54:31<03:28,  1.14s/it]

[성공] 2817번 카드 (iM K-패스 체크카드) 수집 완료

 94%|█████████▍| 2817/2999 [54:33<03:27,  1.14s/it]

[성공] 2818번 카드 (iM K-패스 카드) 수집 완료

 94%|█████████▍| 2818/2999 [54:34<03:26,  1.14s/it]

[Skip] 2819번 카드 정보가 존재하지 않습니다.

 94%|█████████▍| 2819/2999 [54:35<03:22,  1.12s/it]

[성공] 2820번 카드 (원더카드 2.0 FREE+) 수집 완료

 94%|█████████▍| 2820/2999 [54:36<03:20,  1.12s/it]

[성공] 2821번 카드 (원더카드 2.0 HAPPY+) 수집 완료

 94%|█████████▍| 2821/2999 [54:37<03:19,  1.12s/it]

[성공] 2822번 카드 (쿠쿠 X LOCA) 수집 완료

 94%|█████████▍| 2822/2999 [54:38<03:18,  1.12s/it]

[성공] 2823번 카드 (롯데멤버스 카드) 수집 완료

 94%|█████████▍| 2823/2999 [54:39<03:19,  1.14s/it]

[성공] 2824번 카드 (롯데멤버스 카드 프리미엄) 수집 완료

 94%|█████████▍| 2824/2999 [54:41<03:23,  1.16s/it]

[성공] 2825번 카드 (우리 기후동행카드(신용)) 수집 완료

 94%|█████████▍| 2825/2999 [54:42<03:18,  1.14s/it]

[성공] 2826번 카드 (우리 기후동행카드(체크)) 수집 완료

 94%|█████████▍| 2826/2999 [54:43<03:39,  1.27s/it]

[성공] 2827번 카드 (삼성 iD STATION 카드 (GS칼텍스)) 수집 완료

 94%|█████████▍| 2827/2999 [54:45<03:40,  1.28s/it]

[성공] 2828번 카드 (삼성 iD STATION 카드 (SK에너지)) 수집 완료

 94%|█████████▍| 2828/2999 [54:46<03:30,  1.23s/it]

[Skip] 2829번 카드 정보가 존재하지 않습니다.

 94%|█████████▍| 2829/2999 [54:47<03:22,  1.19s/it]

[성공] 2830번 카드 (Point Plan 체크(SOL 모임)) 수집 완료

 94%|█████████▍| 2830/2999 [54:48<03:26,  1.22s/it]

[성공] 2831번 카드 (알리익스프레스 신한카드) 수집 완료

 94%|█████████▍| 2831/2999 [54:49<03:20,  1.19s/it]

[성공] 2832번 카드 (제주항공 트래블제로카드) 수집 완료

 94%|█████████▍| 2832/2999 [54:50<03:15,  1.17s/it]

[Skip] 2833번 카드 정보가 존재하지 않습니다.

 94%|█████████▍| 2833/2999 [54:51<03:10,  1.14s/it]

[Skip] 2834번 카드 정보가 존재하지 않습니다.

 94%|█████████▍| 2834/2999 [54:52<03:05,  1.13s/it]

[성공] 2835번 카드 (신한카드 Discount Plan+) 수집 완료

 95%|█████████▍| 2835/2999 [54:54<03:07,  1.15s/it]

[성공] 2836번 카드 (신한카드 Discount Plan) 수집 완료

 95%|█████████▍| 2836/2999 [54:55<03:05,  1.14s/it]

[성공] 2837번 카드 (WE:SH All+ 카드) 수집 완료

 95%|█████████▍| 2837/2999 [54:56<03:02,  1.13s/it]

[성공] 2838번 카드 (기아 챔피언스카드) 수집 완료

 95%|█████████▍| 2838/2999 [54:57<03:10,  1.19s/it]

[성공] 2839번 카드 (Together 체크카드) 수집 완료

 95%|█████████▍| 2839/2999 [54:58<03:06,  1.17s/it]

[성공] 2840번 카드 (오일모아카드) 수집 완료

 95%|█████████▍| 2840/2999 [54:59<03:02,  1.15s/it]

[성공] 2841번 카드 (에듀플러스카드) 수집 완료

 95%|█████████▍| 2841/2999 [55:01<02:59,  1.14s/it]

[성공] 2842번 카드 (현대카드 X Cut) 수집 완료

 95%|█████████▍| 2842/2999 [55:02<02:56,  1.13s/it]

[성공] 2843번 카드 (현대카드 X Save) 수집 완료

 95%|█████████▍| 2843/2999 [55:03<02:55,  1.12s/it]

[성공] 2844번 카드 (현대카드 ZERO Up) 수집 완료

 95%|█████████▍| 2844/2999 [55:04<02:56,  1.14s/it]

[성공] 2845번 카드 (KB YOU Wish up 카드) 수집 완료

 95%|█████████▍| 2845/2999 [55:05<02:54,  1.13s/it]

[성공] 2846번 카드 (클래시 트래블카드) 수집 완료

 95%|█████████▍| 2846/2999 [55:06<02:52,  1.13s/it]

[성공] 2847번 카드 (신한카드 SOL트래블 J체크) 수집 완료

 95%|█████████▍| 2847/2999 [55:07<02:52,  1.13s/it]

[성공] 2848번 카드 (카드의정석2) 수집 완료

 95%|█████████▍| 2848/2999 [55:09<02:56,  1.17s/it]

[성공] 2849번 카드 (케이뱅크 ALPHA카드) 수집 완료

 95%|█████████▍| 2849/2999 [55:10<02:52,  1.15s/it]

[성공] 2850번 카드 (I-기후동행카드(신용)) 수집 완료

 95%|█████████▌| 2850/2999 [55:11<02:51,  1.15s/it]

[성공] 2851번 카드 (우리카드 7CORE) 수집 완료

 95%|█████████▌| 2851/2999 [55:12<02:52,  1.16s/it]

[성공] 2852번 카드 (KB 틴업 체크카드) 수집 완료

 95%|█████████▌| 2852/2999 [55:13<02:49,  1.15s/it]

[성공] 2853번 카드 (KTX 삼성카드) 수집 완료

 95%|█████████▌| 2853/2999 [55:14<02:51,  1.18s/it]

[성공] 2854번 카드 (미미(美米)카드) 수집 완료

 95%|█████████▌| 2854/2999 [55:15<02:48,  1.16s/it]

[성공] 2855번 카드 (Haru(Hoshino Resorts)) 수집 완료

 95%|█████████▌| 2855/2999 [55:17<02:46,  1.15s/it]

[성공] 2856번 카드 (Biz Prime 카드) 수집 완료

 95%|█████████▌| 2856/2999 [55:18<02:43,  1.15s/it]

[성공] 2857번 카드 (신한카드 처음(선불)) 수집 완료

 95%|█████████▌| 2857/2999 [55:19<02:41,  1.14s/it]

[성공] 2858번 카드 (카카오뱅크 줍줍 신한카드) 수집 완료

 95%|█████████▌| 2858/2999 [55:20<02:39,  1.13s/it]

[성공] 2859번 카드 (KB 전통시장온누리카드) 수집 완료

 95%|█████████▌| 2859/2999 [55:21<02:39,  1.14s/it]

[성공] 2860번 카드 (라이프핏 체크카드) 수집 완료

 95%|█████████▌| 2860/2999 [55:22<02:36,  1.13s/it]

[성공] 2861번 카드 (트래블월렛 하이브리드 롯데카드) 수집 완료

 95%|█████████▌| 2861/2999 [55:23<02:36,  1.13s/it]

[성공] 2862번 카드 (MG+ S 하나카드) 수집 완료

 95%|█████████▌| 2862/2999 [55:25<02:38,  1.15s/it]

[성공] 2863번 카드 (디지로카 Travel) 수집 완료

 95%|█████████▌| 2863/2999 [55:26<02:34,  1.14s/it]

[성공] 2864번 카드 (디지로카 Travel 프리미엄) 수집 완료

 95%|█████████▌| 2864/2999 [55:27<02:31,  1.12s/it]

[성공] 2865번 카드 (신세계 트래블GO 하나카드) 수집 완료

 96%|█████████▌| 2865/2999 [55:28<02:33,  1.15s/it]

[성공] 2866번 카드 (I-Travel(체크)) 수집 완료

 96%|█████████▌| 2866/2999 [55:29<02:30,  1.13s/it]

[성공] 2867번 카드 (갤러리아 Platinum 우리카드) 수집 완료

 96%|█████████▌| 2867/2999 [55:30<02:30,  1.14s/it]

[성공] 2868번 카드 (KB 전통시장온누리체크카드) 수집 완료

 96%|█████████▌| 2868/2999 [55:32<02:35,  1.19s/it]

[성공] 2869번 카드 (E1 우리카드) 수집 완료

 96%|█████████▌| 2869/2999 [55:33<02:35,  1.20s/it]

[성공] 2870번 카드 (넥센타이어 신한카드) 수집 완료

 96%|█████████▌| 2870/2999 [55:34<02:29,  1.16s/it]

[성공] 2871번 카드 (우체국 LUCK-KEY 체크카드) 수집 완료

 96%|█████████▌| 2871/2999 [55:35<02:26,  1.14s/it]

[성공] 2872번 카드 (GS ALL 신한카드) 수집 완료

 96%|█████████▌| 2872/2999 [55:36<02:24,  1.14s/it]

[성공] 2873번 카드 (스타필드 신한카드) 수집 완료

 96%|█████████▌| 2873/2999 [55:37<02:23,  1.14s/it]

[성공] 2874번 카드 (쿵야싱싱체크카드) 수집 완료

 96%|█████████▌| 2874/2999 [55:38<02:20,  1.13s/it]

[성공] 2875번 카드 (삼성 iD CARE 카드) 수집 완료

 96%|█████████▌| 2875/2999 [55:39<02:18,  1.12s/it]

[성공] 2876번 카드 (MG+ 신용카드 Primo 하나카드) 수집 완료

 96%|█████████▌| 2876/2999 [55:41<02:20,  1.14s/it]

[성공] 2877번 카드 (MG+ BLACK 하나카드) 수집 완료

 96%|█████████▌| 2877/2999 [55:42<02:27,  1.21s/it]

[성공] 2878번 카드 (현대카드D) 수집 완료

 96%|█████████▌| 2878/2999 [55:43<02:24,  1.19s/it]

[성공] 2879번 카드 (현대카드H) 수집 완료

 96%|█████████▌| 2879/2999 [55:44<02:20,  1.17s/it]

[성공] 2880번 카드 (현대카드O) 수집 완료

 96%|█████████▌| 2880/2999 [55:45<02:17,  1.15s/it]

[성공] 2881번 카드 (현대카드S) 수집 완료

 96%|█████████▌| 2881/2999 [55:46<02:15,  1.15s/it]

[성공] 2882번 카드 (현대카드T) 수집 완료

 96%|█████████▌| 2882/2999 [55:48<02:12,  1.13s/it]

[성공] 2883번 카드 (현대카드Z everyday) 수집 완료

 96%|█████████▌| 2883/2999 [55:49<02:10,  1.12s/it]

[성공] 2884번 카드 (배민 신한카드 밥친구) 수집 완료

 96%|█████████▌| 2884/2999 [55:50<02:10,  1.13s/it]

[성공] 2885번 카드 (삼성 iD SELECT ALL 카드) 수집 완료

 96%|█████████▌| 2885/2999 [55:51<02:09,  1.14s/it]

[성공] 2886번 카드 (삼성 iD SELECT ON 카드) 수집 완료

 96%|█████████▌| 2886/2999 [55:52<02:13,  1.18s/it]

[성공] 2887번 카드 (신한카드 처음 체크) 수집 완료

 96%|█████████▋| 2887/2999 [55:53<02:09,  1.16s/it]

[성공] 2888번 카드 (DIGILOCA SKYPASS) 수집 완료

 96%|█████████▋| 2888/2999 [55:54<02:07,  1.14s/it]

[성공] 2889번 카드 (신한카드 처음 체크(냐한남자)) 수집 완료

 96%|█████████▋| 2889/2999 [55:56<02:05,  1.14s/it]

[성공] 2890번 카드 (신한카드 Point Plan 체크 캐릭터형(짱구)) 수집 완료

 96%|█████████▋| 2890/2999 [55:57<02:06,  1.16s/it]

[성공] 2891번 카드 (신한카드 Hey Young 체크(잔망루피)) 수집 완료

 96%|█████████▋| 2891/2999 [55:58<02:05,  1.16s/it]

[성공] 2892번 카드 (신한카드 Pick E 체크 캐릭터형(신의탑)) 수집 완료

 96%|█████████▋| 2892/2999 [55:59<02:03,  1.15s/it]

[성공] 2893번 카드 (신한카드 Pick I 체크 캐릭터형(한교동)) 수집 완료

 96%|█████████▋| 2893/2999 [56:00<02:02,  1.16s/it]

[성공] 2894번 카드 (토스 삼성카드) 수집 완료

 96%|█████████▋| 2894/2999 [56:01<02:02,  1.17s/it]

[성공] 2895번 카드 (iM 트래블 카드) 수집 완료

 97%|█████████▋| 2895/2999 [56:03<01:59,  1.15s/it]

[성공] 2896번 카드 (KB라이프 딱좋은 요즘 건강 KB카드) 수집 완료

 97%|█████████▋| 2896/2999 [56:04<01:57,  1.14s/it]

[성공] 2897번 카드 (스타벅스 삼성카드) 수집 완료

 97%|█████████▋| 2897/2999 [56:05<01:55,  1.14s/it]

[성공] 2898번 카드 (우리카드 MILE&POINT) 수집 완료

 97%|█████████▋| 2898/2999 [56:06<01:53,  1.13s/it]

[성공] 2899번 카드 (신한카드 SOL Plan) 수집 완료

 97%|█████████▋| 2899/2999 [56:07<01:53,  1.13s/it]

[성공] 2900번 카드 (오키카드 H) 수집 완료

 97%|█████████▋| 2900/2999 [56:08<01:54,  1.15s/it]

[성공] 2901번 카드 (오키카드 S) 수집 완료

 97%|█████████▋| 2901/2999 [56:09<01:53,  1.15s/it]

[성공] 2902번 카드 (the OPUS silver) 수집 완료

 97%|█████████▋| 2902/2999 [56:11<01:52,  1.16s/it]

[성공] 2903번 카드 (현대카드M-경차전용카드 Edition2 (유류세환급)) 수집 완료

 97%|█████████▋| 2903/2999 [56:12<01:49,  1.14s/it]

[성공] 2904번 카드 (토스뱅크 하나카드 Day) 수집 완료

 97%|█████████▋| 2904/2999 [56:13<01:47,  1.13s/it]

[성공] 2905번 카드 (트래블러스 체크카드) 수집 완료

 97%|█████████▋| 2905/2999 [56:14<01:45,  1.13s/it]

[성공] 2906번 카드 (신한카드 Simple Platinum# Splendor Plus) 수집 완료

 97%|█████████▋| 2906/2999 [56:15<01:44,  1.13s/it]

[성공] 2907번 카드 (위비트래블 J 체크카드) 수집 완료

 97%|█████████▋| 2907/2999 [56:16<01:43,  1.13s/it]

[성공] 2908번 카드 (번개장터 삼성카드) 수집 완료

 97%|█████████▋| 2908/2999 [56:17<01:42,  1.12s/it]

[성공] 2909번 카드 (MG+ W 하나카드) 수집 완료

 97%|█████████▋| 2909/2999 [56:18<01:40,  1.12s/it]

[성공] 2910번 카드 (카카오뱅크 스마트 하이패스카드) 수집 완료

 97%|█████████▋| 2910/2999 [56:20<01:40,  1.13s/it]

[성공] 2911번 카드 (해피메이트 IBK카드(신용)) 수집 완료

 97%|█████████▋| 2911/2999 [56:21<01:40,  1.14s/it]

[성공] 2912번 카드 (LG전자 The 구독케어 신한카드) 수집 완료

 97%|█████████▋| 2912/2999 [56:22<01:39,  1.15s/it]

[성공] 2913번 카드 (SK인텔릭스 올림 KB국민카드) 수집 완료

 97%|█████████▋| 2913/2999 [56:23<01:38,  1.14s/it]

[성공] 2914번 카드 (신세계 신백리워드 삼성카드) 수집 완료

 97%|█████████▋| 2914/2999 [56:24<01:36,  1.14s/it]

[성공] 2915번 카드 (THE iD. 1st) 수집 완료

 97%|█████████▋| 2915/2999 [56:25<01:35,  1.14s/it]

[성공] 2916번 카드 (The CLASSIC NEO) 수집 완료

 97%|█████████▋| 2916/2999 [56:27<01:45,  1.27s/it]

[성공] 2917번 카드 (IBK BUDDY CHECK) 수집 완료

 97%|█████████▋| 2917/2999 [56:28<01:41,  1.24s/it]

[성공] 2918번 카드 (E9pay 신한카드 처음) 수집 완료

 97%|█████████▋| 2918/2999 [56:29<01:37,  1.21s/it]

[성공] 2919번 카드 (웰컴 외국인 올인원 체크카드) 수집 완료

 97%|█████████▋| 2919/2999 [56:30<01:34,  1.18s/it]

[성공] 2920번 카드 (커넥트 하나로 체크카드) 수집 완료

 97%|█████████▋| 2920/2999 [56:31<01:31,  1.16s/it]

[성공] 2921번 카드 (신한카드 SOL글로벌U 체크) 수집 완료

 97%|█████████▋| 2921/2999 [56:32<01:29,  1.14s/it]

[성공] 2922번 카드 (신한카드 SOL글로벌 체크) 수집 완료

 97%|█████████▋| 2922/2999 [56:34<01:28,  1.14s/it]

[성공] 2923번 카드 (신세계 신한카드 Best Fit) 수집 완료

 97%|█████████▋| 2923/2999 [56:35<01:26,  1.14s/it]

[성공] 2924번 카드 (우리카드 UniMile) 수집 완료

 97%|█████████▋| 2924/2999 [56:36<01:24,  1.13s/it]

[성공] 2925번 카드 (수협 ALL드림) 수집 완료

 98%|█████████▊| 2925/2999 [56:37<01:23,  1.13s/it]

[성공] 2926번 카드 (BC 바로 Air Master 카드) 수집 완료

 98%|█████████▊| 2926/2999 [56:38<01:22,  1.13s/it]

[성공] 2927번 카드 (BC 바로 Air Max 카드) 수집 완료

 98%|█████████▊| 2927/2999 [56:39<01:22,  1.15s/it]

[성공] 2928번 카드 (BC 바로 ZONE 카드) 수집 완료

 98%|█████████▊| 2928/2999 [56:40<01:21,  1.14s/it]

[성공] 2929번 카드 (KB Youth Club 체크카드) 수집 완료

 98%|█████████▊| 2929/2999 [56:42<01:20,  1.14s/it]

[성공] 2930번 카드 (KB YOU Prime 카드) 수집 완료

 98%|█████████▊| 2930/2999 [56:43<01:20,  1.16s/it]

[성공] 2931번 카드 (KB NEED Edu카드) 수집 완료

 98%|█████████▊| 2931/2999 [56:44<01:18,  1.15s/it]

[성공] 2932번 카드 (The Aureum(더 아우름)카드) 수집 완료

 98%|█████████▊| 2932/2999 [56:45<01:17,  1.16s/it]

[성공] 2933번 카드 (신한카드 나라사랑카드 체크) 수집 완료

 98%|█████████▊| 2933/2999 [56:46<01:17,  1.17s/it]

[성공] 2934번 카드 (하나 나라사랑카드) 수집 완료

 98%|█████████▊| 2934/2999 [56:48<01:19,  1.22s/it]

[성공] 2935번 카드 (신한카드 SOL트립앤샵 체크) 수집 완료

 98%|█████████▊| 2935/2999 [56:49<01:16,  1.20s/it]

[성공] 2936번 카드 (RROUND PAY X 디지로카) 수집 완료

 98%|█████████▊| 2936/2999 [56:50<01:14,  1.18s/it]

[성공] 2937번 카드 (디지로카 Link) 수집 완료

 98%|█████████▊| 2937/2999 [56:51<01:15,  1.21s/it]

[성공] 2938번 카드 (현대카드MY BUSINESS M F&B) 수집 완료

 98%|█████████▊| 2938/2999 [56:52<01:12,  1.19s/it]

[성공] 2939번 카드 (현대카드MY BUSINESS M Retail) 수집 완료

 98%|█████████▊| 2939/2999 [56:53<01:09,  1.16s/it]

[성공] 2940번 카드 (현대카드MY BUSINESS M E-seller) 수집 완료

 98%|█████████▊| 2940/2999 [56:55<01:07,  1.15s/it]

[성공] 2941번 카드 (IBK나라사랑카드) 수집 완료

 98%|█████████▊| 2941/2999 [56:56<01:06,  1.14s/it]

[성공] 2942번 카드 (에너지플러스 현대카드) 수집 완료

 98%|█████████▊| 2942/2999 [56:57<01:04,  1.13s/it]

[성공] 2943번 카드 (G마켓 삼성카드) 수집 완료

 98%|█████████▊| 2943/2999 [56:58<01:03,  1.13s/it]

[성공] 2944번 카드 (the Orange) 수집 완료

 98%|█████████▊| 2944/2999 [56:59<01:04,  1.17s/it]

[Skip] 2945번 카드 정보가 존재하지 않습니다.

 98%|█████████▊| 2945/2999 [57:00<01:02,  1.15s/it]

[Skip] 2946번 카드 정보가 존재하지 않습니다.

 98%|█████████▊| 2946/2999 [57:01<00:59,  1.13s/it]

[성공] 2947번 카드 (넥슨 현대카드 Edition2 마비노기 모바일팩) 수집 완료

 98%|█████████▊| 2947/2999 [57:02<00:58,  1.12s/it]

[성공] 2948번 카드 (넥슨 현대카드 Edition2 넥슨팩) 수집 완료

 98%|█████████▊| 2948/2999 [57:04<00:58,  1.14s/it]

[Skip] 2949번 카드 정보가 존재하지 않습니다.

 98%|█████████▊| 2949/2999 [57:05<00:56,  1.13s/it]

[성공] 2950번 카드 (신한카드 Simple Plan+) 수집 완료

 98%|█████████▊| 2950/2999 [57:06<00:55,  1.13s/it]

[성공] 2951번 카드 (신한카드 Simple Plan) 수집 완료

 98%|█████████▊| 2951/2999 [57:07<00:53,  1.12s/it]

[성공] 2952번 카드 (삼성 iD STATION 카드 (HD현대오일뱅크)) 수집 완료

 98%|█████████▊| 2952/2999 [57:08<00:53,  1.15s/it]

[성공] 2953번 카드 (스타트래블 우리카드) 수집 완료

 98%|█████████▊| 2953/2999 [57:09<00:52,  1.14s/it]

[성공] 2954번 카드 (LG트윈스 신한카드 체크) 수집 완료

 98%|█████████▊| 2954/2999 [57:10<00:51,  1.14s/it]

[성공] 2955번 카드 (삼성라이온즈카드) 수집 완료

 99%|█████████▊| 2955/2999 [57:12<00:50,  1.15s/it]

[성공] 2956번 카드 (두산베어스 KB카드) 수집 완료

 99%|█████████▊| 2956/2999 [57:13<00:48,  1.14s/it]

[성공] 2957번 카드 (한화이글스 신한카드) 수집 완료

 99%|█████████▊| 2957/2999 [57:14<00:47,  1.14s/it]

[성공] 2958번 카드 (BLISS Mileage) 수집 완료

 99%|█████████▊| 2958/2999 [57:15<00:47,  1.15s/it]

[성공] 2959번 카드 (BLISS Point) 수집 완료

 99%|█████████▊| 2959/2999 [57:16<00:45,  1.14s/it]

[성공] 2960번 카드 (이마트 신한카드) 수집 완료

 99%|█████████▊| 2960/2999 [57:17<00:44,  1.14s/it]

[성공] 2961번 카드 (트래블로그+(플러스) 신용카드) 수집 완료

 99%|█████████▊| 2961/2999 [57:18<00:43,  1.15s/it]

[성공] 2962번 카드 (더한섬 신한카드) 수집 완료

 99%|█████████▉| 2962/2999 [57:20<00:43,  1.17s/it]

[성공] 2963번 카드 (더한섬 신한카드 플래티늄) 수집 완료

 99%|█████████▉| 2963/2999 [57:21<00:43,  1.21s/it]

[성공] 2964번 카드 (KB NEED Pay 카드) 수집 완료

 99%|█████████▉| 2964/2999 [57:22<00:41,  1.18s/it]

[성공] 2965번 카드 (LOCA Biz) 수집 완료

 99%|█████████▉| 2965/2999 [57:23<00:41,  1.23s/it]

[성공] 2966번 카드 (LOCA Biz+) 수집 완료

 99%|█████████▉| 2966/2999 [57:25<00:39,  1.20s/it]

[성공] 2967번 카드 (알파벳카드) 수집 완료

 99%|█████████▉| 2967/2999 [57:26<00:37,  1.19s/it]

[성공] 2968번 카드 (알파벳카드) 수집 완료

 99%|█████████▉| 2968/2999 [57:27<00:38,  1.23s/it]

[성공] 2969번 카드 (알파벳카드) 수집 완료

 99%|█████████▉| 2969/2999 [57:28<00:35,  1.20s/it]

[성공] 2970번 카드 (YOU Wish 카드) 수집 완료

 99%|█████████▉| 2970/2999 [57:29<00:34,  1.18s/it]

[성공] 2971번 카드 (무신사 삼성카드) 수집 완료

 99%|█████████▉| 2971/2999 [57:30<00:32,  1.16s/it]

[성공] 2972번 카드 (현대카드 하이브리드(포인트형)) 수집 완료

 99%|█████████▉| 2972/2999 [57:32<00:31,  1.16s/it]

[성공] 2973번 카드 (현대카드 하이브리드(캐시백형)) 수집 완료

 99%|█████████▉| 2973/2999 [57:33<00:30,  1.17s/it]

[성공] 2974번 카드 (현대카드 하이브리드(Apple Pay Rewards)) 수집 완료

 99%|█████████▉| 2974/2999 [57:34<00:28,  1.16s/it]

[성공] 2975번 카드 (LOCA LIKIT 1.5) 수집 완료

 99%|█████████▉| 2975/2999 [57:35<00:27,  1.15s/it]

[성공] 2976번 카드 (우체국 MY-TYPE 체크카드) 수집 완료

 99%|█████████▉| 2976/2999 [57:36<00:27,  1.21s/it]

[성공] 2977번 카드 (신한카드 SOL트립앤J 체크) 수집 완료

 99%|█████████▉| 2977/2999 [57:38<00:27,  1.24s/it]

[성공] 2978번 카드 (카드의정석2 SHOPPER) 수집 완료

 99%|█████████▉| 2978/2999 [57:39<00:25,  1.21s/it]

[Skip] 2979번 카드 정보가 존재하지 않습니다.

 99%|█████████▉| 2979/2999 [57:40<00:23,  1.17s/it]

[Skip] 2980번 카드 정보가 존재하지 않습니다.

 99%|█████████▉| 2980/2999 [57:41<00:21,  1.15s/it]

[Skip] 2981번 카드 정보가 존재하지 않습니다.

 99%|█████████▉| 2981/2999 [57:42<00:20,  1.15s/it]

[Skip] 2982번 카드 정보가 존재하지 않습니다.

 99%|█████████▉| 2982/2999 [57:43<00:19,  1.12s/it]

[Skip] 2983번 카드 정보가 존재하지 않습니다.

 99%|█████████▉| 2983/2999 [57:44<00:17,  1.11s/it]

[Skip] 2984번 카드 정보가 존재하지 않습니다.

 99%|█████████▉| 2984/2999 [57:45<00:16,  1.10s/it]

[Skip] 2985번 카드 정보가 존재하지 않습니다.

100%|█████████▉| 2985/2999 [57:47<00:15,  1.10s/it]

[Skip] 2986번 카드 정보가 존재하지 않습니다.

100%|█████████▉| 2986/2999 [57:48<00:14,  1.10s/it]

[Skip] 2987번 카드 정보가 존재하지 않습니다.

100%|█████████▉| 2987/2999 [57:49<00:13,  1.10s/it]

[Skip] 2988번 카드 정보가 존재하지 않습니다.

100%|█████████▉| 2988/2999 [57:50<00:12,  1.10s/it]

[Skip] 2989번 카드 정보가 존재하지 않습니다.

100%|█████████▉| 2989/2999 [57:51<00:11,  1.10s/it]

[Skip] 2990번 카드 정보가 존재하지 않습니다.

100%|█████████▉| 2990/2999 [57:52<00:09,  1.10s/it]

[Skip] 2991번 카드 정보가 존재하지 않습니다.

100%|█████████▉| 2991/2999 [57:53<00:08,  1.11s/it]

[Skip] 2992번 카드 정보가 존재하지 않습니다.

100%|█████████▉| 2992/2999 [57:54<00:07,  1.10s/it]

[Skip] 2993번 카드 정보가 존재하지 않습니다.

100%|█████████▉| 2993/2999 [57:55<00:06,  1.10s/it]

[Skip] 2994번 카드 정보가 존재하지 않습니다.

100%|█████████▉| 2994/2999 [57:56<00:05,  1.09s/it]

[Skip] 2995번 카드 정보가 존재하지 않습니다.

100%|█████████▉| 2995/2999 [57:58<00:04,  1.09s/it]

[Skip] 2996번 카드 정보가 존재하지 않습니다.

100%|█████████▉| 2996/2999 [57:59<00:03,  1.08s/it]

[Skip] 2997번 카드 정보가 존재하지 않습니다.

100%|█████████▉| 2997/2999 [58:00<00:02,  1.08s/it]

[Skip] 2998번 카드 정보가 존재하지 않습니다.

100%|█████████▉| 2998/2999 [58:01<00:01,  1.09s/it]

[Skip] 2999번 카드 정보가 존재하지 않습니다.

100%|██████████| 2999/2999 [58:02<00:00,  1.16s/it]

In [45]:
df = pd.DataFrame(card_data_list)

In [ ]:
# df.to_csv('card_data.csv', index=False, encoding='utf-8-sig')

### 데이터 불러오기

In [12]:
df = pd.read_csv('card_data.csv', index_col=0)
df.head()

                     카드명   카드사 카드타입
카드번호
1          신한카드 Hi-Point  신한카드  CRD
2              신한카드 Love  신한카드  CRD
3              신한카드 Lady  신한카드  CRD
4      SK에너지 신한카드The you  신한카드  CRD
8     신한카드 The CLASSIC-Y  신한카드  CRD

In [13]:
df.tail()

                                카드명   카드사 카드타입
카드번호
2974  현대카드 하이브리드(Apple Pay Rewards)  현대카드  CHK
2975                 LOCA LIKIT 1.5  롯데카드  CRD
2976               우체국 MY-TYPE 체크카드   우체국  CHK
2977                신한카드 SOL트립앤J 체크  신한카드  CHK
2978                 카드의정석2 SHOPPER  우리카드  CRD

In [14]:
len(df)

2810

In [15]:
df.shape

(2810, 3)

In [16]:
df.info()

<class 'pandas.DataFrame'>
Index: 2810 entries, 1 to 2978
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   카드명     2810 non-null   str
 1   카드사     2810 non-null   str
 2   카드타입    2810 non-null   str
dtypes: str(3)
memory usage: 87.8 KB

In [17]:
df.isnull().sum()

카드명     0
카드사     0
카드타입    0
dtype: int64

In [21]:
df['카드사'].unique()

<StringArray>
[        '신한카드',         '삼성카드',         '우리카드',         '씨티카드',
       'KB국민카드',       'NH농협카드',         '롯데카드',         '하나카드',
      'IBK기업은행',       'SC제일은행',         '현대카드', 'SSGPAY. CARD',
        '카카오뱅크',         '케이뱅크',          '우체국',         'iM뱅크',
      'BNK부산은행',         '광주은행',       'Sh수협은행',           '신협',
         '교보증권',        '유안타증권',      'KDB산업은행',      'SBI저축은행',
      'MG새마을금고',         '제주은행',         '전북은행',        '카카오페이',
      'BC 바로카드',       '유진투자증권',         'SK증권',       '미래에셋증권',
       'NH투자증권',         'KB증권',       'DB금융투자',       '한국투자증권',
         '토스뱅크',     '엔에이치엔페이코',         '코나카드',        '아이오로라',
           '토스',          '한패스',           '차이',         '핀크카드',
           '다날',        '트래블월렛',      'KG 파이낸셜',           '핀트',
        '현대백화점',      'BNK경남은행',        '네이버페이',         '머니트리',
        'OK캐쉬백',       '웰컴저축은행']
Length: 54, dtype: str

In [18]:
df['카드사'].value_counts()

카드사
롯데카드            548
삼성카드            371
KB국민카드          285
우리카드            277
신한카드            251
현대카드            217
NH농협카드          201
하나카드            184
IBK기업은행         116
BNK부산은행          44
BC 바로카드          43
iM뱅크             41
MG새마을금고          31
우체국              26
광주은행             24
씨티카드             19
신협               14
제주은행             14
전북은행             14
SC제일은행           10
케이뱅크             10
Sh수협은행            7
카카오뱅크             5
SBI저축은행           4
KB증권              4
코나카드              4
현대백화점             4
SSGPAY. CARD      3
교보증권              3
유안타증권             3
카카오페이             2
유진투자증권            2
SK증권              2
미래에셋증권            2
DB금융투자            2
토스뱅크              2
한패스               2
차이                2
OK캐쉬백             2
KDB산업은행           1
NH투자증권            1
한국투자증권            1
엔에이치엔페이코          1
아이오로라             1
토스                1
핀크카드              1
다날                1
트래블월렛             1
KG 파이낸셜           1
핀트                1
BNK경남은행           1
네이버페이             1
머니트리              1
웰컴저축은행            1
Name: count, dtype: int64

In [22]:
card_comp_list = ['삼성카드', '신한카드', '현대카드', 'KB국민카드', '롯데카드', 
                  '우리카드', '하나카드', 'NH농협카드', 'IBK기업은행', 'BC 바로카드']

In [25]:
top_df = df.loc[df['카드사'].isin(card_comp_list)]
len(top_df)

2493

In [30]:
valid_ids = top_df.index.tolist()
len(valid_ids)

2493

### 정보 추가

In [69]:
card_data_list = []

In [70]:
for card_id in tqdm.tqdm(valid_ids):
    url = f"https://api.card-gorilla.com:8080/v1/cards/{card_id}"
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36'}
    
    try:
        response = requests.get(url, headers=headers)
        if response.status_code == 200:
            raw_data = response.json()

            # 혜택 카테고리 추출 (key_benefit 활용 + 중복 제거)
            category_list = []
            if 'key_benefit' in raw_data and raw_data['key_benefit']:
                for benefit in raw_data['key_benefit']:
                    if 'cate' in benefit and 'name' in benefit['cate']:
                        cate_name = benefit['cate']['name']

                        if cate_name not in ['기타', '유의사항']:
                            if cate_name not in category_list:
                                category_list.append(cate_name)

            # 주요 혜택 요약 추출 (top_benefit 활용)
            top_tags_list = []
            if 'top_benefit' in raw_data and raw_data['top_benefit']:
                for top in raw_data['top_benefit']:
                    if 'tags' in top and top['tags']:
                        top_tags_list.append(" ".join(top['tags']))

            # 현재 발급 가능 여부
            is_discontinued = raw_data.get('is_discon', False)
            issuable_status = 'X' if is_discontinued else 'O'

            card_info = {
                '카드번호': card_id,
                '카드명': raw_data.get('name', '이름없음'),       # name 키가 없으면 '이름없음' 반환
                '카드사': raw_data.get('corp').get('name', '알수없음'),  # 예: 신한카드
                '카드타입': raw_data.get('cate', '알수없음'),     # 예: 신용/체크
                '출시일': raw_data.get('release_dt', '알수없음'),
                '전월실적': raw_data.get('pre_month_money', 0),
                '카테고리': ", ".join(category_list),
                '주요혜택': ", ".join(top_tags_list),
                '발급가능여부': issuable_status
                }
            
            card_data_list.append(card_info)
            # print(f"[성공] {card_id}번 카드 ({card_info['카드명']}) 수집 완료")

        elif response.status_code == 404:
            # print(f"[Skip] {card_id}번 카드 정보가 존재하지 않습니다.")
            pass
        else:
            print(f"[Error] {card_id}번 카드 정보 요청 실패 (상태 코드: {response.status_code})")
    
    except Exception as e:
        print(f"[오류] {card_id}번 카드 정보 요청 중 예외 발생: {e}")

    # time.sleep(1)

100%|██████████| 2493/2493 [06:46<00:00,  6.14it/s]

In [71]:
df = pd.DataFrame(card_data_list)
df.head()

,카드번호,카드명,카드사,카드타입,출시일,전월실적,카테고리,주요혜택,발급가능여부
0,1,신한카드 Hi-Point,신한카드,CRD,,0,"쇼핑, 모든가맹점, 주유, 금융, 통신, 적립","전국가맹점 0.2~2.0% 적립, 특정가맹점 1~5% 적립, 에이치디현대오일뱅크 6...",X
1,2,신한카드 Love,신한카드,CRD,,200000,"백화점, 패밀리레스토랑, 주유소, 영화, 적립, 테마파크, 경기관람","백화점/할인점 5% 할인, 스타벅스 20% 할인, GS칼텍스 60원/L 할인",X
2,3,신한카드 Lady,신한카드,CRD,,300000,"쇼핑, 푸드, 영화, 주유소, 교육/육아, 테마파크, 통신, 경기관람","3대백화점 5% 할인, 패밀리레스토랑 20% 할인, 놀이공원 30~50% 할인",X
3,4,SK에너지 신한카드The you,신한카드,CRD,,300000,"주유소, 대중교통, 무이자할부, 테마파크, 영화, 헤어, 경기관람, 여행사","SK주유소 100원/L 할인, 지하철,버스,택시 3~7% 할인, 놀이공원 30~50...",X
4,8,신한카드 The CLASSIC-Y,신한카드,CRD,,0,"선택형, 모든가맹점, 주유소, 생활, 면세점, 진에어, 공연/전시, 프리미엄","Gift Option 매년1회 선택이용, 마이신한포인트 0.7~5% 적립, GS칼텍...",O

In [ ]:
# df.loc[df['발급가능여부'].isnull()].head()

,카드번호,카드명,카드사,카드타입,출시일,전월실적,카테고리,주요혜택,발급가능여부
0,1,신한카드 Hi-Point,신한카드,CRD,,0,"쇼핑, 모든가맹점, 주유, 금융, 통신, 적립","전국가맹점 0.2~2.0% 적립, 특정가맹점 1~5% 적립, 에이치디현대오일뱅크 6...",NaN
1,2,신한카드 Love,신한카드,CRD,,200000,"백화점, 패밀리레스토랑, 주유소, 영화, 적립, 테마파크, 경기관람","백화점/할인점 5% 할인, 스타벅스 20% 할인, GS칼텍스 60원/L 할인",NaN
2,3,신한카드 Lady,신한카드,CRD,,300000,"쇼핑, 푸드, 영화, 주유소, 교육/육아, 테마파크, 통신, 경기관람","3대백화점 5% 할인, 패밀리레스토랑 20% 할인, 놀이공원 30~50% 할인",NaN
3,4,SK에너지 신한카드The you,신한카드,CRD,,300000,"주유소, 대중교통, 무이자할부, 테마파크, 영화, 헤어, 경기관람, 여행사","SK주유소 100원/L 할인, 지하철,버스,택시 3~7% 할인, 놀이공원 30~50...",NaN
4,8,신한카드 The CLASSIC-Y,신한카드,CRD,,0,"선택형, 모든가맹점, 주유소, 생활, 면세점, 진에어, 공연/전시, 프리미엄","Gift Option 매년1회 선택이용, 마이신한포인트 0.7~5% 적립, GS칼텍...",NaN
...,...,...,...,...,...,...,...,...,...
2488,2973,현대카드 하이브리드(캐시백형),현대카드,CHK,2026-04-28,0,"국내외가맹점, 적립, 하이브리드","국내외 가맹점 0.3% 캐시백, 일반음식점, 배달 앱 3% 캐시백, 편의점, 대중교...",NaN
2489,2974,현대카드 하이브리드(Apple Pay Rewards),현대카드,CHK,2026-04-28,300000,"간편결제, 하이브리드",Apple Pay 이용 금액 10% 캐시백,NaN
2490,2975,LOCA LIKIT 1.5,롯데카드,CRD,2026-04-07,0,"국내가맹점, 해외, 무이자할부","국내 가맹점 0.8% 할인, 해외 가맹점 1.5% 할인",NaN
2491,2977,신한카드 SOL트립앤J 체크,신한카드,CHK,2026-03-30,0,"해외이용, 해외, 할인","해외 이용 수수료 면제, 일본 돈키호테/편의점 50% 할인, 국내 편의점/대중교통 ...",NaN
2492,2978,카드의정석2 SHOPPER,우리카드,CRD,2026-04-15,500000,"쇼핑, 온라인쇼핑","온·오프라인 쇼핑 10% 할인, 주중 온라인/주말 오프라인 쇼핑 5% 추가 할인, ...",NaN

In [ ]:
# df.loc[df['발급가능여부'] == 'X'].head()

,카드번호,카드명,카드사,카드타입,출시일,전월실적,카테고리,주요혜택,발급가능여부
2493,1,신한카드 Hi-Point,신한카드,CRD,,0,"쇼핑, 모든가맹점, 주유, 금융, 통신, 적립","전국가맹점 0.2~2.0% 적립, 특정가맹점 1~5% 적립, 에이치디현대오일뱅크 6...",X
2494,2,신한카드 Love,신한카드,CRD,,200000,"백화점, 패밀리레스토랑, 주유소, 영화, 적립, 테마파크, 경기관람","백화점/할인점 5% 할인, 스타벅스 20% 할인, GS칼텍스 60원/L 할인",X
2495,3,신한카드 Lady,신한카드,CRD,,300000,"쇼핑, 푸드, 영화, 주유소, 교육/육아, 테마파크, 통신, 경기관람","3대백화점 5% 할인, 패밀리레스토랑 20% 할인, 놀이공원 30~50% 할인",X
2496,4,SK에너지 신한카드The you,신한카드,CRD,,300000,"주유소, 대중교통, 무이자할부, 테마파크, 영화, 헤어, 경기관람, 여행사","SK주유소 100원/L 할인, 지하철,버스,택시 3~7% 할인, 놀이공원 30~50...",X
2499,11,신한카드 Simple+,신한카드,CRD,,0,"모든가맹점, 생활, 영화","전가맹점 0.7% 캐시백, 이동통신요금 0.7% 추가캐시백, 생활친화가맹점 월 10...",X
...,...,...,...,...,...,...,...,...,...
4802,2762,THE iD. TITANIUM (아시아나),삼성카드,CRD,2024-08-26,0,"바우처, 아시아나항공, 프리미엄 서비스","바우처 연 2가지 제공, 1,500원당 2 마일리지 기본 적립, 여행/골프/면세점 ...",X
4837,2797,SKT T다운 하나카드,하나카드,CRD,,400000,SKT,SKT 라이트할부 청구할인,X
4838,2798,LG전자 스페셜 롯데카드,롯데카드,CRD,,300000,"할인, 캐시백, 멤버십포인트","렌탈료 최대 23,000원 결제일 할인, 장기할부이용 최대 23,000원 캐시백",X
4842,2802,LG U+ NU 우리카드 Ⅱ,우리카드,CRD,,0,LGU+,"LG U+ 통신요금 최대 20,000원 할인, LG U+ 단말기 장기할부 서비스",X
4910,2891,신한카드 Hey Young 체크(잔망루피),신한카드,CHK,,200000,"대중교통, 통신, 영화, 편의점, 카페, 패스트푸드, 배달앱, 생활, 디지털구독, ...","일상 서비스 최대 5천원 캐시백, 간편결제 서비스 최대 5천원 캐시백, 해외 이용서...",X

In [ ]:
# df.loc[df['발급가능여부'] == 'O'].head()

,카드번호,카드명,카드사,카드타입,출시일,전월실적,카테고리,주요혜택,발급가능여부
2497,8,신한카드 The CLASSIC-Y,신한카드,CRD,,0,"선택형, 모든가맹점, 주유소, 생활, 면세점, 진에어, 공연/전시, 프리미엄","Gift Option 매년1회 선택이용, 마이신한포인트 0.7~5% 적립, GS칼텍...",O
2498,10,신한카드 B.Big(삑),신한카드,CRD,,300000,"대중교통, 택시, 백화점, 카페, 편의점, 통신, 영화, 캐시백","대중교통 200~600원 할인, 택시 10% 할인, KTX 10% 할인",O
2500,12,신한카드 Air Platinum#,신한카드,CRD,,0,"항공마일리지, 생활, 프리미엄","1,500원당 1마일 적립, 1,000원당 1마일 적립",O
2501,13,신한카드 Mr.Life,신한카드,CRD,2015-09-03,300000,"공과금, 편의점, 병원/약국, 생활, 온라인쇼핑, 택시, 푸드, 대형마트, 주유소","공과금 10% 할인, 마트,편의점 10% 할인, 식음료 10% 할인",O
2502,14,신한카드 YOLO ⓘ,신한카드,CRD,,300000,"선택형, 카페, 편의점, 소셜커머스, 택시, 베이커리, 영화","6개가맹점 할인율 선택, 스타벅스 쿠폰 제공",O
...,...,...,...,...,...,...,...,...,...
4981,2973,현대카드 하이브리드(캐시백형),현대카드,CHK,2026-04-28,0,"국내외가맹점, 적립, 하이브리드","국내외 가맹점 0.3% 캐시백, 일반음식점, 배달 앱 3% 캐시백, 편의점, 대중교...",O
4982,2974,현대카드 하이브리드(Apple Pay Rewards),현대카드,CHK,2026-04-28,300000,"간편결제, 하이브리드",Apple Pay 이용 금액 10% 캐시백,O
4983,2975,LOCA LIKIT 1.5,롯데카드,CRD,2026-04-07,0,"국내가맹점, 해외, 무이자할부","국내 가맹점 0.8% 할인, 해외 가맹점 1.5% 할인",O
4984,2977,신한카드 SOL트립앤J 체크,신한카드,CHK,2026-03-30,0,"해외이용, 해외, 할인","해외 이용 수수료 면제, 일본 돈키호테/편의점 50% 할인, 국내 편의점/대중교통 ...",O
4985,2978,카드의정석2 SHOPPER,우리카드,CRD,2026-04-15,500000,"쇼핑, 온라인쇼핑","온·오프라인 쇼핑 10% 할인, 주중 온라인/주말 오프라인 쇼핑 5% 추가 할인, ...",O

In [ ]:
df.to_csv('/data/card_data.csv', index=False, encoding='utf-8-sig')